### ISSUE TITLE
Task not stopping after being removed from processing

### ISSUE THREAD

**Issue by dhrida** [HangfireIO/Hangfire#1001]
I need to debug this further, but in a .NET Core 2.0 application, I noticed instances that tasks don't stop even after being removed from the processing queue. The task even persisted 45 minutes after cancellation.

I noticed it because even after removal of the task, logs were still being created from the task. 

I am using Hangfire.SQLServer with Hangfire 1.6.15.

**Comment by pieceofsummer** [comment]
You should use `IJobCancellationToken` to check if the job was deleted from Dashboard. The standard `CancellationToken` won’t detect that, unless PR #976 is merged.
