### ISSUE TITLE
Recurring Jobs Page - When there are 11 jobs, the 11th shows up on both the first and second page

### ISSUE THREAD

**Issue by cacodev** [HangfireIO/Hangfire#1004]
See screen shot, Last job (#11) in the list shows on both pages... probably should only show on the second job
![screen shot 2017-09-20 at 1 58 09 pm](https://user-images.githubusercontent.com/4412526/30659540-118b83ba-9e0c-11e7-9f0f-2944a3b5b335.png)
![screen shot 2017-09-20 at 1 58 20 pm](https://user-images.githubusercontent.com/4412526/30659542-139989d6-9e0c-11e7-8b8c-3d6be63e098b.png)

**Comment by pieceofsummer** [comment]
What storage are you using?

**Comment by Caseyc585** [comment]
SQL server
________________________________

**Comment by pieceofsummer** [comment]
Oh, I haven't really noticed it before, but you're right!

https://github.com/HangfireIO/Hangfire/blob/419ef28cb4db886ebcb9998db40e9ac9e264537d/src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml#L27

Should be `pager.FromRecord + pager.RecordsPerPage - 1` instead.
