### ISSUE TITLE
Server not scheduling/processing jobs when using an always-running ASP.NET application

### ISSUE THREAD

**Issue by RudeySH** [HangfireIO/Hangfire#1005]
I'm using Hangfire with SQL Server storage. I've followed this piece of documentation: [Making ASP.NET application always running](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html). I have verified the Hangfire server starts immediately. However, enqueued jobs are never processed. According to the dashboard my server is alive, the heartbeat is always "a few seconds ago".

If I call `app.UseHangfireServer()` in my startup class, Hangfire works just fine. But to my understanding, I shouldn't call this function because I am using the Hangfire bootstrapper as described in the documentation linked above.

**Comment by rlenders** [comment]
[These docs](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html) seem to suggest `app.UseHangfireServer()` is not required when using `new BackgroundJobServer()`. Is this correct?

**Comment by rlenders** [comment]
Should I be using [Hangfire.AspNet](https://github.com/HangfireIO/Hangfire.AspNet)?

**Comment by rlenders** [comment]
Even with Hangfire.AspNet my jobs still end up stuck in the Enqueued state. Interestingly enough, the server works fine when I remove the application preload and hangfire bootstrapper classes altogether. Although I'm sure this cause my application to not be always running...

In other words, the server only does it's job when it's initialized in Startup.Configuration(IAppBuilder).

Any help would be appreciated.
