### ISSUE TITLE
HangfireServiceCollectionExtensions._initialized makes it impossible to run several integration tests

### ISSUE THREAD

**Issue by NicolasDorier** [HangfireIO/Hangfire#1007]
[This line](https://github.com/HangfireIO/Hangfire/blob/129707d66fde24dc6379fb9d6b15fa0b8ca48605/src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs#L74) prevents me to make integration tests.

If I have two tests, each creating a webhost with HangFire, the second one will fail because the previous `LoggerFactory` of .NET Core got disposed.

Ugly Workaround, calling this instead of `AddHangfire` in `ConfigureServices`:
```
// Big hack, tests fails if only call AddHangfire because Hangfire fail at initializing at the second test run
private void AddHangfireFix(IServiceCollection services)
{
	Action<IGlobalConfiguration> configuration = o =>
	{
		//.....
	};

	ServiceCollectionDescriptorExtensions.TryAddSingleton<Action<IGlobalConfiguration>>(services, (IServiceProvider serviceProvider) =>  new Action<IGlobalConfiguration>((config) =>
	{
		ILoggerFactory service = ServiceProviderServiceExtensions.GetService<ILoggerFactory>(serviceProvider);
		if(service != null)
		{
			Hangfire.GlobalConfigurationExtensions.UseLogProvider<AspNetCoreLogProvider>(config, new AspNetCoreLogProvider(service));
		}
		IServiceScopeFactory service2 = ServiceProviderServiceExtensions.GetService<IServiceScopeFactory>(serviceProvider);
		if(service2 != null)
		{
			Hangfire.GlobalConfigurationExtensions.UseActivator<AspNetCoreJobActivator>(config, new AspNetCoreJobActivator(service2));
		}
		configuration(config);
	}));
	services.AddHangfire(configuration);
}
```

**Comment by NicolasDorier** [comment]
anybody maintaining this project?

**Comment by NicolasDorier** [comment]
@pieceofsummer  please don't do this https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs#L93

This singleton is a big problem which prevent me to run integration testing with 2 servers using hangfire in different way in the same process. I need still to do horrible hacks like about to workaround your hack.

**Comment by NicolasDorier** [comment]
I close this, actually this solved my issue, even though I can have problem for using 2 server with different hangfire configuration.

**Comment by pieceofsummer** [comment]
@NicolasDorier I would be happy not to. But unfortunately, Hangfire still depends too much on static properties, and it can't be changed soon.

It doesn't really matter whether you use a static `IGlobalConfiguration` or create a new one every time. Extension methods don't change the configuration instance itself but set some static properties instead, while `IGlobalConfiguration` is only used as `this`-type to resolve extension methods for.

I think it would be impossible to actually fix it without breaking the current code. But if you have any ideas on making it better in a compatible way, feel free to submit a PR ;)
