### ISSUE TITLE
Dashboard graphs have crazy sizing

### ISSUE THREAD

**Issue by k3davis** [HangfireIO/Hangfire#1011]
The "realtime graph" and "History graph" are loading their SVG in a monstrous size that negatively affects other parts of the dashboard (the footer is nested in the middle of the page, etc.). Though I can't prove a 1:1 correlation it seemed to start happening after updating to Hangfire 1.6.16. I'm attaching a full screen capture of how it's appearing.

![screencapture-msteap-recurringengine-jobs-1506688080839](https://user-images.githubusercontent.com/1307914/31015905-0e1a4526-a4e8-11e7-88ce-2dbb5cb6d574.png)

Can this be fixed in some way, or alternately may I turn these graphs off entirely? Thanks.

**Comment by odinserj** [comment]
Charting library was replaced with [Chart.js](https://www.chartjs.org/) in the latest betas, so I think this issue is resolved.
