### ISSUE TITLE
Asp.net Core And Windows Service Assembly Issue

### ISSUE THREAD

**Issue by bijayshah** [HangfireIO/Hangfire#1016]
I am getting System.IO.FileNotFoundException, Please find the use case below.

Use Case:
**Project :** **Asp.Net Core** With Hangfire Dashboard, and Code to Schedule a Job (BackgroundJob.Enqueue<IJobs>(x => x.RunTestA());)

**Project :** Window Service(.net 4.6) with Hangfire Server, and Code to Run the Job

Error :  Could not load file or assembly 'hangFireWithCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'hangFireWithCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'hangFireWithCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.Deserialize()

![image](https://user-images.githubusercontent.com/1381922/31210929-38419bf4-a9b3-11e7-8483-7b760cf8fe95.png)

**Comment by bijayshah** [comment]
I have create project to achieve same.
https://github.com/bijayshah/hangfirecrossplatform/tree/master

**Comment by pieceofsummer** [comment]
You actually have two problems here:

1. .Net Core assemblies are not compatible with classic .net assemblies, so you cannot reference a single jobs assembly from both .net core and .net 4.6. But you can specify multiple target frameworks for your jobs project, so it would be built for both .net core and .net 4.6, then reference this shared project from two others.

2. .Net Core has primitive types (e.g. `int`, `string` etc.) not in mscorlib, but in System.Private.CoreLib assembly, so primitive types serialized on .net core side can't be seamlessly deserialized on a classic .net. It also can be worked around, but it would take some effort. See #816 for more details.

Why do you need Windows service at all? .Net core applications are hosted in their own process, so they don't have IIS worker process recycling issues. Hosting Hangfire server directly in the .net core application is perfectly fine, and you don't have to work out all these cross-framework issues.

**Comment by PerfectlyNormal** [comment]
I encountered the same issue, and worked around it using the `JsonConverter` mentioned in #816.

Our reason for a Windows service is that we have to generate some PDFs and send to a printer, and that seems to be easier to manage from a Windows service with the full .NET framework than with .NET Core.

**Comment by odinserj** [comment]
In 1.7.0 there're new type resolver and serializer that's plugged into both JSON converter and Hangfire itself. When using `SimpleAssemblyNameTypeSerializer` (via `GlobalConfiguration.Configuration`), it handles `TypeForwardedFrom` attributes in .NET Core to serialize the type name to the format .NET Framework understands. And when working with types, serialized in .NET Framework, .NET Core itself is handling them, thanks to the `TypeForwardedFromAttribute`.

Default type resolver in the new version dynamically loads the required assemblies, so there will be no exceptions, when assembly is on disk, but not loaded into the application. Also, if type resolver was unable to load the assembly using its strong name, it will retry with a partial name, so there's less need in binding redirects.

New version is already released, please see the upgrade guide: https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html.
