### ISSUE TITLE
how to validate cron expression befor run a job

### ISSUE THREAD

**Issue by osmanrahimi** [HangfireIO/Hangfire#1019]
Hi .
I have some jobs but I don't set Interval in hard code and Client Can Set it in Application . now I have a Problem about `Cron expression` . I wanted to use Quartz Library to validate it but `Hangfire` accpet 5 char for `Cron` and Quartz has 7 part in cron expression .
How can I validate Cron  Expression befor assign to `Recuuing Job` .
Thank you very much .

**Comment by pieceofsummer** [comment]
Why don't you just use NCrontab library Hangfire currently uses for cron expressions?

**Comment by osmanrahimi** [comment]
I didn't know Hangfire Uses NCrontab . I do that by Ncrontab . it has Parse and TryParse method to Check Cron Expression .
 thank you

**Comment by SomeoneIsWorking** [comment]
> Why don't you just use NCrontab library Hangfire currently uses for cron expressions?

I don't know what's changed but currently NCrontab and Hangfire doesn't accept the same strings
NCrontab rejects `0 */6 * * ?` (parsing it returns `null`) while 
Hangfire rejects `0 */6 * * *` because either day of month or day of week must be unspecified with `?`

**Comment by GauthierPLM** [comment]
It seems to use Cronos, but they don't use the same format: Cronos uses the format `minute hour day-of-month month day-of-week` (`* * * * *`) while Hangfire also has the year: `minute hour day-of-month month day-of-week year` (`* * * * * *`).

So each time you should add ` *` at the end of your cron expression when sending it to Hangfire, or everything will be shifted to the right (`minute hour day-of-month month day-of-week` will become `0 hour day-of-month month day-of-week year`, ex `1 * * * *` will be treated as `0 1 * * * *` by Hangfire).
