### ISSUE TITLE
DashBoard Not Displaying Graphs

### ISSUE THREAD

**Issue by tomeh100** [HangfireIO/Hangfire#1020]
DashBoard Not Displaying Graphs
Version used: 1.6.17
All Browsers have same issue
Chrome Console output: js1617:100 Error: <path> attribute d: Expected number, "MNaN,250LNaN,250L…". 
![capture](https://user-images.githubusercontent.com/10426017/31344555-a6901248-acd8-11e7-964b-5d12482eb94a.JPG)

**Comment by odinserj** [comment]
I believe this problem was fixed in recent 1.7.0 version, because new charting library is used now that works with canvas.
