### ISSUE TITLE
Some issues with displaying context info with different DB

### ISSUE THREAD

**Issue by bvadeveloper** [HangfireIO/Hangfire#1021]
Hi all, we are need some route to resolve an issue with context.WriteLine() extension.
The problem appears only when we use MySql or Postgres DB for our instances.
When we call method context.WriteLine() the data is placed in a specific table without any problems and we can navigate it.
But in UI no any sections appeared for particular jobs.
This problem doesn't appear for MsSql server. The additional sections we can see in a normal way.
Any suggestions?

Thanks.

**Comment by pieceofsummer** [comment]
What framework and packages/versions are you using? Console works fine with both Hangfire.MySqlStorage and Hangfire.PostgreSql.

```xml
  <package id="Hangfire.Console" version="1.3.8" targetFramework="net452" />
  <package id="Hangfire.Core" version="1.6.17" targetFramework="net452" />
  <package id="Hangfire.MySqlStorage" version="1.0.5" targetFramework="net452" />
  <package id="Hangfire.PostgreSql" version="1.4.8.1" targetFramework="net452" />
```

There were issues with Hangfire.MySqlStorage ≤ 1.0.3 and Hangfire.PostgreSql ≤ 1.4.7, but they're resolved in the later versions.

**Comment by bvadeveloper** [comment]
Sorry guys, our project under version **.Net Core 2.0**
Here are references to nuget packages:
```
    <PackageReference Include="Hangfire" Version="1.6.17" />
    <PackageReference Include="Hangfire.Console" Version="1.3.8" />
    <PackageReference Include="Hangfire.MySql.Core" Version="2.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
```

As example you can see this repo: [https://github.com/bvadeveloper/HangfireCore](https://github.com/bvadeveloper/HangfireCore)

**Comment by bvadeveloper** [comment]
All init logic in [https://github.com/bvadeveloper/HangfireCore/blob/master/WebApplicationHangFireMySqlCoreTest/Startup.cs](Startup.cs) file.

First added service with connection to the MySql:
```
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
  services.AddHangfire(x => x.UseStorage(new MySqlStorage("Server=localhost;Port=3306;Database=Jobs;Uid=root;Pwd=qwerty;Allow User Variables=True")));
  services.AddMvc();
}
```

Second added:
```
app.UseHangfireServer();
app.UseHangfireDashboard("");

RecurringJob.AddOrUpdate(() => Job(null), Cron.Minutely);
```

And last payload for job:
```
public void Job(PerformContext context)
{
    for (int i = 0; i < 10; i++)
    {
        context.WriteLine("Write line through context.WriteLine() extension");
     }
}
```

**Comment by bvadeveloper** [comment]
And screenshots:
![image](https://user-images.githubusercontent.com/28669679/31426548-76e2b312-ae6c-11e7-91c0-96ea6227440c.png)
![image](https://user-images.githubusercontent.com/28669679/31426570-8d2f15ac-ae6c-11e7-8703-82e23081494a.png)

**Comment by pieceofsummer** [comment]
Erm, you seem to never call `UseConsole()` during initialization. 

Also I'm not sure what `Hangfire.MySql.Core` is because it looks like a copy of some version of `Hangfire.MySqlStorage` with changed namespaces and compiled for .net standard. Since `Hangfire.MySqlStorage` now supports .net standard in 1.1.0-alpha, I don't see any reason to use its half-baked clones without even a community support.

**Comment by bvadeveloper** [comment]
Thanks a lot.
Yeh, it's my fault in the sample, in work solutions `UseConsole()` was added earlier.
By your suggestion, I changed the implementation to Hangfire.MySqlStorage 1.1.0-alpha and now it works fine.

![image](https://user-images.githubusercontent.com/28669679/31428706-602ba964-ae74-11e7-8194-d33685f4551c.png)
