### ISSUE TITLE
Intercepting the service scope.

### ISSUE THREAD

**Issue by dazinator** [HangfireIO/Hangfire#1024]
For asp.net core, The `AspNetCoreJobActivator` creates a `JobActivatorScope` from which all services are resolved for the lifetime of a job, and then this scope is disposed of at the end of the job.

I am using a business object framework called `CSLA` and in my hangfire job I need to use my business objects.
CSLA doesn't support DI out of the box, but does allow you to implement your own DI mechanism via various hooks.

I implement one of these hooks, so that when CSLA is used during an ordinary http request (i.e within an MVC controller etc), the `IServiceProvider` from `HttpContext.RequestServices` is used to provide DI for the CSLA objects. This ensures that all services scoped to the request (such as EF db context) are also used by my CSLA business layer.

However when operating from a hangfire job, there is no HttpContext. In this scenario - I need to grab the `JobActivatorScope` that Hangfire is creating, and use it's scoped `IServiceProvider` for DI purposes in my CSLA business layer.

So my question is, is there a recommended path / hook for getting hold of the current `JobActivatorScope` when a job is starting. I suspect I would need to derive my own `AspNetCoreJobActivator` and then register that rather than the default?

**Comment by pieceofsummer** [comment]
Since `IServiceProvider` is also a service, it can be injected in your job's constructor:
```c#
class MyJob
{
    private readonly IServiceProvider _services;

    public MyJob(IServiceProvider services)
    {
        _services = services;
    }

    public void MyJobMethod()
    {
         var service = _services.GetService<IMyService>();
         // ...
    }
}
```

**Comment by dazinator** [comment]
@pieceofsummer - It's too late at that point. I want to inject some business object factory classes into my jobs constructor, which means I need to intercept the service provider before the job is constructed.

**Comment by dazinator** [comment]
@pieceofsummer - hmm wait a sec. Let me think this through properly :-)

**Comment by dazinator** [comment]
Ok have investigated more fully. 
The issue was that one of the services I am injecting into my job, uses `Service Location` to resolve a type (limitation of CSLA framework). The `Service Locator` is not aware of the current hangfire `scope` - so I have to make it aware, _before I use the service_.  This means I can inject the service and the `IServiceProvider` like you have suggested, and set up the service locator in the constructor. I can see this being forgotten quite easily though, so I am now looking at how I can get access to the scope perhaps through a custom activator.

**Comment by pieceofsummer** [comment]
You'll have some troubles writing your own .net core activator because AspNetCoreJobActivator needs `IServiceScopeFactory` instance which you don't have since the underlying `IServiceProvider` is not exposed to `AddHangfire`'s configuration block.

You may workaround it though by changing the way you initialize Hangfire:
```
services.AddSingleton<Action<IGlobalConfiguration>>(serviceProvider =>
{
    return config =>
    {
        var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
        if (loggerFactory != null)
            config.UseLogProvider(new AspNetCoreLogProvider(loggerFactory));

        var scopeFactory = serviceProvider.GetService<IServiceScopeFactory>();
        if (scopeFactory != null)
            config.UseActivator(new YourCustomJobActivator(scopeFactory));

        // things you normally do in AddHangfire() configuration block:
        config.UseSqlServerStorage("connectionString");
        ...
    };
});

services.AddHangfire(config => {});
```

Then you can derive `YourCustomJobActivator` from `AspNetCoreJobActivator` and customize it as you like.

**Comment by dazinator** [comment]
> since the underlying IServiceProvider is not exposed to AddHangfire's configuration block.

Yep you were right, I have been trying to work around this for the last half hour.

> services.AddSingleton<Action<IGlobalConfiguration>>(serviceProvider =>

Ahh damn yes thats sneaky. I went with a worse approach so might change it to your one:

```
services.AddHangfire(config => {});

 services.AddSingleton<JobStorage>((sp) =>
            {
                var configurationInstance = sp.GetService<IGlobalConfiguration>();
                var configurationAction = sp.GetRequiredService<Action<IGlobalConfiguration>>();
                                
                var serviceScopeFactory = sp.GetRequiredService<IServiceScopeFactory>();                
                var activator = new CslaHangfireJobActivator(serviceScopeFactory);
               // configurationInstance.UseActivator<CslaHangfireJobActivator>(activator);
                configurationAction(configurationInstance);
                // Override default activator.
                JobActivator.Current = activator;
                return JobStorage.Current;
            });
```

**Comment by dazinator** [comment]
@pieceofsummer thank you for your help on this.

**Comment by pieceofsummer** [comment]
@dazinator you're welcome!
