### ISSUE TITLE
How to enqueue batch actions into a specific queue?

### ISSUE THREAD

**Issue by rajivkukreja** [HangfireIO/Hangfire#1034]
Folks -

I am able to enqueue standalone Background Jobs into a specific queue using the following:

```
private static string Enqueue(System.Linq.Expressions.Expression<Action> methodCall, string queue = Queue.Default)
{
    var hf = new BackgroundJobClient();
    return hf.Create(methodCall, new Hangfire.States.EnqueuedState(queue));
}
```

I'm trying to do the same (make them go into a specific queue) for bg jobs enqueued as part of a batch. 

Any suggestions on how to accomplish that?

**A bit more context:**
_I'm trying to take a long running process (that operates of a large set of records) and partition it based on the number of VMs available (assign chunks of records to each server) and then have each VM pick up its own partition and execute it._ 

```
Log.Info($"Starting batch jobs for {partitions} ...");
var bid = BatchJob.StartNew(x =>
{
    // Dispatch all partitions
    foreach (var partition in partitions)
    {
        Log.Info($"Enqueing a job to process partition {partition}");
        x.Enqueue(() => BasePipelinePartition<T>.CreateAndExecute(partition));
    }
});
```

_Each of the batch jobs being enqueued is expected to process one partition. So with a 3-node cluster, I want to spawn 3 jobs (part of the same batch) **but then ensure that each node picks up 1**._ 

_I have everything working, except that when these jobs get picked up - often they are ending up running on the same underlying VM. So, a 3-node cluster is still behaving like a 1-node setup._ 

_I have `BackgroundJobServer` instances (semantically representing a queue .. by ensuring a 1-1 relationship between a bg server instance and queue. That seems to be the only way to constrain the worker count for a queue). With 3 instances of the INGESTSOURCE queue available (1 BackgroundJobServer running that queue on each of the 3 nodes)_

_Now, all I need to do is to make sure batch jobs can be told to use a specific queue. (I have different queues for different purposes ... allowing me to throttle parallel processing based on purpose)_

Ideally, I'd be able to do this:
```
Log.Info($"Starting batch jobs for {partitions} ...");
var bid = BatchJob.StartNew(x =>
{
    // Dispatch all partitions
    foreach (var partition in partitions)
    {
        Log.Info($"Enqueing a job to process partition {partition} into the INGESTSOURCE queue");
        x.Enqueue(() => BasePipelinePartition<T>.CreateAndExecute(partition), "INGESTSOURCE");
    }
});
```
Any recommendations greatly appreciated.

Thanks very much
Rajiv

**Comment by odinserj** [comment]
You can use the `Create` method in batches as well:

```csharp
Log.Info($"Starting batch jobs for {partitions} ...");
var bid = BatchJob.StartNew(x =>
{
    // Dispatch all partitions
    foreach (var partition in partitions)
    {
        Log.Info($"Enqueing a job to process partition {partition} into the INGESTSOURCE queue");
        x.Create(() => BasePipelinePartition<T>.CreateAndExecute(partition), new EnqueueState("INGESTSOURCE"));
    }
});
```

**Comment by rajivkukreja** [comment]
Thanks very much Sergey!
