### ISSUE TITLE
Ability to automatically delete job when retry attempts exceeded

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#104]
Implement the following feature for the `AutomaticRetryAttribute` class:

``` csharp
[AutomaticRetry(Attempts = 5, OnAttemptsExceeded = AttemptsExceededAction.Delete)]
public void SomeMethod() 
{
}
```

Instead of failing a job, the filter should change its state to `DeletedState` if specified. Default attempts exceeded action should be `AttemptsExceededAction.Fail`.

**Comment by rohanaceres** [comment]
This only removes the job from error queue, right? What about completely removing it from Hangfire? Is there a way to do this?
