### ISSUE TITLE
In RecurringJob , Job [A] does not  completed and still running, and then a new job [A] starts, it maybe makes two jobs  processing the same data.

### ISSUE THREAD

**Issue by ccccccmd** [HangfireIO/Hangfire#1040]
In RecurringJob , Job [A] does not  completed and still running, and then a new job [A] starts, it maybe makes two jobs  processing the same data. what  should I do to deal with this situation. for i can't handle the job's running time,so i can't set a reasonable Corn

**Comment by dcorbett-fivebridgesllc** [comment]
Check the discussion on this page, covering the topic:

http://docs.hangfire.io/en/latest/background-methods/performing-recurrent-tasks.html

It appears these two attributes deal with this situation:

[DisableConcurrentExecution(5)], 
[AutomaticRetry(Attempts = 0, LogEvents = false, OnAttemptsExceeded = AttemptsExceededAction.Delete)]

I haven't yet tried recurring jobs myself...  So I can't guarantee they work.

**Comment by ccccccmd** [comment]
@dcorbett-fivebridgesllc  
thanks a lot! i'll try it.

**Comment by odinserj** [comment]
@ccccccmd, don't use it, please see #1053. @dcorbett-fivebridgesllc, looks like you are using them, and looks like they do cause your issues with non-processed queues, please see #1053 too.

**Comment by dcorbett-fivebridgesllc** [comment]
Any issues I have are not related to use of DisableConcurrentExecution.   Not using recurring jobs, and not using this attribute.   I had just seen the thread with a solution, and shared it here.

**Comment by henrik-donuts** [comment]
I created a new MaxConcurrentExecutions filter that handles this correctly: https://gist.github.com/henrik-donuts/0e38af74f95ebfce103fd2568d3455f7

**Comment by Ruud-cb** [comment]
@henrik-donuts 404 on that page...

**Comment by odinserj** [comment]
There's a special attribute that can be applied to a recurring job method that prevents recurring job scheduler to schedule a new job while previous one is still running, please see this gist for the [source code](https://gist.github.com/odinserj/a6ad7ba6686076c9b9b2e03fcf6bf74e) for that attribute. You can apply it by placing an attribute to a job method as in the following sample.

```csharp
[SkipWhenPreviousJobIsRunning]
public void MyMethod()
```
