### ISSUE TITLE
Deprecate `Cron.XXXInterval` methods

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#1041]
Neither of these methods works correctly, when the specified interval is not a multiple of the corresponding field's range length (max-min). For example, when we are using `Cron.HourInterval(10)`, we will not get the documented *every 10 hours* semantic, instead we'll get the following occurrences:

```
Nov 6, 00:00
Nov 6, 10:00
Nov 6, 20:00 
Nov 7, 00:00
```

Time interval between the last two entries is only 4 hours and violates what's written in the method's name and in its comments. Cron expressions don't allow to specify "every N" recurring intervals in general, and other methods should be used instead of confusing methods. These methods should be deprecated with the `ObsoleteAttribute` and removed in the next major version.

**Comment by almez** [comment]
Hi,

Please find my first contribution to this repository.

Regards,

**Comment by crawdell** [comment]
I'd like to propose something I've done before to handle cron intervals.  I needed a solution to "every 2 weeks" when using Ncrontab Advanced and so I extended the functionality to allow for "Xnn" to be added to a cron expression.  

Example:
00 00 * * FRI X2

Without "X2" this would just be every Friday at midnight.  But with X2 I would getnextoccurance 2 times and use the second value as the next run time which would be 2 weeks.

This can be useful for doing all kinds of new variations.  It can also lead to confusing results sometimes if you don't think about your expression carefully but that's true of all cron expressions.

This I think helps fill in a gap that cron has and has been very useful for my scheduled jobs. Now that I'm using Hangfire I'll love to see this included.  

I'm on the 1.7.0 beta and it works great.  If this could somehow be added that would be very helpful. If not I might try my own version with the source either by extending Hangfire or more likely Cronos.
