### ISSUE TITLE
How does Hangfire decide which host to execute my job on?

### ISSUE THREAD

**Issue by cottsak** [HangfireIO/Hangfire#1043]
same default queue.
is there some kind of "health check" or performance metric that is maintained with the Heartbeat which guides the dispatch to one host vs another?

**Comment by pieceofsummer** [comment]
It doesn't really. The job is just executed by any free worker that picks it first.

**Comment by dcorbett-fivebridgesllc** [comment]
Worse, is that that free worker, grabs all that it can grab...  so if there are 30 jobs available to grab and you have 3 servers empty, and the capacity of the free worker is 30, it will grab all 30.

There's no way to automatically spread the load amongst the servers.

**Comment by cottsak** [comment]
So is a "pull" strategy from the worker's point of view?
If I'm seeing a bias to one worker verses others it's possible some other contention on the host is preventing the worker from "pulling" as quickly?

MK
On Tue, Nov 7, 2017 at 21:03, dcorbett-fivebridgesllc <notifications@github.com> wrote:
Worse, is that that free worker, grabs all that it can grab... so if there are 30 jobs available to grab and you have 3 servers empty, and the capacity of the free worker is 30, it will grab all 30.

There's no way to automatically spread the load amongst the servers.

**Comment by dcorbett-fivebridgesllc** [comment]
A bias?    I think it's more about timing, as to when the worker is polling.   I think if a server does a pull, it will pull all it can, no matter what else that machine is doing.  At least that is my experience, and something I'd like to change.

**Comment by cottsak** [comment]
I have two hosts and I'm noticing that the one with the least memory pressure often gets all the jobs, sometimes leaving the first with few to none.
If this is by design or simply an artefact of the simple pull syrategy, perhaps it's best left as is, no?

MK
On Tue, Nov 7, 2017 at 21:13, dcorbett-fivebridgesllc <notifications@github.com> wrote:
A bias? I think it's more about timing, as to when the worker is polling. I think if a server does a pull, it will pull all it can, no matter what else that machine is doing. At least that is my experience, and something I'd like to change.

**Comment by odinserj** [comment]
If you are using SQL Server as a job storage, the behavior can be caused by the nature of polling. Default polling interval there is 15 seconds. Workers that didn't get any job on a previous iteration will sleep for 15 seconds, and workers that processed a job on previous iteration will not wait, and will try to get the next job immediately instead.

Regarding spreading the work across servers, it's better to limit the number of workers for CPU-bound jobs to the number of cores (`Environment.ProcessorCount`), and increase their number for I/O-bound jobs. The default value of workers is a compromise.

The things will be much better with the introduction of a fully asynchronous pipeline. In this case we can use `Environment.ProcessorCount` number of threads that are executing background jobs, and other option `MaxConcurrency` will allow a worker to take other jobs, when the previous one awaits for some task.

**Comment by cottsak** [comment]
@odinserj That makes a lot of sense.

To be clear: I'm not having troubles with jobs getting completed or any throughput issues. I'm just curious why I don't see what I might consider an *even distribution* of jobs between servers (default 20 workers each).

**Comment by pieceofsummer** [comment]
@cottsak there’s nothing good about even distribution.

Suppose you have two recurring jobs A and B that run every 3 minutes. Job A completes in just a few seconds, but job B takes around full 3 minutes to complete. 
If you do an even distribution of enqueued jobs between two servers, it is very likely that all A instances will go to first server, while all B instances – to the second one.
So the second server would be running non-stop, but the first one would be idle most of the time. And it could actually take other jobs to execute, but… it won’t be an even distribution then :)

**Comment by odinserj** [comment]
Such a job scheduler will be a bottleneck of a processing system, and any scale out techniques will require to synchronize work between different schedulers and have an even distribution. In a distributed system any synchronization takes a lot of time, so we'll end with greatly reduced throughput, and a very complex system.

**Comment by cottsak** [comment]
Makes sense. I can see how the simplicity of the pull approach makes the most sense then. Thanks everyone.

MK
On Wed, Nov 8, 2017 at 16:32, Sergey Odinokov <notifications@github.com> wrote:
Such a job scheduler will be a bottleneck of a processing system, and any scale out techniques will require to synchronize work between different schedulers and have an even distribution. In a distributed system any synchronization takes a lot of time, so we'll end with greatly reduced throughput, and a very complex system.
