### ISSUE TITLE
Consider how to add the PerformContext.Storage property

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#1044]
By an unknown reason (more precisely for its absence), there's no reference to the current storage in the `PerformContext` class. All the other contexts have it, and any `PerformContext` instance is tied to a single storage, so there are no conceptual problems here.

But there's a backward compatibility problem, because constructor of the `PerformContext` is public, and any modification can introduce compile time errors after migration to 1.7.0. But if such an improvement worth this price, the feature should be implemented. AFAIK that constructor was added only recently.

@pieceofsummer, leaving this decision to you, since you've requested it in https://github.com/pieceofsummer/Hangfire.Console/issues/45#issuecomment-342568847.

**Comment by pieceofsummer** [comment]
> there's a backward compatibility problem, because constructor of the `PerformContext` is public, and any modification can introduce compile time errors after migration to 1.7.0

I think this is not actually an issue because there's little to none 3rd-party implementations of `Worker` class (where `PerformContext` is instantiated), and there's no particular reason to instantiate it anywhere else (except for some unit tests maybe). 

We could preserve the old constructor as well (marking it as deprecated), and initialize `Storage` with `null` for this case. Since the old unit tests won't use the newly added `Storage` property, it would be fine to leave it `null`.

**Comment by odinserj** [comment]
There's little to none *known* implementation, who knows what's happening in proprietary applications... So we will either hurt extension developers who's using the `Storage` property (currently nobody, since no such a property exist), or advanced users who use custom workers (no information).

**Comment by pieceofsummer** [comment]
I personally doubt there's a lot of people who (for whatever reason) rewrote the entire server part to use custom workers, but okay, let's postpone this until v2.0.

**Comment by odinserj** [comment]
Nullable `Storage` property looks fine, so we could introduce it in 1.7. Extension developers should take into consideration that it could be `null`, and throw an exception, use `JobStorage.Current` or whatever. We can also mark constructor overload without the storage parameter with the `ObsoleteAttribute`.

**Comment by odinserj** [comment]
Added in 4beadbcad47d34527e57a5113acfc3c05ac64593 as described above.
