### ISSUE TITLE
Mock BackgroundClientJob. need help

### ISSUE THREAD

**Issue by norvamod** [HangfireIO/Hangfire#1045]
Hi,

Hangfire version: 1.6.17
I have one method and I want to test it. This method is calling hangfire background job:
              `  _hangfireJobClient.Enqueue(() => _myApplicationsJob.GenerateApplicationChangeStatusPrint(hangfireArguments)); `
I don't want to test hangfire job, just run main tests.

We are using Rhino.Mock in unit tests.
I mocked that client:
_`_backgroupJobClient = MockRepository.GenerateStub<IBackgroundJobClient>();`_

but when I am running test, I'm getting error: 
![error](https://user-images.githubusercontent.com/33456591/32542280-b9e4e63e-c47a-11e7-81ad-0730b259fcf1.jpg)

I looked into this http://docs.hangfire.io/en/latest/background-methods/writing-unit-tests.html , but my project is using Rhino.Mock framework, not Moq as it is in example.

maybe here are any ideas how to resolve that?

**Comment by pieceofsummer** [comment]
Since you're using DI, I recommend using `_backgroundJobClient.Enqueue<IMyApplicationJob>(x => x.GenerateApplicationChangeStatusPrint(hangfireArguments))` instead, because it avoids additional instance variable method lookups (which may lead to method not found in your case).

Cannot tell more without knowing what `_myApplicationsJob` is, and what kind of `hangfireArguments ` you're passing.

**Comment by norvamod** [comment]
It worked!
Thanks!

**Comment by pieceofsummer** [comment]
Please provide some more details nevertheless, because it might be actually a bug. Your test case might help to fix it.

**Comment by norvamod** [comment]
Ok,

what additional information do you need?

here is arguments:
```
            var hangfireArguments = new MyApplicationsJobArguments(LocalContext.GetContextObject<CustomerKeyContext>().CustomerKey)
            {
                ApplicationRequestId = applicationRequest.Id,
                SchoolYearId = schoolYear?.Id ?? GetCurrentSchoolYear().Id,
                LogedOnPersonId = GetCurrentPerson().Id,
                JobContextId = Guid.NewGuid(),
            };
```

**Comment by pieceofsummer** [comment]
The declared type of `_myApplicationsJob` variable, the actual type of the object assigned to it, and `GenerateApplicationChangeStatusPrint` method signature, for starters.

A small sufficient example to reproduce the issue would be a plus.

**Comment by norvamod** [comment]
```
        public void GenerateApplicationChangeStatusPrint(MyApplicationsJobArguments myApplicationJobArguments)
        {
            var databaseContextHandler = new DatabaseContextHandler(myApplicationJobArguments.CustomerKey);
            databaseContextHandler.SetUpCustomerContext(_efSession); // get right database

            var applicationRequest = _applicationService.GetApplicationRequestById(myApplicationJobArguments.ApplicationRequestId);
            
            var schoolYear = _schoolYearService.GetSchoolYearByYearId(myApplicationJobArguments.SchoolYearId);
            var logedOnPerson = _personService.GetPerson(myApplicationJobArguments.LogedOnPersonId);

            Guid jobContextId = Guid.NewGuid();
            GenerateApplicationDecisionFile(applicationRequest, schoolYear, logedOnPerson, jobContextId);

           BackgroundJob.Enqueue<IKsSvarUtElectronicDeliveryJob>(x => x.SendDeliveriesCreatedByJob(new KsSvarUtElectronicDeliveryJobArguments(LocalContext.GetContextObject<CustomerKeyContext>().CustomerKey, jobContextId)));
            _efSession.FlushAllOpenSessionsInLocalContext();
            databaseContextHandler.DisposeCustomerContext();
        }

```

**Comment by pieceofsummer** [comment]
Still, need more info. 

What is (was) the type of `_myApplicationsJob` variable? Is it an interface? Please provide its declaration.
Also what class `GenerateApplicationChangeStatusPrint` is declared in, and how it implements the above interface?
