### ISSUE TITLE
System.OutOfMemoryException Dashboard

### ISSUE THREAD

**Issue by reminvestor** [HangfireIO/Hangfire#1051]
After using Hangfire to  BackgroundJob.Enqueue I get a exception thrown that is caught by my OWIN Middlewhere. Any idea on this?

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Hangfire.Dashboard.JobMethodCallRenderer.Render(Job job)
   at Hangfire.Dashboard.Pages.JobDetailsPage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPage.ToString()
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.MiddlewareExtensions.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PPSC.ECT.Web.Helpers.OwinExceptionHandlerMiddleware.<Invoke>d__3.MoveNext() in C:\_code\PPSC.ECT\PPSC.ECT.Web\Helpers\OwinExceptionHandlerMiddleware.cs:line 28

**Comment by odinserj** [comment]
Wow, could you post here the full signature of your background job method?

**Comment by archeg** [comment]
When I click on the details of my job, I see this:
```
[OutOfMemoryException: Der blev udløst en undtagelse af typen 'System.OutOfMemoryException'.]
   System.String.ReplaceInternal(String oldValue, String newValue) +0
   System.String.Replace(String oldValue, String newValue) +20
   Hangfire.Dashboard.ArgumentRenderer.Render(Boolean isJson, String deserializedValue, String rawValue) +288
   Hangfire.Dashboard.JobMethodCallRenderer.Render(Job job) +1425
   Hangfire.Dashboard.Pages.JobDetailsPage.Execute() +2092
   Hangfire.Dashboard.RazorPage.TransformText(String body) +26
   Hangfire.Dashboard.RazorPage.ToString() +7
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +65
   Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +341
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +273
```

Probably the same issue. The job is created via `BackgroundJob.Enqueue` by calling:
```
  [AutomaticRetry(Attempts = 0)]
        public void Execute(ReportTaskResult result)
```
Where `ReportTaskResult` is a rather big object, that even has a few byte arrays having 4 Mb of data each.

**Comment by IanYates** [comment]
That `4 Mb of data each` bit is the key part of your post.

It's recommended that for big chunky things like that you push the data to some permanent storage like a database or file on disk.  Then your job just gets some identifier (database id or filename) and loads the data again itself.  That load could even go via some in-process cache, like a Dictionary, if you want to optimise for the happy path of already having the data in RAM.

Getting the 4Mb of text into a format to display in a webpage is causing you the grief.  Are you able to stash the data elsewhere and just deal with an identifier instead?

**Comment by archeg** [comment]
Yeah, I had an assumption this is the issue. I also think I've seen Out of memory even without dashboard, somewhere during processing, - but I'm not sure.
I have moved this byte chunk out of json and it seemed to work - but I would still expect Hangfire to properly handle such situations. I guess if byte array is bigger than 100 elements - it is sane not to try to display it.
If it prevents normal working conditions - then it is another story. But still would be nice for hangfire to show some kind of warning - I don't think this behaviour is expected.

**Comment by odinserj** [comment]
Recommended or not, we shouldn't cause the whole process to fail. I've added #1153 PR to resolve this as a part of 1.6.18 release.
