### ISSUE TITLE
[DisplayName("testing 123")] doesn't work on override methods

### ISSUE THREAD

**Issue by cottsak** [HangfireIO/Hangfire#1059]
Here is a job method I have:

``` c#
    internal class BiPlatformRefreshJob : CacheRefreshJob
    {
            // snip

        [DisplayName("testing 123")]
        public override void Run()
        {
            // snip
        }
    }

    internal abstract class CacheRefreshJob
    {
        internal virtual int RefreshIntervalInMinutes => 1;
        public abstract void Run();
    }
```

The Job name shows as the base type and renders like `CacheRefreshJob.Run` which isn't ideal since it's the same for every "refresh job". I was expecting the `testing 123`.

I thought this might work since the interface alternative [seems to work according to this comment](https://github.com/HangfireIO/Hangfire/issues/170#issuecomment-50009114).

`[DisplayName("testing 123")]` works when I put it on the base type like:
``` c#
[DisplayName("testing 123")]
public abstract void Run();
```
.. but that's obviously not what I want either since it's the same for everything.

Ideally I'd like to specify the job name when I create the recurring job as I already have to specify the `recurringJobId` manually like so:
``` c#
            foreach (var j in container.Resolve<IEnumerable<CacheRefreshJob>>())
            {
                RecurringJob.AddOrUpdate(j.GetType().Name, (CacheRefreshJob jj) => jj.Run(), Cron.MinuteInterval(j.RefreshIntervalInMinutes));
            }
```

but I'll settle for 
``` c#
    internal class BiPlatformRefreshJob : CacheRefreshJob
    {
            // snip

        [DisplayName(nameof(BiPlatformRefreshJob))]
        public override void Run()
        {
            // snip
        }
    }
```
which also doesn't work. :disappointed: 

My versions:
``` xml
  <package id="Hangfire" version="1.6.17" targetFramework="net452" />
  <package id="Hangfire.Autofac" version="2.3.1" targetFramework="net452" />
  <package id="Hangfire.Core" version="1.6.17" targetFramework="net452" />
  <package id="Hangfire.SqlServer" version="1.6.17" targetFramework="net452" />
```

My `startup.cs` code:
``` c#
            Hangfire.ConfigureAndStart(app, container);
            Hangfire.EnqueueBackgroundJobs(container);
```
which looks like:
``` c#
        internal static void ConfigureAndStart(IAppBuilder app, IContainer container)
        {
            GlobalConfiguration.Configuration
                .UseSqlServerStorage(Config.StoreConnString)
                .UseAutofacActivator(container, useTaggedLifetimeScope: false);

            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            { Authorization = new[] { new StellaAdminHangfireAuthFilter() } });
            app.UseHangfireServer();

            GlobalJobFilters.Filters.Add(new LogToExceptionalAttribute());
            GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 0 });
        }

        internal static void EnqueueBackgroundJobs(IContainer container)
        {
            // Refresh Jobs for dashboards
            foreach (var j in container.Resolve<IEnumerable<CacheRefreshJob>>())
            {
                RecurringJob.AddOrUpdate(j.GetType().Name, (CacheRefreshJob jj) => jj.Run(), Cron.MinuteInterval(j.RefreshIntervalInMinutes));
            }

            // perf sampler for the above jobs
            RecurringJob.AddOrUpdate((HangfireJobSampler s) => s.Run(),
                Cron.MinuteInterval(HangfireJobSampler.SampleFrequencyInMinutes));
        }
```

**Comment by pieceofsummer** [comment]
It is likely not just `DisplayName` not working, but all your jobs won't work as expected too.

`(CacheRefreshJob jj) => jj.Run()` creates a job that would run `Run` method on `CacheRefreshJob` class (and not on its particular subclass), and the actual instance itself will be resolved by activator at runtime. You probably need to use `() => j.Run()` instead (also beware of loop variable capture).

**Comment by cottsak** [comment]
@pieceofsummer I would have made that assumption also however when I used the `j` instance, it wouldn't work. `jj` does work however and I can't explain it. I suspect that the `j` is captured in some way and so when the activator tries to find an instance of `CacheRefreshJob`, it has the `j` instance available and it *is the descendant type*, and so it works. But that's not my [main] issue here. 

I want to set the Job name. Can you help?

**Comment by pieceofsummer** [comment]
I believe the job name will be shown correctly as soon as you make it register a correct descendant type instead of a base one.

You may also try `AddOrUpdate` overload taking `Job` argument, and use `Job.FromExpression(() => j.Run(), j.GetType())` syntax to enforce the specific instance type.

**Comment by cottsak** [comment]
@pieceofsummer You are right. It was my goofed up registration.

Now I register the descendant type as both itself and the base type:
``` c#
        private void RegisterRefeshJobs(ContainerBuilder builder)
        {
            // get all refresh job types
            var refreshJobTypes = typeof(DashboardV2).Assembly.GetTypes()
                .Where(t => typeof(CacheRefreshJob).IsAssignableFrom(t)).Except(new[] { typeof(CacheRefreshJob), })
                .ToList();

            foreach (var jobType in refreshJobTypes)
            {
                builder.RegisterType(jobType).AsSelf().InstancePerLifetimeScope();
                builder.RegisterType(jobType).As<CacheRefreshJob>().InstancePerLifetimeScope();
            }
        }
```

And now this works fine:
``` c#
            foreach (var j in container.Resolve<IEnumerable<CacheRefreshJob>>())
            {
                RecurringJob.AddOrUpdate(j.GetType().Name, () => j.Run(), Cron.MinuteInterval(j.RefreshIntervalInMinutes));
            }
```

And the job name is the unique method rather than the base type so I'm happy so move on:
![happy days](https://image.ibb.co/mzQOAw/Screenshot_2017_11_14_09_24_49.png)
