### ISSUE TITLE
Hash and Set tables too large?

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#1060]
When does data in these tables get expired/truncated?

In our QA system, our SQL backed hangfire database is running quite slow.   There are 35,413,001 Set rows ( probably due to excessive console.WriteLine() messages on our end ), along with 695,377 Hash rows.

This causes our Hangfire UI to crawl.   Not saying there's actually a bug here, just trying to understand what's going on.   The jobs that would have created these console messages are succeeded, and at least 4 days old, probably much older.

Going to clear out the database for now, so that QA can get their work done... but would like to understand better going forward.

Thanks,

   - Daniel

**Comment by pieceofsummer** [comment]
@dcorbett-fivebridgesllc there was an issue in Hangfire.Console that caused lines not being expired in some cases, which is fixed in 1.3.10. Try deleting those rows manually, and update to the latest Console version:
```sql
DELETE FROM HangFire.[Hash]
WHERE [Key] LIKE 'console:refs:%'
  AND CAST(SUBSTRING([Key], 24, LEN([Key]) - 24) AS int) NOT IN (
    SELECT Id FROM HangFire.Job
  )
  AND ExpireAt IS NULL

DELETE FROM HangFire.[Set]
WHERE [Key] LIKE 'console:%'
  AND CAST(SUBSTRING([Key], 19, LEN([Key]) - 19) AS int) NOT IN (
    SELECT Id FROM HangFire.Job
  )
  AND ExpireAt IS NULL
```
