### ISSUE TITLE
Configure SQL polling interval per BackgroundJobServer

### ISSUE THREAD

**Issue by brettzink** [HangfireIO/Hangfire#1062]
I'm using Hangfire to consolidate what was a handful of nservicebus services. I'm using TopShelf, SQL Server and multiple `BackgroundJobServer` instances with named queues to distribute the load so high priority tasks are not affected by lower priority tasks. 

I have a set of tasks that need executed in near real-time. I want to set the polling interval for this queue to be 1 second. This option is only available as a global option though and affects any `BackgroundJobServer`

It appears my only options are to set the polling interval low for all servers/queues. Or deploy a 2nd service who's job is to be the "High Priority" server. 

Is there any thought about moving some of the GlobalConfiguration so it can be specified on a per-server basis?

**Comment by brettzink** [comment]
I eventually found the overload to `BackgroundJobServer` where I can specify the `JobStorage`. I can pass `SqlServerStorageOptions `in that way.

**Comment by burningice2866** [comment]
An option is also to implement your job as a BackgroundProcess. Its described on the [frontpage](https://www.hangfire.io/overview.html#background-process) as when you need to run background processes continuously throughout the lifetime of your application.

I use them throughout my applications and they work fine. Only caveat is that they don't show up in the dashboard, you can't manually trigger them or do Console Logging.
