### ISSUE TITLE
Hangfire dashboard issue nginx proxy

### ISSUE THREAD

**Issue by tru3d3v** [HangfireIO/Hangfire#1067]
Hi, Guys

How to change the url for the css and javascript in the dashboard ? 

var options = new DashboardOptions { AppPath = "http://your-app.net" };
app.UseHangfireDashboard("/hangfire", options);

but the problem is the main page  still error 500. i am using nginx proxy for the interfacing.

	/*NGINX Forwarding*/
			app.UseForwardedHeaders(new ForwardedHeadersOptions
			{
				ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
			});

**Comment by pieceofsummer** [comment]
How exactly is your nginx configured? Also, there should be something meaningful in .net logs.

**Comment by tru3d3v** [comment]
Hi @pieceofsummer 

The problem is the Layout.cshtml is not correctly.

i already follow instruction how to setting the dashboard.

and here is below my nginx configuration:
#Main URL
location / {
	proxy_pass http://localhost:5002;
	proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
	}
location ^~ /hangfire/ {
                 proxy_pass http://localhost:5004/;
        }

**Comment by pieceofsummer** [comment]
Your configuration is a bit strange:
1. `^~` prefix is not necessary because there are no regex patterns present.
2. The second location doesn't have all proxy headers present. They're not inherited from the first one because locations are not nested.
3. You should stop nginx from normalizing URI when passing it to the proxy (by removing trailing slash after `localhost:5004`), or explicitly specify proxy URI (`proxy_pass http://localhost:5004$request_uri;`), or serve Dashboard on the root in your backend (`app.UseHangfireDashboard("/", options);`)

**Comment by tru3d3v** [comment]
Hi @pieceofsummer 

I try with 2 scenario:
Scenario 1 : nginx version 1.12.1 (ubuntu AWS) --> always (error 404)
configuration:
location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
		proxy_pass http://localhost:5002;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection keep-alive;
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}
location /hangfire{
	    proxy_pass http://localhost:5004;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
	}

scenario 2 :  Macbook nginx version 12.2 (it's work)

forwarded headers in startup.cs

var options = new ForwardedHeadersOptions
			{
				ForwardedHeaders = ForwardedHeaders.All
			};
			options.KnownNetworks.Clear();
			options.KnownProxies.Clear();
			app.UseForwardedHeaders(options);

😞

**Comment by tru3d3v** [comment]
Problem solved. 

startup.cs

                       app.UsePathBase("/hangfire/");

			/*NGINX Forwarding*/
			var options = new ForwardedHeadersOptions
			{
				ForwardedHeaders = ForwardedHeaders.All
			};
			options.KnownNetworks.Clear();
			options.KnownProxies.Clear();
			app.UseForwardedHeaders(options);
