### ISSUE TITLE
ReccuringJob delay job x minutes

### ISSUE THREAD

**Issue by rauntska** [HangfireIO/Hangfire#1068]
Hi,

Got a quick question.
I have a reccuring job that runs after every 30mins.
` RecurringJob.AddOrUpdate<DoJob>("job1", x => x.DoWork(null), Cron.MinuteInterval(30))`

It always runs on the full hour xx:00 or xx:30 . How can i trigger the job to still run at after every 30 mins , but lets say that always xx:05 and xx:35 ?

Thanks!
Rauno

**Comment by pieceofsummer** [comment]
You can use the following cron expression: "[5/30 * * * *](https://crontab.guru/#5/30_*_*_*_*)".

**Comment by rauntska** [comment]
Worked thanks :)
