### ISSUE TITLE
ExpirationManager - System.ArgumentOutOfRangeException - Parameter name: timeout

### ISSUE THREAD

**Issue by mberacochea** [HangfireIO/Hangfire#1069]
Hi,

Hangfire is throwing an error constantly and I can't figure out what is happening. The app is working and Jobs are executed as expected.

I'm using:

- Hangfire version=1.6.17 targetFramework=net45
- Hangfire.Core version=1.6.17 targetFramework=net45
- Hangfire.Dashboard.Authorization version=2.1.0 targetFramework=net45
- HangFire.Ninject version=1.2.0 targetFramework=net45
- Hangfire.SqlServer version=1.6.17 targetFramework=net45

My config:

```C#
Hangfire.GlobalConfiguration.Configuration.UseNinjectActivator(CreateKernel());

Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireConnection", new Hangfire.SqlServer.SqlServerStorageOptions
{
	JobExpirationCheckInterval = TimeSpan.FromDays(30),
});

app.UseHangfireDashboard("/hangfire");
app.UseHangfireServer();
```

On the log I'm getting:
```C#
2017-11-30 18:06:53,983 ERROR Hangfire.SqlServer.ExpirationManager - Error occurred during execution of 'Hangfire.SqlServer.ExpirationManager' process. Execution will be retried (attempt #14) in 00:03:14 seconds.
System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: timeout
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout)
   at Hangfire.SqlServer.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

**Comment by pieceofsummer** [comment]
30 days is too much for `JobExpirationCheckInterval`. It would be `2 592 000 000` milliseconds (30 * 24 * 60 * 60 * 1000), which is larger than `Int32.MaxValue`.

`JobExpirationCheckInterval` determines how often Hangfire will check if there are some jobs to clean up, and it shouldn't typically exceed 1 hour.

You've probably mistaken it for `JobExpirationTimeout`, which determines how long the jobs live after completion. That could be set with an `IElectStateFilter`.

I hope there would be more sanity checks for configuration parameters in the future builds.

**Comment by mberacochea** [comment]
Excellent, I completely missed that.

Thank you
