### ISSUE TITLE
Limit length of serialized arguments in Dashboard

### ISSUE THREAD

**Issue by toraora** [HangfireIO/Hangfire#1070]
Occasionally some of my Hangfire requests will have large payloads (List&lt;string&gt; with millions of entries being the most common). It would be nice to configure the dashboard to be able to truncate the lengths of these long arguments.

I can submit a PR for this feature

**Comment by pieceofsummer** [comment]
Passing arguments that big would blow up database size, affect performance, and might even exceed allowed limits for some storages.

See also: https://github.com/HangfireIO/Hangfire/issues/980.

**Comment by odinserj** [comment]
Closing, this feature is already implemented in 1.6.18.
