### ISSUE TITLE
getting error just in once jobs

### ISSUE THREAD

**Issue by osmanrahimi** [HangfireIO/Hangfire#1072]
I've getting below error just in one of the all Background.Enque()
> Autofac.Core.Registration.ComponentNotRegisteredException
> The requested service 'XService' has not been registered. To avoid this exception, either register a 
> component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

I have a method like this :
   
```csharp
 public async Task<Result> Handle(modelCommand message)
        {
          //codes
            if(conditions)
            {
             
                await _unitOfWork.CommitAsync();

                BackgroundJob.Enqueue<IXService>(e =>e.Send(Date, guid));

                return result;
            }
            else
                return falseResult;
        }
```
I used ` BackgroundJob.Enqueue` several times but just this one return this error .
what is the problem ?

**Comment by odinserj** [comment]
As I understand, Hangfire.Autofac was plugged in, but looks like `XService` implementation wasn't registered for the `IXService` interface, that's why there was an exception.
