### ISSUE TITLE
StatsPollingInterval In Dashboard  Hang fire not working

### ISSUE THREAD

**Issue by jeffreyfloresca04** [HangfireIO/Hangfire#1075]
Does anyone knows how to configure dashboard to avoid calling the Authorize() every 2 secs?  
I tried modifying the StatsPollingInterval to some values i.e 5000(ms) but it seems that this value is just ignore and still use the default(w/c is 2000).?

**Comment by odinserj** [comment]
Can't reproduce this in the newest version, all is working as expected.
