### ISSUE TITLE
Dashboard footer should not display the connection string or it should be optional

### ISSUE THREAD

**Issue by sandorfr** [HangfireIO/Hangfire#1078]
Currently, the connection string is displayed in the footer. It shouldn't or at least it must be very easy to disable this behavior. 

PR : #1079

**Comment by odinserj** [comment]
Hangfire dashboard is designed to be an internal part of your application that is accessible only for developers/devops staff. Could you tell me why they shouldn't see the connection string?

**Comment by sandorfr** [comment]
In my case only the accredited people have access to those information. People with access to the administration backend don't have access to the database or the redis or even the filesystem. They don't need it and the should not have it. People operating the software are not people maintaining the infrastructure. I can give you a simple scenario. Someone in the team operating the software quits, if this kind of information has been exposed, it needs to be changed in addition to his account revoked.
