### ISSUE TITLE
404 when navigating to job detail sub pages

### ISSUE THREAD

**Issue by seraphx2** [HangfireIO/Hangfire#1086]
I am getting a 404 only when navigating to the details page of a job. The dashboard itself loads up just fine. I have been unable to find someone having this same issue. It seems like everyone's issues were with the whole app giving a 404 and not even being able to get into it. I can get in and do different operations (except delete tasks in the queue, but I can delete scheduled jobs). But this 404 error on the critical page to see error information is a bit frustrating when the rest of the app works. Any ideas where to start. Anything in particular you need to see?

![image](https://user-images.githubusercontent.com/11561820/34567929-2cd0c080-f132-11e7-8551-44e35429e7e1.png)

**Comment by seraphx2** [comment]
So as an update, it definitely has to do with some level of permissions. but I was never able to pin it down. I used to host my site on a pure web host and I couldn't see details past the main page. I couldnt delete things either.  I moved to a Virtual Private Server and everything works perfectly there now.

**Comment by asgerjensen** [comment]
Thanks. I noticed now, that on the pages that work, I also get 404's for the font files under /hangfire/fonts/xxx

But thanks for the update

**Comment by odinserj** [comment]
We could try to modify the `RouteCollection.FindDispatcher` method to remove trailing splash for path if exists. This indeed may be an annoying behavior.

**Comment by asgerjensen** [comment]
A little followup: I ran failed request traces for a /jobs/details/xxx, both on my test where it worked, and on the one that didnt and compared them. I was able to confirm that in both instanced it hits the Owin router. In the one that failed it just returned CONTINUE, and the other returned REQUEST-END. 

I also checked that i had the (from memory) useRouteQueryAllHandlers attribute

I didnt see any other interesting info from the trace, but can provide them if necessary.

**Comment by odinserj** [comment]
It's relatively easy to reproduce the issue, so I think no further traces required. Route match check checks the entire path with a strict regular expression, and if there are additional characters like `/`, then match fails. And all the routes don't take the trailing slash into account.

**Comment by odinserj** [comment]
Don't know whether the https://github.com/HangfireIO/Hangfire/commit/10d8090d2f844b6eab66363e5e509e90a683ef46 commit fixed this issue, but I've added changes proposed in this conversation and released the fix in version 1.6.22. Please feel free to re-open the issue if the problem persist.

**Comment by asgerjensen** [comment]
I tested using version 1.6.22, and the issue persists.

`/hangfire/jobs/succeeded` works, but
`/hangfire/jobs/details/8834` does not
`/hangfire/servers` works but
`/hangfire/jobs/enqueued/default` does not


All icons are broken too (same as with 1.6.20)

**Comment by hammond13** [comment]
I seem to be getting this exact problem in Hangfire 1.7.28. It works on my local and devel machines, but on my production machine I get 404s for job details pages and fonts. I assume there's a change I need to make on the production server, but I don't know where to look.
