### ISSUE TITLE
NuGet Install-Package Cycle Detected

### ISSUE THREAD

**Issue by mheptinstall** [HangfireIO/Hangfire#1091]
I receive the error message below when trying to install Hangfire via NuGet in a ASP.Net Core 2.0 project targeting .NET Framework 4.7.1

```
Install-Package : Cycle detected. 
  HangFire -> HangFire (>= 1.6.17).
```

**Comment by rdcm** [comment]
Same poblem `Cycle detected ` with `hangfire -> Hangfire (>= 1.6.19).`

**Comment by blpfullstep** [comment]
I had the same problem using Hangfire 1.6.21.
It was all related to using "HangFire" as default namespace and assembly name.
Once I changed both (I guess the problem was only namespace but I haven't tested it) I was able to install the package..
