### ISSUE TITLE
Job arguments duplicated in SQL Server Job table

### ISSUE THREAD

**Issue by dezfowler** [HangfireIO/Hangfire#1092]
Affected version: 1.6.17
Using Hangfire.SqlServer, no special configuration or filters.

The value of InvocationData.Arguments is duplicated in both the `invocationData` and `arguments` columns however only the value from `arguments` is used when the row is read back out of the table.

This is quite inefficient in terms of both serialization effort and storage space, especially if the arguments are large.

**Comment by odinserj** [comment]
Thanks for reporting! This issue is fixed in the recent [1.7.0-beta1](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.0-beta1) release.
