### ISSUE TITLE
Hangfire Dashboard URL mismatch

### ISSUE THREAD

**Issue by wolfmarco** [HangfireIO/Hangfire#1110]
I mapped the Hangfire Dashboard to the route `/hangfire`.

    app.UseHangfireDashboard("/hangfire")

The Dashboard is reachable by the URL `https://app-dev.example.com/exampleapp/api/hangfire/` after deployment, but the Dashboard URLs point to `https://app-dev.example.com/hangfire/`. Because of this, the Dashboard does not work. Is anywhere a possibility to change the BaseUrl of the Dashboard?

![hangfire_dashboard](https://user-images.githubusercontent.com/3786816/36145108-991ce8ca-10b0-11e8-93fe-75882031ca06.png)

**Comment by natiki** [comment]
Webforms, MVC, Self Hosted? Can you let us see your OWIN Startup class?

**Comment by wolfmarco** [comment]
I use MVC inside a ASP.Net core webservice which is hosted in IIS. I use the method extension https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.AspNetCore/HangfireApplicationBuilderExtensions.cs#L31 to register the Dashboard.

**Comment by wolfmarco** [comment]
There you can find an example implementation https://github.com/wolfmarco/AspNetCoreWithHangfireExample/blob/master/src/AspNetCoreWithHangfireExample/Startup.cs

**Comment by burningice2866** [comment]
And what happens if you use `/exampleapp/api/hangfire/` instead of just `hangfire` ?

What is your applications relative root path?

**Comment by wolfmarco** [comment]
The app is hosted at

http://app1.example.com/hangfire/
http://app2.example.com/hangfire/

and we call the app with the url (load balancer)

https://app.example.com/app/hangfire/

The dashboard includes e.g. the CSS stylesheet by `/hangfire/css1617`. But the stylesheet is not available at https://app.example.com/hangfire/css161. Instead the stylesheet should be imported by `/api/hangfire/css1617`.

![hangfire_dashboard2](https://user-images.githubusercontent.com/3786816/36313365-96748d0c-1331-11e8-8fac-3e7427c966c4.png)

**Comment by flomuson** [comment]
Hi,
I have the same issue...
Do you have any solution/workaround ?

thanks

**Comment by wolfmarco** [comment]
I don't really have a solution. Our workaround is to call the dashboard directly without the load balancer.

**Comment by pieceofsummer** [comment]
@flomuson @wolfmarco must be similar to #1049

**Comment by wolfmarco** [comment]
Following workaround seems to work, because our load balancher fills the request header `X-Forwarded-Prefix`. Instead of this header you can use e.g. a setting for your different environments.

```csharp
app.Use((context, next) =>
{
	if (context.Request.Path.StartsWithSegments("/hangfire"))
	{
		context.Request.PathBase = new PathString(context.Request.Headers["X-Forwarded-Prefix"]);
	}
	return next();
});

app.UseHangfireDashboard("/hangfire", new DashboardOptions
{
	Authorization = new[] {new DashboardAuthorizationFilter()},
	AppPath = _appSettings.CurrentValue.WebUiUri
})
.UseHangfireServer(backgroundJobServerOptions);
```

**Comment by Qmannn** [comment]
Now available parameter `Prefix Path`
``new Dashboard Options { Prefix Path = "/app-name-over-balance" }`

It worked for me.

But for local application running/debugging i'm just set `Prefix Path` depending on current environment: is local - use empty `PrefixPath`, if production/stage - use required app prefix on environment.
