### ISSUE TITLE
Is it possible to have implementations of jobs in another process, and to just populate the db with jobs from another?

### ISSUE THREAD

**Issue by nikolalukovic** [HangfireIO/Hangfire#1111]
I've checked out this [link](http://docs.hangfire.io/en/latest/background-processing/placing-processing-into-another-process.html) for `Placing processing into another process` and it's exactly what i need. But i can't figure out how to make it work.

I have a web app that would enqueue emails and sms's to be sent at a certain time, and i would like to use hangfire for that. I've decided to put it in a different process(Azure WebJob) which would execute those jobs. I'm not sure how would i enqueue jobs in webapp, since the jobs themselves are implemented in the different process. I would need something like scheduling a job in web app with lets say emailId and a time when to execute. And at the given time the web job would fire a job with emailid as an argument. 

Is something like this possible?

**Comment by graemechristie** [comment]
Yes, it is definitely possible. This is exactly what we do. For the azure WebJob you just use a continuous WebJob running as a console application. All the scheduling is handled by hangfire. Just enqueue the job to run in your web app at a particular time using hangfire (e.g. with BackgroundJob,Schedule). Make sure do don't start the hangfire server in your web app, or it may try to process the job before your web job gets to it.
 
[here](http://docs.hangfire.io/en/latest/background-processing/processing-jobs-in-console-app.html) is a link to the hangfire docs showing a simple background processor.
