### ISSUE TITLE
Microsoft.AspnetCore.Abrstractions DLL not loading

### ISSUE THREAD

**Issue by dnelly** [HangfireIO/Hangfire#1113]
We encountered a problem when publishing our .net core 2.0.5 application.  The output contains a old version of Microsoft.AspnetCore.Abrstractions and we've been able to track it back to hangfire using .net standard 1.5 and having a dependency on Microsoft.AspnetCore.Abrstractions 1.0.0 which doesn't load in IIS when using .net core 2.0.5.

A fix for this would be to update hangfire to use .net standard 2+.

**Comment by dnelly** [comment]
Any updates on this?

**Comment by odinserj** [comment]
[Hangfire 1.7.0](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.0) released some days ago explicitly targets `netstandard2.0` with new dependency versions.
