### ISSUE TITLE
My job is executing multiple times even though it is fire and forget....

### ISSUE THREAD

**Issue by natiki** [HangfireIO/Hangfire#1115]
Hi,

Apologies for the cross post here with SO, but I have been banging my head against a wall here for days and am no closer to an answer. I also don't seem to have permissions to post to the forum (!).

I hope someone can help me:

https://stackoverflow.com/questions/48904368/my-job-executes-an-arbitrary-number-of-times-even-though-only-scheduled-once

**Comment by iSatishYadav** [comment]
https://stackoverflow.com/a/48985450
You got the solution, right? ☝️

**Comment by iSatishYadav** [comment]
You may want to close the issue.

**Comment by natiki** [comment]
As @iSatishYadav pointed out I posted the solution on SO so I am closing this issue.
