### ISSUE TITLE
Hangfire recurring job skipping intermittently and not being triggered

### ISSUE THREAD

**Issue by Jordan8085** [HangfireIO/Hangfire#1118]
Hi there,
I am using latest version of hangfire 1.6.17 and has scheduled the recurring job to run every day 5 AM and 10 PM. But I noticed sometimes it skips the execution and I cannot find any error or exception in the log. Last week it skipped once and did not triggered the 10 PM one. But this morning I noticed it didn't trigger for last 3 days. I am using SQL server for hosting the Hangfire DB. I have implemented the business logic in WebAPI project. All the other API calls are working fine which means web app is in "Active" state but some reason hangfire is not triggering the execution.
I am using .Net 4.5.2.
Could you please help becoz it's a production issue for us.

Thanks,
Jordan

**Comment by Jordan8085** [comment]
![hangfire tables sql result](https://user-images.githubusercontent.com/36827962/36648065-7f594a28-1ae2-11e8-908e-d263a0acde10.png)
Please find attached Hangfire DB SQL dump

**Comment by Jordan8085** [comment]
Please find the hangfire DB tables SQL dump. You would notice the last execution was on 22nd Feb.
![hangfire tables sql result](https://user-images.githubusercontent.com/36827962/36648118-13d5db3a-1ae3-11e8-817e-67bec5d57e34.png)

**Comment by Jordan8085** [comment]
Please find attached Global.asax.cs code snippet which is responsible for starting/stopping hangfire server. Also code snippet for the hangfire bootstrapper.cs
![hangfire code](https://user-images.githubusercontent.com/36827962/36648342-6267268e-1ae6-11e8-9b7e-edf3b3177439.png)

**Comment by bdn-mca** [comment]
Have you implemented [this](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html)?

> By default, Hangfire Server instance in a web application will not be started until the first user hits your site. Even more, there are some events that will bring your web application down after some time (I’m talking about Idle Timeout and different app pool recycling events). In these cases your recurring tasks and delayed jobs will not be enqueued, and enqueued jobs will not be processed.

**Comment by Jordan8085** [comment]
Thanks bdn-mca.
I did implement that solution but application preload provider registration was conflicting with IIS setting so had to comment it out.
Anyways I have put the monitoring script to ping the application every 5 mins and so far it looks good. I will keep an eye and update here if that doesn't work.
Many Thanks.
