### ISSUE TITLE
Servers disappearing from the server list (Jobs still run)

### ISSUE THREAD

**Issue by itssimple** [HangfireIO/Hangfire#1123]
| Package | Version |
|----|:---:|
| Hangfire.Core | 1.6.17 |
| Hangfire.SqlServer | 1.6.17 |

The problem we are experiencing, is that the table with active servers (`HangFire.Server`), sometimes gets emptied (as if the servers were old/obsoleted)

We use this, to see if we have any active servers, otherwise we send notifications to a couple of people.

**Comment by T-rav** [comment]
I had this problem when I was using a static name of SERVER. Once I swapped over to a name with a Guid attached to it the issue went away.
E.g. SERVER vs SERVER-4DFE8400-6278-4D03-BC22-B5C42169D9B7.

**Comment by odinserj** [comment]
Starting with 1.7.0 those servers will be restarted automatically with the new identifier. The only thing is that storage should throw the `BackgroundServerGoneException` when heartbeat was unsuccessful.
