### ISSUE TITLE
IJobCancellationToken is always null ?

### ISSUE THREAD

**Issue by vuhi** [HangfireIO/Hangfire#1129]
I write some code to test IJobCancellationToken token, when I pass the token it does not stop the Background job, then I try to debug it, I see that my token "IsCancellationRequested" always null. Is it a bug ??

`[HttpGet]`
        `public string Get()`
        `{`
           ` BackgroundJob.Enqueue(() => Job(1, JobCancellationToken.Null));`
           ` var token = new JobCancellationToken(true);`
           ` BackgroundJob.Enqueue(() => Job(3, token));`
            `return "pong";`
       ` }`

`public void Job(int number, IJobCancellationToken token)`
      `  {`
            `var isvalid = token.ShutdownToken.IsCancellationRequested; //This value is always false!`
            `token.ThrowIfCancellationRequested();`
           ` Thread.Sleep(1000);`
           ` Console.WriteLine($"Cron Job every minutes! {DateTime.UtcNow}, job_{number}"); `   
      `  }`
`

![untitled](https://user-images.githubusercontent.com/35607328/36984085-06323cf6-2062-11e8-893b-7c82675e5eca.png)

**Comment by pieceofsummer** [comment]
`IJobCancellationToken` is a special type of argument which would be automatically substituted by Hangfire when executing a job. Passing null or any other value makes no difference, as it would be replaced with actual cancellation token for the job anyway.
