### ISSUE TITLE
Job enqueued on incorrect server

### ISSUE THREAD

**Issue by moskvitin** [HangfireIO/Hangfire#1133]
With this libs
```
Hangfire.AspNetCore Version=1.7.0-beta1
HangFire.SqlServer Version=1.7.0-beta1
```
get strange behavior with recurring job, when have few services working with one hangfire database (used different queues). For example:
_From [JobParameter]_
```
JobId	Name	Value
6452	RecurringJobId	"Job_test_23"
```
_From [State]_
```
Id	JobId	Name	Reason	CreatedAt	Data
22800	6452	Enqueued	Triggered using recurring job manager	2018-03-07 11:37:04.363	{"EnqueuedAt":"2018-03-07T11:37:04.3447106Z","Queue":"test_11"}
```
Job registered by one service (test_23), but try to handle by another (test_11). Previous version doesnt produce this behavior.

**Comment by pieceofsummer** [comment]
Target queue doesn't depend on which server the recurring job was actually created by. And it never did.

**Comment by moskvitin** [comment]
@pieceofsummer excuse me, forgot to add that  for service test_11 was used `BackgroundJobServerOptions` with only one queue `test_11` and same for service test_23 - queue `test_23`.
I thout that only selected queue jobs will be handled by service (test_11 will work only with queue test_11)...

**Comment by pieceofsummer** [comment]
> test_11 will work only with queue test_11

This is true, but the queue doesn't depend on which server the recurring job was added by, but on the `queue` argument passed to `AddOrUpdate` method.

**Comment by moskvitin** [comment]
At last get some time to make little [repro](https://github.com/moskvitin/hangfireIssue): 
when i try to run 2 separate clones of this (test1 for one and test2 for another) get the descibed behaviour. For examle:
![issue](https://user-images.githubusercontent.com/11612097/37216911-a514197c-23ee-11e8-9051-25e9d98626bd.PNG)

**Comment by pieceofsummer** [comment]
You have `QueueAttribute` applied to your job:
```c#
[Queue("test1")]
public void SampleJob()
{
    ...
```
It will supersede the queue specified in recurring job definition.

**Comment by moskvitin** [comment]
Ok, but why if i had 2 services with different `QueueAttribute` one service try to handle job from another? Even if there is supersede, for me it is not obvious :(
When i make a clon - change queue text either. It is just a copy content of `QueueName`...

**Comment by pieceofsummer** [comment]
`RecurringJobScheduler` will peek all jobs that are scheduled to run at the moment, regardless of which queue they're meant for. It would then create an instance for each recurring job, running all job filters associated with the job.

Both your recurring jobs have the same schedule, so they're very likely to be always processed by the same server. If Server1 peeks the recurring jobs and processes the rules, it would run all the filters from **its own codebase**, so it will apply `QueueAttribute` defined for the method (i.e. "test1") to both jobs. Similarly, if Server2 will be first to process the recurring jobs, they'll be processed by its own job filters, so both jobs will go to "test2" queue.

You should just remove `QueueAttribute` from the job method, so the filters would be the same for both servers.

**Comment by moskvitin** [comment]
You are absolutly right! Thanks a lot! But what if exception will be occure during job processing (like in [this issue](https://github.com/HangfireIO/Hangfire/issues/705))? Other attemp will be in `DEFAULT` queue and who will be handle it `test1` or `test2`?

**Comment by pieceofsummer** [comment]
Neither of them, I presume. One of them would enqueue the job to `default` queue after exception, but it would be stuck in there since there’s no server instance processing that queue.

Somewhere in the thread you’ve linked there’s an example of PreserveOriginalQueueAttribute filter that requeues the job to the same queue after exception.
