### ISSUE TITLE
Incompatibility with Newtonsoft.Json 11.0.1 / netstandard2.0

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#1135]
Newtonsoft.Json 11.0.1 adds a separate target for netstandard2.0, so .NET Core 2.0 projects will use it. 

But Hangfire is built against a netstandard1.3 version. There's no built-in `FormatterAssemblyStyle` type in netstandard1.3, so Newtonsoft.Json defines one. If using Hangfire in a netstandard2.0 project, the following setter won't be resolved since there's no `FormatterAssemblyStyle` type in Newtonsoft.Json 11.0.1 anymore.

https://github.com/HangfireIO/Hangfire/blob/662e5b583a5bf34c323603ccb4258146b85f10a4/src/Hangfire.Core/States/AwaitingState.cs#L211

To fix this, Hangfire also needs a new target for netstandard2.0. Using a newer `FormatterAssemblyStyleHandling` property is not an option, since it would require updating Newtonsoft.Json dependency (it was first introduced in 10.0.1).

**Comment by rgmills** [comment]
@pieceofsummer I assume this issue would prevent anyone from consuming Hangfire from an ASP.NET Core 2.1 application as it brings in Newtonsoft.Json 11.x as a dependency?

**Comment by pieceofsummer** [comment]
@rgmills yeah. I had to manually replace Hangfire.Core package with one from the PR build to make things work with Core 2.1.

**Comment by rgmills** [comment]
Gotcha.  Any idea when you'd expect that PR to land or anything that I could contribute to help with?

**Comment by pieceofsummer** [comment]
This is only relevant for 1.7 branch, and it should be included in beta2.

1.6.x should work with Core 2.1 without any changes.
