### ISSUE TITLE
Missing intValue-values in /stats-endpoint

### ISSUE THREAD

**Issue by itssimple** [HangfireIO/Hangfire#1145]
The only metric that does seem to get its `intValue` set is the `succeeded`-property.

![Results from endpoint](https://itssimple.se/share/u/multinet/2018/03/20/1127-017d.png)

Version used in screenshot is `1.6.17`

**Comment by pieceofsummer** [comment]
Not only `succeeded`, but also `failed`. It's just hard to notice when you have no failed jobs.

Those two metrics are required for real-time graphs to work, and have `intValue` property set to avoid locale-dependant number parsing. For all other metrics, the `intValue` property is actually never used, hence there's no need to set it.

There would be no harm setting the `intValue` for all metrics (for consistency). It's just nobody has actually cared until now :)
