### ISSUE TITLE
when BackgroundJobServer dispose EveryMinuteThrottler throw OperationCanceledException

### ISSUE THREAD

**Issue by LeafDuan** [HangfireIO/Hangfire#1147]
i use hangfire in console app,
when use ctrl + c to shotdown the app,  and after call BackgroundJobServer.Dispose(), 
then the OperationCanceledException threw by EveryMinuteThrottler

why?

**Comment by odinserj** [comment]
There's no `EveryMinuteThrottler` in the latest 1.7.0 betas, so I'm closing this issue. Thanks for reporting!
