### ISSUE TITLE
Hangfire 1.6.17 not rescheduling Enqueued Jobs

### ISSUE THREAD

**Issue by Asendo316** [HangfireIO/Hangfire#1148]
Im trying to use hang fire for the first time, Reading from MSMQ. However, the jobs in hangfire  Enqueued do  not trigger automatically instead it re adds the job into the enqueued jobs queue and continuously without processing it or it failing

**Comment by odinserj** [comment]
Please add more details regarding this issue, including configuration code for Hangfire, logs from your application, whether you are using public or private queues. Ensure you are using DTC transactions for your setup and also your outgoing queues and event logs for MSMQ on worker machines are empty and doesn't contain anything interesting.

```csharp
GlobalConfiguration.Configuration.UseMsmqQueues(
    MsmqTransactionType.Dtc, 
    ".\\Private$\\{0}", 
    "default");
```

**Comment by Asendo316** [comment]
This is how i did mine:
            GlobalConfiguration.Configuration

                    .UseSqlServerStorage("HangfireTestServerConn" , new SqlServerStorageOptions { QueuePollInterval = TimeSpan.FromSeconds(10) })
                   // .UseSqlServerStorage("HangfireTestServerConn" /*, new SqlServerStorageOptions { QueuePollInterval = TimeSpan.FromSeconds(10) }*/)
                    .UseMsmqQueues(HangfireQueueName, "transaction_notice_process")
                    //.UseActivator(...)
                    .UseLogProvider(new Log4netHangfireLogProvider())//(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType)
                    .UseFilter(new LogFailureAttribute());

            app.UseHangfireDashboard();
            app.UseHangfireServer();

**Comment by odinserj** [comment]
So the following line is required, because fetching from remote queues in MSMQ doesn't work with internal transactions.

```csharp
GlobalConfiguration.Configuration.UseMsmqQueues(MsmqTransactionType.Dtc, 
```

**Comment by Asendo316** [comment]
im getting a build time error "The name 'MsmqTransactionType' does not exist in the current context"

**Comment by odinserj** [comment]
Just include the `using Hangfire.SqlServer.Msmq` namespace

**Comment by Asendo316** [comment]
Now im getting these errors:
'IGlobalConfiguration' does not contain a definition for 'UseMsmqQueues' and the best extension method overload 'MsmqExtensions.UseMsmqQueues(IGlobalConfiguration<SqlServerStorage>, string, params string[])' requires a receiver of type 'IGlobalConfiguration<SqlServerStorage>'

Argument 2: cannot convert from 'Hangfire.SqlServer.Msmq.MsmqTransactionType' to 'string'

This is how i implemented it:

            GlobalConfiguration.Configuration
                .UseMsmqQueues( MsmqTransactionType.Dtc, HangfireQueueName, "transaction_notice_process")
                .UseSqlServerStorage("HangfireTestServerConn", new SqlServerStorageOptions { QueuePollInterval = TimeSpan.FromSeconds(10) })
                .UseLogProvider(new Log4netHangfireLogProvider())
                .UseFilter(new LogFailureAttribute());

**Comment by odinserj** [comment]
Just swap the lines to get the following ordering. Also, you can remove the `QueuePollingInterval`, because it's used only for SQL Server-based queues.

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage("HangfireTestServerConn", new SqlServerStorageOptions { QueuePollInterval = TimeSpan.FromSeconds(10) })
    .UseMsmqQueues(MsmqTransactionType.Dtc, HangfireQueueName, "transaction_notice_process")
```

**Comment by Asendo316** [comment]
After reordering the code, it did schedule and process task on first run then started adding tasks back to the queue again without processing

**Comment by Asendo316** [comment]
Hangfire recurring job triggers but does not perform the task

**Comment by Asendo316** [comment]
![image](https://user-images.githubusercontent.com/18377936/37897293-c7def7e6-30dd-11e8-9336-a2ce880c3f26.png)

the task CronJobs.ProcessNotificationQueue does not trigger when the time limit is reached

**Comment by vidhyag35** [comment]
I'm having the same issue, I have my configuration as follows, what do I have to do to reschedule the enqueued jobs. 
 //Hangfire
            GlobalConfiguration.Configuration.UseSqlServerStorage(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ToString())
                               .UseMsmqQueues(@".\Private$\hangfire-{0}", "default");

            app.UseHangfireServer();
            app.UseHangfireDashboard();
