### ISSUE TITLE
Hangfire Error Mapper not initilialized

### ISSUE THREAD

**Issue by gustavozafra** [HangfireIO/Hangfire#1157]
Good morning, I'm having trouble running my jobs when the system is idle. Jobs are set to run at dawn when there is no one using the application, but when Hangfire tries to run it it throws the "Mapper not initialized" error.
![errorhangfire](https://user-images.githubusercontent.com/8005476/38195615-c29ab5f0-3654-11e8-9eb0-0c92e50fdae2.JPG)

ApplicationPreload.cs
`public class ApplicationPreload : System.Web.Hosting.IProcessHostPreloadClient
    {
        public void Preload(string[] parameters)
        {
            Startup.Instance.Start();
        }
    }`

Startup.cs
`public class Startup : IRegisteredObject
    {
        public static readonly Startup Instance = new Startup();

        private readonly object _lockObject = new object();
        private bool _started;

        private BackgroundJobServer _backgroundJobServer;

        public Startup()
        {
            Start();
        }

        public void Start()
        {
            lock (_lockObject)
            {
                if (_started) return;
                _started = true;

                HostingEnvironment.RegisterObject(this);

                GlobalConfiguration.Configuration
                .UseSqlServerStorage("SpyMarketDados");

                GlobalConfiguration.Configuration
                    .UseActivator(new SimpleInjectorJobActivator(SimpleInjectorInitializer.GetHangfireContainer()));
                // Specify other options here

                _backgroundJobServer = new BackgroundJobServer();
            }
        }

        public void Configuration(IAppBuilder app)
        {
            //GlobalConfiguration.Configuration
            //    .UseSqlServerStorage("SpyMarketDados");

            //GlobalConfiguration.Configuration
            //    .UseActivator(new SimpleInjectorJobActivator(SimpleInjectorInitializer.GetHangfireContainer()));

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.File(@"C:\Temp\SpyMarketWeb.HangFireLog.log")
                .CreateLogger();

            app.UseHangfireServer();
            app.UseHangfireDashboard("/BackgroundDashboard", new DashboardOptions()
            {
                Authorization = new[] { new HangfireAuthorizationFilter() }
            });

            HangfireJobs.Execute();
        }

        public void Stop()
        {
            lock (_lockObject)
            {
                if (_backgroundJobServer != null)
                {
                    _backgroundJobServer.Dispose();
                }

                Thread.Sleep(TimeSpan.FromSeconds(30));
                HostingEnvironment.UnregisterObject(this);
            }
        }

        void IRegisteredObject.Stop(bool immediate)
        {
            Stop();
        }
    }`

**Comment by parekhkb** [comment]
I couldn't find any references to AutoMapper in this HangFire Repo, but I could have missed it. Perhaps you are using it internally in your project? Have you tried AutoMapper.Mapper.Initialize in your startup class? http://docs.automapper.org/en/stable/Configuration.html

**Comment by gustavozafra** [comment]
In this case, I will initialize my AutoMapper in the Application_Start () of Global.asax.cs. But I will try to start AutoMapper in Startup.cs to see if the same error will occur and I will reply here.

**Comment by parekhkb** [comment]
Global.asax.cs is only ever used in interactive web calls. Scheduled background jobs would have a different context.

**Comment by gustavozafra** [comment]
@parekhkb Thank you so much bro, I'll try. I just find it strange that when the application is running normally I can trigger the methods however this error only occurs when it is idle.

**Comment by parekhkb** [comment]
@gustavozafra, I'm not sure what your setup is. For us, we use a separate process to host hang-fire than our web server. If you are executing these jobs from within your Web server process, then perhaps your web server is going stale, and the startup sequence is not initializing auto-mapper before hangfire is starting the job. That's just a guess.

**Comment by gustavozafra** [comment]
Thanks for your help, apparently the Mapper problem has been solved. But I'm having another problem. My Job is set to run every day at 00:10 AM but on the dashboard it shows a delay of 3 hours so shows the execution of it at 09:10 PM the previous day. Can you tell me why?

Job
`RecurringJob.AddOrUpdate<IFuncionarioHistoricoAppService>(
                (_funcionarioHistoricoAppService) => _funcionarioHistoricoAppService.ProcessarHistoricoDoDia(), Cron.Daily(00, 10));`

![3hoursdelay](https://user-images.githubusercontent.com/8005476/38249344-c574df6c-3721-11e8-9139-3d4c5871af7c.png)

![hangfire1png](https://user-images.githubusercontent.com/8005476/38249349-c88052b8-3721-11e8-8593-9c537ecf93fd.PNG)

**Comment by parekhkb** [comment]
What is your system time zone? It looks like the job is scheduled for 00:10 UTC, my guess is your system is in UTC+3

**Comment by parekhkb** [comment]
My guess is your browser/system time is UTC+3, so 9:10pm for you is 00:10 in UTC. The jobs are scheduled in UTC so you need to change the scheduled time to 03:10 UTC

**Comment by gustavozafra** [comment]
Thank you so much @parekhkb you're awesome. About the TimeZone, i found the solution. [https://discuss.hangfire.io/t/need-local-time-instead-of-utc/279/8](https://discuss.hangfire.io/t/need-local-time-instead-of-utc/279/8)

**Comment by virendraworkmail** [comment]
> Thanks for your help, apparently the Mapper problem has been solved. But I'm having another problem. My Job is set to run every day at 00:10 AM but on the dashboard it shows a delay of 3 hours so shows the execution of it at 09:10 PM the previous day. Can you tell me why?
> 
> Job
> `RecurringJob.AddOrUpdate<IFuncionarioHistoricoAppService>( (_funcionarioHistoricoAppService) => _funcionarioHistoricoAppService.ProcessarHistoricoDoDia(), Cron.Daily(00, 10));`
> 
> ![3hoursdelay](https://user-images.githubusercontent.com/8005476/38249344-c574df6c-3721-11e8-9139-3d4c5871af7c.png)
> 
> ![hangfire1png](https://user-images.githubusercontent.com/8005476/38249349-c88052b8-3721-11e8-8593-9c537ecf93fd.PNG)

Hey gustavozafra,
How did you solved the automapper problem? I am getting the same problem while hangfire calls to Job, the job has expression query with UseAsDataSource which gives error.
