### ISSUE TITLE
BackgroundJob.Schedule - queue name?

### ISSUE THREAD

**Issue by drauch** [HangfireIO/Hangfire#1159]
Hi!

Normally we schedule our jobs using `BackgroundJob.Enqueue(methodCall)` to a specific queue. One of those jobs should have a delay before being executed - so we used `BackgroundJob.Schedule(methodCall, delay)`. However, it looks like such jobs are not scheduled for a specific queue, it looks like any worker process will happily try to execute the job as soon as the delay has passed. That's a problem for us, as not any worker has loaded the necessary DLLs to execute the job, therefore, the job often fails! Is there a way to make sure that the job is only given to specific types of workers - i.e., the workers attached to the queue we scheduled the job on?

My guess is, that `BackgroundJob.Schedule` doesn't schedule a job for a specific queue by default. How to configure it so that the job is scheduled for the given queue?

Best regards,
D.R.

**Comment by drauch** [comment]
OK, it looks like the other workers are not trying to execute the job, they are only trying to move the job from scheduled to enqueued - however, they still need all the DLLs required for that job for doing this...

...is there a way to stop workers from trying to move scheduled jobs to the enqueued state? So that only our "server" is trying to do that? Any other workaround?

**Comment by drauch** [comment]
We looked a bit into the code, and it looks like BackgroundJobServer "hardcoded" starts a DelayedJobScheduler and we cannot disable it in any way. Would you accept a PR that makes `BackgroundJobServer.GetRequiredServices()` virtual and would allow us to disable the `DelayedJobScheduler`?

Then we could use a derived BackgroundJobServer in all workers which are not having references to all the other worker assemblies and run only a specific worker with a DelayedJobScheduler.

**Comment by virtualcca** [comment]
i also have same problem. i find DelayedJobScheduler enqueue is not special queueName so it also is "Default"

**Comment by drauch** [comment]
Is this issue tracker alive?

**Comment by christogav** [comment]
Need this! We've just hit this issue... how far away is a fix?

**Comment by drauch** [comment]
@christogav : Unfortunately, it looks like the project is not actively maintained. I've never heard back from them, most issues just sit there and rot :-(

**Comment by christogav** [comment]
Is #1247 the fix for this? Appears related.

**Comment by Frank591** [comment]
Our team also need this. Pls fix

**Comment by zhuweid** [comment]
same here

**Comment by odinserj** [comment]
It will be possible to do this in version 1.8.0 using the following syntax. Pre-release version is already available, please see https://www.hangfire.io/blog/2023/03/30/hangfire-1.8.0-rc3.html for details.

```csharp
BackgroundJob.Schedule("critical", () => Console.WriteLine("Hello, world"), TimeSpan.FromDays(1));
```

**Comment by simeyla** [comment]
If you're using multiple servers, make sure to update them all to 1.8.0 before using the new queue scheduling overload - otherwise the older server may try to take the job and get confused!
