### ISSUE TITLE
Is it possible use same database as storage for different Hangfire Servers 

### ISSUE THREAD

**Issue by catwarrior** [HangfireIO/Hangfire#1163]
Is it possible use same database as storage for different Hangfire Servers (ex: 2 teams, create different backgroundjobs and deployed seperately)?

can I use different queue to separate them?

I saw below information from the document

> Same storage requires the same code base
> Ensure that all of your Client/Servers use the same job storage and have the same code base. If client > enqueues a job based on the SomeClass that is absent in server’s code, the latter will simply throw a 
> performance exception.

So is there a way for different codebase share same database?

The reason is somehow I don't want to create too many databases.

**Comment by tompazourek** [comment]
I'm assuming you are talking about SQL Server.

You could have two sets of Hangfire tables, each under a different database schema, but still inside the same database.

Then when you set up Hangfire, there's the `.UseSqlServerStorage` call which accepts `SqlServerStorageOptions` as the second parameter. Inside `SqlServerStorageOptions`, you can configure `SchemaName`. That way, you can configure one Hangfire Server to one schema, and the other Hangfire Server to the other schema.

But it doesn't feel like a very clean solution and it's probably not what you're looking for either.  I'd recommend rather setting up multiple databases anyway.

**Comment by catwarrior** [comment]
@tompazourek It really helps,  Thanks!!~~

**Comment by MarounMaroun** [comment]
@tompazourek I agree that it smells. However, there are some scenarios where this might be a good solution. For example, if you're running a monolithic application that exposes different applications (i.e. web-app + backend-app, legacy code), you might want to separate the HangFire servers to use different schemes. Is this acceptable in this case, or you have a better suggestion?
