### ISSUE TITLE
Does Hangfire cache data?

### ISSUE THREAD

**Issue by Thutos** [HangfireIO/Hangfire#1166]
Hello,

My hangfire recurring jobs seem to be caching data from my database. This a problem because my background processes checks for change in data & if there is a change & hangfire can't pick it.... then what i want to achieve won't work... am I doing something wrong or is there a way to stop it from doing that?

Thank you!

**Comment by pksorensen** [comment]
I am googling hangfire / caching because i also am seeing something odd that it seems db values are cached. Have a workflwo that basically throws the same error even though db is updated. Input to hangfire job is just the id, so it does the retrieval of it from db as part of the job.

**Comment by burningice2866** [comment]
I believe that would depend on the actual storage provider being used and how its implemented.

**Comment by pksorensen** [comment]
Hi Pauli :)

SQL backed. The reason why i think something is getting cached is that my EF context FindAsync seems to return old values - like the context is cached. 

I found the aspnet core scope handler / JobActivator and it seems correct with scopes and all, need to som test to figure it out
