### ISSUE TITLE
Cross platform TimeZoneInfo.Local

### ISSUE THREAD

**Issue by jostrander** [HangfireIO/Hangfire#1167]
Ran across an issue I was trying to figure out for a few days. I'm running 2 containers locally in docker on .net core runtime for linux, and developing with windows, all using the same backend sql storage. If you start the containers, they will use the IANA time zone `America/New_York`, and store that in the database. However when windows goes to process the job it will fail with a `TimeZoneNotFoundException`, as it doesn't recognize the time zone. The same happens the other way around. If you start the windows one first, it sets to `Eastern Standard Time`, then the linux containers won't be able to process the job. 

Should the job processor be able to convert from IANA to Windows time zones and vis-versa instead of throwing an exception? I know this is technically an upstream issue in .net core at the moment as well, but curious if you had any plans to support this, maybe with Cronos in the future?

Also, on a related note. The dashboard will break when it can't find the time zone as well with the same exception. So theoretically you can't have your dashboard on a windows server, and your workers on linux using IANA time zones.

Hangfire@1.6.17
Hangfire.SqlServer@1.6.17

**Comment by Karen-Abgaryan** [comment]
Hi!
I also encountered this problem, especially in dashboard. It would be great if calls to the `System.TimeZoneInfo.FindSystemTimeZoneById` would be replaced with `TZConvert.GetTimeZoneInfo`.

Either of these will return same time zone:
`TimeZoneInfo tzi = TZConvert.GetTimeZoneInfo("Eastern Standard Time");`
`TimeZoneInfo tzi = TZConvert.GetTimeZoneInfo("America/New_York");`

[About TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter)

**Comment by mihey8800** [comment]
Hi. Same issue. Will be solved? I think it is a simple fix...

**Comment by odinserj** [comment]
Starting from Hangfire 1.7.0 you can use custom `ITimeZoneResolver` implementation and set it via `BackgroundJobServerOptions`. For example, you can use the [`TimeZoneConverter`](https://www.nuget.org/packages/TimeZoneConverter/) package to have a cross-platform resolver.
