### ISSUE TITLE
Recurring Jobs - Count/offset not correct

### ISSUE THREAD

**Issue by cdschneider** [HangfireIO/Hangfire#1169]
Using HF 1.6.17/ `Hangfire.SqlServer` for storage. 

Noticed this today for the first time as my number of recurring jobs surpassed the default page size of 10. Note there are 11 items listed on this page:

![image](https://user-images.githubusercontent.com/5581662/38745832-5bd9dd04-3f0b-11e8-9c6f-c92be15b65af.png)

This also causes the last item in the list to appear on the second page.

**Comment by pieceofsummer** [comment]
This is already fixed, please update to 1.6.19
