### ISSUE TITLE
use UseSqlServerStorage error datetime2

### ISSUE THREAD

**Issue by bug2018** [HangfireIO/Hangfire#1180]
Error reporting using UseSqlServerStorage: no datetime2 data type can be found.

**Comment by pieceofsummer** [comment]
What version of SQL Server are you using? Datetime2 was first introduced in SQL Server 2008.

**Comment by bug2018** [comment]
I use SQL2008R2.But first I installed SQL2005, and then I installed SQL2008R2 on the same server.This may be the cause of the error.If only SQL2008R2 was installed on the server, there might be no errors.

**Comment by pieceofsummer** [comment]
You should check your database compatibility level. If you've upgraded from SQL 2005, it would be set to 2005 and not allow you to use 2008R2 features. Or just re-create the database :)

**Comment by bug2018** [comment]
101/5000  
The beginning the DBA told me this one instance on the server is SQL2005, another instance is SQL2008, I once again checked the server version, found that two instances of the server, is SQL2005, I misled by the DBA.

You are right, thank you for your reply!
