### ISSUE TITLE
How to prevent success job from removing.

### ISSUE THREAD

**Issue by lousaibiao** [HangfireIO/Hangfire#1192]

**Comment by pieceofsummer** [comment]
Well, Hangfire is designed to cleanup jobs in final states (Succeeded and Deleted), so you can't easily change that. You have two possible solutions here:

1. Create an `IApplyStateFilter` and set `JobExpirationTimeout` to some huge value for succeeded jobs. It would be still deleted after that timeout, but it may take years for It to come.

2. Create a custom non-final state and make an `IElectStateFilter` to transition succeeded jobs into that state. This way the jobs will be never deleted, but you'll need also provide a page for that custom state if you want to see it in dashboard.

Either way, this would lead to constant grow of your storage database, so you should carefully consider which jobs you want to persist forever.

**Comment by lousaibiao** [comment]
Got it, thank you for your help.
