### ISSUE TITLE
Is there support for a favicon?

### ISSUE THREAD

**Issue by carlowahlstedt** [HangfireIO/Hangfire#1198]
I can't seem to find any documentation about favicon support and my current implementation isn't showing one. I also don't see any mention of a favicon in the generated source page, so I would assume there is no support but that it would be nice to be able to set a configuration option on where it is?

**Comment by burningice2866** [comment]
You can place your favicon.ico in the websites root, thats supported by all browser.

**Comment by carlowahlstedt** [comment]
Looks like that did correct the issue. I don't generally put mine there because [supporting multiple scenarios is complicated](https://www.favicon-generator.org/) so instead of putting the list of images needed in the root I put them into a folder. Thanks for the help.

**Comment by burningice2866** [comment]
Yeah, the favicon.ico in root is the lowest common denominator guaranteed to work in all browsers.

To handle all kinds of various resolutions, app icons and whatnot you need to add them to the html. Not that i see that being a common requirement for Hangfire Dashboard though :)
