### ISSUE TITLE
Continuations job never run when parent status is success

### ISSUE THREAD

**Issue by nvasc** [HangfireIO/Hangfire#1206]
![screenshot_4](https://user-images.githubusercontent.com/39476652/41753537-380e7370-75f8-11e8-9c5f-ae5654068ac4.png)

my code: 
var jobId = BackgroundJob.Enqueue<ITest>(t => t.Run1());
var jobId2 = BackgroundJob.ContinueWith<ITest>(jobId, t => t.Run2());

as you see in this images, the Run2 function alway stay Awaiting.

If i don't mistake any thing, in overview site has been written: "Continuations are executed when parent job has finished."

please answer to help me!

**Comment by odinserj** [comment]
@nvasc, what storage are you using and what package versions for Hangfire?

**Comment by nvasc** [comment]
I use SQL server

**Comment by odinserj** [comment]
Could you also tell me the following information?

* Your Hangfire.* package versions – there were some important fixes in the recent versions.
* Full screenshot with all of the states – I want to see whether there was a transition to the Failed state.
* Your configuration logic – I want to ensure you didn't occasionally remove the `ContinuationSupportAttribute` from the filter list.

**Comment by nvasc** [comment]
realy realy thank for answer me!
I were done as following:
Step 1: add from nuget.
![screenshot_10](https://user-images.githubusercontent.com/39476652/41884190-7ddd323e-791c-11e8-85fc-682dfdbd6987.png)
Step 2: create HangfireBootstrapper.cs file with contents:
![screenshot_5](https://user-images.githubusercontent.com/39476652/41884157-4a76d0a8-791c-11e8-9a68-d7cac82011f7.png)
Step 3: register on global file.
![screenshot_6](https://user-images.githubusercontent.com/39476652/41884219-a5d1688c-791c-11e8-8af5-685e295d4b40.png)
Step 4: register dashboard.
![screenshot_7](https://user-images.githubusercontent.com/39476652/41884226-b22f27ae-791c-11e8-9a89-5d211c3becfa.png)
Step 5: Register DI with autofac
![screenshot_8](https://user-images.githubusercontent.com/39476652/41884247-c2db330e-791c-11e8-8927-e5ca9a19da08.png)
Step 6: run it
![screenshot_11](https://user-images.githubusercontent.com/39476652/41884292-f8f30390-791c-11e8-9cf2-5e34548624ff.png)
Step 7: and result
![screenshot_12](https://user-images.githubusercontent.com/39476652/41884346-3b910d0a-791d-11e8-81f2-bc228736040f.png)

**Comment by odinserj** [comment]
The [`ContinuationsSupportAttribute` ](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/ContinuationsSupportAttribute.cs) filter is not added to your filter collection, so Hangfire doesn't know you are using continuations. 

If you just want to override the `AutomaticRetry` filter behavior, just add a new instance of it to the `GlobalJobFilters.Filters` collection. When using filters, there's a de-duplication step, and the last declared one will be used.

**Comment by nvasc** [comment]
hi odinserj! 

I got it!

Thanks and Best Regard!
