### ISSUE TITLE
MySQL-based job storage implementation

### ISSUE THREAD

**Issue by dumbguy5689** [HangfireIO/Hangfire#121]
I would love to see this working on MySQL.  I was just about to start hooking in recurring tasks with Qwartz and came across this project and I would love to give this a try, however I'm using a MySQL back end.

**Comment by bluee** [comment]
Seems like someone started the initial code for MongoDB support:
https://github.com/sergun/Hangfire.Mongo

**Comment by odinserj** [comment]
Regarding MySQL, @chrislove started [Hangfire.MySql](https://github.com/chrislove/Hangfire.MySql). There are a lot of TODOs, but it already performs background jobs. You can help by contributing to the project.

So I'm closing the ticket.

**Comment by S3NS4Ti0N** [comment]
Thank you for the Information !

**Comment by arnoldasgudas** [comment]
If anyone is still looking for Hangfire MySql Storage, might check [this](https://github.com/arnoldasgudas/Hangfire.MySqlStorage) implementation.

**Comment by chrislove** [comment]
@arnoldasgudas As you've probably noticed, I haven't been able to work on my implementation anywhere near as much as I would have liked to. 

Yours seems to be a lot more complete.. so I'm thinking of stopping work on mine and using yours instead. 

If you are happy to take the lead on this, I would like to get Sergey to change the entry on http://hangfire.io/extensions.html to point to your repo. 

Also, assuming you are happy to take the lead, would you like to rename your repo and nuget package to HangFire.MySql so it matches most of the other storage providers? If so, I'll transfer the ownership of the NuGet package name to you or delete it or whatever is most useful.

Thanks for picking up the torch on this - let me know what you'd like me to do :)

**Comment by arnoldasgudas** [comment]
Hi @chrislove 
I am happy to lead on this. I am just not quite sure about renaming it, because nuget will not allow me to rename it and package name should be unique. Since hangfire.mysql already exists on nuget, I will not be able to upload the package.

**Comment by chrislove** [comment]
I'd be happy to transfer the ownership of that nuget package to you. It's easy according to https://docs.nuget.org/create/managing-package-owners 

I think you can rename the Github easily and then I think that's all we need. 

Do you need any help with the project? My time commitments are a bit unreliable but I'd love to help out wherever I can.

Let me know :)

**Comment by chrislove** [comment]
OK great... I'l change my pages in the next day or so and then set you up
as the owner on nuget after that. thanks :)

**Comment by odinserj** [comment]
+1 to have only one package related to MySQL storage. It may be useful to increase the major version to 2.x. However, I like @chrislove's implementation of the `MySqlJobQueue` class, without distributed lock – it is more efficient IMO.
