### ISSUE TITLE
Provide extension point to allow failed job expiration

### ISSUE THREAD

**Issue by sbergot** [HangfireIO/Hangfire#1211]
(don't know if relevant: but here are the details)

Hangfire version: 1.6.19
Storage: Hangfire.sqlserver

Hello,

We have a use case where we would like to have an automatic expiration policy on failed jobs. After some analysis we couldn't find a clean way. The goal of this ticket is to present our use case and analysis and ask for your about this (possible solution with the current api/ direction for a PR).

Use case
----------

We use hangfire with ~ 2000 recurring jobs. Some of them are run every 10 minutes and some once a day. Our hangfire layer is quite thin. We have one job and it only calls an exe with arguments. The output of the exe is captured in the job output AND in our own logs. This means that the hangfire dashboard data is not critical (but really useful for our production team).

We want to clean up all jobs for performance and storage issues. Requesting a manual deletion would be a maintenance burden for our production team

Sometimes they fail for good reason, and sometime for bad reason. Typically some jobs are tightly monitored and other are not. We want to configure an expiration policy that we can apply to all jobs, including the failed ones.

Analysis
---------

We saw that CoreStateMachine implements the expiration decision:

            if (context.NewState.IsFinal)
            {
                context.Transaction.ExpireJob(context.BackgroundJob.Id, context.JobExpirationTimeout);
            }
            else
            {
                context.Transaction.PersistJob(context.BackgroundJob.Id);
            }

We tried calling `context.Transaction.ExpireJob` in a OnStateApplied method but sadly the CoreStateMachine's ApplyState is executed after and wins.

Our current options
----------------------

- try calling context.Transaction.ExpireJob in OnPerformed --> not tested
- create a batch that automatically deleted failed jobs --> it will add noise in our batches
- use a state election filter to auto delete failed jobs --> we would lose the failed category. It will make the dashboard unintuitive to use

Possible PRs
--------------

- Find a way to allow the IsFinal flag configuration?
- other solutions??

**edit**:
I have tested calling context.Transaction.ExpireJob in OnPerformed. It doesn't work. After looking it seems that the Performing step occurs before the new state application.

**Comment by sbergot** [comment]
I have tested calling `context.Transaction.ExpireJob` in `OnPerformed`. It doesn't work. After looking it seems that the `Performing` step occurs before the new state application.

**Comment by pieceofsummer** [comment]
You can introduce a new final state, and create an `IElectStateFilter` to transition jobs to that state in case of failure. You'll need to provide a dashboard page to view the jobs in that state though.

**Comment by sbergot** [comment]
@pieceofsummer sorry for the lack of update. I used the same StateName ("Failed") and everything seems to be working as intended. Thanks for the suggestion!

For the record, I made a carbon copy of the FailedState class, renamed it FinalFailedState and changed the isfinal value (I also changed the constructor to transmit the "FailedAt member"). I used a statelectionfilter to transform the FailedState into my new state and voilà!

**Comment by JohnYoungers** [comment]
It looks like the issue with this approach is it breaks the `AutomaticRetryAttribute`.  Extending `FailedState` doesn't seem to be a solution since it doesn't allow for overriding the `IsFinal` property.

Overall I would think allowing for some sort of configuration in how `CoreStateMachine` is handling this would be a cleaner approach
