### ISSUE TITLE
Update vulnerable libraries (jQuery v2.1.4, Bootstrap v3.3.5 and Moment.js v2.2.1) in HangFire Dashboard dependencies

### ISSUE THREAD

**Issue by rahulisola** [HangfireIO/Hangfire#1239]
Example 1:
jQuery version 2.1.4 has known security issues. For more information, visit these websites:
https://github.com/jquery/jquery/issues/2432
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
http://research.insecurelabs.org/jquery/test/

Example 2:
Bootstrap version 3.3.5 has known security issues. For more information, visit these websites:
https://github.com/twbs/bootstrap/issues/20184

Example 3:
Moment.js version 2.2.1 has known security issues. For more information, visit these websites:
https://github.com/moment/moment/issues/2936

PS: The vulnerability might be affecting a feature of the library that the dashboard is not using. If the vulnerable feature is not used, this alert can be consider as false positive and may be closed. Still, always good to keep it up to date and use the latest version.

**Comment by cmlenz** [comment]
We just ran into this (the outdated jQuery version) in the context of a pen test. Would it be possible to upgrade to a current jQuery version in an upcoming Hangfire release, at least one without open known security vulnerabilities?

**Comment by cmlenz** [comment]
[v1.7.21](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.21) includes updates to jQuery, Bootstrap, and Moment.js:

> Changed – Upgrade jQuery from 2.1.4 to 2.2.4 in Dashboard UI.
> Changed – Upgrade Bootstrap from 3.3.5 to 3.3.7 in Dashboard UI.
> Changed – Upgrade Moment.js to 2.29.1 in Dashboard UI.

So I suppose this issue can be closed now.

**Comment by odinserj** [comment]
Yes, very few features are used by Hangfire, but I've bumped those versions anyway to avoid false positives. However there's a regression in #1844, so it's better to upgrade directly to version 1.7.22 that will be released soon.
