### ISSUE TITLE
IJobCancellationToken.ShutdownToken is not cancelled

### ISSUE THREAD

**Issue by henkmollema** [HangfireIO/Hangfire#1254]
A `CancellationToken` instance retrieved from `IJobCancellationToken.ShutdownToken` is not being cancelled when a job is deleted. Calling `CancellationToken.ThrowIfCancellationRequested` has no effect and `IsCancellationRequested` remains `false`.

However, calling `IJobCancellationToken.ThrowIfCancellationRequested()` does have the desired effect.

**Comment by GangRobinNiu** [comment]
I experienced the same issue. Is there any plan to fix it?

**Comment by odinserj** [comment]
This feature is implemented in 1.7.0, and you can use regular `CancellationToken` or `ShutdownToken` in your jobs – they will be triggered asynchronously not only during shutdown, but also on state change. There's the `BackgroundJobServerOptions.CancellationCheckInterval` property to control how often to check the status of a background job.
