### ISSUE TITLE
How to setup hangfire with .net core and angular spa service???

### ISSUE THREAD

**Issue by phucphanJaneto** [HangfireIO/Hangfire#1261]
Hi,

I use .Net core with Angular Spa Service and I try to setup hangfire with these but I can't connect to hangfire dashboard. 

I always redirect to Angular begin start page. 

Can you help configuration this?

**Comment by rsilvanet** [comment]
Hi @phucphanJaneto, can you provide how did you configured hangfire in your code?

This code should do the job:

```
public static void Configure(IApplicationBuilder app, IConfigurationRoot config)
{
    var dashboardPath = "http://localhost:52858/hangfire";

    app.UseHangfireServer();
    app.UseHangfireDashboard(dashboardPath, dashboardOptions);
}
```

But depending on your application, maybe your problem is the route configuration of your angular app that is forcing the redirect.

**Comment by phucphanJaneto** [comment]
@rsilvanet : Many thanks.

**Comment by rsilvanet** [comment]
Hi @phucphanJaneto, no problem. Did you make it work?

**Comment by phucphanJaneto** [comment]
Hi @rsilvanet . Yes, it works

**Comment by rsilvanet** [comment]
Nice @phucphanJaneto! Close this issue if possible, please.

**Comment by jepzen** [comment]
> 
> 
> Hi @phucphanJaneto, can you provide how did you configured hangfire in your code?
> 
> This code should do the job:
> 
> ```
> public static void Configure(IApplicationBuilder app, IConfigurationRoot config)
> {
>     var dashboardPath = "http://localhost:52858/hangfire";
> 
>     app.UseHangfireServer();
>     app.UseHangfireDashboard(dashboardPath, dashboardOptions);
> }
> ```
> 
> But depending on your application, maybe your problem is the route configuration of your angular app that is forcing the redirect.

Where is dashboardOptions set?

**Comment by yadurajshakti** [comment]
I might be late..
If you don't want to Run Angular App from Visual Studio (i.e. Ctrl+F5 etc) then one option might be to disable running Angular SPA from ASP.NET Core.
I just comment out the following in Startup:

```
            app.UseSpa(spa =>
            {              
                    spa.Options.SourcePath = "ClientApp";
                   if (env.IsDevelopment())
                   {
                          spa.UseAngularCliServer(npmScript: "start");
                   }
            });

            //Hangfire Dashboard
            app.UseHangfireDashboard();
            backgroundJobs.Enqueue(() => Console.WriteLine("Hello world from Hangfire!"));
```

**Comment by jepzen** [comment]
I think I solved it by adding the hangfire dashboard before the SPA
