### ISSUE TITLE
Passing Stream as job argument

### ISSUE THREAD

**Issue by kkorus** [HangfireIO/Hangfire#1271]
My background work needs to work on Stream. 
Would you recommend to serialize it and pass as argument or store Stream in database and pass its ID to background job?

**Comment by pieceofsummer** [comment]
You cannot do that since streams can't be serialized. You may read stream content and pass it to your job as a base64-encoded string (or whatever), then create a MemoryStream with given content inside your job method.

**Comment by kkorus** [comment]
@pieceofsummer  But it may happen that document size will be greater then maximum allowed 16mb right?

**Comment by pieceofsummer** [comment]
@kkorus sure. If you expect large uploads, then just save it into a temp directory and pass your job a file name to process.
