### ISSUE TITLE
Handler/Notification for failed job

### ISSUE THREAD

**Issue by kkorus** [HangfireIO/Hangfire#1272]
Is there any way to be notified if job failed all attempts so I could perform some actions?

For example: Job was reiterated 3 times, after that I would like to do some cleaning as there were some changes made to satisfy background job. You can think of it as deal letter queue subscription.

**Comment by pieceofsummer** [comment]
You may create a custom `IApplyStateFilter`, and do some notifications (e.g. send email) once a job is transitioned to `Failed` state.
