### ISSUE TITLE
Hangfire ignores AutomaticRetry attribute on method (bug)

### ISSUE THREAD

**Issue by kkorus** [HangfireIO/Hangfire#1273]
I have set automatic retry attempts to be default 3 (instead 10 as I believe is by default)

```csharp
Hangfire.GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 3 })
```

but for some job I want to set attempts count to 0

```csharp
public interface IMyJob
{
    void DoSomething();
}

public class MyBackgroundJob : IMyJob
{
    [AutomaticRetry(Attempts = 0)]
    public void DoSomething()
    {
    }
}
```

Hangfire ingores this attribute and tries 3 attempts instead of 0.

**Comment by kkorus** [comment]
It turns out that I need to put attribute on interface method 

```csharp
[AutomaticRetry(Attempts = 0)]
void DoSomething();
```

**Comment by hidegh** [comment]
@kkorus probably depends on whether you use the interface type or class type when enqueuing.
