### ISSUE TITLE
Hangfire Creates Multiple servers under one app pool as soon as I added Queues to it.

### ISSUE THREAD

**Issue by tiaan-lg** [HangfireIO/Hangfire#1279]
It has been running fine for 2 years now

Then i updated to version 1.6.20

Added 3 Queues to it 

`var options = new BackgroundJobServerOptions
            {
                Queues = new[] { critical, default, non_critical }
            };`

Added the critical attribute to 3 jobs, leaving the rest in the default queue

Shortly after that i noticed hangfire was creating multiple servers, up to 30. Causing our application pool to crash

After removing the queues and deleting the servers from the db manualy in the hangfire.server table 
all was normal again

I would still like to be able to use queues in the future and also now why this was happening.

**Comment by Zapnologica** [comment]
I have been experiencing the same issues with hangfire.

**Comment by rsilvanet** [comment]
Hi @tiaan-lg, some questions here:

1 - Is your application a web app? Is it running on IIS?
2 - Which point of the app lifecycle are you creating your servers?
3 - Are you doing the dispose of your servers properly in the "shutdown" of your app?

Asking you these questions to understand better your scenario, because depending on your code structure, if your application restarts it will create new servers without remove the existent ones.

**Comment by tiaan-lg** [comment]
Hi

1. Its a ASP.NET Web API 2 running on ISS 6 on a windows server
2. Im doing it in the API Startup.cs using the Owin Extension

![image](https://user-images.githubusercontent.com/42767734/46534215-b1083980-c8a7-11e8-9652-a05536bddcb4.png)

![image](https://user-images.githubusercontent.com/42767734/46534232-c2514600-c8a7-11e8-90dc-7cc215ff5963.png)

3. I havent added any disposing code cause im using the OWIN extension methods explained here

http://docs.hangfire.io/en/latest/background-processing/processing-jobs-in-web-app.html#using-owin-extension-methods

Could adding queues to my hangfire be causing the Owin extension not to function properly?

**Comment by tiaan-lg** [comment]
I was able to fix this a few months ago, it was not related to hangfire at all. It was caused by a memory leak in my site.
