### ISSUE TITLE
Retries with expired jobs

### ISSUE THREAD

**Issue by woellij** [HangfireIO/Hangfire#1284]
Hi everybody,

we're currently having an issue with retries, that ended up being deleted (either through dashboard or in code)

But they are stuck on the "Retries" tab (with their ID and the count of them)

Deleting them from there has no effect.

![retries](https://user-images.githubusercontent.com/5063919/47147722-25db6a80-d2cf-11e8-9463-802d556b3317.png)

**Comment by odinserj** [comment]
@woellij, what version of Hangfire.Core are you using?

**Comment by woellij** [comment]
We're using Hangfire.Core 1.6.19 with Hangfire.SqlServer 1.6.20

**Comment by odinserj** [comment]
@woellij, try updating [Hangfire.Core to 1.6.20](https://www.hangfire.io/blog/2018/07/21/hangfire-1.6.20.html), the following change could fix the behavior. 

> Fixed – Disallow transitions to the Failed state on retries that bypass all the filters.

And I'm afraid the only way to remove those empty records is to run the following script against your database. 

```sql
DELETE FROM [HangFire].[Set]
WHERE [Key] = N'retries' AND [Value] = N'<jobid>'
```

If there are a lot of them, you can just run the following query several times instead.

```sql
DELETE TOP (1000) FROM [HangFire].[Set]
WHERE [Key] = N'retries'
```
