### ISSUE TITLE
Help with job timing

### ISSUE THREAD

**Issue by Zapnologica** [HangfireIO/Hangfire#1285]
Good day, I am hoping someone can help me.

I utilize hang-fire to run many jobs on a times basis. Generally every 5 minutes. However I have run into a small issue,  it seems hang-fire schedules all the jobs ON the minute, causing a massive peak load on our database  (each job queries the database).

However I only need the jobs to run roughly every 5 minutes. doesn't have to be on the minute,  One job can run at  13:01 and another at 13:03  it doesn't matter to me. However this would spread out my Database load substantially and save us quite a lot on hosting a larger database than we need.

Here is an image of our database usage.  You can see the spikes on the minute when the jobs run.
![image](https://user-images.githubusercontent.com/3656913/47171276-95ba1700-d308-11e8-9e69-92a208bb04c6.png)

Is there any other way I can configure the jobs to be abit more flexible in their execution?

**Comment by pieceofsummer** [comment]
Can you adjust your jobs to use different schedules? Set `0/5 * * * *` for some of them, `1/5 * * * *` for some others, `2/5 * * * *` for others etc.
