### ISSUE TITLE
Cannot create background task for Action that involves 

### ISSUE THREAD

**Issue by rossknudsen** [HangfireIO/Hangfire#1289]
I discovered that it doesn't appear to be possible to chain method calls together when queuing a job.  For instance I wanted to do the following:

`            BackgroundJob.Enqueue<ConverterSelector>(s => s.SelectConverter(supplier, product, source).ConvertRecords());
`

Where I request a `ConverterSelector` class which allows me to get the correct converter by calling `SelectConverter()`.  I then want to call `ConvertRecords()` on the returned object.  However the validation checks performed in [Job.Validate](https://github.com/HangfireIO/Hangfire/blob/175207c2e0f9a70ba02b7dfc409e1a79e3c066c9/src/Hangfire.Core/Common/Job.cs#L391) seem to check that the object returned by `SelectConverter()` is of type `ConverterSelector` (i.e. the generic type).  Which is obviously incorrect.

When I change my code to the following:

`
            BackgroundJob.Enqueue<ConverterSelector>(s => s.Convert(supplier, product, source));
`

It works without issue.  I'm not sure if the validation can accommodate handling chained method calls or if there is some limitation.  Also I didn't run across any discussion on this topic in my travels, but apologies if it has already been covered.

**Comment by burningice2866** [comment]
I suppose the obvious question here is, why? Why would you want to do it like this instead of wrapping your SelectConverter resolver and related ConvertRecords() call into a higher method that can be scheduled, like

```
public static void ConvertRecords(... supplier, ... product, ... source)
{
    var converter = ConverterSelector.SelectConverter(supplier, product, source);

    converter.ConvertRecords();
}    
```

And then enqueue that method

**Comment by burningice2866** [comment]
You could put the higher `ConvertRecords` method in a seperate class that takes `ConverterSelector` as a DI on its contstructor and then get the dependency graph resolved that way.

Common practice as i've seen it amongst most users of Hangfire is to wrap the enqued method in a dedicated Hangfire job runner class which then internally can instantiate and invoke the underlying and concrete logic. That way you don't get existing backend code mixed up with Hangfire directly but can decouple the enquing of jobs from the actual code you want to run.

**Comment by rossknudsen** [comment]
Hmmm, yes it looks quite difficult to make it work with a method chain as I was originally trying to do.  Serializing/deserializing the arbitrary number of method calls in the chain and then invoking them, doesn't seem to be worth the effort.  I'll make use of your suggestion above.

For anyone finding this, the error I was getting was:

> ArgumentException: The type `IConverterSelector` must be derived from the `ConverterSelector` type.
