### ISSUE TITLE
Feature Request : Customizing Navbar Brand Header of Hangfire Dashboard

### ISSUE THREAD

**Issue by iSatishYadav** [HangfireIO/Hangfire#1292]
## Feature Request : Customizing Navbar Brand Header of Hangfire Dashboard
Currently _Hangfire Dashboard_ is hard-coded in `LayoutPage.cshtml` here:
https://github.com/HangfireIO/Hangfire/blob/053afff4b7fcfa2be060760b14879c5ac7a93204/src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml#L41

Can we think of customizing it with a property in `DashboardOptions`?

**Comment by odinserj** [comment]
Please describe what problem did you face with – i.e. why do you need to customize the header.

**Comment by odinserj** [comment]
Duplicate of #1310
