### ISSUE TITLE
Hangfire could not load file or assembly 'App_Web.*, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies

### ISSUE THREAD

**Issue by elricstorm** [HangfireIO/Hangfire#1294]
I do not have this issue on my Dev server but on my Prod server, which has load balancers in effect, whenever the server instance changes, this message occurs.

PRODDNETLS01:1604 is an example of one server.

Later on:

PRODDNETLS02:3845 is an example of another server that comes up in the pool.  LS01 then goes away.

Right after this occurs, I receive the message above.  

This is just a standard vb.net asp.net setup and again, I've run thousands of jobs with no issue.  However, whenever the server instance changes, the file or assembly error occurs.  It always begins with App_Web and the remainder of the error is dependent on the instance.

We only have two servers (as shown above) 01 and 02, but they do not show up in the Server list on the hangfire dashboard at the same time.  Also, the ports can and will change as well.

**Comment by odinserj** [comment]
Looks like you define your background jobs in views or in something like that, which lead to the fact that they are compiled into a temporary assembly (and each time with a different name). Instead place them at least near controllers or other application classes that compile into the main assembly of your application. If it isn't possible, create a new class library project and put them into it.

**Comment by odinserj** [comment]
As I've said earlier, that's because your background jobs belong to a dynamic type that's generated in run-time, when your application is started, and that type exists only for its process lifetime. You need to place your background job methods into a type that doesn't belong to a web page:

```csharp
public class MyBackgroundJobs
{
    public void MyMethod(int arg1, string arg2)
    {
        // Processing
    }
}
```
