### ISSUE TITLE
Using DI in Dashboard RazorPage with AspNetCore

### ISSUE THREAD

**Issue by salem84** [HangfireIO/Hangfire#1300]
I'm extending Dashboard in AspNetCore web application, using RazorPages with a code similar at https://gist.github.com/gandarez/9df813fc7d11f85c0d585a8257aedd79 described in #608 issue.

I have to use EF Core DbContext using DI... do you have any sample to achieve it ?
Thanks

**Comment by odinserj** [comment]
I'm afraid the only way currently is to use singleton-based factories in your pages. The things could be changed in 2.0, where a single IoC container could be used for all the features, including job filters and pages.
