### ISSUE TITLE
Recurring job and mulptiple servers 

### ISSUE THREAD

**Issue by sebitsi** [HangfireIO/Hangfire#1305]
Hi, 

Documets said

> A special component in Hangfire Server (see Processing background jobs) checks the recurring jobs on a minute-based interval and then enqueues them as fire-and-forget Jobs

If we have more than one server which "special component" will enqueue recurring job ?
If there are two servers Will this job be enqueded twice ?

Thanks for advance.

Edvin

**Comment by odinserj** [comment]
Under normal circumstances they are synchronized using the underlying storage, so you can run multiple servers, and you'll get only one fired recurring job at a time. But this is a distributed processing, and there always may be a case that your background job method will be executed twice or more when failure occurs – processing with *exactly once* semantics processing is really hard to achieve.
