### ISSUE TITLE
Hangfire Dashboard title or logo

### ISSUE THREAD

**Issue by HakanKaraoglu** [HangfireIO/Hangfire#1310]
Hi,

How to change Hangfire title? I want to put there company name or logo.

Is there an improvement in this issue?

B.R.

**Comment by odinserj** [comment]
There's no easy solution for now, and I doubt custom re-branding will be available for the dashboard in open-source version.

**Comment by ivanvoitovych** [comment]
there is a solution for .net core application, you just need to catch hangfire request and inject whatever you want, for example:
```
//in Startup
app.UseMiddleware<CustomHangfireFilter>();

//CustomHangfireFilter.cs

 public class CustomHangfireFilter
    {
        private readonly RequestDelegate next;
        public CustomHangfireFilter(RequestDelegate next)
        {
            this.next = next;
        }
        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Path.Value.StartsWith("/hangfire/js")) //for example, you can catch js file
            {

                var newContent = string.Empty;
                var existingBody = context.Response.Body;

                using (var newBody = new MemoryStream())
                {
                    context.Response.Body = newBody;

                    await next(context);

                    // Set the stream back to the original.
                    context.Response.Body = existingBody;

                    newBody.Seek(0, SeekOrigin.Begin);

                    newContent = new StreamReader(newBody).ReadToEnd();

                    newContent += @"
                                    $(function(){
                                   //use jQuery to append your custom html
                                    });";

                    // Send our modified content to the response body.
                    await context.Response.WriteAsync(newContent);
                }

            }
            else
            {
                await next(context);
            }
        }
}

```

**Comment by caioproiete** [comment]
For others looking for a workaround to change the title of a Hangfire dashboard, I've put together a simple library that does the job - same approach as above using a custom middleware to make the replacement. Works with ASP .NET Core apps as well as with Owin-based apps.

https://github.com/caioproiete/hangfire-dashboard-customize

[![hangfire-dashboard-customize](https://raw.githubusercontent.com/caioproiete/hangfire-dashboard-customize/master/assets/hangfire-dashboard-customize-small.png)](https://github.com/caioproiete/hangfire-dashboard-customize)

**Comment by caveofjulian** [comment]
> For others looking for a workaround to change the title of a Hangfire dashboard, I've put together a simple library that does the job - same approach as above using a custom middleware to make the replacement. Works with ASP .NET Core apps as well as with Owin-based apps.
> 
> https://github.com/caioproiete/hangfire-dashboard-customize
> 
> [![hangfire-dashboard-customize](https://raw.githubusercontent.com/caioproiete/hangfire-dashboard-customize/master/assets/hangfire-dashboard-customize-small.png)](https://github.com/caioproiete/hangfire-dashboard-customize)

Pretty flawed logic. This would only work if hangfire is the only HTML page you are serving

**Comment by augustoproiete** [comment]
> Pretty flawed logic. This would only work if hangfire is the only HTML page you are serving

@caveofjulian I'm not sure what you were expecting, but your tone here is rude and completely uncalled for - unlike most users whom I do my very best to support, I'm happy I won't be needing to interact with you in the future 👋

**Comment by caveofjulian** [comment]
@augustoproiete sorry, was just direct - not rude. It's good to point out because it causes bugs while that's totally unnecessary for this library.

**Comment by riaadh** [comment]
> @augustoproiete sorry, was just direct - not rude. It's good to point out because it causes bugs while that's totally unnecessary for this library.

So fix it instead of whining.

**Comment by sacalata** [comment]
This issue should be closed, this feature was already added, although I'm not sure which version introduced it.

In the current release of Hangfire you can do this:
```
        app.UseRouting();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapHangfireDashboard("/hangfire", new DashboardOptions
            {
                DashboardTitle = "My very cool title",
                DarkModeEnabled = true
            });
        });
```

**Comment by odinserj** [comment]
Yep thanks!
