### ISSUE TITLE
Use guid for job id? 

### ISSUE THREAD

**Issue by ArcadeRenegade** [HangfireIO/Hangfire#1312]
Hi, is it possible to use guid or bigint for jobid?

I'm concerned that this application I am working on will reach the max size of integer jobids fairly quickly as a lot of jobs are created.

I'm using PostgreSQL for storing hangfire data.

Thanks!

**Comment by burningice2866** [comment]
Technically that's a storage implementation, Hangfire itself uses strings
as it's id-type.

My Hangfire.CompositeC1 storage implementation uses guids since C1 doesn't
necessarily have a SQL database as its underlying backing but can use text
files.

**Comment by ArcadeRenegade** [comment]
OK thank you. I have submitted an issue to the Hangfire.PostgreSQL repository.

https://github.com/frankhommers/Hangfire.PostgreSql/issues/100
