### ISSUE TITLE
Wrong date/time on dashboard

### ISSUE THREAD

**Issue by thdotnet** [HangfireIO/Hangfire#1313]
I'm trying to find a way to fix the datetime from the dashboard but without redeploying the app. Is there a way to update it by deleting / updating the records directly through the table? When I've setup the hangfire, it was based on UTC that was configured on the server, but now I've set a different timezone, but it's still displaying as utc. I already restarted the IIS, but seems that it didn't work. Any clues?

**Comment by odinserj** [comment]
Hangfire always uses UTC for working with dates internally. Time zone is applied only in your browser using the [moment.js](https://momentjs.com) library, while you are using the dashboard. So the problem relates either to wrong time zone detection in your browser, or by the fact you've changed time settings on your machine. Which one is yours?

**Comment by thdotnet** [comment]
Got it. In this case, the problem was with my machine which is using UTC -3 and made me think it was wrong in the server.
