### ISSUE TITLE
How to configure Hangfire in N-tier scenarios?

### ISSUE THREAD

**Issue by furqansafdar** [HangfireIO/Hangfire#1317]
My question, what if client does not have any knowledge about Hangfire database connection-string instead I want to configure the client-side to enqueue background job via some kind of exposed service in an n-tier setup? Please direct me to some articles and documentations that can help. Thanks.

**Comment by natiki** [comment]
Create your service (that does have the DBMS knowledge) and then the API exposed by the service is up to you. 

But largely you would probably want to allow it to do the same things you see off [BackgroundJob](http://docs.hangfire.io/en/latest/background-methods/calling-methods-in-background.html) and [RecurringJob](http://docs.hangfire.io/en/latest/background-methods/performing-recurrent-tasks.html)
