### ISSUE TITLE
Why finished job state has not been setted to Success?

### ISSUE THREAD

**Issue by gouhan** [HangfireIO/Hangfire#1322]
![image](https://user-images.githubusercontent.com/8605053/50686599-05fb4d80-1059-11e9-8dca-15faff5de83f.png)
![7b c89 lquq9u5vn6w jei](https://user-images.githubusercontent.com/8605053/50686626-1ad7e100-1059-11e9-864b-34b7658ba6f0.png)
the processing state jobs,actually are all finished .but why its state has not been changed to Success.
The later dispatched jobs are all enqueued in the job queue,have not been dequeued.

**Comment by gouhan** [comment]
![image](https://user-images.githubusercontent.com/8605053/50686909-28419b00-105a-11e9-9e6d-c9ae6a3072bb.png)

**Comment by gouhan** [comment]
I found in the log file,that normally once a job executed.will take these steps:
Acquire resource=job:67:state-lock, timeout=00:15:00 
SetJobState jobId=67 
IncrementCounter key=stats:succeeded 
ExpireJob jobId=67 
Release resource=job:67:state-lock 
RemoveFromQueue JobId=67 

but the later jobs have not been executed with these steps.

**Comment by odinserj** [comment]
If you are using MySQL as a job storage, the problem may relate to its implementation. Does the problem persist when using SQL Server as a job storage?
