### ISSUE TITLE
Calls to ReadFormSafeAsync only returns values on first call

### ISSUE THREAD

**Issue by DC-jc** [HangfireIO/Hangfire#1324]
In OwinRequestExtension there is a hack to 

> "prevent "Unable to cast object of type 'Microsoft.Owin.FormCollection'  to type 'Microsoft.Owin.IFormCollection'" exception, when internalized version does not match the current project's one."

The first time this method is called the Form collection is returned as it should without any problems. Subsequent calls to this method however returns an empty collection.

The root cause of this seems to be the removing of the FormCollection entry in context.Environment.
After the FormCollection entry is re-added to the collection, calls to ReadFormAsync again returns the correct values.

I'm speculating on the cause of the behavior here, but my guess is that ReadFormAsync is optimized to only parse the request body on the first call and adds the entry in the Environment collection. After that, ReadFormAsync just returns the already stored collection.

I haven't been able to reproduce the problem that the hack was supposed to fix so I'm don't really have any suggestions on any workarounds since any changes might break the original fix.

**Comment by odinserj** [comment]
@DC-jc, could you tell me what problem is caused by the behavior you've described?

**Comment by DC-jc** [comment]
@odinserj I ran in to problems when I tried to use the Hangfire.Core.Dashboard.Management extension. The same issue I had is described here: https://github.com/tracstarr/Hangfire.Core.Dashboard.Management/issues/2

The extension lets users set parameters and create new jobs, and the parameters are sent by POST to the server which then tries to retrieve them by calling `Task.Run(() => context.Request.GetFormValuesAsync(PARAMETERNAME)).Result.FirstOrDefault();` where context is DashboardContext. 

The problem was that the jobs always got created with the parameter value set to `null`.  

My current workaround is to add the Microsoft.Owin package to the affected extension and call 
```
var owinContext = new Microsoft.Owin.OwinContext(context.GetOwinEnvironment());    
var formValues = owinContext.Request.ReadFormAsync().Result;
```

**Comment by odinserj** [comment]
Thanks for the details, now I understand this is definitely a problem. May be we should cache the `form` variable somewhere after reading it in https://github.com/HangfireIO/Hangfire/blob/053afff4b7fcfa2be060760b14879c5ac7a93204/src/Hangfire.Core/Dashboard/Owin/OwinDashboardRequest.cs#L45.

**Comment by DC-jc** [comment]
That would solve my problem, and is essentially what the current Owin implementation does.
The current implementation looks like this:
```
public async Task<IFormCollection> ReadFormAsync()
        {
            var form = Get<IFormCollection>("Microsoft.Owin.Form#collection");
            if (form == null)
            {
                string text;
                // Don't close, it prevents re-winding.
                using (var reader = new StreamReader(Body, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: 4 * 1024, leaveOpen: true))
                {
                    text = await reader.ReadToEndAsync();
                }
                form = OwinHelpers.GetForm(text);
                Set("Microsoft.Owin.Form#collection", form);
            }

            return form;
        }
```
The reason multiple calls to ReadFormSafeAsync only returns result on the first attempt is that the owin authors for some reason decided to leave the Body stream open to prevent re-winding.

This change was added to Owin 3.0.0 and from what I can tell ReadFormAsync didn't exists in Owin 2.1.0, so there's only a few versions of the Owin 3 alpha releases where the ReadFormSafeAsync hack actually works.

So my suggestion is to change the GetFormValuesAsync method to this:
```
		
IFormCollection _cachedFormCollection;
		
public override async Task<IList<string>> GetFormValuesAsync(string key)
{
	IFormCollection form;
			
	try
	{
		var form = await _context.Request.ReadFormAsync();
	}
	catch(InvalidCastException)
	{
		if(_cachedFormCollection == null) _cachedFormCollection = await _context.ReadFormSafeAsync();
		form = _cachedFormCollection;
	}
	finally
	{
		return form.GetValues(key) ?? new List<string>();
	}
}
```

I'm thinking that this way any future changes to Owin has less chance to break anything.
It might also be appropriate to add a logger warning in the catch to alert any consumer that they might have versioning issues.

**Comment by odinserj** [comment]
Maybe we need only to add a caching field like in the following sample? That package is internalised anyway, so there should be no versioning issues, e.g. when application uses different version of Microsoft.Owin package.

```csharp
IFormCollection _cachedFormCollection;
		
public override async Task<IList<string>> GetFormValuesAsync(string key)
{
    if (_cachedFormCollection != null) return _cachedFormCollection;

    _cachedFormCollection = await _context.Request.ReadFormSafeAsync();
    return _cachedFormCollection;
}
```

**Comment by DC-jc** [comment]
Yeah, I was wondering how the original issue could have happened.

So I went back and tried to reproduce the original issue in https://github.com/HangfireIO/Hangfire/issues/386 and it is kind of an edge case. The only way I could reproduce it was by adding Owin 3.0.1 to GAC and then build the consumer project against other versions (tried both 3.0.0 and 4.0.0) and disable binding-redirects. Then I added a new middleware in the owin pipeline which invoked OwinContext.Request.ReadFormAsync. That way I could get InvalidCastExceptions in Hangfires middleware. So this issue can probably only happen if the solution is hosted in IIS or a self-hosted service.

So as I said it is kind of an edge case and its more of a system configuration problem than a bug in Hangfire. Another way to see it, if hangfire gets called first in the pipeline, then ReadFormAsync will always succeed and then fail in whatever meddleware that is next in the pipeline.

Also since Owin 3.0.1 prevents the Body stream from being reset, ReadFormSafeAsync can't really solve anything.

The only workaround I found that might possibly work is this
```
public override async Task<IList<string>> GetFormValuesAsync(string key)
{
                if (_context.Environment.ContainsKey("Microsoft.Owin.Form#collection") && 
                   !(_context.Environment["Microsoft.Owin.Form#collection"] is IFormCollection))
                {
                    dynamic form = _context.Request.Environment["Microsoft.Owin.Form#collection"];
                    return form.GetValues(key) ?? new List<string>();
                }
               else
               {
                    var form = await _context.Request.ReadFormAsync();
                    return form.GetValues(key) ?? new List<string>();
               }
}
```
It's by no means an elegant solution though.

So my suggestion is to drop the ReadFromSafeAsync function all together. If someone gets a InvalidCastException then they have a problem in their environment and it's not Hangfire's responsibility to work around it. That will only obscure their root problem.

**Comment by odinserj** [comment]
Thanks for the great investigation, @DC-jc. But what if we change the method to the following one? In this case we'll be able to handle other form types. And if another middleware will fail, because Hangfire set its own version of IFormCollection then no problem – it was dashboard-related request. Since an ideal solution can't be approached, we can end with using best-effort one.

```csharp
public override async Task<IList<string>> GetFormValuesAsync(string key)
{
    IList<string> values;

    if (_context.Environment.ContainsKey("Microsoft.Owin.Form#collection"))
    {
        if (_context.Environment["Microsoft.Owin.Form#collection"] is IFormCollection)
        {
            var form = (IFormCollection)_context.Request.Environment["Microsoft.Owin.Form#collection"];
            values = form.GetValues(key);
        }
        else
        {
            dynamic form = _context.Request.Environment["Microsoft.Owin.Form#collection"];
            values = form.GetValues(key);
        }
    }
    else
    {
        var form = await _context.Request.ReadFormAsync();
        values = form.GetValues(key);
        // We can also try to seek at the beginning of a stream hoping it works.
    }

    return values ?? new List<string>();
}
```

**Comment by DC-jc** [comment]
This looks good, it covers pretty much all circumstances I can think of. Should I create a pull request for this so we'll have the change properly documented?

**Comment by odinserj** [comment]
Sure, pull request will be great!
