### ISSUE TITLE
Duplicate Job Processing for Job Type ( Schedule )

### ISSUE THREAD

**Issue by LucasFarley** [HangfireIO/Hangfire#1326]
Hangfire is processing a schedule job ( one time ) twice incorrectly.

It is happening the Schedule Job.  See how the job was scheduled.

`BackgroundJob.Schedule(() => funcScheduleDocScanAsync(null, varBatchItem.BtsDocType, varBatchItem.BtsId), TimeSpan.FromMilliseconds(30));`

![screenshot_2](https://user-images.githubusercontent.com/22159940/51116231-b0116d00-17f1-11e9-9dc0-ee0ce31202d2.png)

**Comment by LucasFarley** [comment]
I am using Hangfire 1.6.21 with MySQL ( https://github.com/arnoldasgudas/Hangfire.MySqlStorage ).

**Comment by odinserj** [comment]
Does this problem persist when using SQL Server as a job storage? There are a lot of [intricate details](https://github.com/HangfireIO/Hangfire/issues/1296) required in job storage implementation to function correctly. So if the problem relate only to MySql storage, it's better to add an issue in its repository instead. 

I will try hard to implement some metrics to allow others to see the quality state of this or that storage implementation by the end of the year, but the topic is hard enough.

**Comment by LucasFarley** [comment]
@odinserj, thank you. I will open a ticket on MySql storage repository.
