### ISSUE TITLE
Web application shuts down after period of inactivity

### ISSUE THREAD

**Issue by PanzerKunst** [HangfireIO/Hangfire#1327]
I have been using Hangfire to execute recurring jobs, in a .NET MVC application.

My current issue is that after a period of inactivity (webapp receiving no requests), it shuts down. Hangfire writes a bunch of `Background process 'Worker #17ccb20d' was stopped due to a shutdown request` log lines.

I am struggling to have the web application always running. I have followed the [documentation page on how to make .NET applications always running](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html), namely:
- Configured Automatic Startup for an Application pool
- Set appliction pool property `Start Mode` to `AlwaysRunning`
- `ApplicationPreload` class with `Preload()` function
- Updated functions `Application_Start()` and `Application_End()` in `global.asax.cs`
- Created class `HangfireBootstrapper`
- Updated function `Configuration()` in `Startup.cs`

I have not tweaked `applicationHost.config` so far, as I don't think that it will solve my issue.

How do I prevent my web application from stopping due to inactivity, and Hangfire with it?

**Comment by odinserj** [comment]
Without enabling service autostart-providers via `applicationHost.config` file, always running mode will not be enabled for your application.

**Comment by PanzerKunst** [comment]
@odinserj Thank you for your reply. I am now trying to configure `applicationHost.config`, but due to lack of knowledge of the platform, as well as a not-so-basic setup, I would need some help to do it right.

We have a .NET web application that manages what we call "terminals". We deploy one instance of that web application for each terminal. Those apps run in 1 application pool (`EspProd`), and inside a single umbrella site (`EspProd`). In the scenario of terminals "abc" and "xyz", this would be the configuration in `applicationHost.config`:

    <configuration>
        <system.applicationHost>
            <applicationPools>
                <add name="EspProd" autoStart="true" startMode="AlwaysRunning" />
                <applicationPoolDefaults managedRuntimeVersion="v4.0">
                    <processModel identityType="ApplicationPoolIdentity" idleTimeout="00:00:00" />
                </applicationPoolDefaults>
            </applicationPools>

            <customMetadata />

            <listenerAdapters>
                <add name="http" />
            </listenerAdapters>

            <log>
                <centralBinaryLogFile enabled="true" directory="%SystemDrive%\inetpub\logs\LogFiles" />
                <centralW3CLogFile enabled="true" directory="%SystemDrive%\inetpub\logs\LogFiles" />
            </log>

            <sites>
                <site name="EspProd" id="1" serverAutoStart="true">
                    <application path="/abc" applicationPool="EspProd" serviceAutoStartEnabled="true" serviceAutoStartProvider="abcPreload">
                        <virtualDirectory path="/" physicalPath="C:\terminals\abc" />
                    </application>
                    <application path="/xyz" applicationPool="EspProd" serviceAutoStartEnabled="true" serviceAutoStartProvider="xyzPreload">
                        <virtualDirectory path="/" physicalPath="C:\terminals\xyz" />
                    </application>

                    <bindings>
                        <binding protocol="http" bindingInformation="*:80:ne.aefttt.com" />
                        <binding protocol="https" bindingInformation="*:443:ne.aefttt.com" sslFlags="0" />
                    </bindings>
                </site>
                <siteDefaults>
                    <logFile logFormat="W3C" directory="%SystemDrive%\inetpub\logs\LogFiles" />
                    <traceFailedRequestsLogging directory="%SystemDrive%\inetpub\logs\FailedReqLogFiles" />
                </siteDefaults>
                <applicationDefaults applicationPool="DefaultAppPool" />
                <virtualDirectoryDefaults allowSubDirConfig="true" />
            </sites>

            <webLimits />
            
            <serviceAutoStartProviders>
                <add name="abcPreload" type="terminal_web_page.Helpers.Hangfire.ApplicationPreload, terminal_web_page" />
                <add name="xyzPreload" type="terminal_web_page.Helpers.Hangfire.ApplicationPreload, terminal_web_page" />
            </serviceAutoStartProviders>

        </system.applicationHost>
    </configuration>

The webapp root folders `C:\terminals\abc` and `C:\terminals\xyz` have the same content, except for configuration files (read at app startup).

I wrote the above `applicationHost.config` with the following understanding:

![image](https://user-images.githubusercontent.com/1530772/51184447-97c64e80-18d4-11e9-86f2-401bd866bc07.png)

Is this a correct configuration in order to have both web applications running always?

**Comment by odinserj** [comment]
Yes, looks fine. Have you tried to run your applications with this configuration file?

**Comment by PanzerKunst** [comment]
The changes to `applicationHost.config` made the webapp always running, that was the issue. Overall, the .NET framework makes that simple feature really difficult, and I don't like that platform.

Big thank you @odinserj for your help!

**Comment by odinserj** [comment]
I agree it's very complex, it took many days to learn in what cases each option works, and in what cases it doesn't. That's simply because of an evolutionary architecture – those features were added one by one through the product lifetime. Try to check .NET Core platform, it's much simpler.
