### ISSUE TITLE
Failed job state information is not in DB

### ISSUE THREAD

**Issue by deimastep** [HangfireIO/Hangfire#1328]
https://github.com/HangfireIO/Hangfire/blob/a92ecf571eb61cd2b50b069cd7cbb9281bd76c04/src/Hangfire.SqlServer/SqlServerMonitoringApi.cs#L157

I'm using version 1.6.20.

I'm facing a `System.NullReferenceException` for certain failed jobs when issuing `JobStorage.Current.GetMonitoringApi().FailedJobs(...)` because `Func<>` parameter `stateData` value is `null`. And it is `null` because there is no such record in DB table `Hangfire.State` for certain `Hangfire.Job` entries which actually holds concrete `StateId` value.

P.S. The secondary question is why `Hangfire.State` have no record for `Hangfire.State.StateId`?
Similar tasks are failing in the same manner but for some of them there is not State record in DB.

StackTrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Hangfire.SqlServer.SqlServerMonitoringApi.<>c.b__13_1(SqlJob sqlJob, Job job, SafeDictionary`2 stateData)
 at Hangfire.SqlServer.SqlServerMonitoringApi.DeserializeJobs[TDto](ICollection`1 jobs, Func`4 selector)
 at Hangfire.SqlServer.SqlServerMonitoringApi.GetJobs[TDto](DbConnection connection, Int32 from, Int32 count, String stateName, Func`4 selector)
 at Hangfire.SqlServer.SqlServerMonitoringApi.<>c__DisplayClass13_0.b__0(DbConnection connection)
 at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
 at Hangfire.SqlServer.SqlServerMonitoringApi.FailedJobs(Int32 from, Int32 count)
 at SyncCustomers.Api.Admin.AdminController.HangfireRequeueFailedJobs(RequeueRequest request, CancellationToken cancellationToken)
```
DB excerpt for query
``` sql
;with cte as 
(
  select j.Id, row_number() over (order by j.Id desc) as row_num
  from [HangFire].Job j with (nolock, forceseek)
  where j.StateName = 'Failed'
)
select j.*, s.Reason as StateReason, s.Data as StateData
from [HangFire].Job j with (nolock)
inner join cte on cte.Id = j.Id 
left join [HangFire].State s with (nolock) on j.StateId = s.Id
where cte.row_num between 299100 and 299200
order by j.Id desc
```
Result. First record has state, second doesn't. Failing reason is the same.
```
54	9648	Failed	{"Type":"SyncCustomers.Api.Managers.Interfaces.ISyncManager, SyncCustomers.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Method":"SynchronizeAsync","ParameterTypes":"[\"System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"SyncCustomers.HostIntegration.Common.Country, SyncCustomers.HostIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\"]","Arguments":"[\"8\",\"1\"]"}	["8","1"]	2018-03-20 13:30:00.207	NULL	An exception occurred during performance of the job.	{"FailedAt":"2018-12-03T16:31:40.3537661Z","ExceptionType":"System.IO.FileLoadException","ExceptionMessage":"Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.... bla bla bla ..."}
53	9580	Failed	{"Type":"SyncCustomers.Api.Managers.Interfaces.ISyncManager, SyncCustomers.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Method":"SynchronizeAsync","ParameterTypes":"[\"System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"SyncCustomers.HostIntegration.Common.Country, SyncCustomers.HostIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\"]","Arguments":"[\"6\",\"1\"]"}	["6","1"]	2018-03-20 13:30:00.127	NULL	NULL	NULL
```

**Comment by odinserj** [comment]
Hm, do you have any records in the `State` table for the job 53, could you post them here? Also, what Hangfire version are you using?

**Comment by deimastep** [comment]
Version 1.6.20

As I've mentioned the strange thing that there is no State record at all for job 53 despite Job record holds StateId as 9580.

```sql
SELECT j.*, s.*
FROM HangFire.Job j (nolock)
LEFT JOIN HangFire.State s (nolock) ON s.Id = j.StateId
WHERE j.Id in (53,54)
```
produce
```
53	9580	Failed	{"Type":"SyncCustomers.Api.Managers.Interfaces.ISyncManager, SyncCustomers.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Method":"SynchronizeAsync","ParameterTypes":"[\"System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"SyncCustomers.HostIntegration.Common.Country, SyncCustomers.HostIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\"]","Arguments":"[\"6\",\"1\"]"}	["6","1"]	2018-03-20 13:30:00.127	NULL	NULL	NULL	NULL	NULL	NULL	NULL
54	9648	Failed	{"Type":"SyncCustomers.Api.Managers.Interfaces.ISyncManager, SyncCustomers.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Method":"SynchronizeAsync","ParameterTypes":"[\"System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"SyncCustomers.HostIntegration.Common.Country, SyncCustomers.HostIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\"]","Arguments":"[\"8\",\"1\"]"}	["8","1"]	2018-03-20 13:30:00.207	NULL	9648	449257	Failed	An exception occurred during performance of the job.	2018-12-03 16:31:40.353	{"FailedAt":"2018-12-03T16:31:40.3537661Z","ExceptionType":"System.IO.FileLoadException","ExceptionMessage":"Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies...."}
```

**Comment by odinserj** [comment]
Could you also run the following query to see is there any states for that job?

```sql
SELECT * FROM [HangFire].[State] WHERE [JobId] = 53
```

**Comment by deimastep** [comment]
No result for this query.

**Comment by odinserj** [comment]
The latest query results don't contain failed state information even for background job `54` (unlike in previous results). Hangfire removes records from the `State` table only together with related records in the `Job` table by using cascade deletion. Do you have any idea why and by whom those records in the `State` tables are removed?

**Comment by deimastep** [comment]
Sorry for delay,
As I see `Job` table holds `StateId` field. `State` table holds `JobId` fields.
The first query joins on `s.Id = j.StateId` and the second joins on `s.JobId = j.I`. And the result is different for them.
I have no idea ėow did it happen that `State` table doesn't have a related record for job in `Job` table. I only see that quite many failed jobs do not have state records. Other failed jobs do have.

P.S. I've solved an issue just by inserting fake records in `State` table for failed jobs in order to be able to use HangFire monitoring API to get failed jobs info.

**Comment by odinserj** [comment]
The `s.Id = j.StateId` query returns jobs with their current states, and `s.JobId = j.Id` condition returns jobs and all of their states. However regardless of the query, the `j.Id` should be equal to `s.JobId`, and this condition is wrong in the following results:

j.Id | j.StateId | j.StateName | j.InvocationData | j.Arguments | j.CreatedAt | j.ExpireAt | s.Id | s.JobId | s.Name | s.Reason | s.Data | s.CreatedAt
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
53 | 9580 | Failed | {"Type":...} | ["6","1"] | 2018-03-20 13:30:00.127 | NULL | NULL | NULL | NULL | NULL | NULL | NULL
54 | 9648 | Failed | {"Type":...} | ["8","1"] | 2018-03-20 13:30:00.207 | NULL | 9648 | 449257 | Failed | An exception occurred during performance of the job. | 2018-12-03 16:31:40.353 | {"FailedAt":"2018-12-03T16:31:40.3537661Z","ExceptionType":"System.IO.FileLoadException","ExceptionMessage":"Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies...."}

As you can see from the table, the second row has `j.Id = 54` and `s.JobId = 449257`, and the latter value is garbage. Try to install the latest `System.Data.SqlClient` package to your project, maybe this issue relate to some bug in .NET Core.

**Comment by deimastep** [comment]
Ok, Thanks!

I'm gonna close this issue I guess.
