### ISSUE TITLE
Dashboard URL not reachable but Hangfire running well

### ISSUE THREAD

**Issue by 2kPi** [HangfireIO/Hangfire#1339]
Hi all,

I have this issue in staging/production but not in my local machine.

All works well on dev machine, but when I deploy on staging/production server, the dashboard is not reachable under "localhost/hangfire" but Hangfire works (I use the DB to check the task status)!

- Version of `Hangfire.Core` : 1.6.19
- Storage : `Hangfire.SqlServer`
- Version of `Hangfire.Dashboard.Authorization`: 2.1.0
- Configuration logic: 2 recurents job, fisrt every 2 min, second dayly at 5:00pm 

I don't use OWIN, only filter by localhost:

```C#
public partial class Startup
{
    public void Configuration(IAppBuilder app)
    {
        // For OWIN use
        //ConfigureAuth(app);

        GlobalConfiguration.Configuration.UseSqlServerStorage(new L2VContext().Database.Connection.ConnectionString);

        var options = new DashboardOptions{
            Authorization = new[]{
                new LocalRequestsOnlyAuthorizationFilter()
            }
        };

        app.UseHangfireDashboard("/hangfire", options);
        app.UseHangfireServer();
    }
}
```
My staging IIS structure:

![image](https://user-images.githubusercontent.com/5517670/51893251-a583d580-23a4-11e9-9122-54408c17651b.png)

So when I try to reach the Dashboard at http://localhost/scheduler/hangfire (localy on the staging) I have this:

![image](https://user-images.githubusercontent.com/5517670/51893264-addc1080-23a4-11e9-8538-e4672cd1faa4.png)

Thank you in advance for the help ;-)

Question also posted here: https://github.com/HangfireIO/Hangfire/issues/819#issuecomment-458187391

**Comment by 2kPi** [comment]
@odinserj Thank you for having taken into consideration my issue and tagged as support.
I spent a lot of time on google, hangfire documentation, hangfire forum and stackoverflow but I saw that a lot of people have the same issue but no clear solution how to fix that issue.

**Comment by odinserj** [comment]
Sorry for confusing you, I've renamed the `support` tag to the `question` one. Regarding the problem, it's caused by the wrong handler selected by IIS for this request. Your error details page shows as that `StaticFile` handler is used, so there are problems with the configuration. Run the following command and ensure ASP.NET is properly installed on your system, also ensure that integrated pipeline is used for your application pool.

```
aspnet_regiis.exe -i
```
