### ISSUE TITLE
Job never succeeds when viewed in dashboard.

### ISSUE THREAD

**Issue by TGerds** [HangfireIO/Hangfire#1346]
When I open a job in the dashboard, a new state "created" is added. This state comes from the Dashboard itself and makes no sense to me.

When this state is added to a currently processing job it will never have the state "Succeeded" in its history. The only way to tell that this job is done is by the "ExpiryAt" property.

I wouldn't expect the Dashboard to add new history entries.

This picture shows how it looks when I visited the Dashboard after the job finished.
![hangfire_notvisited](https://user-images.githubusercontent.com/26063481/52289934-4d823b80-296f-11e9-971b-8f1a0591bd87.png)

This picture shows how it looks when I visited the Dashboard before the job finished.
![hangfire_visited](https://user-images.githubusercontent.com/26063481/52290648-ce8e0280-2970-11e9-93ff-faa149bab68e.png)

I'm using Hangfire 1.6.22.

**Comment by pieceofsummer** [comment]
What storage are you using? Looks like your storage implementation uses a wrong order when selecting job state (the most recent state should be the first one).

**Comment by TGerds** [comment]
> What storage are you using?

You are right! I used the in-memory storage while developing and it behaves different to the sql storage. Now I switched to the sql storage and it works fine.
