### ISSUE TITLE
IJobCancellationToken - Preventing memory leaks

### ISSUE THREAD

**Issue by gravity00** [HangfireIO/Hangfire#1347]
Hi,

This isn't a bug, but an improvement suggestion.

When using the `IJobCancellationToken`, from what I'm seeing in the source code, the cancellation token used is the same used when shutting down the server, which is completely ok.
But because it essentially is a singleton, I believe with would be a good approach to prevent eventual memory leaks due to bad usage to create a linked token scoped to the job execution (ex: `CancellationTokenSource.CreateLinkedTokenSource`).

This suggestion comes from the following issue, related to `DbCommand` memory leak in .NET Framework (fixed in .NET Core) when using _async_ overloads: https://github.com/dotnet/corefx/issues/16439#issuecomment-459313520

Obviously this isn't an Hangfire problem, but I believe this prevention with minimum overhead won't hurt.

**Comment by odinserj** [comment]
Thanks for the hint, @gravity00! So the thing is when using the same cancellation token, there may be thousands of non-disposed registrations, if someone uses async methods of the `DbCommand` class. Apparently the problem is already solved in 1.7.0-beta4, where linked tokens are already [in use](https://github.com/HangfireIO/Hangfire/blob/d207b44f911c9bb984cb5e2212c45d317b9af81c/src/Hangfire.Core/Server/ServerJobCancellationToken.cs#L48) thanks to the new feature from PR #1209.

**Comment by gravity00** [comment]
@odinserj great! I'll give it a good test in the **1.7.0** release.

> 2500 databases 😳

Ahahah yes, this is a big challenge for us. As of now, with only an aplicacional server with a single Windows Service with Hangfire.Pro, backed up with a single (but shared) SQL Server instance, it has proven to be extremely reliable. Creating batch operations takes around 1 to 2 minutes, and the synchronization with 40 workers takes other 2 minutes. Because with new developments we are going to double the number of jobs per week (from 100 million to more than 200 million), we probably will need to escalate and give a look at your Redis packages.

I must tell you that I've been extremely impressed with Hangfire ever since I decided to introduce it as our batch server.

**Comment by odinserj** [comment]
If you are running on .NET Framework, you can try to use command batching by configuring the `CommandBatchMaxTimeout` option as shown below. Also, there are great changes in Hangfire.SqlServer 1.7 (available now as beta) that optimize the schema and reduce locking, so you can try them first.

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(@"connection_string", new SqlServerStorageOptions
    {
        CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
        TransactionIsolationLevel = IsolationLevel.ReadCommitted,
    });
```
