### ISSUE TITLE
Schedule a task to run x seconds for y seconds

### ISSUE THREAD

**Issue by jdahan91** [HangfireIO/Hangfire#1351]
I want to run a task for x seconds [duration] but i want it to be called every y seconds [interval]

For example, if i have duration 5 seconds and interval 1 second, the task will run every 1 second for an entire 5 seconds.

is it possible to do this?

**Comment by pieceofsummer** [comment]
Hangfire sure can run jobs on scheduled intervals, but a sub-minute resolution may be a problem. You may reduce the `SchedulePollingInterval` value to somewhat increase the resolution (at the cost of higher database load), but there are still factors you can't control (e.g. all workers are busy at the moment) that may affect the actual execution time.

But it can neither predict nor control the duration of a job. Only the job itself can choose to finish its execution, based on some external factors. For example, if your job supports cancellation, you may set a time limit on how long it is allowed to run before it is aborted:
```c#
public async Task JobMethodWithTimeout(TimeSpan timeout, CancellationToken cancellationToken)
{
    using (var timeoutTokenSource = new CancellationTokenSource(timeout))
    using (var linkedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutTokenSource.Token))
    {
        try
        {
             await JobMethod(linkedTokenSource.Token);
        }
        catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            // job is aborted because of a timeout
            // exit gracefully instead, so it is not re-queued
        }
    }
}

public async Task JobMethod(CancellationToken cancellationToken)
{
    // your original job method
}
```

But again, it can only tell the job to cancel. For that to actually work, the job method itself should properly support it (by forwarding the cancellation token to library method calls, and periodically checking if it was cancelled in synchronous parts of the code).

**Comment by jdahan91** [comment]
Do you think it would be possible to add this feature request?
