### ISSUE TITLE
SetRangeInHash

### ISSUE THREAD

**Issue by burningice2866** [HangfireIO/Hangfire#1352]
How come there is a SetRangeInHash method on both JobStorageConnection and IWriteOnlyTransaction ?

The two methods in SqlServer implementation used to be implemented quite the same but with the introduction of [SqlCommandBatch](https://github.com/HangfireIO/Hangfire/commit/6e55bc64ccab41a2b293d0b22ac0df7b47b24067#diff-9dcbe8a9726db571bb962b37dbab70d8), it was only the implementation in SqlServerConnection which was updated, not the method in SqlServerWriteOnlyTransaction.

**Comment by odinserj** [comment]
It was 2014, and I didn't want to spawn the whole transaction to call just a single method. This was a wrong reason, but we can't do anything now, except, perhaps removing it in 2.0. What problem did you face with?

**Comment by burningice2866** [comment]
@odinserj no problem, i just stumpled upon this when going through changes to update my own Storage Provider and i was just curious why we would want two different implementations of what seems to be the same thing. Looked like Code Duplication to me and why one could call the other?

**Comment by odinserj** [comment]
I simply didn't consider we can make a trivial change to remove this duplication, and in my opinion that's a non-easy task, especially in the `dev` branch.

**Comment by burningice2866** [comment]
Of course not. My initial question was also more on whether there is a difference in expected behavior - are the twho methods called in different scenarios expecting different behavior using the same input? Or are they exactly the same?

**Comment by odinserj** [comment]
Exactly the same, at least should be 😄
