### ISSUE TITLE
Incorrect Queues shown on 

### ISSUE THREAD

**Issue by wyeack** [HangfireIO/Hangfire#1356]
I have two servers, running Hangfire.  Each server has their own queue and there is one common queue between them, for example:

Server 1
```csharp
app.UseHangfireServer(new BackgroundJobServerOptions
{
    Queues = new [] { "cluster", "eos1" }
});
```

Server 2
```csharp
app.UseHangfireServer(new BackgroundJobServerOptions
{
    Queues = new [] { "cluster", "eos2" }
});
```

This is reflected in the Hangfire Dashboard:
https://www.screencast.com/t/gyhfkjgeM

However, when I go to the "Queues" part of the bashboard, I don't see any of these queues - I only see references to old queues that have been long-deleted:
https://www.screencast.com/t/dSUrjMOm

How do I get rid of these old queues and make sure the correct ones show up?

**Comment by odinserj** [comment]
That's because job identifiers aren't removed from queues instantly to avoid scanning through the entire queue. Just let your workers to finish those queues or delete those identifiers manually.
