### ISSUE TITLE
Dashboard error for Recurring Jobs [NullReferenceException: Object reference not set to an instance of an object.]

### ISSUE THREAD

**Issue by segios** [HangfireIO/Hangfire#1362]
When accessing recurring job page got NullReferenceException
Hangfire  Hangfire.SqlServer - v. 1.6.22, 

> [NullReferenceException: Object reference not set to an instance of an object.]    Hangfire.Dashboard.Pages.RecurringJobsPage.Execute() +3839    Hangfire.Dashboard.RazorPage.TransformText(String body) +26    Hangfire.Dashboard.RazorPage.ToString() +7    Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +64    Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +413    Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +274    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +182    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +180    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64    System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159
--

**Comment by odinserj** [comment]
Thanks for reporting this, @segios, I will look for possible reasons.
