### ISSUE TITLE
Run background job every {minute} starting from 10

### ISSUE THREAD

**Issue by NtFreX** [HangfireIO/Hangfire#1365]
I use the following cron expression to register a recurring job.
`10/1 * * * *` => `Every 1 minutes, starting at 10 minutes past the hour`

When I register the job at 15:00 the first run is at 15:10 as I would expect it. But the next execution is 16:10 and I would have expected 15:11.

I would have expected the job to run every minute from 15:10-15:59 and then every minute from 16:10-17:59 and so on.

---------------------

Is my expection wrong or does hangfire handle the cron expression wrong?

-----------------

When I use the following expression the task is executed as following.
`10/2 * * * *` => `Every 2 minutes, starting at 10 minutes past the hour`

Starting at 15:00. Runs at 15:10, 15:12, 15:14, 15:16 etc.
In my opinion this is correct.

--------------------

When I use the following cron expression it works as I expect it.
`10-59/1 * * * *`  => `Every 1 minutes, minutes 10 through 59 past the hour`

-----------------

I'm using v1.6.21

**Comment by burningice2866** [comment]
According to https://crontab.guru/#10/1_*_*_*_* the `10/1` part is non-standard so that's most likely why Hangfire doesn't behave as you expect it to.

**Comment by NtFreX** [comment]
@burningice2866 Thank you for your quick answer. Then I'll do as the standard says and use `10-59/1 * * * *`
