### ISSUE TITLE
Scheduled jobs always enqueue to default queue

### ISSUE THREAD

**Issue by kodithuwa** [HangfireIO/Hangfire#1366]
Hi,
I want to keep scheduled jobs in queues for implement multi-tenancy in my project.
but, always scheduled jobs enqueued to default queue. is it possible to assign scheduled jobs to other queues?

**Comment by pieceofsummer** [comment]
Queue name can be specified when creating a scheduled job. Use `AddOrUpdate` overload that accepts `queue` argument.

**Comment by odinserj** [comment]
Please see [this comment](https://github.com/HangfireIO/Hangfire/issues/1372#issuecomment-473330597) for possible workaround.

**Comment by kodithuwa** [comment]
Thanks, Anyway I implement IElectStateFilter and changed its queue.

**Comment by josephserrano15** [comment]
> Queue name can be specified when creating a scheduled job. Use `AddOrUpdate` overload that accepts `queue` argument.

I have try that, unfortunately it doesn't work.

`RecurringJob.AddOrUpdate(job.JobName,() => executeReport(job), job.Cron, queue: "default");`
