### ISSUE TITLE
Running hangfire from a virtual directory

### ISSUE THREAD

**Issue by TOMKT** [HangfireIO/Hangfire#1368]
Due to the fact that Dashboardroutes are configured on root (eg /js1245) hangfire tries to load css and js from the wrong location.
I have a webapp on / underneath I have another webapp wih hangfire on /AppX/ 
Due to the routing the css and js are not found because hangfire searches for them in / which in this case is a different application not containing hangfire. 
In my opinion hangfire should allow prefixes for its routing or set up routing not using / as a starting point

**Comment by TOMKT** [comment]
Due to the fact that Dashboardroutes are configured on root (eg /js1245) hangfire tries to load css and js from the wrong location.
I have a webapp on / underneath I have another webapp wih hangfire on /AppX/ 
Due to the routing the css and js are not found because hangfire searches for them in / which in this case is a different application not containing hangfire. 
In my opinion hangfire should allow prefixes for its routing or set up routing not using / as a starting point

**Comment by pieceofsummer** [comment]
You may override `PathBase` with a simple middleware. See #1110 or #1049 for details.

**Comment by TOMKT** [comment]
Nope unfortunately that doesnt work since requests are already diverted to the routing table of the upper app.

**Comment by pieceofsummer** [comment]
I think you've missed the point. `PathBase` is not only used for routing, but also for [building links](https://github.com/HangfireIO/Hangfire/blob/27ed4b2a629e9d7a57b54946483714c05d05077f/src/Hangfire.Core/Dashboard/UrlHelper.cs#L50) to js/css or other dashboard pages. So unless you set it correctly for the request, you'll get wrong hrefs in the response html.

**Comment by TheElectricCo** [comment]
Hi @pieceofsummer,

I'm also struggling with this. I have seen #1110 and #1049, but my doesn't change the links of js/css. the only prefix that seems to change is the prefix I enter with app.UseHangfireDashboard. 

I'm using Traefik as a reverse proxy. The header X-Forwarded-Prefix returns the correct prefix (being "/hangfire". 


` app.UseHangfireDashboard("/dashboard", new DashboardOptions()
            {
                Authorization = new [] { new AuthorizationFilter() },
                AppPath = "https://sarplan3.sarens.com"
            });`

`app.Use((context, next) =>
            {
                var pathBase = new PathString(context.Request.Headers["X-Forwarded-Prefix"]);
                if (pathBase != null)
                    context.Request.PathBase = new PathString(pathBase.Value);
                return next();
            });`

this results in "
`<link rel="stylesheet" href="/dashboard/css1623">`

where I would expect
`<link rel="stylesheet" href="/hangfire/dashboard/css1623">`

Could you please help me sorting out what I'm doing wrong? 
Thanks!

**Comment by TheElectricCo** [comment]
found it! You need to write app.use before app.useHangfireDashboard!

**Comment by TOMKT** [comment]
Works like a charm, thanks!!!
