### ISSUE TITLE
Realtime Graph and History Graphs are not rendering in 1.7.0-beta4

### ISSUE THREAD

**Issue by MovGP0** [HangfireIO/Hangfire#1369]
The Graph was working in 1.7.0-beta3; but is broken in 1.7.0-beta4

![image](https://user-images.githubusercontent.com/83339/54026567-93b10180-419e-11e9-9840-5ddc375b34eb.png)

**Comment by odinserj** [comment]
That’s strange, because there were no changes related to dashboard between beta3 and beta4. Do you see any errors in the console?

**Comment by MovGP0** [comment]
I reverted back to beta3 and it's working again. Might have a look at it next week when I'm back at work.

**Comment by MovGP0** [comment]
The fun thing is, that it works in the localhost/dev environment.

**Comment by MovGP0** [comment]
Console log is empty 

![image](https://user-images.githubusercontent.com/83339/54109360-be899880-43de-11e9-9c7e-bf0afb62082c.png)

**Comment by odinserj** [comment]
Hm, could you also check the Network tab? Looks like there's an issue likely related to antiforgery validation. Are you using ASP.NET Core?

**Comment by MovGP0** [comment]
@odinserj the network tab is in the first screenshot. the data is properly sent to the browser. 

yes, ASP.NET Core 2.2

**Comment by odinserj** [comment]
Hm, definitely it's on the first screenshot. I still don't understand what's the reason for this behavior and couldn't reproduce the error. May be there's a chance to get it by debugging at least the `hangfire.js` file that's not minified with the browser's development tools.

**Comment by MovGP0** [comment]
I think we can close this issue. It works in the final Hangfire 1.7.0 release 😊

**Comment by odinserj** [comment]
Hm, so let's change my last comment to *I've worked hard to fix the issue by analyzing network traffic, debugging in multiple browsers at the same time and eventually fix the problem by patching JavaScript VMs* 😂

Thanks for getting me know it's gone!
