### ISSUE TITLE
Dashboard Errors in Chrome and IE - Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by bcronje** [HangfireIO/Hangfire#137]
Using v1.0.0-alpha1 I get loads of `Cannot read property 'removeChild' of null` errors in Chrome and IE developer console. 

![image](https://cloud.githubusercontent.com/assets/462097/3332203/859446ba-f7e4-11e3-9433-07366877391b.png)

The JS in minified so it's a bit difficult to debug, but from what I can see it happens inside Rickshaw graph at the following line:

https://github.com/shutterstock/rickshaw/blob/c0a20cbfade400466ccb81007fe764a400c3d0a9/src/js/Rickshaw.Graph.Axis.Time.js#L56

Anyone else experiencing this?

**Comment by stajs** [comment]
Still happens on 1.5.2.

**Comment by stajs** [comment]
You could try and get the bug fixed upstream, but I see that you take a local dependency on Rickshaw here:

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/Content/js/rickshaw.min.js

In that case it's probably easier to null check the single usage of `removeChild()` in that file yourself.

**Comment by odinserj** [comment]
Fixed, will be shipped with 1.6.0.
