### ISSUE TITLE
Not possible to add custom IBackgroundJobPerformer or IBackgroundJobStateChanger anymore in 1.7.0

### ISSUE THREAD

**Issue by KorsG** [HangfireIO/Hangfire#1375]
Since v. 1.6.18 it has been possible to add a custom IBackgroundJobPerformer and IBackgroundJobStateChanger via DI like this example with ASP.NET Core "ConfigureServices":
```csharp
services.AddSingleton<Hangfire.States.IBackgroundJobStateChanger, CustomBackgroundJobStateChanger>();
services.AddSingleton<Hangfire.Server.IBackgroundJobPerformer, CustomBackgroundJobPerformer>();

services.AddHangfire(x =>
{
    // other options...
}
```

But since the release of v. 1.7.0-beta3 it does not work anymore, and have been removed by at least a couple of commits: https://github.com/HangfireIO/Hangfire/commit/0e797e43 and https://github.com/HangfireIO/Hangfire/commit/3000eef4.

Do you have plans to support this again in a future version?

**Comment by odinserj** [comment]
@KorsG, could you tell me more what implementation you are using and why? There's a problem with this feature as we are getting confusing behavior (and a breaking change in 1.6.18 for some users also), when specifying custom filter providers or an activator using `BackgroundJobServerOptions` – they simply aren't used.

I've heard developers are using custom performers or state changers only to specify custom filter provider, so I've decided to improve this scenario only. Please tell me more about your case and I'll think how to avoid problems.

**Comment by KorsG** [comment]
Thank you for the quick response @odinserj 👍 

**Use case 1 - log properties:**
I am using Serilog in combination with Seq (https://datalust.co/seq), which enables me to add Job properties to all logs written from Hangfire within a state changing scope or job performing scope, and then correlate/filter on this in Seq.
So by using the example custom BackgroundJobStateChanger below, I get the "JobId" added to all logs written by custom/built-in state changing filters like the AutomaticRetryAttribute, so that when filtering on a specific "JobId" in Seq, I also get the logs written by this filter which is very valuable.
```csharp
    /// <summary>
    /// Custom state changer which only purpose is to add log properties on execution.
    /// </summary>
    public class CustomHangfireBackgroundJobStateChanger : IBackgroundJobStateChanger
    {
        private readonly ILogger _log = Log.ForContext<CustomHangfireBackgroundJobStateChanger>();
        private readonly IBackgroundJobStateChanger _inner;

        public CustomHangfireBackgroundJobStateChanger([NotNull] IJobFilterProvider filterProvider)
        {
            // Default state changer.
            _inner = new BackgroundJobStateChanger(filterProvider);
        }

        public IState ChangeState(StateChangeContext context)
        {
            using (LogContext.PushProperty("JobId", context.BackgroundJobId))
            {
                return _inner.ChangeState(context);
            }
        }
    }
```
The same goes for the BackgroundJobPerformer.
The only workaround I can think of is making custom versions of the built-in filters and add the log properties in their methods... but that is something I would very much like to avoid 😉 


**Use case 2 - adding PerformContext to DI:**
I am injecting PerformContext into various jobs, so I made an "Accessor" similar to the "HttpContextAccessor" known from ASP.NET Core: 
```csharp
    public class HangfirePerformContextAccessor
    {
        private static AsyncLocal<(string jobId, PerformContext context)> _current = new AsyncLocal<(string jobId, PerformContext context)>();

        public static PerformContext Current
        {
            get
            {
                var (jobId, context) = _current.Value;
                // Only return the context if the stored jobId matches the stored jobId.
                return jobId == context?.BackgroundJob?.Id ? context : null;
            }
            set
            {
                _current.Value = (value?.BackgroundJob?.Id, value);
            }
        }
    }
```

which is assigned/de-assigned from a custom BackgroundJobPerformer:

```csharp
    /// <summary>
    /// Custom performer that adds functionality to the built-in performer.
    /// </summary>
    public class CustomHangfireBackgroundJobPerformer : IBackgroundJobPerformer
    {
        private readonly ILogger _log = Log.ForContext<CustomHangfireBackgroundJobPerformer>();
        private readonly IJobFilterProvider _filterProvider;
        private readonly JobActivator _activator;
        private readonly IBackgroundJobPerformer _inner;

        public CustomHangfireBackgroundJobPerformer([NotNull] IJobFilterProvider filterProvider, [NotNull] JobActivator activator)
        {
            _filterProvider = filterProvider;
            _activator = activator;
            // Built-in performer.
            _inner = new BackgroundJobPerformer(filterProvider, activator);
        }

        public object Perform(PerformContext context)
        {
            using (LogContext.PushProperty("JobId", context.BackgroundJob.Id))
            {
                try
                {
                    // Assigned
                    HangfirePerformContextAccessor.Current = context;
                    return _inner.Perform(context);
                }
                finally
                {
                    // De-assigned
                    HangfirePerformContextAccessor.Current = null;
                }
            }
        }
    }
```
and added to DI like this:

```csharp
    public void ConfigureServices(IServiceCollection services)
    {
            //...
            // Allows Hangfire PerformContext to be constructor injected to handlers.
            services.AddTransient(x => HangfirePerformContextAccessor.Current);
            //...
    }
```
The only workaround I can think of is using a server filter instead like this:

```csharp
    public class HangfireServerFilter : IServerFilter, IServerExceptionFilter
    {
        public void OnPerforming(PerformingContext context)
        {
            // Assign
            HangfirePerformContextAccessor.Current = context;
        }

        public void OnPerformed(PerformedContext context)
        {
            // De-assign
            HangfirePerformContextAccessor.Current = null;
        }

        public void OnServerException(ServerExceptionContext filterContext)
        {
            // De-assign
            HangfirePerformContextAccessor.Current = null;
        }      
    }
```

This seems to work okay, but not as "safe" as the try-finally block in the custom performer. 

Furthermore I am working on functionality to "parse" certain job types that implements certain interfaces and puts the parsed metadata into the PerformContext.Items dictionary for re-use throughout the pipeline - I could probably do this with filters also, but it is just so much easier/cleaner to do it this way (in my opinion), and resembles a middleware-like approach. 

What would be even better than the above, would be the possibility to make a custom/wrapped version of the Worker class (https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/Worker.cs) where I can do the same, but I don't think it is possible to replace the default worker as it is now, right?

Let me know if you need more information or if you have suggestions to workarounds 🙏

**Comment by odinserj** [comment]
Thanks for the detailed description. I've rolled back that change, but a bit partially. You are able to use this feature, but only when registering all the interfaces – `IBackgroundJobFactory`, `IBackgroundJobStateChanger` and `IBackgroundJobPerformer`. Only in this case configuration is straightforward. 

New changes are available in [RC2](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.0-rc2) that's just released.

**Comment by KorsG** [comment]
Thanks you very much @odinserj, it works as advertised - you rock! 👍
