### ISSUE TITLE
Trigger HTTP Controller method using Hangfire in ASPNETCORE

### ISSUE THREAD

**Issue by ethlyseria** [HangfireIO/Hangfire#1379]
Good day,

Is there a way to trigger HTTP using Hangfire?

Let's say I have sample Controller.
```
public class TestingController : Controller {
    ...
    public async Task<IActionResult> TriggerMe(){
       ...
    }
    ...
}
```

```
RecurringJob.AddOrUpdate(
                () => // how trigger the `TriggerMe()` controlller method? ),
                Cron.Minutely);
```

**Comment by pieceofsummer** [comment]
You should avoid doing that. 

The main reason is, Hangfire jobs are executed in background, so you don't have a valid HttpContext (and other web server features) available at that point, so you may run into unexpected errors.

If you need some functions to be called from both HTTP requests and from background jobs, you should consider moving them to a separate service (with no dependencies on MVC stack). Then you may inject It into your controller and call its methods from actions, and also use it in background jobs.

The other option is to actually perform a HTTP request to a localhost from your background job. That way it will have HttpContext available. But this would also create an unnecessary roundtrip to a server and increase resource consumption (at least one extra thread pool thread for handling that web request), so I don't actually recommend it.
