### ISSUE TITLE
System.NullReferenceException Error version 1.6.23

### ISSUE THREAD

**Issue by ethlyseria** [HangfireIO/Hangfire#1380]
Good day,

I'm having an error that says, `System.NullReferenceException` even there's a value in my method. My hangfire works fine lately and I was able to debug it but it doesn't work now. I don't know why. 

I already tried to downgrade, re-install the package but still it doesn't work. I also tried to trigger manually from dashboard but it doesn't work either.

I'm using ASP.NET Core 2.2 version

Please help

![hangfireerror01](https://user-images.githubusercontent.com/42052787/54983950-c48b9600-4fe8-11e9-86e5-3094b60bb55c.JPG)

**Comment by odinserj** [comment]
Could you show full stack trace for this exception, e.g. the whole screenshot?

**Comment by ethlyseria** [comment]
It's weird, I already changed my DB in hangfire startup.cs but when I view the dashboard, it still shows the db name and connection from old connection. maybe that's the reason I'm getting the System.NullReferenceException?

**Comment by odinserj** [comment]
Yes, you may have old instances running, and depending on your changes, it may cause your issue.
