### ISSUE TITLE
QueueAttribute is not work for BackgroundJob.Enqueue<T>

### ISSUE THREAD

**Issue by laozhuorun** [HangfireIO/Hangfire#1383]
![image](https://user-images.githubusercontent.com/5772553/55230172-f48da000-5259-11e9-8394-a8703f4c5fe3.png)

i use like：

 jobUniqueIdentifier = BackgroundJob.Enqueue<TJob>(job => job.Execute(args));

job is enqueue in “default” queue because ElectStateContext.CandidateState In ProcessingState， not EnqueuedState

**Comment by odinserj** [comment]
Please tell me what version of Hangfire you are using, what platform, e.g. .NET Framework or .NET Core, and how do you apply that filter (by using an attribute or via global filter collection)?

**Comment by laozhuorun** [comment]
> Please tell me what version of Hangfire you are using, what platform, e.g. .NET Framework or .NET Core, and how do you apply that filter (by using an attribute or via global filter collection)?

I use .NET Core 2.2，my hangfire.core version  is 1.6.22.0

**Comment by odinserj** [comment]
Can't reproduce the issue neither by applying an attribute, nor by adding a global filter. Looks like there's some trouble with your configuration. Could you post it here or create a repro as a GitHub repository?

**Comment by laozhuorun** [comment]
![image](https://user-images.githubusercontent.com/5772553/55668421-d6005800-589c-11e9-8167-bc1ecdd631f4.png)

![image](https://user-images.githubusercontent.com/5772553/55668416-c3861e80-589c-11e9-8038-e7e4baaf0bd4.png)

![image](https://user-images.githubusercontent.com/5772553/55668445-2081d480-589d-11e9-80bc-147053a4e917.png)
really thinks for you help，my application used [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate) ，you can test in this repro

**Comment by odinserj** [comment]
Does the `QueueAttribute` works correctly in this case? Looks like you are applying an attribute to `ClassB.Execute` method, while enqueueing `ClassA.Execute`.
