### ISSUE TITLE
Is it possible to limit what jobs are queued to an agent?

### ISSUE THREAD

**Issue by xumix** [HangfireIO/Hangfire#1391]
For example, I want some jobs to be executed only on some agents and not another.
It would be great to add some condition for a job like `[AgentEnvironmentCondition(VarExist=true, Name="Core_22")]` so a job with this condition is sent only to agents that have this Env var set.

**Comment by odinserj** [comment]
Use different [queues](https://docs.hangfire.io/en/latest/background-processing/configuring-queues.html) for this purpose by applying the `[Queue("your-queue")]` attributes on target method.

**Comment by xumix** [comment]
@thanks!
