### ISSUE TITLE
After upgrading to 1.7.0 Recurring Jobs stopped working

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#1392]
Was something changed in 1.7.0 about RecurringJobs? All my recurring jobs stoped working.
I cannot even trigger them in Hangfire Dashboard.

(Other Enqueue Jobs are working OK)

EDIT: We use MSSql Hangfire version

**Comment by odinserj** [comment]
Do you have any warning or error messages in [your log](https://docs.hangfire.io/en/latest/configuration/configuring-logging.html)? Could you show me the output of the following queries?

```sql
SELECT TOP (1000) * FROM [HangFire].[Set] WHERE [Key] = N'recurring-jobs'

-- And replace <some-recurring-job-id> with some actual recurring job id
SELECT TOP (1000) * FROM [HangFire].[Hash] WHERE [Key] = N'recurring-job:<some-recurring-job-id>'
```

**Comment by sabiland** [comment]
I’ll check on Monday!

**Comment by odinserj** [comment]
Ok, please also post here your configuration logic related to Hangfire and tell me what version did you use before the upgrade.

**Comment by sabiland** [comment]
Before upgrade I used version: <PackageReference Include="Hangfire" Version="1.6.23" />

I'll check SQL queries later this day.

**Comment by odinserj** [comment]
Could you also try to call the RecurringJob.Trigger, catch the exception with full stack trace and post it here?

**Comment by sabiland** [comment]
Damn I don't have rights to see HangFire tables.

I'll run RecurringJob.Trigger and catch the Exception...

**Comment by sabiland** [comment]
Hm I got the exception, CRON expression invalid?

"System.ArgumentException: CRON expression is invalid. Please see the inner exception for details.
Parameter name: cronExpression ---> Cronos.CronFormatException: Hours: Value must be a number between 1 and 23 (all inclusive)."

My current (which worked until now) CRON: "0 */24 * * *"

**Comment by sabiland** [comment]
I think I have solved the issues by tweaking CRON strings.

**Comment by odinserj** [comment]
Yes, that expression is simply equal to `0 0 * * *`. Is everything working now in your environment? I will do something in 1.7.1 to address this issue and visibility of errors related to recurring jobs.

**Comment by sabiland** [comment]
Yes everything is working ok now. I've re-run RecurringJobs and it works ok now!

**Comment by odinserj** [comment]
Oh great, thanks for reporting this! Need to add some compatibility flag for Cron expressions to not to throw exceptions in this case.

**Comment by sabiland** [comment]
@odinserj FYI, I've also noted after upgrading, that I cannot Enqueue jobs where methods-parametes "is to big" (say some huge string). I get this: "<VALUE IS TOO BIG>"

**Comment by odinserj** [comment]
@sabiland it's simply not displayed in dashboard, but those jobs are get enqueued. But anyway, that's a bad practice, and better to store those big arguments somewhere else.

**Comment by odinserj** [comment]
With today's changes, existing recurring jobs with invalid cron expressions will be gracefully handled and displayed in dashboard as failed with specific cron parsing error.
