### ISSUE TITLE
Cron.MinuteInterval(x) when x > 59 in Hangfire 1.7.0

### ISSUE THREAD

**Issue by jansokoly** [HangfireIO/Hangfire#1397]
After 1.7.0 made `Cron.MinuteInterval()` deprecated, I rewrote
`RecurringJob.AddOrUpdate<Foo>(p => p.Bar(), Cron.MinuteInterval(110));`
to
`RecurringJob.AddOrUpdate<Foo>(p => p.Bar(), "*/110 * * * *");`

But that results in:
> Cronos.CronFormatException: Minutes: Value must be a number between 1 and 59 (all inclusive).

The expression to run every 110 minutes validates [https://crontab.guru/#*/110_\*\_\*\_\*\_\*](https://crontab.guru/#*/110_*_*_*_*).
What's the correct way to run every x minutes where x > 59 in Hangfire 1.7.0?

**Comment by pieceofsummer** [comment]
If you carefully look at the crontab.guru’s next execution times, you may notice it actually shows execution every hour for any values larger than 60.

Also take a look at the description of `/` specifier at Wikipedia. It specifically says:
> Note that frequencies in general cannot be expressed; only step values which evenly divide their range express accurate frequencies (for minutes and seconds, that's /2, /3, /4, /5, /6, /10, /12, /15, /20 and /30 because 60 is evenly divisible by those numbers; for hours, that's /2, /3, /4, /6, /8 and /12); all other possible "steps" and all other fields yield inconsistent "short" periods at the end of the time-unit before it "resets" to the next minute, second, or day.

So you’ll need to do some tricks if you want an arbitrary interval between your jobs, maybe schedule the same job with multiple schedules.

**Comment by jansokoly** [comment]
Thanks @pieceofsummer.

**Comment by clockwiseq** [comment]
Why was this deprecated?
