### ISSUE TITLE
 Unable to find method:“System.String Newtonsoft.Json.JsonConvert.SerializeObject(System.Object, System.Type, Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonSerializerSettings)”

### ISSUE THREAD

**Issue by Cloud33** [HangfireIO/Hangfire#1400]
I'm using this code to encounter a problem like this.

string url="xxxx";
var paramData = JsonConvert.SerializeObject(tasks);
BackgroundJob.Enqueue(() => DoHttpPost(url, paramData));

The environment:
Hangfire  1.7.0
Newtonsoft.Json  12.0.1
targetFramework  net471

Background job creation failed. See inner exception for details. ---> System.MissingMethodException: Unable to find method:“System.String Newtonsoft.Json.JsonConvert.SerializeObject(System.Object, System.Type, Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonSerializerSettings)”。 在 Hangfire.Common.SerializationHelper.Serialize(Object value, Type type, SerializationOption option) 在 Hangfire.Client.CoreBackgroundJobFactory.<>c.b__4_1(KeyValuePair`2 x) 在 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) 在 Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context) 在 Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass9_0.b__0() 在 Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation) 在 Hangfire.Client.BackgroundJobFactory.Create(CreateContext context) 在 Hangfire.BackgroundJobClient.Create(Job job, IState state) 

I've tried a lot of versions of Newtonsoft.Json, but it doesn't work.
Please help me.

**Comment by Cloud33** [comment]
I'm trying to use it again in my own code call JsonConvert.SerializeObject(System.Object, System.Type, Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonSerializerSettings)

Type type = tasks.GetType();
var data = JsonConvert.SerializeObject(tasks, type, Newtonsoft.Json.Formatting.None, new JsonSerializerSettings { });

data There's data.
{xxxxxxx}

I don't know, in Hangfire, why can't it be used? Is it a question of the Newtonsoft.Json version, or is it a problem with my use?

**Comment by odinserj** [comment]
Could you create a repository on GitHub with a minimal project that reproduces this error? I've tried to create a test project with the following code, but don't get this exception.

```csharp
class Program
{
    static void Main(string[] args)
    {
        GlobalConfiguration.Configuration.UseMemoryStorage();

        string result = JsonConvert.SerializeObject("hi");
        BackgroundJob.Enqueue(() => Console.WriteLine("askjfh"));
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Hangfire.Core" version="1.7.0" targetFramework="net471" />
  <package id="Hangfire.MemoryStorage" version="1.6.0" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="12.0.1" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net47" />
</packages>
```

![image](https://user-images.githubusercontent.com/1078718/55960645-e38b5880-5c75-11e9-9b1d-10e006dcc72b.png)

**Comment by Cloud33** [comment]
Sorry, it cannot be copied because it is running in the process of another program and is normal under the console.

I called it manually before I started.
```
Type type = test.GetType();
 var data = Hangfire.Common.SerializationHelper.Serialize(test, type, Hangfire.Common.SerializationOption.Internal);

```
There will be the same error here, I do not know if this program has a loaded bottom version of the Newtonsoft.Json

Is there a way to enter the current version of Newtonsoft.Json?

**Comment by odinserj** [comment]
Looks like Newtonsoft.Json of version 4.5.X is loaded from GAC to resolve Hangfire.Core references, despite Hangfire references the version 5.0.1. This is because Newtonsoft.Json 5.0.1's `AssemblyVersion` was set to 4.5.0.0 to not to cause breaking changes due to strong signing that time. Ironically, it causes breaking changes now. 

And the thing is newest Hangfire version now uses methods that aren't available in 4.5.X. I don't know whether this is a bug or a feature, but Hangfire was never intended to use Newtonsoft.Json versions below 5.0.1, and was never tested against them.

So try adding binding redirects to your `app.config` or `Web.config` file, depending on the type of your application. They should be added automatically by NuGet client itself, but something went wrong in your case also with this step.

```xml
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
  <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
</dependentAssembly>
```

And here's the full picture of a sample Web.config file:

![image](https://user-images.githubusercontent.com/1078718/56022727-0456bb00-5d15-11e9-91c4-f232e92119d9.png)

**Comment by odinserj** [comment]
The only way to fix this in Hangfire itself is to bump Newtonsoft.Json dependency version to 6.0.1, but I can't do this before 2.0, because it will be a breaking change for others.

**Comment by Cloud33** [comment]
I found that the GAC Newtonsoft.Json version on the server is 4.5, the application is to take the GAC Newtonsoft.Json, I upgrade the GAC Newtonsoft.Json version, should be able to solve this problem, thank you very much
