### ISSUE TITLE
QueueAttribute is not work for BackgroundJob.Enqueue<T>

### ISSUE THREAD

**Issue by Skolley** [HangfireIO/Hangfire#1406]
.net core 2.2 , I am Use MySql
![image](https://user-images.githubusercontent.com/48314725/56353937-28c70180-6205-11e9-88e8-111e5ef8f0ce.png)

Code
![image](https://user-images.githubusercontent.com/48314725/56353985-472cfd00-6205-11e9-932f-75c68d940950.png)
Only useing Client 
Start Code 

![image](https://user-images.githubusercontent.com/48314725/56354113-8e1af280-6205-11e9-8855-af5feb1e4ffb.png)

**Comment by Skolley** [comment]
![image](https://user-images.githubusercontent.com/48314725/56354219-c5899f00-6205-11e9-96a2-291f65c06172.png)

**Comment by odinserj** [comment]
Place the `Queue("critical")` attribute on `ICheckProviderService.Check` method instead, otherwise Hangfire doesn't know about it.
