### ISSUE TITLE
Dashboard doesn't use custom ITimeZoneResolver

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#1407]
Should this view be updated to use ITimeZoneResolver also?

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml#L158

_Originally posted by @PaitoAnderson in https://github.com/HangfireIO/Hangfire/issues/1268#issuecomment-484514680_

**Comment by odinserj** [comment]
Thanks for reporting, @PaitoAnderson! Closed in `master` branch and fixed in version `1.7.1-build-02882`, available on CI feed – https://ci.appveyor.com/nuget/hangfire.

**Comment by PaitoAnderson** [comment]
@odinserj Thank you sir!
