### ISSUE TITLE
Thought about joining the .Net Foundation?

### ISSUE THREAD

**Issue by carlowahlstedt** [HangfireIO/Hangfire#1416]
Joining the [.Net Foundation](https://dotnetfoundation.org/projects), seems like it would be something that could really help support this project. [Here are the guidelines](https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md).

**Comment by odinserj** [comment]
Thanks Carlo, but I’m not interested in joining the foundation – it’s not a silver bullet anyway.
