### ISSUE TITLE
Background async tasks are not being waited on

### ISSUE THREAD

**Issue by EricStG** [HangfireIO/Hangfire#1418]
Hangfire.Core version: 1.7.2 (also tested in 1.6.23)
Storage package: Hangfire.PostgreSql 1.5.0

Using Hangfire in an asp.net core 2.2 app, background tasks are not being waited on.

They fire right await, but since there's no waiting, the scheduler shows them as succeeded, even if they are still going.

```cs
// Job ID: #16947
using x;

var orderProcessingJobs = Activate<IOrderProcessingJobs>();
orderProcessingJobs.ProcessOrderAsync(
    FromJson<Guid>("\"7e1b648b-9b7c-4197-9a3a-32154bdc449e\""),
    CancellationToken.None);
```

**Comment by candidodmv** [comment]
I'm with the same problem here. The enqueued methods not are respecting the logic queue, it's appering  that they are running in parallel, and then throw execption because the logic implemented must wait one processing to finish before another to be started

**Comment by odinserj** [comment]
@EricStG please show me the signature of your async methods or better full source code of such a method.

@candidodmv all enqueued background jobs will be processed concurrently, unless you specify dependencies explicitly by using continuations or batches.

**Comment by candidodmv** [comment]
Hi @odinserj , thanks for repaly. my issue was solved magically with the DisableConcurrentExecution attribute \o/ . Let me know if my reasoning about timeout parameter of this attribute is it right:
The timeoutInSeconds parameter is referring how much time the background job executor must wait until try execute again?

```
[DisableConcurrentExecution(timeoutInSeconds: 10 * 60)]
public void SomeMethod()
{
    // Operations performed inside a distributed lock
}
```

**Comment by EricStG** [comment]
@odinserj I have a repro at https://github.com/EricStG/potential-bassoon

Digging a bit into this, it seems to happen when I use an interface instead of a concrete class.

Ex:
This generates the issue
```
RecurringJob.AddOrUpdate<ISleepMe>("Sleep", e => e.WaitAsync(CancellationToken.None), Cron.Minutely());

// From the Hangfire dashboard:
using HangfireNotWaiting.Tasks;

var sleepMe = Activate<ISleepMe>();
sleepMe.WaitAsync(CancellationToken.None);
```
but this does not:
```
RecurringJob.AddOrUpdate<SleepMe>("Sleep", e => e.WaitAsync(CancellationToken.None), Cron.Minutely());

// From the Hangfire dashboard:
using HangfireNotWaiting.Tasks;

var sleepMe = Activate<SleepMe>();
await sleepMe.WaitAsync(CancellationToken.None);
```

**Comment by odinserj** [comment]
@EricStG ah now I see, thanks a lot for details. Actually the job is awaited in Hangfire Server itself, and the problem appears only when dashboard tries to display it. I've modified sleep time to 1 minute and ran the project you've referenced:

![image](https://user-images.githubusercontent.com/1078718/58719347-14ffe500-83d8-11e9-95f1-fa35ba55ad9c.png)

So it's a bug, yes, but minor and relates only to Dashboard UI. And to not to confuse anyone it will be fixed in 1.7.4.

**Comment by odinserj** [comment]
@candidodmv what storage are you using?

**Comment by candidodmv** [comment]
@odinserj I'm using SqlServer Storage
