### ISSUE TITLE
Skip next planned execution when the job got manually triggered

### ISSUE THREAD

**Issue by Flydancer** [HangfireIO/Hangfire#1428]
Hi,

I'm trying to find a way to skip the next planned execution when the job got manually triggered before.
Background is:
I'm sending Reports to clients monthly, weekly etc. but sometimes they want them before the planned execution is getting triggered. I know there is a "Trigger now" Button in the UI but that means it will also execute the Job when it was supposed to be before manually triggering it, which means the clients will receive the reports twice.

I'm pretty new to hangfire and couldn't find something to solve this scenario.

Thanks in advance.

**Comment by burningice2866** [comment]
You should keep track of which reports you have sent to clients, so when a job runs multiple times within the same month you won't send any report for successive runs if a report have already been generated for that month.

**Comment by Flydancer** [comment]
Hi burningice2866,
thanks for your response. Yes, that would be the manual option. So there is no way to modify the "next execution time"?

**Comment by burningice2866** [comment]
It sounds to me that you're mixing concerns and want to put more logic into Hangfire than its meant for.

A task scheduler just execute jobs, it can be by manual trigger, by delay or at a specified recurring time. It should never be the task schedulers jobs to keep track on what logic the job consist of and what the rules are for multiple runs. A job should optimally always be designed in a way so it won't affect your business logic whether it runs once a month, once a day or every minute.

We say that scheduled jobs should be **_idempotent_**. That is the result needs to be the same no matter how many times you call it.

So if your business logic states, that a customer should get a monthly report, only one, never multiple reports within the same month, and the report can be sent at any time within a month, then you need to implement that logic in your business logic and not rely on Hangfire never executing that method more than once each month.

What if you accidentally trigger the method manually twice in a month, how do you then protect against the customer receiving multiple reports?

You need to implement a tracker for when which reports have been sent to what customers, and in your job-generating-code you check whether the report you're about to generate already has been generated or not before continuing.

**Comment by Flydancer** [comment]
Hi burningice2866,
you're right. I'm trying to build a replacement for the current Report Server and probably got stuck in the SSRS-way of thinking. Thanks for the explanation, I'll rebuild my approach
