### ISSUE TITLE
Generate Pdfs using wkhtmltopdf.exe in operation

### ISSUE THREAD

**Issue by sameerAhmad9291** [HangfireIO/Hangfire#1430]
We have a background operation that needs to run inorder to generate PDFs on file system. 'wkhtmltopdf.exe' is used from https://github.com/codaxy/wkhtmltopdf

When we run that operation from NUnit test case it runs fine.

When we wrap this operation in HangFire and deploy it on IIS - its a MVC application - after generating 1 - 2 PDFs, the application pool crashes, error popup is shown in windows and below log is seen in the event viewer.

Application: w3wp.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon) at Hangfire.Processing.BackgroundDispatcher.DispatchLoop() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart() An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/3/ROOT Process ID: 14880 Exception: System.InvalidOperationException

Message: An attempt was made to transition a task to a final state when it had already completed. StackTrace: at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result) at Hangfire.Processing.BackgroundDispatcher.DispatchLoop() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart()

**Comment by sameerAhmad9291** [comment]
I solved issue by adding HangFire.ASP.NET missing library in project references.

**Comment by odinserj** [comment]
The `InvalidOperationException` mentioned above will not be thrown anymore, and will not hide the original exception. Thank you for reporting this!
