### ISSUE TITLE
Descriptive names for background jobs in dashboard

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#144]
@dsincl12 [proposed a feature](http://discuss.hangfire.io/t/text-name-for-background-jobs/65) to improve the HangFire Dashboard experience with a textual descriptions for background jobs:

![Names](http://i.imgur.com/fOVxOpO.jpg)

This feature can be implemented in a very easy way – the `HtmlHelper.DisplayJob` method can look for a `System.ComponentModel.DisplayNameAttribute` that is applied to a job and return the formatted value. The usage is very simple:

``` csharp
[DisplayName("Send order #{0} to warehouse")]
public void CopyOrderToLevel4(int orderId)
{
    // Processing
}
```

The display name string can use positional arguments, and their values can be automatically substituted with real job arguments:

``` csharp
String.Format(attribute.DisplayName, job.Arguments);
```

**Comment by dikoga** [comment]
I would like to leave something documented here.

If you are using an interface to decouple server and dashboard, this attribute should be added to the interface instead. The reason as far as I can see is because the dashboard knows only the interface.

**Comment by jwgiblin3** [comment]
I added the DisplayName and I still see the job displayed as the original, ScanEngine,RunScan instead of Scan Path \\ddddd\ddd

Am I missing something?

Public class ScanEngine
    {

        [DisplayName("Scan Path {0}")]
        public void RunScan(string path, int pathId)

**Comment by andorremus** [comment]
> I added the DisplayName and I still see the job displayed as the original, ScanEngine,RunScan instead of Scan Path \ddddd\ddd
> 
> Am I missing something?
> 
> ```
> Public class ScanEngine
>     {
> 
>         [DisplayName("Scan Path {0}")]
>         public void RunScan(string path, int pathId)
> ```

Make sure that the display name is set on the method signature that is getting called by the hangfire job server. That was my issue, I had an abstraction on the job scheduling part and I was setting the name on them, after I did it on the actual interface being run by hangfire everything worked great.
