### ISSUE TITLE
Recurring job execution is duplicated

### ISSUE THREAD

**Issue by StuFrankish** [HangfireIO/Hangfire#1440]
I've got a single task that executes a separate schedule, created in my startup.cs as:
`RecurringJob.AddOrUpdate("ExecuteJobSchedule", () => serviceProvider.GetService<IJobServices>().ExecuteSchedule(), "*/5 4-23 * * *");`

This appears only once in the Recurring Jobs tab:
![image](https://user-images.githubusercontent.com/5624629/58088279-3253d880-7bba-11e9-80a7-0b96e6ff9530.png)

But when Hangfire is running, it's duplicating the execution:
![image](https://user-images.githubusercontent.com/5624629/58088075-d1c49b80-7bb9-11e9-8021-6240d56e2f2f.png)

**Comment by odinserj** [comment]
@Saldash what storage are you using, and what are the versions of all the Hangfire-related packages?

**Comment by actionthomas** [comment]
Hello
I have the same problem; some recurring tasks are created multiple times at once (~twice per task).
I'm using SQL Server as the storage backend, and I'm using hangfire 1.7.31 in a .net 4.8 app.
