### ISSUE TITLE
Allow Hangfire.AspNet to set BackgroundJobServerOptions

### ISSUE THREAD

**Issue by SzabKel** [HangfireIO/Hangfire#1444]
I am using Hangfire with an Owin startup class and running it in IIS 10. At first, my startup class was almost the same [as the example here](https://github.com/HangfireIO/Hangfire.Highlighter/blob/master/Hangfire.Highlighter/Startup.cs). Later, I had to add different Queues to allow prioritization of certain jobs. I followed [this article](https://docs.hangfire.io/en/latest/background-processing/configuring-queues.html). And I realized calling `app.UseHangfireServer()` starts another Hangfire server, so I had two instead of one. I can't find any way to set the `BackgroundJobServerOptions` along with `app.UseHangfireAspNet()`, so I decided to just use `app.UseHangfireDashboard()`, but looks like it was supposed to solve the [app pool recycling issue](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html), also, If I just follow the article, the app pool recycling still stops the hangfire server and the Autofac integration is not working.

Would it be possible to set server options along with the `Hangfire.AspNet` package?

**Comment by odinserj** [comment]
Could you show your configuration logic?

**Comment by SzabKel** [comment]
> 
> 
> Could you show your configuration logic?

You mean the app start? Almost the same as the example I linked.

```c#
using Autofac;
using Hangfire;
using Hangfire.Dashboard;
using Hangfire.SqlServer;
using Microsoft.Owin;
using Owin;

[assembly: OwinStartup(typeof(ForkliftWatcher.Web.Startup))]

public class Startup {

	private static IContainer _container; // The Autofac container
	
	private IEnumerable<IDisposable> GetHangfireServers()
	{
		GlobalConfiguration.Configuration
			.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
			.UseSimpleAssemblyNameTypeSerializer()
			.UseRecommendedSerializerSettings()
			.UseSqlServerStorage(@"...DbContext", new SqlServerStorageOptions
			{
				CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
				SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
				QueuePollInterval = TimeSpan.Zero,
				UseRecommendedIsolationLevel = true,
				UsePageLocksOnDequeue = true,
				DisableGlobalLocks = true
			});

		yield return new BackgroundJobServer();
	}
	
	 public void Configuration(IAppBuilder app) {
		_container = ;// ... builds autofac container
		// also, the autofac builder calls UseAutofacActivator
		// with Hangfire.GlobalConfiguration.Configuration.UseAutofacActivator(savedContainer);
		
		app.UseHangfireAspNet(GetHangfireServers); // can't set background job server options
	 
		// https://discuss.hangfire.io/t/multiple-queue-priority-order-is-not-working/784/5
		// Workers fetch by alphabetical order!
		// Commented out, coz I don't want to start two servers
		/* app.UseHangfireServer(new BackgroundJobServerOptions
		 {
			 Queues = new[] { "aaa_pagination_queue", "default" },

		 });*/
		 
		app.UseHangfireDashboard("/hangfire", new DashboardOptions
		{
			Authorization = new[] { new AllowAllAuthorizationFilter() }
		});

		Init();

		app.Run(async context =>
		{
			await context.Response.WriteAsync("App");
		});
	 }
	 
	private static void Init()
	{
		_container.Resolve<LoggerInitializer>().Init();

		var recurringJobInitializer = _container.Resolve<RecurringJobInitializer>();
		recurringJobInitializer.AddOrUpdate();
	}
}
```

**Comment by SzabKel** [comment]
Okay, I just realized I can pass the `` into the `BackgroundJobServer`'s ctor directly, my bad. 

```c#
yield return new BackgroundJobServer(new BackgroundJobServerOptions
{
	Queues = new[] { "aaa_pagination_queue", "default" },

});
```

The application pool recycling is still a problem though, but a different issue I guess.

**Comment by odinserj** [comment]
So try to change the following line

```csharp
yield return new BackgroundJobServer();
```

to

```csharp
yield return new BackgroundJobServer(new BackgroundJobServerOptions
{
    // ...
});
```
