### ISSUE TITLE
Can not change the state to 'Processing': target method was not found

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#1445]
I see a lot of those messages in Hangfire Retries tab.
`Can not change the state to 'Processing': target method was not found`

We run 2-identical Web Applications on 2 servers (ASP Net Core) and use MSSQL for Hangfire storage.
I think that the enqueued job is even correctly finished, but anyways the message "target method was not found" appears in Hangfire dashboard.

**Comment by rsilvanet** [comment]
Hi @sabiland,

[Here](https://github.com/HangfireIO/Hangfire/blob/23d81f5ca61c3238d7da3591fd2f5d386dd0532e/src/Hangfire.Core/States/BackgroundJobStateChanger.cs#L77) are described some reasons for this error message. In my experience with hangfire, it really happened sometimes when we changed methods declaration, so Hangfire couldn't proceed with already enqueued jobs that were serialized with the old declaration. Does that make sense for your case?

Hope it's helpful 😄

**Comment by sabiland** [comment]
@rsilvanet I will check your link.

@rsilvanet I most surely do not change method signature, because it is unchanged for more than a year now.

Could maybe changes (new lines) in the same .cs file and then building/publishing have any effect on this "target method was not found" ?

**Comment by sabiland** [comment]
I have found out the reason. OMG, it was my fault. I once (long time ago) integrated Hangfire with same DB (& default queue) into one of our other API's, and of course that is why those messages were appearing in Hangfire dashboard.
