### ISSUE TITLE
How to add New Recurring Job after Deployment

### ISSUE THREAD

**Issue by meygnanamp** [HangfireIO/Hangfire#1446]
Dear All,

Good day

I have a Recurring Job in HangFire. I deployed that in Production Server. I need to add another Recurring Job in HangFire. How do I add another Job without deleting the existing HangFire Job?

Example Code:

if (dtEntity.Rows.Count > 0)
                {
                    int i = 0;
                    foreach (var item in dtEntity.Rows)
                    {
                        RecurringJob.AddOrUpdate(dtEntity.Rows[i]["Entity"].ToString(),() => homeController.DocumentUploadFromEmail(dtEntity.Rows[i]["APIURL"].ToString(), dtEntity.Rows[i]["APIMethod"].ToString()), dtEntity.Rows[i]["Cron"].ToString());
                        i++;
                    }
                    
                }

Regards,
Meygnanam. P

**Comment by rsilvanet** [comment]
Hi @meygnanamp,

Once you give a new id to the RecurringJob.AddOrUpdate(), a new recurring job will be created as well. Using the same id will make the existent recurring job to be overwritten.

It's better explained here: https://docs.hangfire.io/en/latest/background-methods/performing-recurrent-tasks.html

Hope it's helpful 😄

**Comment by meygnanamp** [comment]
Hi Rsilvanet,
Yes, got it. Thank you so much...

Regards,
Meygnanam.P
