### ISSUE TITLE
Unit testing BatchJob

### ISSUE THREAD

**Issue by panupetteri** [HangfireIO/Hangfire#1449]
HangFire provides `IBackgroundJobClient` interface to support unit testing, see https://docs.hangfire.io/en/latest/background-methods/writing-unit-tests.html. That works well, as `IBackgroundJobClient` is registered to `IServiceCollection` (IoC container) making it easy to provide mock implementation. The registration code is in `HangfireServiceCollectionExtensions.AddHangfire()` method.

However, there is not a mention on how to unit test `BatchJob` (https://www.hangfire.io/pro/). Looking the source code there is `IBatchJobClient` interface that could be used in unit testing, but instance of `IBatchJobClient` is not registered to IoC container.

How to unit test `BatchJob`?

**Comment by odinserj** [comment]
There's the `BatchJobClient` class that implements the `IBatchJobClient` interface. You can inject your own `JobStorage`, `IBatchFactory` and `IBackgroundJobFactory` mocks in the following way (uses Moq).

```csharp
GlobalConfiguration.Configuration.UseBatches();

// Arrange
var storage = new Mock<JobStorage>();
var connection = new Mock<JobStorageConnection>();
var transaction = new Mock<JobStorageTransaction>();
var batchFactory = new Mock<IBatchFactory>();
var jobFactory = new Mock<IBackgroundJobFactory>();

storage.Setup(x => x.GetConnection()).Returns(connection.Object);
connection.Setup(x => x.CreateWriteTransaction()).Returns(transaction.Object);

jobFactory
    .Setup(x => x.Create(It.IsNotNull<CreateContext>()))
    .Returns((CreateContext ctx) => new BackgroundJob("some-id", ctx.Job, DateTime.UtcNow));

// Act
var client = new BatchJobClient(storage.Object, batchFactory.Object, jobFactory.Object);
client.StartNew(x => x.Enqueue(() => Console.WriteLine()));

// Assert
batchFactory.Verify(x => x.Create(It.Is<BatchCreateContext>(ctx =>
    ctx.InitialState.Name == "Started" &&
    ctx.BatchedJobs.Count == 1)));
```

**Comment by shlonny** [comment]
What about unit testing BatchJob.Attach?
