### ISSUE TITLE
am i do something wrong in Startup.Configure

### ISSUE THREAD

**Issue by LC95** [HangfireIO/Hangfire#1450]
IN .NET CORE 2.2
i didn't configure UseHangfireServer() in Startup.cs `s Configure Section
but I find heartbeat in the database 
i wonder whether the heartbeat is always run no matter what i wrote in configure
if i register some RecurringJobs  and they are writed into database. 
Even if I don't configure to start Hangfire Server, the jobs still will run. is this normal ?

**Comment by walizada** [comment]
Yes, based on my analysis the heartbeat check is always run. Based of how the IHostedService is used now to run Hangfire, you don't directly have access to the BackgroundJobServerOptions as before (via UseHangfireServer).

Here's how you can set the options:

`

           BackgroundJobServerOptions hangfireOptions = new BackgroundJobServerOptions()
            {
                SchedulePollingInterval = TimeSpan.FromMinutes(5),
                ServerCheckInterval = TimeSpan.FromMinutes(10),
                HeartbeatInterval = TimeSpan.FromMinutes(10)
            };

            services.AddSingleton<BackgroundJobServerOptions>(hangfireOptions);
         
            // Add the processing server as IHostedService
            services.AddHangfireServer();
`
AddHangireServer will check DI for the options and use it.

**Comment by LC95** [comment]
Thank you very much!
