### ISSUE TITLE
Add support for DB SSL certificate

### ISSUE THREAD

**Issue by lansman** [HangfireIO/Hangfire#1461]
I've added Hangfire 1.7.3 to ASP.NET Core app. My database (postgres) has self-signed ceritificate so i had to write some custom ceritficate check logic (**ProvideClientCertificatesCallback**, **RemoteCertificateValidationCallback** methods). I use these methods to configure Entity Framework's DbContext, i need to pass these methods to Hangfire DB configuring as well. Isn't this possible right now? Could you add such feature and provide me access to the underlying NpgsqlDbContextOptionsBuilder or similar?

```
public void ConfigureServices(IServiceCollection services)
{    
    string connectionString = "CONNECTION_STRING";
    
    services.AddDbContextPool<MyDbContext>((provider, dop) =>
    {
        dop.UseNpgsql(connectionString,
            noa =>
            {
                noa.ProvideClientCertificatesCallback(dbOptionsReader.AddSslCertificate);
                noa.RemoteCertificateValidationCallback(dbOptionsReader.VerifySslManually);                
            });
    });

    services.AddHangfire((provider, config) =>
    {
        config.UsePostgreSqlStorage(connectionString);

        // how to set ProvideClientCertificatesCallback and RemoteCertificateValidationCallback ??
    });
}
```

**Comment by burningice2866** [comment]
@lansman i suggest adding an issue here since its a 3rd party package https://github.com/frankhommers/Hangfire.PostgreSql/issues

**Comment by lansman** [comment]
@burningice2866 ty for advice, created https://github.com/frankhommers/Hangfire.PostgreSql/issues/116
