### ISSUE TITLE
Hangfire unable to insert into its own JobQueue table

### ISSUE THREAD

**Issue by molson504x** [HangfireIO/Hangfire#1464]
I'm working in a system with 42 instances of hangfire running (8 workers per instance), backed by SQL Server.  We are also running without `SlidingInvisibilityTimeout` enabled.  Occasionally, I've noticed that when we have a large number of long-running processes running Hangfire seems to be unable to insert into the JobQueue table due to having too many transactions open on the database.  Hangfire is NOT hosted in its own database server (there are 6 other databases on this server, one of which is very heavily utilized).  The solution is to always shut down the hangfire instances, wait a moment for SQL to stabilize, and slowly bring the instances back online a couple at a time.

We are running 1.7.2 currently, in case that helps.

What we see in hangfire is hangfire workers time out when attempting to insert into the JobQueue table, pull information from the JobQueue table, etc.  We don't see any network outages during these times, CPU utilizations are below 30%, memory utilization is below 50%, suspension rate is below 50% (nothing's able to run, so no surprise there)...  When we do get it back to being stable, SQL reports running over 10,000 batch requests per second, but when it is in a failed state we see in the activity monitor that there's a lot of things deadlocked on the hangfire database (presumably the JobQueue table) and batch requests are under 5000 per second.  The longest-running transaction has a "last query" of `SELECT (1)`, which based on the source code is a keep-alive for the transaction.

SQL Server is using the default value for connection timeout (15s) and command timeout (30s).

This problem began happening shortly after we updated to 1.7.2 from 1.6.19.

Any ideas of what we should do to improve the performance of this or prevent this from happening again?

Thanks!

**Comment by odinserj** [comment]
Please try to upgrade to the latest version [1.7.4](https://github.com/HangfireIO/Hangfire/releases). Looks like you have long-running jobs, since `SELECT (1)` query is executed, and there were sub-optimal queries for prolonging a message lease in prior versions that cause `SCAN` operations instead of `SEEK` ones, affecting too many rows and acquiring too many locks. Here's a short excerpt from release notes:

> * Fixed – Potential deadlocks cause by suboptimal queries when using `SlidingInvisibilityTimeout` fetching.
> * Fixed – Prevent zero delays between fetch retry attempts when lock acquisition failed without blocking.

Please let me know if the problem persists.
