### ISSUE TITLE
.Net Core service fails to start listen on the port

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [HangfireIO/Hangfire#1465]
I was using hangfire in my .net core service for processing long-running tasks.
It was working great so far till I found this issue on the server this morning.  The service stopped working and restarting the app pool or even the windows server didn't resolve the issue.
It was throwing 504 gateway timeout error and when I check the log events, I could see that the service failed to start listening on the port for some reason.
I tried to troubleshoot the issue and finally figured it out by removing all records from the hangfire DB tables.
I am not sure how it could happen - Do I need to clean DB periodically before it gets too large?

Any input on this would be appreciated!

**Comment by odinserj** [comment]
>  I could see that the service failed to start listening on the port for some reason

You need to realize that reason and fix it – perhaps there's another instance of the application running. Regarding the cleanup, Hangfire automatically expires Succeeded and Deleted (but not Failed) background jobs in 24 hours that can be configured as written here – https://discuss.hangfire.io/t/how-to-configure-the-retention-time-of-job/34/2?u=odinserj
