### ISSUE TITLE
BackgroundJob not completing on server 

### ISSUE THREAD

**Issue by viral-etymon** [HangfireIO/Hangfire#1467]
I am using BackgroundJob to enqueue some process on demand. Using UseSqlServerStorage.

Application pool is configure to recycle on memory usage.
![image](https://user-images.githubusercontent.com/23634389/61528804-58241f00-aa3d-11e9-9f3e-b51e8921dab3.png)

And job go endless processing and creating after every minutes and job is not being completed.
![image](https://user-images.githubusercontent.com/23634389/61528915-9de0e780-aa3d-11e9-887a-706907033299.png)

It is also creating multiple severs under Servers.
![image](https://user-images.githubusercontent.com/23634389/61529122-38d9c180-aa3e-11e9-8849-23c49b7b6a65.png)

If remove memory based maximums configuration from application pool then everything is running smoothly.

Please help.

**Comment by odinserj** [comment]
I see that each execution is performed in a different process. Any chance that background job itself does consume too much memory and causing IIS to restart the process?
