### ISSUE TITLE
Error reporting with SQL Server 2008 R2 on 1.7.5

### ISSUE THREAD

**Issue by webgj** [HangfireIO/Hangfire#1468]
CREATE INDEX failed because of incorrect set:'ARITHABORT'.

Is there any other method to solve this question except  change the setting(ALTER DATABASE dbname SET ARITHABORT ON)?

Thanks

**Comment by odinserj** [comment]
Hangfire doesn't use the ARITHABORT option. Could you trace error to the concrete CREATE INDEX query and tell about it more?
