### ISSUE TITLE
Jobs setup with ContinueJobWith are not running

### ISSUE THREAD

**Issue by rtaylor72** [HangfireIO/Hangfire#1473]
I am trying out your product to see if it will meet my needs.  I have a job created that has 5 chained jobs using the ContinueJobWith.  The initial job is started and completed with "Succeeded" status, but the next job never triggers and is in "Awaiting" status.

4946971: {"SucceededAt":"1563987122673","PerformanceDuration":"30295","Latency":"31377"}
4946976: {"ParentId":"4946971","NextState":"{\"$type\":\"Hangfire.States.EnqueuedState, Hangfire.Core\",\"Queue\":\"default\"}","Options":"1"}

If I cannot get this solved soon, I will have to find something else.

Thanks!

**Comment by rtaylor72** [comment]
Version 1.7.4, using Hangfire.FluentNHibernateStorage 1.1.2392 to support Oracle DB.

**Comment by odinserj** [comment]
Does the code work with Hangfire.SqlServer storage? Perhaps that's a problem of FluentNHibernateStorage storage.

**Comment by rtaylor72** [comment]
Unfortunately, the client only has Oracle. For the time being, I have the job add to the queue at the end of its run to do the chaining.  Was not sure if there was something in the log file to look for internal events not firing.  We do see a heatbeat like stuff in the log file, so we know the process is still running.

**Comment by rtaylor72** [comment]
Because of the lack of support for Hangfire.FluentNHibernateStorage, we unfortunately will have to use something else.  Thanks!
