### ISSUE TITLE
net461 TargetFramework for Hangfire.AspNetCore

### ISSUE THREAD

**Issue by danstur** [HangfireIO/Hangfire#1487]
Would it be possible to add net461 as a target framework for the Hangfire.AspNetCore csproj? The problem is that people using .NET 4.6.1 or higher get the Net451 nuget which excludes many useful helper functions such as `AddHangfireServer`, since these are hidden behind a `#IF NETSTANDARD2_0` check. 

.NET 4.6.1 and higher implement NetStandard 2.0, so the same code could be used. Adding net461 to the TargetFrameworks for the project and expanding the #IF (preferably via an additional property?) checks would allow people to use all this functionality. 

Currently we're simply copy-pasting the parts we need into our own project, but clearly this is a suboptimal solution. I'd be happy to provide a PR that handles this.

**Comment by odinserj** [comment]
Sure, will be happy to accept that PR! One side effect here is that project that target .NET 4.6.1 and still sitting on ASP.NET Core 1.X will be unable to use the newer version. However I don't see any reason to still use those early versions – there were too many bugs and non-implemented features.

**Comment by danstur** [comment]
@odinserj I guess with the right app.config redirections they could get it to work, but yeah I doubt there's much interest in that configuration in any case. I'll try to get the PR done ASAP - looks pretty simple on first glance :-)
