### ISSUE TITLE
ServicePrincipal AccessToken based authentication

### ISSUE THREAD

**Issue by tauqirghani** [HangfireIO/Hangfire#1490]
Hi. What will it take to implement ServicePrincipal based authentication for SQL server. It needs an AccessToken to be added to the connection object. If there was a method to pass the AccessToken in like 
`UseSqlServerStorage(ConnectionString, AccessToken)`
then the CreateConnection class could just add it to connection before returning the connection object.

**Comment by odinserj** [comment]
Hi, it's possible to pass a connection factory when creating SqlServerStorage instances, please see: https://github.com/HangfireIO/Hangfire/blob/70502ebf375ffb875efedce41b0507b32656c258/src/Hangfire.SqlServer/SqlServerStorage.cs#L117

This parameter may not be added to the `UseSqlServerStorage` extension methods, so likely you'll need to call `UseJobStorage(new SqlServerStorage(/* ... */))` instead. But I will be happy to accept a PR to add `Func<DbConnectopn>`-based overload for `UseSqlServerStorage` method.

**Comment by tauqirghani** [comment]
I will look at both alternatives and get back soon.

**Comment by tauqirghani** [comment]
Hi Sergie, first thanks a lot for your guidance.
I am seeing something not quite in-line with my expectations from above.
1. IGlobalConfiguration does not expose UseJobStorage()
am I missing something?
and UseSqlServerStorage presents these constructors 


```
namespace Hangfire
{
    public static class SqlServerStorageExtensions
    {
        public static IGlobalConfiguration<SqlServerStorage> UseSqlServerStorage([NotNull] this IGlobalConfiguration configuration, [NotNull] string nameOrConnectionString);
        public static IGlobalConfiguration<SqlServerStorage> UseSqlServerStorage([NotNull] this IGlobalConfiguration configuration, [NotNull] string nameOrConnectionString, [NotNull] SqlServerStorageOptions options);
        public static IGlobalConfiguration<SqlServerStorage> UseSqlServerStorage([NotNull] this IGlobalConfiguration configuration, [NotNull] Func<DbConnection> connectionFactory, [NotNull] SqlServerStorageOptions options);
    }
}
```

Can you comment on these observations

**Comment by EvgeniyZ** [comment]
@tauqirghani as far as I can see, you can use SqlServerStorageExtensions.UseSqlServerStorage(
            [NotNull] this IGlobalConfiguration configuration,
            [NotNull] Func<DbConnection> connectionFactory,
            [NotNull] SqlServerStorageOptions options)
and pass SqlConnection with AccessToken as Func<DbConnection>

**Comment by tauqirghani** [comment]
yes, it sure does and works fine too.

**Comment by manojkgarg2019** [comment]
I am using application context like this

` public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
            var conn = (SqlConnection)this.Database.GetDbConnection();
            conn.AccessToken = new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/").Result;
        }`


How i will be using  
`SqlServerStorageExtensions.UseSqlServerStorage(
            [NotNull] this IGlobalConfiguration configuration,
            [NotNull] Func<DbConnection> connectionFactory,
            [NotNull] SqlServerStorageOptions options)`
