### ISSUE TITLE
ASP.NET Core RecurringJob wrong timing

### ISSUE THREAD

**Issue by Hulkstance** [HangfireIO/Hangfire#1492]
I think that there is a bug in `RecurringJob` which leads to a wrong timing (time drift).

In the code below, `RecurringJobManager` is supposed to execute `DoWork` method on each hour, e.g. 09:00 pm, 10:00 pm, 11:00 pm and so on. What really happens is that it never really executes it at 10:00:00 (precisely) but it adds a few additional seconds to the actual time. I'm observing that anomaly from the log message from ``DoWork` method.
```
RecurringJobManager manager = new RecurringJobManager();
manager.RemoveIfExists("myjob");
manager.AddOrUpdate("myjob", Job.FromExpression(() => DoWork()), $"0 * * * *", TimeZoneInfo.Local);
```

DoWork method:
```
public void DoWork()
{
	_logger.LogError($"Timed Background Service is working. Current time: {DateTime.Now.ToLocalTime()}");
}
```

I don't believe that the code is supposed to work like that. Because imagine that this is in production and it's keeps adding additional seconds to each execution. What's going to happen is that if it keeps on that way, those additional seconds will cause a huge anomaly depending on the server uptime (minutes/hours mismatch).

One more `RecurringJob` sample below, this time `DoWork` is executed on each 5 minutes and the outputs are presented as well. You can imagine how bad it can get if that `RecurringJob` lasts longer:

```
RecurringJob.AddOrUpdate("myjob", () => DoWork(), $"0/5 * * * *", TimeZoneInfo.Local);
```

Output:
```
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:00:04 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:05:04 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:10:04 AM
```
Another output (different machine):
```
info: Binance.Services.BotHostedService[0]
      Timed Background Service is starting. Current time: 8/16/2019 3:22:39 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:25:10 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:30:10 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:35:10 AM
fail: Binance.Services.BotHostedService[0]
      Timed Background Service is working. Current time: 8/16/2019 3:40:11 AM
```
Is there a solution for that issue?

By the way, I'm using ASP.NET Core 2.2 Web API and the following NuGet Packages:
```
<PackageReference Include="Hangfire.AspNetCore" Version="1.7.6" />
<PackageReference Include="Hangfire.SqlServer" Version="1.7.6" />
```

**Comment by odinserj** [comment]
> I don't believe that the code is supposed to work like that. Because imagine that this is in production and it's keeps adding additional seconds to each execution. What's going to happen is that if it keeps on that way, those additional seconds will cause a huge anomaly depending on the server uptime (minutes/hours mismatch).

Those additional seconds don't sum up with each invocation. By default, recurring job scheduler wakes up each 15 seconds, and this behavior can affect the timings. You can try to change the `BackgroundJobServerOptions.SchedulePollingInterval` and set it to a lower value.

However Hangfire isn't supposed to perform anything in real time with almost zero delays. There are a lot of factors like network and storage that may increase the latency.

**Comment by Hulkstance** [comment]
Thanks! I figured it out 1 day after I posted it but I forgot to edit it.

**Comment by burningg** [comment]
@Hulkstance  hey，how did you solve this problem

**Comment by Hulkstance** [comment]
> @Hulkstance hey，how did you solve this problem

I didn't. I just accepted the fact that the seconds are not important, as long as it executes on the minute it should. It's due to the `BackgroundJobServerOptions.SchedulePollingInterval`
