### ISSUE TITLE
Run jobs synchronously or store in-memory

### ISSUE THREAD

**Issue by Lobosque** [HangfireIO/Hangfire#1499]
I wonder if it is possible to execute jobs immediately, in a synchronous manner, or use a memory provider to store the jobs when running tests?
I am using a redis setup but do not want to run a redis instance for tests.
Any other tips for a simple setup to use on tests are welcome.
However, i need the jobs to actually be executed (ie NOT mocks)

**Comment by stevendesrochers** [comment]
Why do you want to use Hangfire in your test?

Can't you just instantiate the class you're trying to test and call the method from your test?

**Comment by Lobosque** [comment]
@stevendesrochers I am testing my API end-to-end - I am basically calling endpoints and checking for expected responses and database states.

**Comment by stevendesrochers** [comment]
You could use [Hangfire.MemoryStorage](https://github.com/perrich/Hangfire.MemoryStorage) for you use-case

> It can be useful for testing purpose like check the behaviour and use it in a development environment. Please note that :
> - it should not be used in production (no integrity and no thread safe even if many cases are managed).
> - data are stored in memory using a dictionary in a static way (See Data created at the storage creation)

**Comment by Lobosque** [comment]
thanks, this is what i was looking for!
