### ISSUE TITLE
Every 17 minutes from the current time

### ISSUE THREAD

**Issue by bxjg1987** [HangfireIO/Hangfire#1507]
Let's say my current time is 10:31
`RecurringJob.AddOrUpdate<DialysisMachineJob>(
                "DialysisMachineJob.Do",
                job => job.Do(),
                "0 0/17 * * * ?");`
It's 10:48 11:00 11:17
The interval here starts at 0 minutes,

But I want to start with the current system time
The expected result should be: 10:48 11:05 11:22

What should I do without periodic tasks? Use deferred tasks instead

**Comment by fasetto** [comment]
Its scheduled to run for every 17th minute. So, its normal.
Change the cron expression with 15mins if you want an easy solution.

**Comment by bxjg1987** [comment]
@fasetto Is there a way to start periodic tasks from the current time?

**Comment by fasetto** [comment]
There is a package called [FluentScheduler](https://github.com/fluentscheduler/FluentScheduler)
You can run periodic tasks with help of this package I think.
I used once.

**Comment by bxjg1987** [comment]
@fasetto thanks a lot
