### ISSUE TITLE
Is support for Microsoft.Data.SqlClient in the plans

### ISSUE THREAD

**Issue by tauqirghani** [HangfireIO/Hangfire#1514]
Microsoft has released Microsoft.Data.SqlClient that lets .Net Core application to connect to SQL Server and Azure SQL using Active Directory based authentication. Moving forward the new development will be in this package. Is this part of the roadmap for Hangfire? Any timelines?

**Comment by tonihele** [comment]
Yep, not supported at the moment:
```
Message: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.
System.Data.SqlClient.SqlCommand.set_DbConnection(DbConnection value)
Hangfire.SqlServer.SqlCommandBatch.ExecuteNonQuery():222
Hangfire.SqlServer.SqlServerWriteOnlyTransaction.<Commit>b__12_0(DbConnection connection, DbTransaction transaction):270
Hangfire.SqlServer.SqlServerStorage+<>c__DisplayClass33_0.<UseTransaction>b__0(DbConnection connection, DbTransaction transaction):13
Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func):14
Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel):83
Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action):42
Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit():34
Hangfire.Client.CoreBackgroundJobFactory+<>c__DisplayClass14_0.<Create>b__3(Int32 attempt):162
Hangfire.Client.CoreBackgroundJobFactory+<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt):12
Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action):34
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action):132
Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context):221
Hangfire.Client.BackgroundJobFactory+<>c__DisplayClass12_0.<CreateWithFilters>b__0()
Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation):250
Hangfire.Client.BackgroundJobFactory.Create(CreateContext context):77
Hangfire.BackgroundJobClient.Create(Job job, IState state):56
```

**Comment by tonihele** [comment]
You list this in 1.7.7 release. But it seems that just feeding a Microsoft.Data.SqlClient.SqlConnection still fails as stated in the above comment. Is there something that I'm missing? Is there a different Storage object?

**Comment by odinserj** [comment]
Sorry for the confusion, I was thinking upgrading Dapper will be enough and ran only smoke test where Hangfire Server was connecting to a database with no jobs. So it's likely this feature will be postponed to version 1.7.8, but you can use version `1.7.7-build-03035` from the CI Feed `https://ci.appveyor.com/nuget/hangfire` (or download it from the ["Artifacts" tab](https://ci.appveyor.com/project/odinserj/hangfire-525/builds/28355411)).

**Comment by tonihele** [comment]
Very nice, thanks. This is actually quite a big issue for us, so I definitely appreciate the speedy service.

**Comment by molesinski** [comment]
This is acutally more complex issue for us as well, as it is last package blocking us from moving to NET Core 3.0 and EF Core 2.1. The reason for that is that we share SqlConnection and transaction for EF Core database changes and hangfire job dispatching, on which we have modelled reactive event processing. And since EF Core 2.1 moved to Microsoft.Data.SqlClient it is obvious which this is blocking us.

**Comment by ccjx** [comment]
Hi all, thanks for the quick fix. Do we have a target date for 1.7.8 release? I am just planning my release and would like to know when this can be merged in (hopefully in time before .Net Core 2.2 is EOL in Dec 2019).

**Comment by odinserj** [comment]
Hangfire 1.7.8 was just released, so I'm closing this issue.

**Comment by bao2314483** [comment]
1.7.8 not supported

**Comment by alexstewart-meb** [comment]
Reading this, I can see that Microsoft.Data.SqlClient is supported from v1.7.8/9 however the current version v1.7.13 still references  System.Data.SqlClient v4.4.0. I ask a slightly more specific question than the original: is removing the dependency on System.Data.SqlClient and replacing it with Microsoft.Data.SqlClient in Hangfire.SqlServer package in the roadmap?

My specific use case is for Always On Encryption ("Column Encryption Setting" in the connection string) which is supported by Microsoft.Data.SqlClient but not System.Data.SqlClient. In a .NET Core 3.1 app.

**Comment by odinserj** [comment]
Try to use the following code to use the newest client. Unfortunately it can't be replaced without causing a lot of applications to be broken, so there will be no change in 1.X version. Perhaps there's a way to add `UseMicrosoftSqlServer` or better method name (to point that the new package will be used) by using reflection.

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(
        () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
```

**Comment by alexstewart-meb** [comment]
Thanks for the suggestion and I'll give it some thought. Other packages I've seen have gone down the route of publishing two (clearly named ;-)) nuget packages because of the compatibility issues you mention. Presumably they'll support both for a limited period of time. It's not pretty but it does give a migration path for people.

**Comment by landlogicit** [comment]
> Try to use the following code to use the newest client. Unfortunately it can't be replaced without causing a lot of applications to be broken, so there will be no change in 1.X version. Perhaps there's a way to add `UseMicrosoftSqlServer` or better method name (to point that the new package will be used) by using reflection.
> 
> ```cs
> GlobalConfiguration.Configuration
>     .UseSqlServerStorage(
>         () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
> ```

Good
