### ISSUE TITLE
Max items per page in Hangfire Dashboard (max. 500) should be higher

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#1518]
We do a lot of jobs through Hangfire every day. If there are some issues on our other sub-systems I can get +5000 failed jobs in one day and it's time consuming to delete them only by 500 in batch. Would be nice if max **Items per page** should be a higher number (1000, 1500 ?).

**Comment by paul-v-g** [comment]
Nice! Though I think it would be even nicer to be able to set the pager array with a customizable option and leave it up to the developer to add higher 'items per page' numbers.

**Comment by odinserj** [comment]
I don't like the idea of taking all the resources of your database by providing an unbounded button, because some pages issue N additional queries, because of the abstracted storage and since SQL may be not available. 

However you can tweak URL to have whatever count you like :wink:

**Comment by wub** [comment]
@odinserj Is it possible to configure the default number of items per page? 10 is really small.
