### ISSUE TITLE
After Update to .Net Core 3  "An unhandled exception has occurred while executing the request."

### ISSUE THREAD

**Issue by aseif83** [HangfireIO/Hangfire#1549]
I using Hangfire version 1.7.7 with SQL server Store  i got below message in Dashboard
"Unable to refresh the statistics: the server responded with 500 (error). Try reloading the page manually, or wait for automatic reload that will happen in a minute."
,Here is logged exception details ,
An unhandled exception has occurred while executing the request.

System.IO.InvalidDataException: Form key length limit 2048 or value length limit 2147483647 exceeded.\r\n   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ThrowKeyOrValueTooLargeException()\r\n   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)\r\n   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)\r\n   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)\r\n   at Hangfire.Dashboard.AspNetCoreDashboardRequest.GetFormValuesAsync(String key)\r\n   at Hangfire.Dashboard.BatchCommandDispatcher.Dispatch(DashboardContext context)\r\n   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\\projects\\netescapades-aspnetcore-securityheaders\\src\\NetEscapades.AspNetCore.SecurityHeaders\\SecurityHeadersMiddleware.cs:line 68\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware"

**Comment by aseif83** [comment]
it is related to Core 3 overflow issue "Using the RequestFormLimits attribute throws an InvalidDataException."
Issue: https://github.com/aspnet/AspNetCore/issues/13719
Fixed by change KeyLengthLimit value from int.MaxValue to appropriate  limit

**Comment by rohanaceres** [comment]
How this issue was solved?
