### ISSUE TITLE
Problem with cron expression

### ISSUE THREAD

**Issue by gilsoncabacazzo** [HangfireIO/Hangfire#1559]
What would be the cron expression to execute tasks every day, at a specific time
I am using these expressions, but they are not working for me.

What I want is to execute a task every day, at a specific hour and minute.

Please if you could help me

![Inked1_LI](https://user-images.githubusercontent.com/56260092/68230563-085f6880-ffd8-11e9-9d01-32c3c0ef1873.jpg)

Thank you
Regards

**Comment by pieceofsummer** [comment]
Your expressions look fine, and estimated execution times on the screenshot correspond to 15:23 UTC.

Check if at least one Hangfire server instance is actually running to execute those jobs. Make
sure the app pool is [configured to be always running](https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html) if the Hangfire server is running inside IIS web application.

Also note your recurring jobs are created a few seconds ago, so ensure your jobs’ registration logic is correct and you’re using some persistent storage to retain the jobs between app restarts.
