### ISSUE TITLE
Hangfire.Set.Score = -1, Jobs stop running until restart server

### ISSUE THREAD

**Issue by chadwixk** [HangfireIO/Hangfire#1560]
version Hangfire 1.7.3
used in ASP.NET MVC web app using SQL Server storage

Hello, having an new issue after many years of this working fine. Suddenly hangfire jobs have stopped running. The Job is stating: `Value cannot be null. Parameter name: values`

![image](https://user-images.githubusercontent.com/5115308/68239113-a860c600-ffc7-11e9-9bf6-5c27aecd7d5b.png)

Looking at the db tables to see what is different between them, I see the Hangfire.Set.Score value is -1 for these affected jobs.

![image](https://user-images.githubusercontent.com/5115308/68240210-b44d8780-ffc9-11e9-971a-0fab0c0fea28.png)

The recurring  jobs are being added via:

`var syncErpWithNewOrUpdatedItemsTask = new SyncErpWithNewOrUpdatedItemsTask();
                RecurringJob.AddOrUpdate(storeFront.StoreFrontFullName + _JobDescription_Item_Import,
                    () => syncErpWithNewOrUpdatedItemsTask.Execute(storeFront.Id),
                        "*/5 * * * *", //every 5 min 
                    TimeZoneInfo.Local);  `

Any ideas on why this could be happening suddenly?

**Comment by chadwixk** [comment]
I upgraded to 1.7.7 and also ran the db schema upgrade script to get on schema 7 and all is working now.

**Comment by Ongken** [comment]
#2147
