### ISSUE TITLE
ASP.NET Core 3 Endpoint Authorization

### ISSUE THREAD

**Issue by chris5287** [HangfireIO/Hangfire#1561]
Any idea on how to configure the Hangfire dashboard UI to use the new endpoint routing, so that specific Authorization policies can be applied to the route using .RequireAuthorization(...) syntax, eg:

```
app.UseEndpoints(endpoints =>
    {
        endpoints
            .MapHangfireUI("/hangfire")
            .RequireAuthorization(new AuthorizeAttribute(){ Roles = "admin" });
    }); 
```

Ref: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#authorization

**Comment by lyoeril** [comment]
I'm having the same issue at the moment. can't seem to setup hangfire correctly to recognize the loggedin users. Have you figured this out yet?

**Comment by kendaleiv** [comment]
`MapHangfireDashboard` is added in https://github.com/HangfireIO/Hangfire/pull/1577.
