### ISSUE TITLE
Dashboard showing incorrect date and time

### ISSUE THREAD

**Issue by WilliamT-Streamba** [HangfireIO/Hangfire#1572]
The dashboard is showing the date as 3 days in the past, (22nd instead of 25th) and the time as ~3:50am instead of 9am, I've attached an image that shows the realtime graph showing the correct time but the historical graph and viewing individual jobs are all in the wrong time.

I've checked the timezone of the machine is correct and I read another issue that mentioned momentjs is used and double checked that returns expected results in the browser console.

Any pointers to things to check?

![hangfire-bug](https://user-images.githubusercontent.com/19775073/69526920-25e27b00-0f63-11ea-9b29-56cf6a4f0720.PNG)

**Comment by felixclase** [comment]
Are you using Internet Explorer?

I had the same inconvenience and it was because of the browser.

https://github.com/codeyu/Hangfire.LiteDB/pull/17#issuecomment-542706707

https://github.com/codeyu/Hangfire.LiteDB/pull/17#issuecomment-542718764

**Comment by WilliamT-Streamba** [comment]
Thanks @felixclase tried using chrome instead of firefox and correct date/times were shown.
