### ISSUE TITLE
Why Newtonsoft.Json v5.0.1 is being used for .NET 4.5/4.6 builds?

### ISSUE THREAD

**Issue by DonKonfetti** [HangfireIO/Hangfire#1579]
This is merely a question, not a bug report. I ran into a version conflict with Newtonsoft.Json while introducing another dependency in one of our projects that itself depends on Newtonsoft.Json v11. Wondering why your .NET Framework builds are still referencing v5.0.1 (whereas .NET Standard builds are referencing newer versions). Are there any special reasons?

**Comment by odinserj** [comment]
Backward compatibility, Don, backward compatibility – somewhere there's a project that still use that version.

**Comment by burningice2866** [comment]
Hopefully it wasn't an actual conflict but just a matter of keep using Newtonsoft.Json v11, Hangfire runs fine with all newer versions since 5.0.1 but doesn't force it.

**Comment by DonKonfetti** [comment]
> Hopefully it wasn't an actual conflict but just a matter of keep using Newtonsoft.Json v11, Hangfire runs fine with all newer versions since 5.0.1 but doesn't force it.

Actually, Hangfire 1.6.20 refused to work with v11. But it surely can be solved with binding redirect.

**Comment by burningice2866** [comment]
> Actually, Hangfire 1.6.20 refused to work with v11. But it surely can be solved with binding redirect.

That's more a detail of .Net Assembly Binding than a issue with Hangfire. You'll find that to be a general recurring theme when working with NuGet libraries because there is much more focus on versioning that in the old days before NuGet.

But its good you resolved it.
