### ISSUE TITLE
NextExecution values are only updated upon execution

### ISSUE THREAD

**Issue by sjwoodard** [HangfireIO/Hangfire#158]
This method does not affect the execution time on recurring jobs:

```
AddOrUpdate<T>(string recurringJobId, Expression<Action<T>> methodCall, string cronExpression);
```

The CRON settings appear correctly in the dashboard, but the event's execution time is null for new jobs or registered to a previous CRON string for pre-existing jobs. Restarting my application and the storage server (redis in my case) did not solve the issue.

I will investigate further and post back. Thanks!

**Comment by bassebaba** [comment]
It seems like this was never fixed?
I am using this to fetch the scheduled job:  JobStorage.Current.GetConnection().GetRecurringJobs()

**This is directly after adding the job:**
11:23:39,891 Runner :: INFO  - ID: EchoJob - Next:  - Last:

**This is after it has run once:**
11:24:02,478 Runner :: INFO  - ID: EchoJob - Next: 2017-05-24 09:25:00 - Last: 2017-05-24 09:24:00

**What I expect is that "NEXT" in the first print would have shown "2017-05-24 09:24:00"**
