### ISSUE TITLE
Adding recurring job in worker service

### ISSUE THREAD

**Issue by chris5287** [HangfireIO/Hangfire#1596]
I am using the worker service template, utilising the `AddHangfireServer()` extension method. 

When I tried to add a recurring job after calling that extension method `RecurringJob.AddOrUpdate...` I get the following error: `System.InvalidOperationException: ‘JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.’`

Anyone worked out how to add a recurring job using the worker service template?

**Comment by pieceofsummer** [comment]
Background job client and recurring job manager are parts of client api, and probably shouldn’t be used in a pure worker service app.

Generally, you might want to use `AddHangfire()` extension method to configure Hangfire before using `AddHangfireServer()`. This would configure global job storage and other services such as job activator to be used by both server and client parts.

Also using `IBackgroundJobClient` and `IRecurringJobManager` services instead of `BackgroundJob`/`RecurringJob` static methods is preferred in modern apps.

**Comment by chris5287** [comment]
I have called the `AddHangfire()` extension before, so that shouldn’t be an issue. 

If I build the host and then call `host.Services.GetServices<IHostedServices>()` then adding a recurring job appears to work, but it’s suspicious that I have to fetch the service to get it to initialise?

**Comment by pieceofsummer** [comment]
Services are lazy initialized, so the service itself and its dependencies won’t be instantiated unless you inject/resolve it somewhere. That’s the other reason you should use services instead of static methods.

**Comment by chris5287** [comment]
Here’s what I ended up with:

```
    public class Program
    {
        public static async Task Main(string[] args)
        {
            // Build the host.
            var host = CreateHostBuilder(args).Build();
 
            // Execute pre-setup items.
            using (var scope = host.Services.CreateScope())
            {
                // Configure Hangfire recurring jobs.
                var recurringJobManager = scope.ServiceProvider.GetRequiredService<IRecurringJobManager>();
                recurringJobManager.AddOrUpdate("IService.Heartbeat", Hangfire.Common.Job.FromExpression<IService>(service => service.Heartbeat()), "* * * * *");
            }
 
            // Run the host.
            await host.RunAsync();
        }
 
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    // Add the Hangfire services.
                    services.AddHangfire(options =>
                        options
                            .UseSqlServerStorage(configuration.GetConnectionString("HangfireDbContext")));
                    services.AddTransient<IService, RealService>();
 
                    // Add the Hangfire server.
                    services.AddHangfireServer();
                });
    }
```
