### ISSUE TITLE
RecurringJobScheduler should use UTC time

### ISSUE THREAD

**Issue by sjwoodard** [HangfireIO/Hangfire#160]
Everywhere that _dateTimeProvider.GetNextOccurrence(cronSchedule) is used in RecurringJobScheduler should be appended with .ToUniversalTime(). That way if the server and client are in different time zones, the scheduling will make sense.

This creates a problem of converting CRON strings to UTC. I'm experimenting with using the system's UTC offset to move the CRON hours value around. *(EDIT: see next post for a helper method solution)*

That then causes trouble with the CronExpressionDescriptor used on the dashboard pages. It reads directly from the CRON string, which may not be the same as UTC. I'm in the Eastern U.S., so my CRON value is 4 hours ahead of the ExecutionTime.

**Comment by jkodroff** [comment]
I am also on the East Coast of the US and getting a job to fire at 7:00 PM is trickier than expected.  Will post an update when we figure it out.

**Comment by jkodroff** [comment]
Had to set the job to run at 6:59 PM (local) because the offset (-5 hours) would change the job to run on the wrong days.

**Comment by jkodroff** [comment]
Had to set the job to fire at 6:59 PM because the offset (-5 hours) would then set the job to run on the wrong day.  Thus, I really don't like the UTC-only functionality.  It also makes it difficult for my users to read the admin panel (they don't really get UTC).
