### ISSUE TITLE
Recurring job fails to run - Error : System.MissingMethodException: No parameterless constructor defined for type

### ISSUE THREAD

**Issue by ghetze** [HangfireIO/Hangfire#1607]
I have a .net core 3.1 console application (HangFire v1.6.3, HangFire.MemoryStorage v1.7.8) which will run an reccuring that will call a_redis.StartProceessing() method. The job should run every minute 
In console the following error is display each time the job shoud run:

Failed to process the job '6c3facce-7b39-4766-8bf1-6561f14980b3': an exception occurred.|System.MissingMethodException: No parameterless constructor defined for type 'SMPP.DeliveryCleanup.Redis'.    at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)    at System.Activator.CreateInstance(Type type)    at Hangfire.JobActivator.ActivateJob(Type jobType)    at Hangfire.JobActivator.SimpleJobActivatorScope.Resolve(Type type)    at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()    at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)    at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)    at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

What am i doing wrong ?

Here is my code 
in Program.cs i have : 
public class Program
    {
private static IConfigurationRoot _configuration;
private static ILogger _logger;
private static readonly ManualResetEvent _quitEvent = new ManualResetEvent(false);
public async static Task Main(string[] args)
{
// create service collection
 var serviceCollection = new ServiceCollection();
ConfigureServices(serviceCollection);

// create service provider
var serviceProvider = serviceCollection.BuildServiceProvider();

_logger = serviceProvider.GetService<ILogger<Program>>();

 // entry to run app
var engine = serviceProvider.GetService<Engine>();
GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 0 });
RecurringJob.RemoveIfExists("test");
RecurringJob.AddOrUpdate("test", () => engine.StartToListenForKeys(), Cron.Minutely, TimeZoneInfo.Local);
_quitEvent.WaitOne();
}
private static void ConfigureServices(IServiceCollection serviceCollection)
        {
            // build configuration
            _configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .Build();
            //add NLog to .NET Core. Nothing already added. Logging section not mapped by default
            serviceCollection.AddLogging(builder => builder
                .AddConfiguration(_configuration.GetSection("Logging"))
                .AddNLog());

            //Hangfire support ;
            var inMemory = GlobalConfiguration.Configuration.UseMemoryStorage();
            serviceCollection.AddHangfire(x => x.UseStorage(inMemory));

            // Add the processing server as IHostedService
            serviceCollection.AddHangfireServer();

            //DI
            serviceCollection.AddSingleton<Redis>();
        }
}

public class Redis : IDisposable
{
public Redis(IServiceProvider serviceProvider, IOptions<RedisSettings> redisOptions, ILogger<Redis> logger)
{
..............
}
..................
public async Task StartToListenForKeys()
{
//connects to redis and starts some processiig based on some keys.
}
}

**Comment by alexandrutatagit** [comment]
Hi!

I have the same issue. Appreciate!

Alex

**Comment by pieceofsummer** [comment]
I'm not sure if "HangFire v1.6.3" is a typo, but it is very old and doesn't have `IHostedService` server implementation. I'm also pretty sure the code above is broken/incomplete, because you cannot run hosted services without a proper host.

> at Hangfire.JobActivator.SimpleJobActivatorScope.Resolve(Type type)

This line indicates you're using the wrong activator which knows nothing about DI (hence cannot do constructor injection of services), so this is a configuration issue. I suggest you to start with updating Hangfire version (if that was not a typo after all) and setting up a [proper hosting environment](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1).

**Comment by ghetze** [comment]
"HangFire v1.6.3" was a typo, I'm using Hangfire (1.7.9) and HangfireMemoryStorage(1.6.3)...the error still appears.

**Comment by pieceofsummer** [comment]
Can you provide some minimal working project so it could be tested? The code above doesn't seem complete.

**Comment by ghetze** [comment]
[TestHangfireProject.zip](https://github.com/HangfireIO/Hangfire/files/4116901/TestHangfireProject.zip)

Hi,I,ve added the test project ... by adding a constructor with no parameters the error is gone , but now it crashed with another error as i want to give an interface as paramaeter.

**Comment by pieceofsummer** [comment]
Oh, now I see where your problem is. You cannot just create `BackgroundJobServer` like this:
```c#
using (new BackgroundJobServer())
{
    _logger.LogInformation("Hangfire Server started. Press ENTER to exit...");
    _quitEvent.WaitOne();
}
```

It doesn't know about DI when instantiated without proper options. This is why I suggested you to use a proper hosting environment for your application.

Here's a test project with proper changes: [TestHangfireProject.zip](https://github.com/HangfireIO/Hangfire/files/4119631/TestHangfireProject.zip)

**Comment by ghetze** [comment]
Thanks a lot for your help, now it's working.
