### ISSUE TITLE
Dapper reference and NuGet package version conflicts

### ISSUE THREAD

**Issue by besley** [HangfireIO/Hangfire#1608]
When using Hangfire library into .net core application, There is a version conflict occured between two different Dapper library. One version is V1.5.0 from Nuget package, and another version is V1.0.0 reference from my local .net core project. There is an error when running program. I need to keep my local dapper version, because I have extended some code in dapper.

[dapper conflict issue in stackoverflow](https://stackoverflow.com/questions/54236536/how-to-resolve-net-core-reference-and-nuget-package-version-conflicts-when-usin)

I hope hangfire use it's dapper refrence, and not conflict my local dapper version, is there a way to resolve this issue？ Thanks!

**Comment by odinserj** [comment]
Hangfire doesn't reference Dapper package, and it's internalized and merged into the Hangfire.SqlServer.dll assembly, and I don't understand why does it thinks that those types should be loaded from the `Dapper` assembly.

What version of Hangfire are you using? Could you create a repository with the reproduction of this problem?

**Comment by odinserj** [comment]
Also, where did you get those Hangfire packages? Any chance you was building them manually?

**Comment by besley** [comment]
Hi, Thanks your reply and tips. After the dapper version 1.50.1 is referenced from nuget package. the project will work well, the job list page will be fine.

But there still is a issue, if we reference our local dapper library in the project, it seemed firstly to reference the dapper version 1.50.1 when executing some our business logic program, not our local dapper version.

The Hangfire verson v1.7.9 is from nuget, and the .netcore version is v2.1.

**Comment by besley** [comment]
This issue is fixed by getting the fully nuget package of HangFire. HangFire.Core, HangFire.SqlServer and HangFire.AspNetCore library. Thanks
