### ISSUE TITLE
Dashboard configuration is painfuly slow on startup when using Redis storage

### ISSUE THREAD

**Issue by shake82** [HangfireIO/Hangfire#1610]
**Using dotnet core 2.1:**

`app.UseHangfireDashboard` is really slow when using redis as storage taking upto 4-10 secs that slows down the overall startup of the application

I have narrowed the issue to the `AspNetCoreDashboardMiddleware` . The problem seems to be that JobStorage class is injected into its constructor instead of the `Invoke` method. And the Redis JobStorage object take a while to construct because it seems to wait for the Redis connectivity to complete during its constructor execution.

I can understand the reasons for this design because it allows you pass a custom JobStorage during configuration instead of using whatever is configured in the IOC/ServiceCollection

The only options I can see is to either give an additional `AspNetCoreDashboardMiddleware` implementation that gets the JobStorage class in the `Invoke` method from the ServiceCollection or make the Redis JobStorage class lazy loaded\asynchronous so that it may not hold up the application startup activities during its construction.

I played around with the following piece of code to see if I can improve the performance and there was a huge difference. It is not meant to be an actual solution but just to highlight the issue:

```
public class HangFireDashboardMiddlewareEx
    {
        private readonly RequestDelegate _next;
        private AspNetCoreDashboardMiddleware _encapsulatedMiddleware = null;

        ILogger<HangFireDashboardMiddlewareEx> _logger;

        public HangFireDashboardMiddlewareEx(
            RequestDelegate next,
            ILogger<HangFireDashboardMiddlewareEx> logger)
        {
            if (next == null) throw new ArgumentNullException(nameof(next));

            _next = next;

            this._logger = logger;

            _logger.LogTrace($"HangFireDashboardMiddlewareEx instance created");
        }
        public async Task Invoke(HttpContext httpContext,
            JobStorage storage,
            DashboardOptions options,
            RouteCollection routes)
        {
            _logger.LogTrace($"HangFireDashboardMiddlewareEx invoked");
            var middleware = this.GetDashboardMiddleware(storage, options, routes);

            await middleware.Invoke(httpContext);
        }

        private AspNetCoreDashboardMiddleware GetDashboardMiddleware(JobStorage storage,
            DashboardOptions options,
            RouteCollection routes)
        {
            if(this._encapsulatedMiddleware == null)
            {
                lock (this)
                {
                    if(this._encapsulatedMiddleware == null)
                    {
                        _logger.LogTrace($"creating new instance of AspNetCoreDashboardMiddleware");
                        this._encapsulatedMiddleware = new AspNetCoreDashboardMiddleware(this._next, storage, options, routes);
                    }                    
                }
            }

            return this._encapsulatedMiddleware;
        }
    }
```

**Comment by odinserj** [comment]
Thanks for reporting this @shake82! Indeed, there's an unnecessary wait for connection to be established (but connection setup is held asynchronously) in the `RedisStorage` class' constructor. We are waiting for this event in other methods anyway, so we can remove that call. 

I've changed this in Hangfire.Pro.Redis version `2.5.5-build-01258` and you can pull the package from the CI feed `https://nuget.hangfire.io/nuget/hangfire-pro-ci/` using credentials you already have. If it solves the issues, I will release the changes in 2.5.6.
