### ISSUE TITLE
There are no active servers. Background tasks will not be processed.

### ISSUE THREAD

**Issue by jiangyimm** [HangfireIO/Hangfire#1645]

**Comment by sabiland** [comment]
@odinserj After I upgraded from `1.8.12` to version `1.8.13`, I get this message (0 servers). First time I see this, Hangfire Dashboard works, but nothing else is happening/working.

**Comment by sabiland** [comment]
Everything is OK with version `1.8.14`!

**Comment by odinserj** [comment]
Great to hear! So I'm closing this issue
