### ISSUE TITLE
Reccuring job cannot be triggered from a client without reference to the job target

### ISSUE THREAD

**Issue by gius** [HangfireIO/Hangfire#165]
If I trigger a recurring job from Hangfire client (the job should be ran by another Hangfire server), a System.IO.FileNotFoundException - "Could not load file or assembly (the assembly of the recurring job)" is thrown.

I believe this is wrong behavior as clients should not need reference to job targets that are about to be executed on another server.

**Comment by noleafclover614** [comment]
@odinserj 
Are you saying that you create interfaces for the methods you need in your client apps and then create those same interfaces with implementations, along with an IoC container, in the server (processing) app?  

This same issue is also referenced at #433
