### ISSUE TITLE
Set workers per queue

### ISSUE THREAD

**Issue by sjwoodard** [HangfireIO/Hangfire#166]
I have found a need to set the number of workers per queue.

As an example, say I want to run 5 workers to run processes on a CPU-intensive queue, but I want another 20 processes dedicated to a less intense processes queue. Is that possible? Thanks!

**Comment by alastairtree** [comment]
I had the same problem but if you have lots of jobs with different numbers of workers, it get a bit messy having one server per queue so I tried to solve it using a job attribute. You can find it at https://github.com/alastairtree/Hangfire.MaximumConcurrentExecutions if your still interested.

**Comment by danielcor** [comment]
I wonder if this approach can be modified to support memory Spain
constraints?   I.e.  only start a job if there is X system memory left?

**Comment by alastairtree** [comment]
@danielcor it's not really an extension to do that but sure you could write a job filter that reads performce counters and acts appropriately. Although with RAM being so cheap you money might be better spent sticking more RAM in your machine!
