### ISSUE TITLE
Hangfire is hammering the database

### ISSUE THREAD

**Issue by nmg196** [HangfireIO/Hangfire#1664]
Hi,
We are suffering from a poor SQL performance problem on one application which uses Hangfire. While looking at the activitiy monitor, it seems Hangfire runs the following code over 2000 times per minute.  

```
update top (1) JQ
set FetchedAt = GETUTCDATE()
output INSERTED.Id, INSERTED.JobId, INSERTED.Queue, INSERTED.FetchedAt
from [HangFire].JobQueue JQ with (forceseek, paglock, xlock)
where Queue in (@queues1) and
(FetchedAt is null or FetchedAt < DATEADD(second, @timeout, GETUTCDATE()))
```
![image](https://user-images.githubusercontent.com/8134047/81187192-a0e89c80-8fab-11ea-9393-dc6832bce90c.png)

Is this normal?  The actual Hangfire.JobQueue table itself is empty whenever I look. 

What might be causing this?

**Comment by odinserj** [comment]
Hi Nick! In the latest 1.7.X versions you can use the following configuration to dramatically decrease the number of requests to SQL Server and decrease the overall latency at the same time:

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage("connection_string", new SqlServerStorageOptions
    {
        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
        QueuePollInterval = TimeSpan.Zero
    });
```

**Comment by jgrandydev** [comment]
But setting those options switches off transactional message dequeue into a mode that seems to permanently have hundreds of explicit low-level locks open.  This behavior alarms DBAs monitoring database health and leads them to ( possibly erroneously ) blame Hangfire for database performance issues.

**Comment by odinserj** [comment]
> But setting those options switches off transactional message dequeue and switches on a mode that permanently has open hundreds of explicit low-level locks.

Could you elaborate? That query is running under read committed isolation level, releasing all the locks just after UPDATE query is finished. `XACT_ABORT` mode is also turned on for this query, and all the locks will be released in case of any error on SQL Server's side. `WAITFOR` statement is also bounded, so SQL Server's worker thread is released soon.

**Comment by jgrandydev** [comment]
Here's the query that alarmed our DBAs : 

```
select * 
from sys.sysprocesses
where blocked <> 0
```

This revealed 20 locks with : 

`waittype=0x0005`
`waittime=89 to 918 range`
`lastwaittype=LCK_M_X`
`waitresource=APP: 236:0:[HangFire_FetchLockLock_default_f]: ...`

Once we removed `SlidingInvisibilityTimeout` from `SqlServerStorageOptions` we no longer experienced these locks and our DBAs were happy.

Maybe this is an education thing ?

**Comment by odinserj** [comment]
Please upgrade Hangfire.Core and Hangfire.SqlServer packages to the latest version 1.7.11 and apply the settings above again – FetchLockLock is not acquired since version 1.7.9.
