### ISSUE TITLE
Should be able to specify seconds in RecurringJobScheduler

### ISSUE THREAD

**Issue by sgrassie** [HangfireIO/Hangfire#167]
The `RecurringJobScheduler` should be able to set a job to reoccur every X seconds.

There is support for this in NCrontab [see #7](https://code.google.com/p/ncrontab/issues/detail?id=7), although a build has not yet been released.

I think it would involve making a change [here](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/RecurringJobManager.cs#L64), such that `CrontabSchedule.Parse` takes a second options argument, where you specify that you want to recognise six-part crontab expressions.

**Comment by bbakkebo** [comment]
Hi, I am currently testing 1.40, but I cannot see that it was updated.  Hangfire works great, but I have one job that needs to run everything 30 seconds..Is there a workaround to this?
Thanks in advance. :+1:

**Comment by bahram-hodjaev** [comment]
bbakkebo, you can workaround this

    public void Configuration(IAppBuilder app)
    {
        GlobalConfiguration.Configuration.UseSqlServerStorage("DefaultConnection");            
        app.UseHangfireDashboard();
        app.UseHangfireServer();
        BackgroundJob.Enqueue(() => Cron());
    ...

    public void Cron()
    {
        BackgroundJob.Schedule(() => Cron(), System.TimeSpan.FromSeconds(15));
    }

**Comment by reggieboyYEAH** [comment]
Hi @bahram-hodjaev i tested this and this does not work,
this will only run the job once. 

any update on this? i have a job that needs to run every 30 seconds.

Thanks in advance :)

**Comment by bahram-hodjaev** [comment]
Hi, @reggieboyYEAH, for now i am using this

    protected void Application_Start()
    {
        AreaRegistration.RegisterAllAreas();
        FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
        RouteConfig.RegisterRoutes(RouteTable.Routes);
        BundleConfig.RegisterBundles(BundleTable.Bundles);

        clock = new ApplicationClock().Start();
    }   

    //...
    public class ApplicationClock
    {
        readonly object tickLock = new object();
        private Timer ticker = null;

        void tick(object _)
        {
            lock (tickLock)
            {
                try
                {
                    // DoSomeStuff();
                }
                catch
                {
                    if (ticker != null)
                    {
                        ticker.Dispose();
                    }

                    Start();
                }
            }
        }

        public ApplicationClock Start()
        {
            ticker = new Timer(tick, null, 0, 1 * 1000);
            return this;
        }
    }

This works great

**Comment by LordMike** [comment]
Is there an update on this?
I'll probably try the Enqueue/Schedule trick, but if Hangfire internally only works in minutes, then that's not gonna work.. :/

**Comment by alisherdavronov** [comment]
how about enqueue delayed jobs in every minute? if 5 second granularity needed there will be 30 jobs every minute

**Comment by timgaunt** [comment]
This is also something we'd be interested in as the hacks we have in place at the moment are a little hampering

**Comment by LeifDC** [comment]
This would be a very useful feature!

**Comment by darrenbenn-dc** [comment]
This feature would be awesome!!  👍

**Comment by Omenjay** [comment]
Does anyone know when we can expect this release?

**Comment by enrico-padovani** [comment]
This is a log awaited feature, we'd use it immediately!

**Comment by heithvaldr1** [comment]
Очень жду!

**Comment by odinserj** [comment]
Support for seconds implemented in the latest betas of 1.7.0 so you can just pass six-part cron expression and it will work. However, you'll need to tweak the `BackgroundJobServerOptions.SchedulePollingInteval` option correspondingly to avoid extra delays, because default polling interval is 15 seconds.
