### ISSUE TITLE
CommandBatchMaxTimeout supported in .NET Core ? 

### ISSUE THREAD

**Issue by jgrandydev** [HangfireIO/Hangfire#1670]
https://www.hangfire.io/blog/2017/09/20/hangfire-1.6.17.html

States that CommandBatchMaxTimeout is only supported by .NET Framework and not .NET Core.

Is this still true ?

**Comment by odinserj** [comment]
It’s also supported in .NET Core since version 3.0, since corresponded changes in System.Data.SqlClient were implemented only in this version.
