### ISSUE TITLE
Cannot access a disposed object IServiceProvider

### ISSUE THREAD

**Issue by reZach** [HangfireIO/Hangfire#1683]
Upgrading from 1.6.23 to 1.7.11 causes a `Cannot access a disposed object 'IServiceProvider'` error to be thrown in a ASP.NET Core 2.2 application. I am asking this because there does not seem to be [any change](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html) to the JobActivator in the migration guide.

The error is thrown when trying to resolve dependencies with a custom **Hangfire.JobActivator**
```
internal class JobActivator : Hangfire.JobActivator
    {
        private readonly IServiceProvider _serviceProvider;

        public JobActivator(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;

        public override object ActivateJob(Type jobType) => _serviceProvider.GetService(jobType);
    }
```

The configuration is done in Startup.cs, like so:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider serviceProvider)
{
    app.UseHangfireServer(new BackgroundJobServerOptions
    {
        Queues = new string[3] {"", "", ""}, // these are fine
        Activator = new JobActivator(serviceProvider)
    });
}
```

Is there something that also needs to be changed in order to resolve this error? `IServiceProvider` is a framework interface.

**Comment by reZach** [comment]
The fix is to not use a custom Activator, see below:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider serviceProvider)
{
    app.UseHangfireServer(new BackgroundJobServerOptions
    {
        Queues = new string[3] {"", "", ""}, // these are fine
    });
}
```

**Comment by ZubSam** [comment]
Why this `Queues = new string[3] {"", "", ""}, // these are fine` help in this problem 

> _Cannot access a disposed object 'IServiceProvider'_ ?

**Comment by reZach** [comment]
> 
> 
> Why this `Queues = new string[3] {"", "", ""}, // these are fine` help in this problem
> 
> > _Cannot access a disposed object 'IServiceProvider'_ ?

It's not the `Queues` that fixed the issue, it was removing the custom `JobActivator` that fixed the problem.

**Comment by ZubSam** [comment]
> > Why this `Queues = new string[3] {"", "", ""}, // these are fine` help in this problem
> > > _Cannot access a disposed object 'IServiceProvider'_ ?
> 
> It's not the `Queues` that fixed the issue, it was removing the custom `JobActivator` that fixed the problem.
thanks, but if I remove custom JobActivator, how to add DI in job class in asp.net core app ?

**Comment by reZach** [comment]
> 
> 
> > > Why this `Queues = new string[3] {"", "", ""}, // these are fine` help in this problem
> > > > _Cannot access a disposed object 'IServiceProvider'_ ?
> > 
> > 
> > It's not the `Queues` that fixed the issue, it was removing the custom `JobActivator` that fixed the problem.
> > thanks, but if I remove custom JobActivator, how to add DI in job class in asp.net core app ?

It's upgrading to hangfire 1.7.11 that automatically adds the DI into your hangfire jobs, at least in my case the issue was fixed when I removed my customer JobActivator class we were using in hangfire 1.6.23.

**Comment by ZubSam** [comment]
> > > > Why this `Queues = new string[3] {"", "", ""}, // these are fine` help in this problem
> > > > > _Cannot access a disposed object 'IServiceProvider'_ ?
> > > 
> > > 
> > > It's not the `Queues` that fixed the issue, it was removing the custom `JobActivator` that fixed the problem.
> > > thanks, but if I remove custom JobActivator, how to add DI in job class in asp.net core app ?
> 
> It's upgrading to hangfire 1.7.11 that automatically adds the DI into your hangfire jobs, at least in my case the issue was fixed when I removed my customer JobActivator class we were using in hangfire 1.6.23.

thanks
