### ISSUE TITLE
Hangfire how can i clear all data?

### ISSUE THREAD

**Issue by moxixuan** [HangfireIO/Hangfire#1692]
hi,
![图片](https://user-images.githubusercontent.com/19483437/84111661-007a1200-aa5a-11ea-968e-eae206885b83.png)
i want to clear all of this data immediately.
how can i do?

**Comment by FrancoisAR** [comment]
I normally have the following run in a job calling sql sp when starting the server, though should work while running as well from what I've tested. Should do what you're after I think?

essentially resets the server tables.

Although not sure if there are any side-effects on running this against a running server mind you, just test that I guess, but in my case no issues cropped up.

TRUNCATE TABLE [HangFire].[AggregatedCounter]
TRUNCATE TABLE [HangFire].[Counter]
TRUNCATE TABLE [HangFire].[JobParameter]
TRUNCATE TABLE [HangFire].[JobQueue]
TRUNCATE TABLE [HangFire].[List]
TRUNCATE TABLE [HangFire].[State]
TRUNCATE TABLE [HangFire].[Server]
TRUNCATE TABLE [HangFire].[Set]
TRUNCATE TABLE [HangFire].[Hash]
DELETE FROM [HangFire].[Job]

DBCC CHECKIDENT ('[HangFire].[Job]', reseed, 0)
UPDATE [HangFire].[Hash] SET Value = 1 WHERE Field = 'LastJobId'

**Comment by moxixuan** [comment]
> 
> 
> I normally have the following run in a job calling sql sp when starting the server, though should work while running as well from what I've tested. Should do what you're after I think?
> 
> essentially resets the server tables.
> 
> Although not sure if there are any side-effects on running this against a running server mind you, just test that I guess, but in my case no issues cropped up.
> 
> TRUNCATE TABLE [HangFire].[AggregatedCounter]
> TRUNCATE TABLE [HangFire].[Counter]
> TRUNCATE TABLE [HangFire].[JobParameter]
> TRUNCATE TABLE [HangFire].[JobQueue]
> TRUNCATE TABLE [HangFire].[List]
> TRUNCATE TABLE [HangFire].[State]
> TRUNCATE TABLE [HangFire].[Server]
> TRUNCATE TABLE [HangFire].[Set]
> TRUNCATE TABLE [HangFire].[Hash]
> DELETE FROM [HangFire].[Job]
> 
> DBCC CHECKIDENT ('[HangFire].[Job]', reseed, 0)
> UPDATE [HangFire].[Hash] SET Value = 1 WHERE Field = 'LastJobId'

thanks, i have delete the datatable what i'm config, it's useful for me.
