### ISSUE TITLE
Not able to setup always encryption with hangfire

### ISSUE THREAD

**Issue by bharatprajapat11** [HangfireIO/Hangfire#1698]
I am trying to setup always encryption with hangfire i am getting below error `Keyword not supported:Column encryption setting`. you can check detailed error from this image [HangfireError](https://mandatly-my.sharepoint.com/:i:/p/bprajapat/ERhHz69YZENDj8LMGgTI9BkBM6PNdIymG0qj695xdbozZw?e=q8b2ff).

I found may be below as issue,
I setup always encryption and its working perfectly till i enable the Hangfire. If i enable hangfire i am getting error. Which is may be for `Hangfire.SqlServer` package is using `System.Data.SqlClient` for database connections if i am able to use `Microsoft.Data.SqlClient` insted of `System.Data.SqlClient` in `Hanfire.SqlServer` may be this can resolve my issue.
Can you guide me how can i use `Microsoft.Data.SqlClient` i also tried with latest version of `Hangfire.SqlServer`.

Can you guide me how can I fix this or how can i setup always encryption with hangfire?
Thanks.

**Comment by odinserj** [comment]
In Hangfire 1.7.X it is possible to use Microsoft.Data.SqlClient package by using an explicit connection factory as in the following example:

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(
        () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
```

In Hangfire 1.8.X, Microsoft.Data.SqlClient will be used by default if installed into the target project, please see https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#installation for detalis.
