### ISSUE TITLE
Recurring job runs every minute for an hour after initial execution

### ISSUE THREAD

**Issue by Karamethien** [HangfireIO/Hangfire#1704]
The only other thread I found on this topic was 2 years old and has no answers.  So I am posting it here, sorry if I am not supposed to, I am very new to GitHub.

I am using Hangfire.AspnNetCore 1.7.7

and set up a single tally job that is scheduled for 6 hours run time. “* */6 * * *”

However, when it runs, Hangfire will execute the job every minute for the next hour.

I have no idea why it is doing this.

**Comment by Deantwo** [comment]
> * */6 * * *

That sounds correct to me. Did you expect that cron string to do something else?
See: [`https://crontab.guru/#*_*/6_*_*_*`](https://crontab.guru/#*_*/6_*_*_*)
