### ISSUE TITLE
How about a one-time (idempotent) job?

### ISSUE THREAD

**Issue by geirsagberg** [HangfireIO/Hangfire#171]
Scenario: I have some code that I want to run -once- when the application starts, e.g. for a one-time processing of records when publishing a new version.

Would be very cool to do something like this:

```
BackgroundJob.OneTimeJob(action);
```

which would run the job only if it has not been previously run.

Barring this, is there some way to examine the history manually and see if a job has been run?

**Comment by FarshanAhamed** [comment]
In my case, i need to fetch some data from the table and do some calculation on C# and update the database.

I have added a column to the table using SQL script (db-up). The release is configured in a way that database scripts are executing first.

1. Fetch the latitude and longitude of an entity from a table.
2. Calculate the timezone of that location (using other libraries)
3. Update the table with timezone.

Here i can't solve it without C#. So i added a function for this.

Now i have these options

1. Invoke this function inside an API which i have to call after the release.
2. Invoke this function as Background job on Program Startup. Also i should remove this on next release to avoid executing this again.

For me the one-time job would be better. 

`BackgroundJob.OneTimeJob(action);` or even if `RecurringJob` with Cron expression accepting `Cron.OneTime` would do.
