### ISSUE TITLE
Upgrading Hangfire to .Net Core causing multiple recurring job instances

### ISSUE THREAD

**Issue by JesterMalone** [HangfireIO/Hangfire#1738]
We have upgraded our Hangfire to the latest .net core version 1.7.13 as well as using the latest SQL Server package and suddenly our recurring job is now spawning multiple instances.  We have three servers running and each server instance is now creating up to five instances of the recurring job.  This is creating heavy load with the contents of the job and cause server CPU spikes which is impacting us heavily.  

We have three IIS hosted .net core nodes running as InProcess of the same service with a hangfire recurring job to clean up bad phone numbers from carrier disconnects.   

With the upgrade we did see the server instances duplicate our servers with an extra instance as well and so we believe there is an issue with our set up but not sure what we are doing wrong. 

I am not sure what else to provide.  I am relatively new to hangfire and what i have inherited.

![image](https://user-images.githubusercontent.com/12864761/93358907-4552d900-f7ff-11ea-9280-083d02780c7b.png)

![image](https://user-images.githubusercontent.com/12864761/93358983-58fe3f80-f7ff-11ea-932b-21a6f94f9df5.png)

Where job is scheduled:
![image](https://user-images.githubusercontent.com/12864761/93359078-6ddad300-f7ff-11ea-83f6-9bfaeb12a16a.png)

**Comment by odinserj** [comment]
Please show us your configuration logic related to Hangfire and include some dashboard screenshots (corresponding job details page with state transitions, recurring jobs page, servers page) that highlight the issue.

**Comment by JesterMalone** [comment]
Found our issue was around someone who was trying to do sub minute stuff with Cron.  They added extra vars in our cron expressions which broke us.

 

        /// <summary>
        /// Returns cron expression that fires every minute.
        /// </summary>
        public static CronExpression Minutely()
        {
            return new CronExpression("* * * * * *");
        }


versus what works: 

    public static CronExpression Minutely()
        {
            return new CronExpression("* * * * *");
        }
