### ISSUE TITLE
Database Schema Changes For UseIgnoreDupKeyOption 

### ISSUE THREAD

**Issue by danstur** [HangfireIO/Hangfire#1739]
With Hangfire 1.7.13 a new option UseIgnoreDupKeyOption  was added (see commit 1edef17c). The release notes mention "changes to [Set] and [Hash] tables required". But the Install.sql script was not changed and I find mention of `IGNORE_DUP_OPTION` only in comments but nowhere in a SQL script/code. 

It seems like the flag is supposed to be called `IGNORE_DUP_KEY` when looking at the actual code, but I still don't see where that database schema change would be done.

Is the script missing or what do I have to do to be able to enable that feature?

**Comment by odinserj** [comment]
IGNORE_DUP_KEY option should be added for primary keys of those tables before using the feature, otherwise some "upsert" queries will constantly fail with duplicate key violation. I'm planning to add these options to 1.8 migration, but still don't want to change anything automatically between patch versions.

```sql
ALTER TABLE [HangFire].[Hash] REBUILD WITH (IGNORE_DUP_KEY = ON)
ALTER TABLE [HangFire].[Set] REBUILD WITH (IGNORE_DUP_KEY = ON)
```

**Comment by danstur** [comment]
Thanks for the quick reply. In this case we'll just wait for the 1.8 release to update with the new install.sql script.

**Comment by odinserj** [comment]
Could you tell me more about the problem you have?

**Comment by danstur** [comment]
Not a problem, we were just wondering about the "changes to [Set] and [Hash] tables required" comment in the release notes. 

Since we cannot use the automatic migration in code, we have to include the SQL migration script whenever changes to the database schema are necessary. We interpreted the comment above that there had been a schema change and were confused why we couldn't find these changes in the Install.sql script.
