### ISSUE TITLE
Performance Issue on Job List Page

### ISSUE THREAD

**Issue by jcspader** [HangfireIO/Hangfire#1742]
Hi

I'm having performance issues when listing the failed jobs on the dashboard.
When analyzing the queries in the SQL Profile and the source, I noticed that the problem is due to the loading of column [State].[Data].

![image](https://user-images.githubusercontent.com/1699660/94353403-33ff9d00-0047-11eb-8111-7d03d3d55248.png)

- Trial 1: (52 sec) - with [State].[Data] column on query.
- Trial 2: (6 sec) - without [State].[Data] column on query.

I'd like suggest to change the jobs list page to use Ajax to load the details information. 
Details information is not always displayed which is a waste of processing and loading on demand makes more sense.

![image](https://user-images.githubusercontent.com/1699660/94353456-b8522000-0047-11eb-955b-7f5a9406c880.png)

Is there an adjustment process in way?
I can try to help.

**Comment by odinserj** [comment]
Thanks for sharing information about this problem. Could you also send an example of what's being serialised into the `StateData` column? I believe very large stack traces are causing the issue, but need to understand how do the look first. Ajax support is great, but I'm afraid it requires some breaking changes to be made first, and there's a chance we can do something to decrease payload size instead.

**Comment by jcspader** [comment]
This is a sample of [State].[Data].

`{"FailedAt":"1601057486501","ExceptionType":"Microsoft.Data.SqlClient.SqlException","ExceptionMessage":"Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.","ExceptionDetails":"Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.\r\n ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.\r\n   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)\r\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)\r\n   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)\r\n   at WS.EIS.Application.Integracao.Middleware.VetorSistemas_Tray.IntegracaoVetorSistemasTray.ImportProdutos()\r\n   at WS.EIS.Application.Integracao.Middleware.VetorSistemas_Tray.IntegracaoVetorSistemasTray.RunStore() in R:\\WS\\wseis\\Fontes\\WS.EIS.Application\\Integracao\\Middleware\\VetorSistemas_Tray\\IntegracaoVetorSistemasTray.cs:line 195\r\n   at WS.EIS.Application.Integracao.MotorIntegracao.RunJobStore(Guid id_integration, PerformContext performContext) in R:\\WS\\wseis\\Fontes\\WS.EIS.Application\\Integracao\\MotorIntegracao.cs:line 121\r\nClientConnectionId:13be8804-5f3d-421a-8d16-9e8e0e9f1946\r\nError Number:-2,State:0,Class:11"}`

**Comment by odinserj** [comment]
Thank you for details Julio. Hm, I can't say this stack trace is huge, may be there are other stack traces, much larger?

**Comment by odinserj** [comment]
Julio, I see that number of bytes received from server on the first try is really, really large, so some of your failed jobs have huge stack traces. To avoid uncontrollable sizes, I've just added the `IGlobalConfiguration.UseMaxLinesInExceptionDetails` and capped the number of stack traces for exceptions to 100 by default. Changes will be released with 1.7.15 tomorrow.
