### ISSUE TITLE
Replace Performance Counters wih Event Counters in .net core

### ISSUE THREAD

**Issue by AndiRudi** [HangfireIO/Hangfire#1747]
I think the Performance Counters of Hangfire Pro are no supported in .net core so they should be updated to event counters?

Similiar question: https://discuss.hangfire.io/t/performance-counters-in-core/5564
MS Blog Post: https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/

**Comment by odinserj** [comment]
Please check this GIST – https://gist.github.com/odinserj/975b05848c728df3daf79015c542e8b6. These counters are much easier to implement and use than performance counters, so they are available under the MIT License.
