### ISSUE TITLE
Recurring job not getting executed on Start Date Time

### ISSUE THREAD

**Issue by shefalivashishtha** [HangfireIO/Hangfire#1748]
Need help in fixing the below issue.
When we configure a weekly/monthly/daily recurring job, the job doesn't get executed on the provided start date. For example, I've a job which should start from 1st September and should recur on every 1st of following months for a year or so. This job gets created on 1st September but doesn't get executed and populates 1st October as its next execution date. The job thereafter works as expected. Is there any configuration that I might be missing or is this the expected behavior ?

**Comment by mellamokb** [comment]
I believe that would be expected.  Recurring jobs start on the next available time in the future. If you are scheduling the job in the middle of the day on 1st September, but it is set for beginning of the day on the 1st of each month (midnight), technically 1st September schedule is now in the past so the next available time is 1st October.

In that case your best bet is probably to manually trigger the job using RecurringJob.Trigger("some-id") immediately after it is created, to make sure it is run right away.

(see: https://docs.hangfire.io/en/latest/background-methods/performing-recurrent-tasks.html)
