### ISSUE TITLE
Decouple Microsoft.Extensions.DependencyInjection from AspNetCore?

### ISSUE THREAD

**Issue by dahlbyk** [HangfireIO/Hangfire#1751]
Would you be open to a PR that introduces `Hangfire.DependencyInjection` to decouple basic service registration (`AddHangfireCore()`?) from AspNetCore? I'm not sure familiar with Hangfire internals, but I'd be glad to give it a shot.

From https://github.com/arex388/Arex388.AspNet.Mvc.Startup/ by @arex388:

> The only annoyance I've had so far is with HangFire's IServiceCollection extensions because they're in the HangFire.AspNetCore NuGet package and that force's a bunch of other NuGet packages to be added in.

**Comment by odinserj** [comment]
There's also more lightweight package Hangfire.NetCore with fewer dependencies than Hangfire.AspNetCore. Did you consider to use it instead?

**Comment by dahlbyk** [comment]
> There's also more lightweight package Hangfire.NetCore with fewer dependencies than Hangfire.AspNetCore. Did you consider to use it instead?

I didn't notice that, but the actual context for that project (and my own needs) is a NetFx project using MS DI to ease future migration.

**Comment by odinserj** [comment]
Unfortunately `Hangfire.MicrosoftExtensions` and `Hangfire.Extensions` aren't great names too 😁

**Comment by dahlbyk** [comment]
In case anyone else runs into the same issue I had: if it seems like the configuration delegate passed to `services.AddHangfire()` isn't called, you're right. It waits until an `IGlobalConfiguration` is resolved.

For full ASP.NET Core that's part of `app.UseHangfireDashboard()`, `endpoints.MapHangfireDashboard()`, or `app.UseHangfireServer()` (via [`ThrowIfNotConfigured`](https://github.com/HangfireIO/Hangfire/search?q=ThrowIfNotConfigured&type=code)).

Otherwise, you need to `ServiceProvider.GetRequiredService<IGlobalConfiguration>()` or equivalent before you wire up the dashboard/server.

I also found when starting my server that I needed to specifically set its `Activator`, i.e.

```csharp
            app.UseHangfireServer(new BackgroundJobServerOptions
            {
                // Uses AspNetCoreJobActivator registered by services.AddHangfire()
                Activator = ServiceProvider.GetService<JobActivator>(),
            });
```

I was surprised that didn't Just Work. Thoughts?
