### ISSUE TITLE
Job run unexpected when use seconds job(Cron expression)

### ISSUE THREAD

**Issue by zhaobingwang** [HangfireIO/Hangfire#1756]
My code is here: 
```csharp
RecurringJob.AddOrUpdate(() => TestRecurringJob(), "*/10 * * * * *", TimeZoneInfo.Utc)
```
The result is: the job always runs every 15 seconds, something wrong in my code?

**Comment by djl394922860** [comment]
because schedule poll interval is default 15 s

**Comment by zhaobingwang** [comment]
My expectation is to perform the task every 10 seconds, How do I modify my code to make it work?

**Comment by djl394922860** [comment]
> My expectation is to perform the task every 10 seconds, How do I modify my code to make it work?

`x.SchedulePollingInterval = TimeSpan.FromSeconds(1);`  will be worked

**Comment by djavier** [comment]
This can be considered as closed!
