### ISSUE TITLE
Not firing at the correct time.

### ISSUE THREAD

**Issue by ejbrennan** [HangfireIO/Hangfire#1758]
I have used Hangfire successfully for years, has always been rock solid for me - I generally use it to fire off about a dozen +/- recurring jobs that occur at various frequencies during the day (i.e. once a day, one every 5 minutes, every day at 4AM) etc, and in my experience jobs always fire at almost the exact right time - within a few seconds.

I created a brand new console application yesterday, and installed all the newest nuget packages (using .net 4.8)

I created a single, simple recurring job that fires every 5 minutes, and all it does it write the execution timestamp to a text/log file.

When I run the application in Visual studio - it runs/fires perfectly - every 5 minutes like clockwork it fires.

If I compile the application, and run it as a console application - it immediately starts running at random intervals from 15 to 75 seconds - with no rhyme or reason.

Has anyone experience this type of issue before?

**Comment by odinserj** [comment]
Please send screenshots – with recurring jobs page, with state transitions of background jobs with wrong timings to see what's going. Also, what storage are you using and what's the configuration logic related to Hangfire you have in this sample application?

**Comment by ejbrennan** [comment]
My apologies, looks like it was an unrelated piece of code that was throwing a permissions related exception, which re-queued the job repeatedly at random times. When I fixed the exception, my tasks are running on time. In VS it was running with a different set of permissions.

**Comment by odinserj** [comment]
Thanks for update!
