### ISSUE TITLE
Issue with SqlServer 2008r2

### ISSUE THREAD

**Issue by noxe** [HangfireIO/Hangfire#1759]
Hi Guys,

we started using Hangfire - but we see an problem where one customer has an SQL Server 2008 R2. (The Documentation says Supported database engines Microsoft SQL Server 2008R2)

JobStatus cannot be changed correctly because of an SqlException:

System.Data.SqlClient.SqlException: Falsche Syntax in der Nähe von 'throw'.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bei Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   bei Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   bei Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   bei Hangfire.SqlServer.SqlServerConnection.<>c__DisplayClass10_0.<SetJobParameter>b__0(DbConnection connection)
   bei Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass32_0.<UseConnection>b__0(DbConnection connection)
   bei Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   bei Hangfire.AutomaticRetryAttribute.ScheduleAgainLater(ElectStateContext context, Int32 retryAttempt, FailedState failedState)
   bei Hangfire.States.StateMachine.InvokeOnStateElection(Tuple`2 x)

Looking at sql profiler and hangfire source code it seems the "throw" statement is used - which seems to be not supported by sql 2008 - any ideas?

Executed SQL:

exec sp_executesql N'
set xact_abort off;
begin try
  update [HangFire].JobParameter set Value = @value where JobId = @jobId and Name = @name;
  if @@ROWCOUNT = 0 insert into [HangFire].JobParameter (JobId, Name, Value) values (@jobId, @name, @value);
end try
begin catch
  IF ERROR_NUMBER() not in (2601, 2627) throw;
  update [HangFire].JobParameter set Value = @value where JobId = @jobId and Name = @name;
end catch',N'@jobId bigint,@name nvarchar(4000),@value nvarchar(4000)',@jobId=37,@name=N'RetryCount',@value=N'1'

**Comment by odinserj** [comment]
Hi, just upgrade to the latest version, this issue was fixed.

**Comment by noxe** [comment]
great - thx for the fast response! have not noticed the new release!
