### ISSUE TITLE
Hangfire job history is bloating memory due to  semaphore job rescheduling

### ISSUE THREAD

**Issue by CBlaize** [HangfireIO/Hangfire#1770]
I am using `Hangfire.Redis`.

I have thousands of jobs in a queue that are limited by a semaphore.

It appears that every second, hangfire will add an entry to the "history" key if the job cannot be enqueued because of the semaphore.

![image](https://user-images.githubusercontent.com/6540262/100275418-806f3800-2f25-11eb-97fd-a88bcbf8d7e5.png)

As you can see from the picture, there are 500+ entries in the history key for this one job, and I have thousands of jobs like this.  I believe this to be the cause of my bloated memory problem.

I do not require the entire history state to be kept in Redis.  Is there a way to remove these keys, limit how many gets inserted, or change the interval at which jobs are attempted to be requeued?

Any help is much appreciated, thank you!

**Comment by chendingqi** [comment]
yes

**Comment by odinserj** [comment]
Thanks for reporting. I've already though about it, so was able to implement the change quickly, please see release notes for version 2.8.4 – https://www.hangfire.io/blog/2020/11/26/hangfire.pro.redis-2.8.4.html, the new version is already available.
