### ISSUE TITLE
Race condition in AspNetShutdownDetector

### ISSUE THREAD

**Issue by jr01** [HangfireIO/Hangfire#1784]
We have concurrent unit tests that sometimes fail in [AspNetShutdownDetector.cs](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/AspNetShutdownDetector.cs) with: 
```
Error Message:
--
Unable to create instance of class App.Test.BackgroundTaskTest. Error: System.NullReferenceException: Object reference not set to an instance of an object..
Stack Trace:
at Hangfire.Server.AspNetShutdownDetector.GetShutdownToken()
```

**root cause**
```C#
public static CancellationToken GetShutdownToken()
{
    EnsureInitialized();
    return _cts.Token;
}

private static void EnsureInitialized()
{
    if (Interlocked.Exchange(ref _isInitialized, 1) != 0) return;

    try
    {
        _cts = new CancellationTokenSource();
```

Imagine 2 parallel unit tests (threads) that both execute `GetShutdownToken()` at roughly the same time.
Thread 1 reads and sets `_isInitialized` to 1 but hasn't executed `_cts = new CancellationTokenSource()` yet.
Thread 2 reads `_isInitialized` and it's now 1 so it tries to read `_cts.Token` resulting in the `System.NullReferenceException`.

**workaround**
The workaround for us is easy by setting these tests to `[DoNotParallelize]`

**solution**
A simple fix could be to move creating the _cts:
```C#
private readonly static CancellationTokenSource _cts = new CancellationTokenSource();
```

Let me know if you'd like a PR that fixes that!

( I do find it very strange that there is an `AspNetShutdownDetector` in Hangfire, in my mind that shouldn't be a Hangfire concern. )

**Comment by odinserj** [comment]
Great catch, @jr01, will be happy to get PR to fix this bug!
