### ISSUE TITLE
HangfireServiceCollectionExtensions ASP.NET reference

### ISSUE THREAD

**Issue by domagojmedo** [HangfireIO/Hangfire#1790]
Why are AddHangfireServer and AddHangfire in ASP.NET Core package?

I understand if we want to use Dashboard then it has to depend on ASP.NET, but just queueing and executing jobs shouldn't require ASP.NET reference to be introduced in the system

Because of that if we are using worker service as processing server it has to take dependency on ASP.NET which shouldn’t be needed.

**Comment by odinserj** [comment]
For worker services please use the `Hangfire.NetCore` package – unfortunately it wasn't clear there will be a worker template in the early days of Hangfire.AspNetCore package. Also, `AddHangfire` will configure everything for using Hangfire – including storage, service registrations, etc, and `AddHangfireServer` will only register background job server as ASP.NET Core's `IHostedService`.

**Comment by domagojmedo** [comment]
Didn't know Hangfire.NetCore package existed, that fixes my issue.
