### ISSUE TITLE
Allow creating any job with a specific job id

### ISSUE THREAD

**Issue by andersme** [HangfireIO/Hangfire#181]
My current need is a way to associate jobs running in Hangfire to certain objects in our system. We do this using Quartz.NET by setting the JobKey to an Id of an object in our system so we can reference it in the future (for cancelling or rescheduling the job). Would be awesome if there was a way to do this in HangFire. It is the only holding us back from using this in our system.

**Comment by Tho77** [comment]
This seems to be a common use case for us. We want to schedule a job to run at some point in the future, but we also want to be able to find and delete that job before it runs.
Without being able to specify a job name for a scheduled job, we can't go back to look for it to remove/update it.

At the moment we are creating a recurring job to run at the point in time in the future, which then deletes itself from the recurring job list the first time it runs.

**Comment by gandarez** [comment]
Do you mean manual starting job?

**Comment by Tho77** [comment]
Yes
`BackgroundJob.Schedule(() => Console.WriteLine("Hello, world"), TimeSpan.FromDays(1));`

**Comment by gandarez** [comment]
@Tho77 it's totally possible in the latest version I'm using.
If you want something just manual you can take a look at my post into the forum
https://discuss.hangfire.io/t/introducing-the-new-manual-state/1600

**Comment by dominikfoldi** [comment]
@odinserj there are no `SetEntryInHash` and `GetValueFromHash` methods for `IStorageConnection` in Hangfire 1.7.2 but as I see by browsing the repo never have been neither in earlier versions of Hangfire.

Can I use `SetRangeInHash` and `GetAllEntriesFromHash` for the same purpose?

**Comment by elepner** [comment]
I'm struggling the same way as @dominikfoldi does. How can I get ``jobId`` using ``key``?

**Comment by alexandis** [comment]
> 

Probably it has to look something like this?

    public class AddEnqueuedJobKeyFilterAttribute : JobFilterAttribute, IApplyStateFilter
    {
        public AddEnqueuedJobKeyFilterAttribute()
        {
        }

        public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            if (context.NewState is EnqueuedState)
            {
                transaction.AddToSet("customKey", "your_custom_key_value");
                transaction.Commit();
            }
        }

        public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            // TODO
        }

**Comment by mhkolk** [comment]
Soo, this is old and all but let me get it straight. We're allowed to create reccurring jobs with passed in ID but not schedule/enqueue regular, fire&forget jobs with our own IDs? And there is a whole page explanation of various workaround bc of the oversight that happened when designing thinking people won't need to provide IDs to F&F jobs?

**Comment by alen-resser** [comment]
> Soo, this is old and all but let me get it straight. We're allowed to create reccurring jobs with passed in ID but not schedule/enqueue regular, fire&forget jobs with our own IDs? And there is a whole page explanation of various workarounds bc of the oversight that happened when designing thinking people won't need to provide IDs to F&F jobs?

this is absolutely silly. i have a reccuring job that enqueues many F&F jobs, now, this job runs every night and i have no way to tell if some of those F&F jobs have been executed or not. well, at least not easily, with an id that could be added to the f&f job. 
has there been any proper solution to this besides all the hacky stuff recommended above?
