### ISSUE TITLE
Jobs fail after 10 retries with exception: Cannot insert duplicate key

### ISSUE THREAD

**Issue by JljHook** [HangfireIO/Hangfire#1820]
Hi,
After updating to 1.7.19 version we started to suffer from extremely long latencies. We found out that after 10 retries this exception happens:
Cannot insert duplicate key row in object 'HangFireProd.Counter' with unique index 'CX_HangFire_Counter'. The duplicate key value is (stats:succeeded
We are hosting in Azure App Service with 2 instances.
Is there some configuration we have missed?

**Comment by odinserj** [comment]
Duplicates #1672, please see https://github.com/HangfireIO/Hangfire/issues/1672#issuecomment-785101816
