### ISSUE TITLE
Provide current job details through dependency injection

### ISSUE THREAD

**Issue by rossknudsen** [HangfireIO/Hangfire#1822]
I'm looking for a solution that would allow job details (job ID etc) to be made available by dependency injection.  This means it would be possible to depend on an abstraction in the constructor of a service rather than having to depend on `PerformContext` as an argument in the service method.  That way we don't need Hangfire specific dependencies in the service interfaces.

```cs
// job definition
interface IProcessor
{
    void Execute();
}

// enqueue
BackgroundJob.Enqueue<IProcessor>(j => j.Execute());

// preferred implementation
class Processor
{
     private PerformContext context;

     Processor(PerformContext context)
     {
         this.context = context;
     }

     void Execute()
     {
          // TODO
     }
}
```

Now whether the provided dependency is exactly `PerformContext` or a slightly different type, doesn't really matter.  I'm happy to raise a PR for this feature if it is something that is consistent with the direction of Hangfire.  But if it would never be accepted, I won't bother wasting time.  I have an idea on how to implement.

I primary reason this would be useful is to make it simpler to use the built in logging functionality of AspNetCore (i.e. `ILogger`).  Having a custom logger depend on the job details would make it possible to log out to the Dashboard using something similar to Hangfire.Console.

**Comment by Frazi1** [comment]
There is a way to make it work already. Check how https://github.com/AnderssonPeter/Hangfire.Console.Extensions library is implemented. If you need that feature right away, you can build logic similar to Hangfire.Console.Extensions for your specific case.
- https://github.com/AnderssonPeter/Hangfire.Console.Extensions/blob/07768b4a5446ab50e24e39874cefba16e145c00c/Hangfire.Console.Extensions/HangfireSubscriber.cs
- https://github.com/AnderssonPeter/Hangfire.Console.Extensions/blob/07768b4a5446ab50e24e39874cefba16e145c00c/Hangfire.Console.Extensions/IPerformingContextAccessor.cs

However, I agree that it should be supported in Hangfire out-of-the-box to make it more convenient for everyone.

**Comment by rossknudsen** [comment]
The `Hangfire.Console.Extensions` package seems to do what I want without any further config.  Thanks for the heads up.  Although I might need to configure the colors to be more readable.

**Comment by Borc92** [comment]
Source code from `Hangfire.Console.Extensions` project is really helpful to get PerformContext via DI instead.
Thank you @Frazi1! 
This should definitely be in Hangfire by default.
