### ISSUE TITLE
The logging of the the general health of the Hangfire server

### ISSUE THREAD

**Issue by yong2khoo-lm** [HangfireIO/Hangfire#1824]
Perhaps this is a general question, not only to Hangfire.
Today, my colleagues told me that, our production Hangfire is down, without knowing what happened.
The way to resolve, is to restart the Azure App Service.

I am aware of the [logging documentation](https://docs.hangfire.io/en/latest/configuration/configuring-logging.html). But I am curious, is the logging able to log the general health of the Hangfire server?
Such that, if the server crashes, there is logging under the hood. A minimal logging to a text file will do.

Or, the Logging is to be used by us in the application codes. It only captures if we specifically execute `Log.Debug`... etc

**Comment by Frazi1** [comment]
Do you mean that the whole application was down? Or was the app working, but Hangfire wasn't?

I'm not sure how "general health" term is applicable to Hangfire, but here some thoughts.

### Hangfire logs
You can try enabling Hangfire logs. As explained on the documentation page, Hangfire relies on a logging abstraction. With that, you can set up any type of logging (file, console, azure logs, etc). For file logging, take a look at Serilog or NLog libraries.

If there are some Hangfire internal issues, you will probably discover them under `Warning` level and higher.

Enabling `Debug` log level from `Hangfire` will give you access to heartbeat logs. In Hangfire, worker servers send heartbeat messages every `x` seconds (depending on configuration). If a server hasn't been reporting heartbeats for a while, most likely it is dead. But that is not always true. For example, under 100% CPU usage, heartbeat threads may not get any CPU time, so no heartbeats might be reported while the server is actually working.
In some cases, Hangfire logs maybe enough.

That's for Hangfire itself.

### Other types of issues
Again, I'm not sure what "general health" is. An application may have different kind of issues. For example, high memory consumption. If your app crashes with an out-of-memory error, Hangfire will not catch that. For catching an out of memory, it is better to look at system logs. Such issues are usually reported at system level. 

You can also try seting up a global error handler for your app to log unhandled exceptions leading to app crash. But this is not related to Hangfire.

**Comment by yong2khoo-lm** [comment]
Thanks @Frazi1 for the suggestions!
Yes, I do mean "High CPU usage", "High Memory Usage", "Hangfire Internal issues", or etc that potentially bring down the server. (which you have mostly covered)

So, from my understanding, after the "setup", I would be mostly able to tell, what are the potential issues in the last moment. (Except out-of-memory, which, as mentioned, is reported at system level)

I shall re-visit this again next week, and close it if i make it :)
