### ISSUE TITLE
setup example without owin?

### ISSUE THREAD

**Issue by wingyiu** [HangfireIO/Hangfire#183]
i really dont need owin, any example?

**Comment by scinfu** [comment]
i have the same problem but i can't remove Owin , the error is 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to uninstall 'Microsoft.Owin.Host.SystemWeb.3.0.0' because 'Hangfire.1.5.4' depends on it.			0	
```

**Comment by odinserj** [comment]
@scinfu, you can't remove OWIN, Hangfire depends on it. Why do you want to remove it?

**Comment by scinfu** [comment]
I'm trying to not use it because i do not need it, 
but at the end i use it .
Thank you.
you can close this issue.

**Comment by odinserj** [comment]
Okay. I've thought about removing it, but this will cause Hangfire's Dashboard to be moved to another package. This step will make things more complicated.

**Comment by scinfu** [comment]
we all appreciate your hard work. Thank you

**Comment by Dynalon** [comment]
Just for future reference (this issue is ranked very high at google): I could get HangFire to run without removing the OWIN Assemblies but rather disabling OWIN startup configuration by putting this into the `web.config`:

    <add key="owin:AutomaticAppStartup" value="false" /> 

I am bound to the ASP.NET pipeline as I am using a framework that does not support OWIN. Using the `web.config` entry above did it for me.

**Comment by odinserj** [comment]
@Dynalon, what framework are you using? ASP.NET fully supports OWIN via `Micsoroft.Owin.Hosting.SystemWeb` package.What problem did you have?

**Comment by Dynalon** [comment]
I'm using [ServiceStack](https://servicestack.net) which has no OWIN support and [possibly might never get it](https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/4851342-owin-compatible-servicestack)

**Comment by odinserj** [comment]
`Hangfire.Core` package have reference only to the `OWIN` package that contains only the `IAppBuilder` interface. Looks like you've installed the `Hangfire` package (it is for ASP.NET setups) that depends on `Hangfire.Core` `Hangfire.SqlServer`, **`Microsoft.Owin.???`** packages.

If this is true, just remove `Hangfire` and all `Microsoft.Owin.*` packages, keep the others (Hangfire.Core and Hangfire.StorageYouUse), and use the `BackgroundJobServer` class directly. There still be a reference to the `OWIN` package, but once again, it only contains a single interface.

Hangfire itself (`Hangfire.Core` package) don't require OWIN.

**Comment by yassira6** [comment]
Removing owin startup class will help in using impersonation in order to connect to SQL DB. Because owin startup class configuration function is triggered before the impersonation happens.
