### ISSUE TITLE
Migrate Schema to .Net Core?

### ISSUE THREAD

**Issue by ryburn52** [HangfireIO/Hangfire#1836]
We're in the process of upgrading our codebase to .net core from .net 4.7.  We noticed that there are some slight differences when we create a new Hangfire SQL Server database to when we Run it on an existing. 

For example, left is a New DB and right is an Existing DB. Bother are after running Hangfire.SqlServer 1.7.17
![image](https://user-images.githubusercontent.com/643962/113646913-60623900-96bc-11eb-91a1-77e74126b731.png)
 
Our previous hangfire version was 1.7.2 but i can't seem to see any info on database migrations. Everything still seems to be running ok but is there some sort of migration we should be using?

**Comment by odinserj** [comment]
Migrations are added in new minor versions (like 1.6.0 and 1.7.0) to fix bugs (including the possible ones), but they are optional to support backward compatibility, when upgrade is performed step by step, not all the machines simultaneously.

Looks like that setup is still using the 5th schema (select * from HangFire.Schema can confirm this) from Hangfire 1.6 or below. Please see https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#migrating-the-schema for upgrade guide, and I highly recommend to eventually upgrade to the latest schema version.

And I highly discourage you from using external automatic comparators or migrators based on such diffs. Always use Hangfire's own migration script https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/DefaultInstall.sql it's always here for the latest released version.

**Comment by ryburn52** [comment]
Thanks, that's what i was looking for, the dif was mainly for our Entity Framework migration to EF core but noticed these as well.
