### ISSUE TITLE
1.7.21 svg fonts is lost..

### ISSUE THREAD

**Issue by nsnail** [HangfireIO/Hangfire#1844]
Request URL: http://xxxxxxx:5000/fonts/glyphicons-halflings-regular.ttf
Request Method: GET
Status Code: 404 Not Found

**Comment by Plasma** [comment]
Yes, it looks like the fonts have disappeared and so the icons on buttons in the dashboard etc are now gone.

**Comment by odinserj** [comment]
Thanks for reporting this. This is a regression after upgrading Bootstrap to 3.3.7 – I forgot that font URLs were changed in the past to fix this issue and problem with MIME types in IIS. I've made the corresponding changes and will release 1.7.22 as soon as possible. Sorry for the troubles.

**Comment by odinserj** [comment]
New version is already available, please upgrade.
