### ISSUE TITLE
Dashboard graphical issue: Recurring job table doesn't handle very long cron strings

### ISSUE THREAD

**Issue by piaste** [HangfireIO/Hangfire#1859]
We recently tried setting a job to run every 5 minutes, except between 08:00 and 09:00. `*/5 0-7,9-23 * * *`

This creates an annoying graphical glitch when Hangfire expanded the cron string into individual values:

![image](https://user-images.githubusercontent.com/12280683/118101238-a99e5a80-b3d7-11eb-8697-8e0ae66b1124.png)

**Comment by odinserj** [comment]
Thanks for reporting, will be fixed in 1.7.23!
