### ISSUE TITLE
Recurring job overwriting jobs calling same method with different arguments

### ISSUE THREAD

**Issue by zdjohn** [HangfireIO/Hangfire#186]
Problem:
in RecurringJob.cs line 98

``` c#
private static string GetRecurringJobId(Job job)
        {
            return String.Format("{0}.{1}", job.Type.Name, job.Method.Name);
        }
```

Key is formated by type and name, there for, the argument is ignored. 
as a result, in my code, JobsExecutor saves job details into db first then pass its reference id onto RecurringJob. if I call code below multiple times:

``` c#
RecurringJob.AddOrUpdate<JobsExecutor>(x => x.Execute(referenceId), job.Cron.ToCronString());
```

the previous jobs will be overwrittern (updated instead of added) even they could be completely different jobs.

**Comment by biapar** [comment]
The problem is still open.

**Comment by biapar** [comment]
Bypass the problem with ID...

RecurringJob.AddOrUpdate("FireDaily-"+parameter+"-xyz",() => service.xyz(parameter), Cron.Daily);

**Comment by saidalsaidi** [comment]
how to show actionresult when hangfire recurringjob done?
