### ISSUE TITLE
Hangfire not working in Mono

### ISSUE THREAD

**Issue by aikkian** [HangfireIO/Hangfire#1864]
Caught this error when using Visual Studio Mac(mono 6.12.0.125), these are the packages used in the project:
Hangfire.Core (1.7.22)
Hangfire.SqlServer (1.7.22)
Hangfire.AspNet (0.2.0)

It throws an error when execute this line of code:
 BackgroundJob.Enqueue(() => Debug.WriteLine("Hello world from Hangfire!"));

Error:
System.NotImplementedException at System.Transactions.Transaction.EnlistPromotableSinglePhase
(System.Transactions.IPromotableSinglePhaseNotification 
promotableSinglePhaseNotification, System.Guid promoterType) 

![image](https://user-images.githubusercontent.com/1859012/119636957-bbf0ad80-be47-11eb-877d-770214a4f753.png)

Just checked from StackOverFlow, I think this guy experienced the similar issue:
https://stackoverflow.com/questions/63571309/hangfire-system-notimplementedexception-on-any-background-job

If we run the same project in Windows, VS 2019, it works like a charm!

**Comment by aikkian** [comment]
I found a way to resolve this, download the source and modify Hangfire.SqlServer project file. Remove the FEATURE_TRANSACTIONSCOPE then rebuild the project.

**Comment by odinserj** [comment]
`ObjectDisposedException` described in this issue – https://github.com/mono/mono/issues/16440 – is another source of problems with Mono. Looks like something was changed in the recent versions, but I've just commit a change to stop using `TransactionScope` on non-Windows platforms, so buggy code will not be used anymore. I will try to release the changes with 1.7.23 tomorrow.
