### ISSUE TITLE
Trying to use Managed Identity Authentication for Azure SQL Server doesn't work

### ISSUE THREAD

**Issue by mhintzke** [HangfireIO/Hangfire#1879]
Our team has moved all of our SQL Server authentication to use Managed Identity, but when I try to use the same Connection String with Hangfire I run into the issue that is spoken of in #1827 and #1514, however, the workaround that is provided there does not seem to work in my case. 

Where is what I have

![image](https://user-images.githubusercontent.com/8990993/121962874-2c3f7000-cd1e-11eb-9976-edffc4ffd43e.png)

I still get this when trying to schedule a job

![image](https://user-images.githubusercontent.com/8990993/121962743-01551c00-cd1e-11eb-8d70-47aefa2dd421.png)

```
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
```

**Comment by fb5000** [comment]
A solution was provided in the following issue: #1827
