### ISSUE TITLE
Feature: Option to hide "Back to site" on Dashboard

### ISSUE THREAD

**Issue by msallin** [HangfireIO/Hangfire#1881]
I would like to introduce an option (boolean flag) to hide the Link "Back to site" on the Hangfire Dashboard.
I'm going to drop a PR with this, if you approve.

Context:
We built a "Scheduler" for our microservice architecture based on Hangfire.
The Scheduler receives the configuration to invoke certain HTTP endpoints or send Kafka/RabbitMQ/MQTT-messages either by using the custom REST API or by Kafka.
As we are using Hangfire as a standalone application there is no site to go back to we would like to hide the link.

**Comment by walizada** [comment]
@msallin Did you try the AppPath Dashboard options setting? [AppPath](https://api.hangfire.io/html/P_Hangfire_DashboardOptions_AppPath.htm)

I know it's not direct but it achieves the same purpose if you set the value to Null.

**Comment by msallin** [comment]
Works... Ty!
