### ISSUE TITLE
All missed recurring jobs not running on server restart

### ISSUE THREAD

**Issue by prichakraborty09** [HangfireIO/Hangfire#1891]
Hi,

I have a recurring job setup that should execute every 5 mins like this :-

recurringJobManager.AddOrUpdate("Run every 5 minutes",
                () => serviceProvider.GetRequiredService<IEmail>().CreateEmail(),
                "*/5 * * * *"
                );

I had stopped the server for 15 minutes. On restarting the server, the job automatically ran once. I was expecting that it will run for all the 3 missed schedules (in 15 mins) instead of 1. Is that an expected behaviour ? Is there a way hangfire can run all the missed schedules during server down-time ?

Thanks
PC

**Comment by Frazi1** [comment]
>Is that an expected behaviour ?

Yes.

>Is there a way hangfire can run all the missed schedules during server down-time ?

Checkout [1.8.0-beta2](https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.0-beta2) release. It mentions the following:

> Added – MisfireHandlingMode.Strict to create job for each missed recurring job occurrence.

Looks like exactly what you need. Though I'm not sure how stable that beta is. You may want to wait until Hangfire 1.8 stable release is out.

**Comment by prichakraborty09** [comment]
@Frazi1 thanks for your response. Yeah, I am looking for the capability to auto run all missed recurring job schedules. This is how it's been setup in the current production instance using Quartz.Net and we would expect the same behavior as we're migrating to Hangfire.

Any idea if MisfireHandlingMode.Strict just works out of the box if I setup a recurring job using the beta version package? Or do I need to configure something Couldn't find any documentation on how I can put this to test.

Thanks
PC

**Comment by Frazi1** [comment]
I haven't really used that feature myself, but I think that's how you configure it:

```c#

RecurringJob.AddOrUpdate<MyRecurringJobs>(x => x.TestJob(),
    Cron.Hourly, new RecurringJobOptions()
    {
        MisfireHandling = MisfireHandlingMode.Strict
    });
```

**Comment by prichakraborty09** [comment]
@Frazi1 Thanks for your help. We changed the requirement a bit to suit the default implementation. I had to do a workaround to stop recurring jobs from being picked up once the server restarts.
