### ISSUE TITLE
Is it safe to run the migration concurrently? If not, how to perform "locking"?

### ISSUE THREAD

**Issue by drauch** [HangfireIO/Hangfire#1896]
Our application runs in k8s, and the Hangfire database migration is running as part of init containers. This means, that each node will try to run the migration when it comes up -> as we have multiple nodes, that may happen concurrently.

Are Hangfire database migrations safe to perform concurrently? 

If not, how to properly lock the database before running the migration?

Best regards,
D.R.

**Comment by pieceofsummer** [comment]
That depends on the storage implementation you're using. For example, Hangfire.SqlServer acquired transaction-owned exclusive lock when running migrations so it would be safe to run multiple migrations concurrently. The other one will just block until the first one is completed and see there's nothing to do anymore once the lock is released.

**Comment by drauch** [comment]
Thanks, yes, we're using SqlServer as our backend. Great news! We're fine then :-)
