### ISSUE TITLE
accept suggestions from comunity

### ISSUE THREAD

**Issue by marcocochar** [HangfireIO/Hangfire#1901]
There are a plenty bug and bad design and architectural decisions.

You should accept community suggestions it's pretty annoying fixing your bugs and navigating through forks to check if other one has fixed it and you don't accept the pull.

You have a good visibility for a poor designed project and you should embrace that. I really want to use do Pro version for Redis, but judging by this source code i would'nt take a chance. I prefer to write Redis it by myself instead of risk me to pay 500 USD in another piece of crap.

**Comment by odinserj** [comment]
Could you please be more specific about architectural decisions you are talking about?

**Comment by marcocochar** [comment]
I can tell you, but not discuss about. We will not accept any argues. There are 600 issues, 50 pull request that you do not accept (couse you're right and everybody else in the world is wrong).

But let's start to say that a pretty simple piece of software needs to run in Redis or another storage couse we don't know how to write the correct SQL code,  Or why on hell the GUI must had a reference to code that that the agents run to work properly.

Just accept what community says to you, if you thing that you are the best programmer ever, and the entire community is full of dumb ass, the dumbass tends to be you.

**Comment by odinserj** [comment]
Oh

**Comment by sabiland** [comment]
> I can tell you, but not discuss about. We will not accept any argues. There are 600 issues, 50 pull request that you do not accept (couse you're right and everybody else in the world is wrong).
> 
> But let's start to say that a pretty simple piece of software needs to run in Redis or another storage couse we don't know how to write the correct SQL code, Or why on hell the GUI must had a reference to code that that the agents run to work properly.
> 
> Just accept what community says to you, if you thing that you are the best programmer ever, and the entire community is full of dumb ass, the dumbass tends to be you.

Dude, chill.

**Comment by marcocochar** [comment]
OMG    why 1000?

                    for (var i = 0; i < 1000; i++)
                    {
                        if (context.IsStopping) break;

                        var now = _nowFactory();
                        var timestamp = JobHelper.ToTimestamp(now);

                        var recurringJobId = connection.GetFirstByLowestScoreFromSet("recurring-jobs", 0, timestamp);
                        if (recurringJobId == null) break;

                        TryEnqueueBackgroundJob(context, connection, recurringJobId, now, true);
                        jobsProcessed++;
                    }
