### ISSUE TITLE
Out of Memory Job Retry Loop

### ISSUE THREAD

**Issue by blasky** [HangfireIO/Hangfire#1903]
We recently had a background job that went rogue and caused an out of memory situation. After system restart, Hangfire came back online along with the rest of the system and restarted the job. So the job ran again, and ran out of memory again, and. so on in a loop until we intervened and deleted the job.

Now, the underlying bug that caused the OOM has been diagnosed and fixed. But we have several types of jobs that are long running and intensive. Another OOM bug will undoubtedly be waiting for us at some point down the road. What can we do differently to protect against this situation?

The job itself was already flagged with [AutomaticRetry(Attempts = 0)]. And this works fine for us for other types of exceptions and failures. But clearly the memory exception is such that the job is not being marked as failed prior to restart. Presumably it was left in  a processing state.

If a job is in a processing state and the server restarts, is this not considered a retry of that job to requeue and rerun it? How can we ensure that a particular job, or class of jobs are never retried after a server crash/interrupt if they had already begun processing?

Thanks.

**Comment by Frazi1** [comment]
> But clearly the memory exception is such that the job is not being marked as failed prior to restart. Presumably it was left in a processing state.

It's very likely. OOM exception can really mess up things. That's because, if you don't have enough memory, you can't allocate new objects, and cannot execute code to change the state of your jobs properly. Or even worse, the whole runtime can be just terminated.


> If a job is in a processing state and the server restarts, is this not considered a retry of that job to requeue and rerun it

No, it is not considered a retry. But the job will be restarted. If you open job details on the dashboard, you'll notice that the job state was changed from `Processing` to another `Processing`. There is nothing in between.

> How can we ensure that a particular job, or class of jobs are never retried after a server crash/interrupt if they had already begun processing?

You can try to use the following filter to prevent re-running interrupted jobs:
```c#
using Hangfire.Common;
using Hangfire.States;
public class PreventInterruptedJobRestartAttribute : JobFilterAttribute, IElectStateFilter
{
	//NOTE: NOT TESTED. PLEASE TEST BEFORE USING IN PRODUCTION.
    public void OnStateElection(ElectStateContext context)
    {
        if (context.CurrentState == ProcessingState.StateName
            && context.CandidateState.Name == ProcessingState.StateName)
        {
            context.CandidateState = new DeletedState
            {
                Reason = "Removing interrupted job"
            };
        }
    }
}
```

You can apply the filter to your jobs individually or at the class level.

**Comment by blasky** [comment]
Thanks. I was already in the process of trying to write my own Filter. Good to know I was on the right track. I will report back when I get something that seems to be working well.

**Comment by blasky** [comment]
I'm still working on setting up my tests for this. But in the meantime, is ProcessingState to ProcessingState the only transition I need to worry about in this scenario? Could an interrupted job like this be trying to go from ProcessingState to EnqueuedState if the queue is already full prior to this transition? Or other possible candidate states?

What are the expected state transitions from ProcessingState? I feel like the only ones I wish to allow in this scenario are from ProcessingState to FailedState or ProcessingState to SuceededState...?

**Comment by blasky** [comment]
Currently testing with the following. Pretty much as you suggested except I'm blocking all ProcessingState transitions other than to SucceededState or FailedState. And I'm setting the CandidateState to Failed instead of Deleted, so the caller can make this a non-reentrant job but still determine whether any retries will be allowed as a separate issue after the failure is registered. Thanks.
```
public class NoJobReentryAttribute : JobFilterAttribute, IElectStateFilter
{
   public void OnStateElection(ElectStateContext context)
   {
      bool isOldRunState = context.CurrentState == ProcessingState.StateName;

      bool isNewRunState = context.CandidateState.Name != FailedState.StateName &&
                           context.CandidateState.Name != SucceededState.StateName;

      if (isOldRunState && isNewRunState)
      {
         context.CandidateState = new FailedState(
            new ArgumentException($"Job reentry transition not allowed: {context.CurrentState} to {context.CandidateState.Name}")
         );
      }
   }
}
```
