### ISSUE TITLE
Why hangfire is considering 2 separate application instances as one ?

### ISSUE THREAD

**Issue by prichakraborty09** [HangfireIO/Hangfire#1914]
Hi, So finally I deployed the hangfire application today. But I am facing a major challenge. I am going to have 2 instances running for my application, Prod 1 and Prod 2(deployed in containers, may or may not be same server). Prod 1 is connected to Prod1Db and Prod2 is connected to Prod2Db. Both the DBs are in the same server and have the same schema but have different data. I deployed just to Prod1 instance yesterday to see how its working. It was picking up the recurring jobs correctly. Today I deployed the same changes to Prod2. Observation :

There were 10 jobs in Prod1Db that started appearing in Prod2 as well(from yesterday).
Only Prod1 is picking up the recurring jobs, Prod2 isn't, but the data from Prod1Db is getting updated to the Prod2Db as well
I stopped the Prod1 instance, Prod2 did pick the job, it shows executed successfully, but the work that it was supposed to do actually didn't happen.
Prod1 and Prod2 hangfire dashboard, shows about 4-6 servers(different in both though)
I am really confused at the moment. Prod1 and Prod2 are the same application running on 2 instances(deployed in containers, may or may not be same server) and connected to 2 different DBs. How/Why Hangfire is treating them as a single unit?

**Comment by odinserj** [comment]
Sounds strange, can you show me configuration logic related to Hangfire and its storage? Looks like application settings mixed somehow.

**Comment by prichakraborty09** [comment]
@odinserj Yup that was the issue. Looks like Hangfire wasn't reading the DB connection details from the Environment variables setup in the CI/CD pipeline and was instead reading the connection string details from local app settings file. I changed the way I was reading the connection string to setup the sql server config with Hangfire. Posting it here for future reference. 

Earlier -
Startup.cs
services.AddHangfire(options =>
            {
                options.UseSqlServerStorage(Configuration.GetConnectionString("TestDb"));
            });

Now-
Startup.cs

services.AddHangfire(options =>
            {
                var testDBConnections = services.BuildServiceProvider().GetRequiredService<IOptions<TestDb>>().Value;
                options.UseSqlServerStorage(testDBConnections.HangfireDb);
            });
