### ISSUE TITLE
Sonatype reports Newtonsoft.Json 11.0.1 as vulnerable

### ISSUE THREAD

**Issue by fingerprint-boss** [HangfireIO/Hangfire#1919]
Hangfire has a dependency on Newtonsoft.Json 11.0.1 and that version is reported as vulnerable to a DoS attack by Sonatype.

https://alephsecurity.com/vulns/aleph-2018004

**Comment by odinserj** [comment]
Please note that this version is *minimal required*, and the concrete version should specified in the application that uses Hangfire. Hangfire itself is a framework, not an application. Concrete application should be inspected for concrete dependencies. Bumping minimal required versions in Hangfire will lead to breaking changes and will break existing applications, even those who aren't using deeply nested objects.

![image](https://user-images.githubusercontent.com/1078718/128518296-5405c0ad-0521-483b-b0fc-bd946c6084bb.png)

```xml
<ItemGroup>
  <PackageReference Include="Hangfire.Core" Version="1.7.24" />
  <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
</ItemGroup>
```

**Comment by fingerprint-boss** [comment]
Thanks. I missed that on the NuGet page. I was looking and the packages.config file to see which version was referenced. Apologies for the false alarm.
