### ISSUE TITLE
"Back to site" link always directs to domain root

### ISSUE THREAD

**Issue by jeremycook** [HangfireIO/Hangfire#192]
I'm running hangfire in sub-applications on IIS (e.g. /SiteA/hangfire and /SiteB/hangfire). Right now the "Back to site" link will take me to "/" whereas I would like it to take me to /SiteA/ if I'm at /SiteA/hangfire... or /SiteB/ if I'm at /SiteB/hangfire.

Not sure what the best way is to address this. It could be configurable via an app setting like hangfire:ParentSiteUrl. If not set then default to the current URL of "/".

**Comment by ysasaki1985** [comment]
Hi, has anyone worked on this yet?
I attempted making this change. e46e04b19f6268a3ac957076305b6c00dcd40e16
Please let me know your thoughts...

**Comment by Krishloozer** [comment]
@jeremycook, I have an issue related to hangfire dashboard when I configure it within the web site.
For example, SiteA is my root site inside that I have created a web application as service (so my web application inside the site will look like this **SiteA/service** ) that contains my hangfire implementation as a Web Api, after configuring the site I am not able to access the dashboard throwing 404 Not Found error on trying to access the link like ~/service/hangfire.
Please let me know how to configure the dashboard.

**Comment by jeremycook** [comment]
@Krishloozer If I had a quick answer I'd give it to you. Unfortunately I don't, I encourage you to ask over at https://discuss.hangfire.io/ or use the [hangfire] tag on https://stackoverflow.com/

**Comment by Krishloozer** [comment]
@jeremycook , Thanks for the update, I managed to resolve the issue, Owin startup is configured to false in my client web.config file I removed **_<add key="owin:AutomaticAppStartup" value="false" />_** from web.config and it all works fine. Due to this startup class is not called up on app initialization.
