### ISSUE TITLE
DashboardUI jQuery, Bootstrap, chart.js vulnerabilities

### ISSUE THREAD

**Issue by Lukas-26** [HangfireIO/Hangfire#1925]
I have found that current release [1.7.24](https://github.com/HangfireIO/Hangfire/releases/tag/v1.7.24) using 
 jQuery v2.2.4, Bootstrap v3.3.7 and chart.js v2.7.3. These libraries has known security issues.

- [https://snyk.io/test/npm/jquery/2.2.4](https://snyk.io/test/npm/jquery/2.2.4)
- [https://snyk.io/test/npm/bootstrap/3.3.7](https://snyk.io/test/npm/bootstrap/3.3.7)
- [https://snyk.io/test/npm/chart.js/2.7.3](https://snyk.io/test/npm/chart.js/2.7.3)

Is it possible to upgrade these libraries to jQuery v3.5.0, Bootstrap v3.4.1, chart.js v2.9.4?

Thanks for your consideration.

**Comment by odinserj** [comment]
Thanks, I've upgraded everything and updated versions will be available in the upcoming 1.7.25 release to avoid any dependency alarms.

**Comment by Lukas-26** [comment]
Hi Sergey,
Thanks for solving it.
