### ISSUE TITLE
Can one force RecurringJob to run on every server?

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#1926]
We have N servers running same App (same DB MSSQL).
Can one **force** RecurringJob to be run on every app-server ?

**Comment by akarboush** [comment]
You could make a private queue for every server and enqueue the job on each

**Comment by sabiland** [comment]
> You could make a private queue for every server and enqueue the job on each

But the code is identical for all N app servers. So this would not work right?

In the end I integrated Quartz library and use it as an in-memory scheduler, so each app server executes same job.

**Comment by sabiland** [comment]
I have used Quartz library for this task.
