### ISSUE TITLE
Json serialization settings ignored

### ISSUE THREAD

**Issue by MauroMon** [HangfireIO/Hangfire#1927]
Hello.

I have to schedule a job with some parameters that have self referering loops (this is required by application, i cant' just serialize identifiers or similar).

In order to avoid execption i have tried this:

https://discuss.hangfire.io/t/self-referencing-loop-detected-for-property-namingcontainer-with-type-system-web-ui-webcontrols-gridviewrow-path-footerrow-cells-0/6418

But the jsonSerializerSettings are ignored...

![image](https://user-images.githubusercontent.com/31884152/129878960-124e3dab-bda2-450e-a966-b10426c28103.png)

![image](https://user-images.githubusercontent.com/31884152/129875500-0de1b5fe-12db-4301-94ea-9c6a71a50111.png)

If i serialize directly using ` JsonConvert.SerializeObject(classA, settings);` it works.

This is the sample project i have created for the screens:
https://github.com/MauroMon/HangfireSerializationSettings.git

Thanks for your help

**Comment by odinserj** [comment]
That's because Hangfire.LiteDb rewrites serialization options with its own values, please see https://github.com/codeyu/Hangfire.LiteDB/blob/6e6336cb03954ca9b81c67caf935eaa96ba1638c/src/Hangfire.LiteDB/HangfireDbContext.cs#L55. So it's better to ask question there I think.

**Comment by MauroMon** [comment]
thank you, i will open an issue on the correct section
