### ISSUE TITLE
Create a recurring job from BackgroundJobClient

### ISSUE THREAD

**Issue by EugeneDeveloper** [HangfireIO/Hangfire#1937]
Hi everyone. Thanks a lot for such library.

I missed one functionality. I have multiple hangfire servers and one producer (BackgroundJobClient) which knows what to execute and when. Producer and Servers connected only via database.
I would like to create or update recurring job from producer. All servers uses the same database. 
BackgroundJobClient class can schedule new job and etc. But I cannot create or update settings for recurring job. Maybe I missed something or I am using it wrong?

Thanks a lot in advance.

**Comment by EugeneDeveloper** [comment]
@odinserj You are absolutely right! RecurringJobManager  also has access to SqlServerStorage. It works. 

I was confused with comment to `BackgroudJobClient` class:

`/// Provides methods for creating all the types of background jobs`
Because recurring jobs was missing. 

Thank you.

**Comment by odinserj** [comment]
Fix that comment, thanks!
