### ISSUE TITLE
Item has already been added. Key in dictionary: 'ExecutionId' 

### ISSUE THREAD

**Issue by akarzazi** [HangfireIO/Hangfire#1949]
We are having the following error from time to time.

```
Dispatcher is stopped due to an exception, you need to restart the server manually. Please report it to Hangfire developers.

System.ArgumentException: Item has already been added. Key in dictionary: 'ExecutionId'  Key being added: 'ExecutionId'
   at System.Collections.ListDictionaryInternal.Add(Object key, Object value)
   at Hangfire.Processing.BackgroundExecution.HandleException(Guid executionId, Exception exception, TimeSpan& delay)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
   at Hangfire.Processing.BackgroundDispatcher.DispatchLoop()
```

I guess that in the following code there is some racing condition on the raised exception.

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Processing/BackgroundExecution.cs

```
    if (!exception.Data.Contains("ExecutionId"))
    {
         exception.Data.Add("ExecutionId", executionId);
    }
```

Hangfire 1.7.3

**Comment by akarzazi** [comment]
I guess you are referring to this fix : 
https://github.com/HangfireIO/Hangfire/commit/bc73c78b08b47528941059da57037d9bccef16f9

This is not related to the error I'm reporting.

**Comment by odinserj** [comment]
Oh wow, thanks, something terrible is happening, because race condition can happen here only when there's another thread that modifies that collection, and this is almost impossible. It looks like Contains method returns wrong result, may be due to the current culture. How often do you see such exceptions? I've never seen them.

**Comment by akarzazi** [comment]
Yeah, this is a rare racing condition we observe once a week on a dozen of servers.
I guess the same instance of exception is caught by multiple threads.

We do use StackExchange / StackExchange.Redis library to connect to Redis.
Actually, when inspecting an error stack trace we have. We can observe that an instance of exception can be throw multiple times.

See : 
https://github.com/StackExchange/StackExchange.Redis/blob/v2.0.601/src/StackExchange.Redis/ConnectionMultiplexer.cs#L2256

```CS
var  val = source.GetResult(out var ex, canRecycle: true); 
 if (ex != null) throw ex; // the ex is not necessary a new instance.
```

**Comment by odinserj** [comment]
You are right. It looks like the same exception object instance was reused in different threads – I never even thought about such a possibility, that some code can reuse and throw the same exception object from multiple threads. But as for StackExchange.Redis, that sample code just rethrows an exception that was caught in another place, and generally StackExchange.Redis will always [create a new instance](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ExceptionFactory.cs) of the exception object without reusing them. So it looks like that some other code is doing the wrong thing and reuse exception objects.

Moreover object of `IDictionary` type isn't intended to be accessed from different threads anyway, so it's hard to work around this issue in Hangfire itself. I can implement catching such ArgumentException and log the original exception to understand what is the exception type and stack trace to find the code that throws it and fix it somehow (and if it's in the external package, at least to report this behaviour to its authors).
