### ISSUE TITLE
LocalRequestsOnlyAuthorizationFilter is automatically called even when removed

### ISSUE THREAD

**Issue by jc4gh** [HangfireIO/Hangfire#1964]
I've updated the package to 1.7.25 to 1.7.27 and LocalRequestsOnlyAuthorizationFilter is still getting called.

I've tried
1. Using my own filter as https://docs.hangfire.io/en/latest/configuration/using-dashboard.html
2. Tried to empty filters `                    endpoints.MapHangfireDashboard("/hangfire", new DashboardOptions()
                    {
                        Authorization = new List<IDashboardAuthorizationFilter> { },
                        AsyncAuthorization = new List<IDashboardAsyncAuthorizationFilter> { },
                    })
                    .RequireAuthorization(HangfireDashboardAuth);`
3. Tried to use middleware `                    endpoints.MapHangfireDashboardWithAuthorizationPolicy(HangfireDashboardAuth);
`

none of the above seems to work.
![image](https://user-images.githubusercontent.com/82118227/140563658-123f9efc-76b8-43e5-9337-c50af4a83c10.png)

**Comment by odinserj** [comment]
Unfortunately I can not reproduce the problem, please show me your full Startup.cs class.

**Comment by jc4gh** [comment]
relevant parts

`
    public class Startup
    {
        private const string HangfireDashboardAuth = "DashboardAuth";
        private readonly IWebHostEnvironment env;
        private readonly bool enableHangfire;

        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            this.Configuration = configuration;
            this.env = env;
            this.enableHangfire = this.Configuration.GetValue<bool>("EnableHangfire", false);
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry();

            // This is required to be instantiated before the OpenIdConnectOptions starts getting configured.
            // By default, the claims mapping will map claim names in the old format to accommodate older SAML applications.
            // 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' instead of 'roles'
            // This flag ensures that the ClaimsIdentity claims collection will be built from the claims in the token
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            services.AddMicrosoftIdentityWebApiAuthentication(this.Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();

            services.AddAuthentication() // Note that we don't provide the default scheme (there is only one default)
                .AddMicrosoftIdentityWebApp(this.Configuration);

            // The following lines code instruct the asp.net core middleware to use the data in the "groups" claim in the Authorize attribute and User.IsInrole()
            // See https://docs.microsoft.com/aspnet/core/security/authorization/roles?view=aspnetcore-2.2 for more info.
            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // Use the groups claim for populating roles
                options.TokenValidationParameters.RoleClaimType = "roles";
            });

            // TO DO: Fix auth
            services.AddAuthorization(options =>
            {
                options.AddPolicy(HangfireDashboardAuth, policy =>
                {
                    policy
                    .AddAuthenticationSchemes(OpenIdConnectDefaults.AuthenticationScheme)
                    .RequireAuthenticatedUser();
                    //.RequireRole("Service.ReadWrite");
                });
            });

            services.Configure(JwtBearerDefaults.AuthenticationScheme, (JwtBearerOptions options) =>
            {
                var existingOnTokenValidatedHandler = options.Events.OnTokenValidated;
                options.Events.OnTokenValidated = async context =>
                {
                    await existingOnTokenValidatedHandler(context).ConfigureAwait(false);

                    // Your code to add extra configuration that will be executed after the current event implementation.
                    options.TokenValidationParameters.ValidIssuers = new[] { "https://sts.windows.net/TENANT1/", "https://sts.windows.net/TENANT2/" };
                };
            });

            services.AddControllers().AddNewtonsoftJson(
                options =>
                {
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                });

            services.AddSwaggerGen(c => c.SwaggerDoc("v1", new OpenApiInfo { Title = "Service", Version = "v1" }));

            services.AddHealthChecks();

            string sqlConnectionString = this.Configuration.GetConnectionString("Database");

            services.AddDbContext<CommerceTransactionDbContext>(options =>
                options.UseSqlServer(sqlConnectionString));

            services.AddScoped<ICTDbContext>(provider => provider.GetService<CTDbContext>());

            services.AddHealthChecks()
                    .AddDbContextCheck<CTDbContext>();

            services.AddDatabaseDeveloperPageExceptionFilter();

            if (this.enableHangfire)
            {
                SqlConnection ConnectionFactory()
                {
                    SqlConnection sqlConnection = new(sqlConnectionString);
                    sqlConnection.AccessToken = new DefaultAzureCredential().GetToken(new Azure.Core.TokenRequestContext(new[] { "https://database.windows.net//.default" })).Token;
                    return sqlConnection;
                }

                services.AddTransient<SqlConnection>(db => ConnectionFactory());

                var storageOptions = new SqlServerStorageOptions
                {
                    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                    QueuePollInterval = TimeSpan.Zero,
                    UseRecommendedIsolationLevel = true,
                    DisableGlobalLocks = true,
                    SchemaName = this.Configuration.GetValue("HangfireSchemaName", "HangFire"),
                };

                services.AddHangfire(configuration => configuration
                .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseSqlServerStorage(ConnectionFactory, storageOptions));

                JobStorage.Current = new SqlServerStorage(ConnectionFactory(), storageOptions);

                // Add the processing server as IHostedService
                services.AddHangfireServer(options => options.WorkerCount = 20);
            }
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();

                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Service v1"));
            }

            if (!env.IsProduction())
            {
                Microsoft.IdentityModel.Logging.IdentityModelEventSource.ShowPII = true;
            }

            app.UseHttpsRedirection();

            // Adding nosniff for static files
            StaticFileOptions staticFileOptions = new()
            {
                OnPrepareResponse = ctx => ctx.Context.Response.Headers["x-content-type-options"] = "nosniff",
            };

            app.UseStaticFiles(staticFileOptions);

            app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                ResultStatusCodes =
                    {
                        [HealthStatus.Healthy] = StatusCodes.Status200OK,
                        [HealthStatus.Degraded] = StatusCodes.Status200OK,
                        [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable,
                    },
                AllowCachingResponses = false,
            });

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            if (this.enableHangfire)
            {
                app.UseHangfireDashboard();
            }

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

                if (this.enableHangfire)
                {
                    endpoints.MapHangfireDashboardWithAuthorizationPolicy(HangfireDashboardAuth);
                }
            });
        }
	}
}
`

**Comment by odinserj** [comment]
Thank you for providing the source code. Please remove the following call to `UseHangfireDashboard` as it overrides the `MapHangfireDashboardWithAuthorizationPolicy` – both methods register the dashboard, and one of them is enough.

```csharp
            if (this.enableHangfire)
            {
                app.UseHangfireDashboard();
            }
```

**Comment by jc4gh** [comment]
That fixed the issue, thank you!
