### ISSUE TITLE
BackgroundJob is not fired on .NET 6

### ISSUE THREAD

**Issue by mtorromacco** [HangfireIO/Hangfire#1967]
Hi guys,

I'm trying to migrate from .NET 5 to .NET 6 but I've a problem with the Hangfire configuration.
When I try to create a BackgroundJob I receive the error:

> InvalidOperationException: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.

```c#
var builder = WebApplication.CreateBuilder(args);

// ...

MemoryStorageOptions memoryStorageOptions = new() {
    FetchNextJobTimeout = TimeSpan.FromHours(10)
};

builder.Services.AddHangfire(options => options.UseMemoryStorage(memoryStorageOptions));
builder.Services.AddHangfireServer();

// ...

builder.Services.AddTransient<MyJobService>();

var app = builder.Build();

// ...

RecurringJob.AddOrUpdate<MyJobService>("test-job", job => job.Run(), Cron.Daily(12), TimeZoneInfo.Local); // Throw Exception

// ...
```

Everything working correctly in .NET 5 but not in .NET 6.

Any advice?
Thanks in advance!

Packages:
**_Hangfire.AspNetCore_**: **1.7.27**
**_Hangfire.Core_**: **1.7.27**
**_Hangfire.MemoryStorage_**: **1.7.0**

Framework: **.NET 6.0.100**

**Comment by mtorromacco** [comment]
**UPDATE**

I found a solution for this problem:

```c#
GlobalConfiguration.Configuration.UseMemoryStorage(memoryStorageOptions);
```

Now I have another problem: if I don't use `app.UseHangfireServer();` or `app.UseHangfireDashboard("...");` my BackgroundJobs are not fired.
The first one in deprecated and I don't want to use the dashboard.

How can I resolve it?

**Comment by odinserj** [comment]
Please use code from the first comment, but instead of using static `RecurringJob` and `BackgroundJob` classes please use `IRecurringJobManager` and `IBackgroundJobClient` services. 

```csharp
var builder = WebApplication.CreateBuilder(args);

// ...

MemoryStorageOptions memoryStorageOptions = new() {
    FetchNextJobTimeout = TimeSpan.FromHours(10)
};

builder.Services.AddHangfire(options => options.UseMemoryStorage(memoryStorageOptions));
builder.Services.AddHangfireServer();

// ...

builder.Services.AddTransient<MyJobService>();

var app = builder.Build();

// ...

// Use IRecurringJobManager for recurring jobs
app.Services.GetService<IRecurringJobManager>().AddOrUpdate<MyJobService>("test-job", job => job.Run(), Cron.Daily(12), TimeZoneInfo.Local);

// Use IBackgroundJobClient interface for regular jobs
app.Services.GetService<IBackgroundJobClient>().Enqueue(() => Console.WriteLine("Hello, world"));

// ...
```

**Comment by mtorromacco** [comment]
That's work! Thank you very much!
