### ISSUE TITLE
Remove dot net 4.5 from project

### ISSUE THREAD

**Issue by mohammad4x** [HangfireIO/Hangfire#1973]
Hi.
Can Dotnet 4.5 be removed from solution? It is not building in Visual Studio 2022

**Comment by richardgundersen** [comment]
Was just trying this myself as I am trying to get it working with .NET 5. Here's my SO post:

https://stackoverflow.com/questions/70114466/hangfire-net-5-could-not-load-type

Is there a way to get it building in the meantime?

**Comment by berkerdong** [comment]
> 

> Was just trying this myself as I am trying to get it working with .NET 5. Here's my SO post:
> 
> https://stackoverflow.com/questions/70114466/hangfire-net-5-could-not-load-type
> 
> Is there a way to get it building in the meantime?

Hello, I tested that hangfire works with sqlite and there is no problem, it can run normally, I use Hangfire.AspNetCore and Hangfire.Storage.SQLite

`builder.Services.AddHangfire(options => options.UseSQLiteStorage("hangfire.db"));
`

**Comment by t03apt** [comment]
I'd like to run sample apps and I can't build the solution in VS 2022 either. .NET 4.5 SDK is no longer supported.
See: https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
There is no Developer Pack for .NET Framework 4.5 anymore.

**Comment by pranaydevops28** [comment]
This should be a feature request, not an issue.

**Comment by odinserj** [comment]
Yes, I see SDK 4.5 is missing on that page, thanks for letting know. I will dump support to 4.5.1 in 1.8.0 release, but know currently when it will be released.

**Comment by mohammad4x** [comment]
That works fine now, thank you.
