### ISSUE TITLE
Is ITimeZoneResolver still needed when running on .NET6?

### ISSUE THREAD

**Issue by dmytro-gokun** [HangfireIO/Hangfire#1975]
It looks like .NET 6 understands IANA timezone names now. We've been using ITimeZoneResolver previously to resolve IANA timezone names. But it seems it should be fine to stop using it and everything should just work on .NET6. Am I right?

**Comment by dmytro-gokun** [comment]
TWIMC: .NET 6 IANA support only works when you run your app on Windows 10 1903 and higher. Windows Server 2016 & 2019 are not supported (i'm not sure about 2022 though). If you want to use this feature on those OSes you need to carry around icu.dll by adding this to you project file:

```
    <ItemGroup>
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2" />
    </ItemGroup>
```

For us this is not the most convinient solution, so we will keep using ITimeZoneResolver (implemented using TimeZoneConverter) for the time being.

**Comment by odinserj** [comment]
Thanks for your valuable feedback!

**Comment by dmytro-gokun** [comment]
UPD: this looks like to work on Windows Server 2022 & Windows 11
