### ISSUE TITLE
Homepage Example needs comma

### ISSUE THREAD

**Issue by cocoon** [HangfireIO/Hangfire#1992]
Hi there,

just copied and pasted the example from the Homepage and it lacks a comma:

https://github.com/HangfireIO/HangfireIO.github.io/blob/master/index.html#L138

![example](https://user-images.githubusercontent.com/1071741/148914640-e30c60bc-7633-4a66-9e28-5d3f127bc396.png)

**Comment by odinserj** [comment]
Fixed, thanks a lot for letting me know!
