### ISSUE TITLE
RecurringJob.AddOrUpdate wrong queue

### ISSUE THREAD

**Issue by ms92ita** [HangfireIO/Hangfire#1999]
Hi to all,

i have an application that runs in multiple instances and multiple version. Each "site" has an own queue, version queue and default queue valid for all instances.

But from the beta 1.8 (i am using 1.8.0-beta4), if I add RecurringJob.AddOrUpdate(jobid, queuename, function), I've noticed that in the SQL [Hash] table the job has a "default" value as queue. In the previous versions, the queue was correct

If there is a bug, can I do a workaround in orderd to reset the job with the correct queue?

**Comment by odinserj** [comment]
That field doesn't matter in 1.8, because queue metadata now belongs to a background job itself, so the one in the Job table will be used instead.
