### ISSUE TITLE
Enqueue Jobs that requires the Http Context with a Clean Architecture.

### ISSUE THREAD

**Issue by YannickRondeau** [HangfireIO/Hangfire#2004]
We're currently using[ Jason Taylor's clean architecture](https://github.com/jasontaylordev/CleanArchitecture) for our new DotNet Core application. This architecture implements a specific service to retrieve the user from a request and decouple it from other layers. This service relies on the `HttpContext` to get the user's information and claims.

We've been doing a lot of research on how we could possibly keep the current `CurrentUserService` which rely on the `HttpContext` since it is used pretty much everywhere in the application.

I was wondering if there are any ways of changing or, at least, control which instance is passed to Hangfire by the DI whenever a job is created. I've tried with the Job Activator, but it doesn't seem to work. Reading from #670 and #1485 I found out that our problem with our service was the scope of if.

The `CurrentUserService : ICurrentUserService` is currently registered as a Singleton, changing it to Scope seems to create an issue within Hangfire since there aren't any scope when it runs.

I was wondering if anyone could help on that specific topic.

**Current user implementation :**
```
public interface ICurrentUserService { [...] }

public class CurrentUserService : ICurrentUserService
{
    private readonly IHttpContextAccessor httpContextAccessor;
    public CurrentUserService(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }
    public string UserId => httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier);
}
```
We're using an extension to enqueue jobs with Mediatr, the issue comes when the job (or command) is ran and there `ICurrentUserService` is being injected.

```
public class TestingCommandHandler : IRequestHandler<TestingCommand>
{
    private readonly ICurrentUserService currentUserService;
    public TestingCommandHandler(ICurrentUserService currentUserService)
    {
        this.currentUserService = currentUserService;
    }
    
    public Task<Unit> Handle(TestingCommand request, CancellationToken cancellationToken)
    {
        var userId = currentUserService.UserId; // Null since HttpContext is empty.
        return Unit.Task;
    }
}
```

Note : We could be passing the user in the request or using a filter, however the `ICurrentUserService` is used in some underlying layer such as the infrastructure. Therefore, we need to change its value or inject a specific service to replace it whenever Hangfire is the initiator fo the command.

**Comment by burningice2866** [comment]
Pass the UserId to the job as argument when you're enqueing it. 

There is no context when the job runs at some point in the future. The user is long gone, maybe even closed the browser and went out to get some coffee.

**Comment by YannickRondeau** [comment]
@burningice2866 In fact, we've tried that route. However, since there are some underlying classes that uses the `ICurrentUserService` passing the `UserId` isn't working very well.

We've tried passing the `UserId` to Hangfire request's parameters on creation, then settings this `UserId` in the `CurrentUserService`, using filters, when the request starts processing. However, the service being a Singleton, this obviously led to some concurrency issues when processing multiple requests.

Changing the scope of the `CurrentUserService` from Singleton to Scoped didn't work either, since the scope isn't created when Hangfire raises the request.

We've also tried using an AspNet Middleware to set the `UserId`, this allowed us to remove the `HttpContext` from the service and rather set it directly from the middleware whenever a request was created. The same thing happened though with the service being changed from a Singleton to a Scoped service… 

The error was `cannot resolve scoped service [...] from root provider`

**Comment by burningice2866** [comment]
Having underlying classes relying on anything related to HttpContext doesn't sound like Clean Architecture to me. 

There is a issue here touching the subject https://github.com/jasontaylordev/CleanArchitecture/issues/44 where its stated that CurrentUserService shouldn't be leaked to other levels of the code. A job needing to be run by Hangfire shouldn't have anything to do with WebUI and shouldn't by relying on any logic related to WebUI.

HttpContext can be used in the first layer of your application which handles the incoming requests, so controllers and middleware related to the request/response pipeline, but not anywhere else. Every time your controllers need to call infrastructure logic, never pass around the HttpContext or expect on being able to resolve it at any given time in your code. Instead make it a habit to extract the values needed from your HttpContext and pass those as arguments to the other layers of your code.

**Comment by burningice2866** [comment]
What you could do is make a Hangfire filter that takes the UserId argument passed to the job and assign it to Thread.CurrentPrincipal.

You would then update your CurrentUserService, so when in case there is no HttpContext, then you would resolve the UserId from Thread.CurrentPrincipal instead.

**Comment by burningice2866** [comment]
There are other related issues on the Clean Architecture project touching the issue, here using the Quartz scheduler but the principle is 100% the same https://github.com/jasontaylordev/CleanArchitecture/issues/29

Another suggestion is to mark the UserId property as Set-able, and then run this following code in the Hangfire filter

```
 var currentUserService = serviceProvider.GetRequiredService<ICurrentUserService>();
 currentUserService.UserId = userIdFromJobArgument;
```

**Comment by odinserj** [comment]
Some time ago I've written the following background job filter to inject username identifier when first parameter of background job method is `string` and called `userName`.

```csharp
public sealed class UserIdSetterFilter : IClientFilter
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public UserIdSetterFilter(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }
    
    public void OnCreating(CreatingContext context)
    {
        var parameters = context.Job.Method.GetParameters();
        if (parameters.Length > 0 &&
            parameters[0].Name == "userName" &&
            parameters[0].ParameterType == typeof(string))
        {
            var argumentsArray = context.Job.Args as object[];
            if (argumentsArray == null) throw new InvalidOperationException("context.Job.Args is no more an array!");

            // Passing user name is for clarity, it's better to pass its identifier instead.
            argumentsArray[0] = _httpContextAccessor.HttpContext?.User.Identity?.Name;
        }
    }

    public void OnCreated(CreatedContext context)
    {
    }
}
```

HttpContextAccessor should be registered and filter can be registered globally in the following way:

```csharp
services.AddHttpContextAccessor(); // Required to make IHttpContextAccessor work
services.AddHangfire((provider, configuration) => configuration
    .UseXXXStorage()
    .UseFilter(new UserIdSetterFilter(provider.GetRequiredService<IHttpContextAccessor>())));
```

And background job method could look like the following one:

```csharp
public void MyJob(string userName, int someArg) {}

backgroundJob.Enqueue(() => MyJob(null, 12345));
```

**Comment by burningice2866** [comment]
@odinserj  I believe the problem is not getting the username passed as argument to the background job, but that the job later calls some underlying code which relies on HttpContext and therefor fails.

`@burningice2866 In fact, we've tried that route. However, since there are some underlying classes that uses the ICurrentUserService passing the UserId isn't working very well.`

So we need to decouple HttpContext from CurrentUserService when executing in a bacground job.

**Comment by YannickRondeau** [comment]
Thank you both for the prompt answers. As @burningice2866 mentioned, the `ICurrentUserService` is being used in underlying layers, (in Infrastructure of the `AuditableEntity` for example). 

Therefore, we need to decouple the service from the `HttpContext` which is kind of _hard_ to achieve right now, or set the `UserId` in a filter which doesn't really work because the `CurrentUserService` is a singleton and therefore, if any jobs are run in parallel, the `UserId` is overridden.

@burningice2866 I will read the post you shared on the Clean Architecture and see if there are any clues from these that could lead us to a better solution.

Using the `Thread.CurrentPrincipal` could be a way to achieve this.

**Comment by bobzer** [comment]
Hi, 
Actually you can I did it :) but it's a little hack because the way I did works perfectly but require you to serialize the claims principal.
you currentUserService need to get the httpContextAccessor
and contains a singleton of the claimsPrincipal.
something like : 

        private HttpContext? _httpContext =>
            _httpContextAccessor?.HttpContext;
        private ClaimsPrincipal? _claimsPrincipal;
        private ClaimsPrincipal _claims
        {
            get
            {
                if (_claimsPrincipal == null)
                    _claimsPrincipal = _httpContext?.User ?? new ClaimsPrincipal();
                return _claimsPrincipal;
            }
            set
            {
                _claimsPrincipal = value;
            }
        }
        public CurrentUser(IHttpContextAccessor httpContextAccessor, ILogger<CurrentUser> logger)
        {
            _httpContextAccessor = httpContextAccessor;
            _logger = logger;
        }
        public ClaimsPrincipal? Deserialize(string? userSerialized)
        {
            if (userSerialized == null) return null;
            var userByte = Convert.FromBase64String(userSerialized);
            using var mStream = new MemoryStream(userByte);
            using var bReader = new BinaryReader(mStream);
            return new ClaimsPrincipal(bReader);
        }

        public string? Serialize()
        {
            if (!IsAuthenticated()) return null;

            // Remove claims that you don't want to serialize
            var clone = Deserialize(Serialize(_claims));
            var session = clone?.FindFirst(c => c.Type == UserClaims.Session);
            if (session != null)
                (clone?.Identity as ClaimsIdentity)?.RemoveClaim(session);

            return clone == null ? null : Serialize(clone);
        }
        private static string Serialize(ClaimsPrincipal principal)
        {
            using var mStream = new MemoryStream();
            using (var bWriter = new BinaryWriter(mStream))
            {
                principal.WriteTo(bWriter);
            }
            mStream.Flush();
            return Convert.ToBase64String(mStream.GetBuffer());
        }

then you need a combination of BackgroundJobFilterAttribute, CustomJobActivator to do the serialization and deserialization:
filter :
```
        public void OnCreating(CreatingContext filterContext)
        {
            try
            {
                if (!filterContext.Parameters.ContainsKey(nameof(ICurrentUser)))
                {
                    using IServiceScope serviceScope = _serviceScopeFactory.CreateScope();
                    var currentUser = serviceScope.ServiceProvider.GetService<ICurrentUser>();
                    string userSerialized = currentUser?.Serialize() ?? string.Empty;
                    filterContext.SetJobParameter(nameof(ICurrentUser), userSerialized);
                }
            }
            catch (Exception)
            {
                // at startup you don't have a user 
            }
        }
```

then the activator:
```
        public override JobActivatorScope BeginScope(JobActivatorContext context)
        {
            var serviceScope = _serviceScopeFactory.CreateScope();

            var userSerialized = context.GetJobParameter<string>(nameof(ICurrentUser));
            var currentUser = serviceScope.ServiceProvider.GetService<ICurrentUser>();

            if (currentUser != null
                && !string.IsNullOrEmpty(userSerialized))
            {
                currentUser.SetPrincipal(userSerialized);
            }

            return new ServiceJobActivatorScope(serviceScope);
        }
```

BTW: the currentUserService is not a singleton but a scoped and it worked perfectly because the activator set the currentUser inside the currentUserService

**Comment by YannickRondeau** [comment]
@bobzer Thanks for the example. I was able to get something working similarly by using a filter attribute and using the `Thread.CurrentPrincipal`, as @burningice2866 mentioned, whenever the `HttpContext` wasn't available. However, I'm pretty sure my solution wasn't as safe as yours. I'm using a singleton; therefore there could be some concurrency issues when processing a large amount of request.

I will modify my code to get it working with the `JobActivatorScope` you described.

Thanks,

**Comment by Brawns** [comment]
> Hi, Actually you can I did it :) but it's a little hack because the way I did works perfectly but require you to serialize the claims principal. you currentUserService need to get the httpContextAccessor and contains a singleton of the claimsPrincipal. something like :
> 
> ```
>     private HttpContext? _httpContext =>
>         _httpContextAccessor?.HttpContext;
>     private ClaimsPrincipal? _claimsPrincipal;
>     private ClaimsPrincipal _claims
>     {
>         get
>         {
>             if (_claimsPrincipal == null)
>                 _claimsPrincipal = _httpContext?.User ?? new ClaimsPrincipal();
>             return _claimsPrincipal;
>         }
>         set
>         {
>             _claimsPrincipal = value;
>         }
>     }
>     public CurrentUser(IHttpContextAccessor httpContextAccessor, ILogger<CurrentUser> logger)
>     {
>         _httpContextAccessor = httpContextAccessor;
>         _logger = logger;
>     }
>     public ClaimsPrincipal? Deserialize(string? userSerialized)
>     {
>         if (userSerialized == null) return null;
>         var userByte = Convert.FromBase64String(userSerialized);
>         using var mStream = new MemoryStream(userByte);
>         using var bReader = new BinaryReader(mStream);
>         return new ClaimsPrincipal(bReader);
>     }
> 
>     public string? Serialize()
>     {
>         if (!IsAuthenticated()) return null;
> 
>         // Remove claims that you don't want to serialize
>         var clone = Deserialize(Serialize(_claims));
>         var session = clone?.FindFirst(c => c.Type == UserClaims.Session);
>         if (session != null)
>             (clone?.Identity as ClaimsIdentity)?.RemoveClaim(session);
> 
>         return clone == null ? null : Serialize(clone);
>     }
>     private static string Serialize(ClaimsPrincipal principal)
>     {
>         using var mStream = new MemoryStream();
>         using (var bWriter = new BinaryWriter(mStream))
>         {
>             principal.WriteTo(bWriter);
>         }
>         mStream.Flush();
>         return Convert.ToBase64String(mStream.GetBuffer());
>     }
> ```
> 
> then you need a combination of BackgroundJobFilterAttribute, CustomJobActivator to do the serialization and deserialization: filter :
> 
> ```
>         public void OnCreating(CreatingContext filterContext)
>         {
>             try
>             {
>                 if (!filterContext.Parameters.ContainsKey(nameof(ICurrentUser)))
>                 {
>                     using IServiceScope serviceScope = _serviceScopeFactory.CreateScope();
>                     var currentUser = serviceScope.ServiceProvider.GetService<ICurrentUser>();
>                     string userSerialized = currentUser?.Serialize() ?? string.Empty;
>                     filterContext.SetJobParameter(nameof(ICurrentUser), userSerialized);
>                 }
>             }
>             catch (Exception)
>             {
>                 // at startup you don't have a user 
>             }
>         }
> ```
> 
> then the activator:
> 
> ```
>         public override JobActivatorScope BeginScope(JobActivatorContext context)
>         {
>             var serviceScope = _serviceScopeFactory.CreateScope();
> 
>             var userSerialized = context.GetJobParameter<string>(nameof(ICurrentUser));
>             var currentUser = serviceScope.ServiceProvider.GetService<ICurrentUser>();
> 
>             if (currentUser != null
>                 && !string.IsNullOrEmpty(userSerialized))
>             {
>                 currentUser.SetPrincipal(userSerialized);
>             }
> 
>             return new ServiceJobActivatorScope(serviceScope);
>         }
> ```
> 
> BTW: the currentUserService is not a singleton but a scoped and it worked perfectly because the activator set the currentUser inside the currentUserService

Hi, I have the same problem. Do you have a demo?

**Comment by Brawns** [comment]
@bobzer Hi, I have the same problem. I think your solution might work, but I tried it without success. Can you provide a demo?

**Comment by bobzer** [comment]
> @bobzer Hi, I have the same problem. I think your solution might work, but I tried it without success. Can you provide a demo?

I know for sure my solution works, it's in production, but I don't have the source code anymore, so I'm sorry but I can't provide a demo.

**Comment by alikleitcr7** [comment]
@burningice2866  You acknowledge that (regardless of HttpContext User) - an application that replies on user authentication, where many functions are tied together and are authenticating the current user - has to find a way to get the current user in some way or another from the current execution.. 

One would expect something similar to HttpContext, Thread.CurrentPrincipal, etc. to be able to get that "True" context data accross the running functions.


So far answers are hacky and do not look safe. Already tried:

```

// Service Filter
public void OnCreating(CreatingContext context)
{
    Thread.CurrentPrincipal = new GenericPrincipal(new GenericIdentity("ali", "session"), ["admin"]);
}


// UserContext:

 GetAuthenticatedUser() 
{

    IPrincipal threadPrincipal = Thread.CurrentPrincipal;    <-- null after triggering a job. 😞 
}
```


Would appreciate if there is an official working solution for that other than passing down parameters (eg. username) that can be written down.  😄
