### ISSUE TITLE
AggregateException (OperationCanceledException) when shutting down .net core app hangfire

### ISSUE THREAD

**Issue by sommmen** [HangfireIO/Hangfire#2008]
Hiya,

Running .net core 6 /w hangfire in a windows application. I'm running into issues where the app does not exit gracefully,

![image](https://user-images.githubusercontent.com/8641495/157020346-ba88ba5c-3c17-4eb3-9377-6bfd788a5930.png)

This only seems to happen when a background job is being processed. I'm thinking the job get canceled and throws an operation canceled exception, which gets propagated to `Backgrounddispatcher.WaitAsync`. Perhaps the wrapping of operationcanceled exception inside an aggregate exceptions kills the shutdown flow somwhere?

EDIT: confirmed that if no jobs are running there is no issue.

**Comment by odinserj** [comment]
Looks like `HostOptions.ShutdownTimeout` is elapsed that's why cancellation is triggered. Please try to specify a bigger timeout as written in this article – https://andrewlock.net/extending-the-shutdown-timeout-setting-to-ensure-graceful-ihostedservice-shutdown/.

**Comment by sommmen** [comment]
> Looks like `HostOptions.ShutdownTimeout` is elapsed that's why cancellation is triggered. Please try to specify a bigger timeout as written in this article – https://andrewlock.net/extending-the-shutdown-timeout-setting-to-ensure-graceful-ihostedservice-shutdown/.

Hello @odinserj  thanks for taking some time out of your busy schedule.

I've done some more investigating and it seems that i have some jobs that don't exit in time and therefore i get the  `OperationCanceledException`.

Rather than just setting larger timeouts i'd like to identify jobs that don't cancel in time and fix those - do you have any tips regarding finding those jobs?

**Comment by odinserj** [comment]
No worries! Try adding cancellation tokens to methods of background jobs whose identifier is shown as being re-queued like shown on the first screenshot https://docs.hangfire.io/en/latest/background-methods/using-cancellation-tokens.html

**Comment by sommmen** [comment]
> No worries! Try adding cancellation tokens to methods of background jobs whose identifier is shown as being re-queued like shown on the first screenshot https://docs.hangfire.io/en/latest/background-methods/using-cancellation-tokens.html

Ah yes - i made a base class for any and all jobs so my colleagues are forced to use the cancellationToken somewhat for this reason:

``` csharp
public abstract class JobBase<TOptions> : IJob<TOptions>, IDisposable 
    where TOptions : JobOptionsBase, new()
{
    private readonly IDisposable _loggerScope;
    protected DateTime CreatedAt { get; }
    protected string JobId { get; }

    protected IHangfireLogger Logger { get; }

    protected JobBase(PerformContext context, ILoggerFactory loggerFactory)
    {
        ...
    }

    public abstract Task Run(CancellationToken cancellationToken, TOptions? jobOptions = default);

}
``` 

The problem is that some jobs dont properly propagate the cancellationToken or don't use it at all - for ex:

``` csharp
class JobBaseImpl<TOptions> : 
    JobBase<TOptions> where TOptions : JobOptionsBase, new()
{
    private readonly IRepository<Order> orderRepository;

    public JobBaseImpl([NotNull] PerformContext context, [NotNull] ILoggerFactory loggerFactory, IRepository<Order> orderRepository)
        : base(context, loggerFactory)
    {
        this.orderRepository = orderRepository;
    }

    public override async Task Run(CancellationToken cancellationToken, TOptions? jobOptions = default)
    {
        var entities = await orderRepository
            .AsQueryable()
            .ToListAsync(); // OOPS - someone forgot the cancellation token and now this job can't exit :/
    }
}
```

So i was hoping there'd be a way to get the jobs that were too slow to cancel so i can identify which ones those are and try to improve on them.

Like you mentioned the jobs that are re-queued are the ones that are cancelled when the worker is stopped so i can inspect those jobs further.

I can also activate a job, stop the worker and see if it exits in time - so i can systematically go through the jobs and see if they exit on time. It would perhaps be a good addition that hangfire would report when the host is timed out and not all jobs have cancelled yet - something like: `OperationCanceledException: 'The following jobs could not be canceled in time: 11234, 23245,923521'` - if i have some time ill dig in the source of hangfire to see if something like that would be easy to achieve and submit a pr.

Anyways I don't want to take up more of your time - i can investigate this issue myself further and the fault is in my app not in hangfire. Thanks for your support!
