### ISSUE TITLE
In-memory execution for Windows Service

### ISSUE THREAD

**Issue by killnine** [HangfireIO/Hangfire#203]
Hey all,

Just discovered Hangfire today and thought it might be a fit for a Windows Service I am writing.

Primarily, I am interested in creating a clean interface for scheduling periodic work to execute within my service. However, I don't need the persistence of a data store like you might need with an IIS deployment. 

Is there any interest in having a simpler, in-memory Storage option rather than requiring something like a SqlServer install? I saw someone mention [RavenDB support](https://github.com/HangfireIO/Hangfire/issues/26) which might also be suitable since Raven has an embedded mode.

Really, I think it would just help newbiews get up to speed faster and, as long as they are on a Windows Service or non-Load Balanced IIS install, I'd imagine it work just fine, no?

Thanks, this looks like a great project.

**Comment by agonzalezm** [comment]
+1 in memory storage

**Comment by carlos-sarmiento** [comment]
+1 It is useful if you just want a simple server to have an API and do some background job

**Comment by odinserj** [comment]
[Hangfire.MemoryStorage](https://www.nuget.org/packages/Hangfire.MemoryStorage/) package is available.
