### ISSUE TITLE
Page: jobs/enqueued throw an exception 1.7.28

### ISSUE THREAD

**Issue by jacksonwj** [HangfireIO/Hangfire#2032]
Hi

I met an exception in dashboard page (1.7.28).

A background job is processing, and it will take a very long time, the **Stats page** like this

![Stats page](https://user-images.githubusercontent.com/61455/167242963-7e24c239-9b9e-4ac9-b19b-5a7f6451ad4d.png)

When I click the **Queue** in menu above, then the page will throw an exception (**Object reference not set to an instance of an object**) like this

![Enqueued page exception](https://user-images.githubusercontent.com/61455/167243030-2f1bbf62-e6fa-45cf-b882-5d0080dee228.png)

Help me please, thanks.

**Comment by jacksonwj** [comment]
The hangfire is version 1.7.28

**Comment by odinserj** [comment]
Hi, was you able to eliminate the issue? What was the problem?

**Comment by jacksonwj** [comment]
> Hi, was you able to eliminate the issue? What was the problem?

Yes, there is a bug in my realm storage code. This page visits `MonitoringApi.Queues()`, and I return a NULL value to the `JobList<T>`, so I modified my code, change it to `new JobList<T>(new List<KeyValuePair<string, T>>())`, then the bug has gone.

**Comment by odinserj** [comment]
Thanks for details, wanted to confirm this is storage related, and doesn't happen with the regular use.
