### ISSUE TITLE
Using Edge browser, several buttons don't function (Chrome works).

### ISSUE THREAD

**Issue by adenysen** [HangfireIO/Hangfire#2035]
Just upgraded to Hangfire 1.7.28 and the Dashboard used to work fine with with Edge in Hangfire 1.7.22.

Edge is our new corporate web browser and when I use the Hangfire Dashboard (version 1.7.28), several buttons just don't work in the UI.

For example, unable to use the "Select All" jobs checkbox to select multiple jobs in batch.  This works fine in Chrome.

Screenshot using Edge browser:

![image](https://user-images.githubusercontent.com/3720596/168940908-508daa15-cf5f-41f4-9564-297e8f092fbf.png)

Using latest version of Edge:
![image](https://user-images.githubusercontent.com/3720596/168940679-72b6f64c-7b1a-4adf-8603-924e78269814.png)

Similarly, when trying to delete a job, the "Delete Selected" button does not enable when an item is selected.

![image](https://user-images.githubusercontent.com/3720596/168944096-8d8fee10-ec71-49ee-85d9-6037d2bb5849.png)

**Comment by odinserj** [comment]
Can't reproduce this with `Version 101.0.1210.47 (Official build) (64-bit)`, possible there's a problem with loading JavaScript. What status is shown in the developer tools regarding the `/jsXXXXX` resource? Is it succeeded or failed, what is the response in the latter case?

![image](https://user-images.githubusercontent.com/1078718/169005939-c38069b7-320b-486d-b687-285973f13dba.png)

**Comment by adenysen** [comment]
Thanks @odinserj for responding.

It must be our internal network firewall rules or something since I don't see any traffic in the Network view (see below).

Feel free to close the issue if you like since it works for you as it is most likely something on our internal corporate network - unless you would prefer to keep it open and for me to follow-up once I figure out the issue on our end.  My work-around for now is to use Chrome and I will take it up with our networking team.  

It is odd that this used to work fine with 1.7.22 (just confirmed this still works with Edge on our network) but no longer works with 1.7.28.  I wonder if one of the new? js files is getting blocked.

![image](https://user-images.githubusercontent.com/3720596/169031370-80254033-f681-4db7-9b07-0060d2c02260.png)

**Comment by odinserj** [comment]
Please try to refresh the page when Network tab is opened, to ensure that all requests are captured – that's really strange you don't have any requests, because at least CSS should be queried. There were some updates to jQuery and Bootstrap libraries in version 1.7.25, but they should work fine with Edge.

**Comment by adenysen** [comment]
Actually, we just got the bottom of the problem.  Our internal network is configured to use Edge in IE mode (https://docs.microsoft.com/en-us/deployedge/edge-ie-mode) for certain sites that still use Silverlight - so what was happening was the Hangfire Dashboard was being hosted in the Internet Explorer browser.  We have multiple apps on the one web server - Silverlight and classic HTML/JavaScript.  We will need to figure out a way on our end to ensure that Hangfire Dashboard uses the Edge Chromium engine.  Feel free to close the issue.

**Comment by odinserj** [comment]
> We were able to figure that out and our networking guys were able to configure a policy (though not sure where that is done) to have our Hangfire based apps to use Edge while still allowing the rest of our legacy apps on that same web server to default to IE.
> 
> It looks like something like this:
> 
> ```xml
> <site url="webserver1/AppThatNeedsEdge">
>     <open-in>MSEdge</open-in>
> </site>
> ```
