### ISSUE TITLE
SecurityException should not be ignored as an uncatchable exception

### ISSUE THREAD

**Issue by Plasma** [HangfireIO/Hangfire#2046]
Regarding 9bc6bde133c664e22f4d247d9affd22db8ba2ea0 code was added to not try and catch `OutOfMemoryException` etc, however `SecurityException` was included I believe by mistake.

Valid user code can throw a `SecurityException` for access control reasons, this should be a valid exception caught by Hangfire and fail the job just like other exceptions do.

I suggest removing the `SecurityException` filter from `IsCatchableExceptionType` (in the two places that method is set) to revert the behavior for `SecurityException` so its caught again.

**Comment by odinserj** [comment]
It's usually included in such an exception filter, but let's add it only when there's a reasonable use case for this, and revert the change for now regarding `SecurityException`.
