### ISSUE TITLE
Lost event class on serialization

### ISSUE THREAD

**Issue by LucioPelinson** [HangfireIO/Hangfire#2049]
if pass the class with parameter to function the event become null.
Example:

Call method
```
 ...
  app.UseHangfireDashboard();

  var writer = new CsvWriter();
  writer.FileName = "Foo.csv";
  writer.OnRender += (s, e) => { e.Message = "TestOk3 " + e.Progress; };

  var taskTrigger = new TaskTrigger();
  taskTrigger.Run(writer);

```

Mock a external lib
```
public class CsvWriter
{
    public string FileName { get; set; }

    public event EventHandler<MessageEventArgs> OnRender;

    public async Task RunWorkerAsync(CancellationToken cancellationToken)
    {
        Debug.WriteLine("File: " + FileName);
        await Task.Run(() =>
        {
            for (int i = 0; i < 1000; i++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                string message = "Exporting " + i;
                if (OnRender != null)
                {
                    var msg = new MessageEventArgs(message, i);
                    OnRender.Invoke(this, msg);
                    message = msg.Message;
                }
                Debug.WriteLine(message);
                Task.Delay(1000).Wait();
            }
        });
    }
}

public class MessageEventArgs : EventArgs
{
    public string Message { get; set; }
    public int Progress { get; private set; }

    public MessageEventArgs(string message, int process)
    {
        Message = message;
        Progress = process;
    }
}
```

The Problem
```
public class TaskTrigger
{
    public void Run(CsvWriter writer)
    {
        //this work but i can't use console.log
        //BackgroundJob.Enqueue(() => writer.RunWorkerAsync(CancellationToken.None).Wait());

        //this lost custom event from CsvWriter.OnRender
        BackgroundJob.Enqueue(() => RunInBackground(writer, CancellationToken.None, null));
    }

    public void RunInBackground(CsvWriter writer, CancellationToken cancellationToken, PerformContext context)
    {
        context.WriteLine("any console log here...");
        writer.RunWorkerAsync(cancellationToken).Wait();
    }

}
```

Debug

![image](https://user-images.githubusercontent.com/28662273/174163366-2f3d835a-4dd1-448b-ae02-b16ea183d628.png)

Next step
![image](https://user-images.githubusercontent.com/28662273/174163504-691456a7-9aed-4ed6-8a83-f4168228f345.png)

Any suggestion?

**Comment by FlorentBunjaku1** [comment]
this will "fix" your problem.

` public void Run(CsvWriter writer)
        {
            //this lost custom event from CsvWriter.OnRender
            BackgroundJob.Enqueue(() => RunInBackground(writer, CancellationToken.None).Wait());
        }

        public Task RunInBackground(CsvWriter writer, CancellationToken cancellationToken)
        {
            Console.WriteLine("Executing");
            return writer.RunWorkerAsync(cancellationToken);
        }`

**Comment by FlorentBunjaku1** [comment]
I putted fix on quotes because with that approach you are not scheduling the actual job, in fact, that is starting to be executed at the moment that you are calling `RunInBackground(writer, CancellationToken.None)..` and then you are enqueueing just the Wait method of the Task. That is why you have access to the event.
A proper way to do this could be something like this:

```
public class TaskTrigger
      {
          private static CsvWriter _csvWriter;
          public TaskTrigger()
          {
              if (_csvWriter != null) return;
              
              _csvWriter = new CsvWriter
              {
                  FileName = "Foo.csv"
              };
              _csvWriter.OnRender += (s, e) => { e.Message = "TestOk3 " + e.Progress; };
          }
          
          public void Run()
          {
              BackgroundJob.Enqueue<TaskTrigger>(x => x.RunInBackground(CancellationToken.None));
          }
  
          public async Task RunInBackground(CancellationToken cancellationToken)
          {
              Console.WriteLine("Executing");
              await _csvWriter.RunWorkerAsync(cancellationToken);
          }
      }
    ```
    
    ```
     var taskTrigger = new TaskTrigger();
      taskTrigger.Run();
      
      var server = new BackgroundJobServer();
      Console.ReadLine();
    ```

**Comment by LucioPelinson** [comment]
> I putted fix on quotes because with that approach you are not scheduling the actual job, in fact, that is starting to be executed at the moment that you are calling `RunInBackground(writer, CancellationToken.None)..` and then you are enqueueing just the Wait method of the Task. That is why you have access to the event. A proper way to do this could be something like this:
> 
> ```
> public class TaskTrigger
> {
>     private static CsvWriter _csvWriter;
>     public TaskTrigger()
>     {
>         if (_csvWriter != null) return;
>         
>         _csvWriter = new CsvWriter
>         {
>             FileName = "Foo.csv"
>         };
>         _csvWriter.OnRender += (s, e) => { e.Message = "TestOk3 " + e.Progress; };
>     }
>     
>     public void Run()
>     {
>         BackgroundJob.Enqueue<TaskTrigger>(x => x.RunInBackground(CancellationToken.None));
>     }
> 
>     public async Task RunInBackground(CancellationToken cancellationToken)
>     {
>         Console.WriteLine("Executing");
>         await _csvWriter.RunWorkerAsync(cancellationToken);
>     }
> }
> ```
> 
> ```
> var taskTrigger = new TaskTrigger();
> taskTrigger.Run();
> 
> var server = new BackgroundJobServer();
> Console.ReadLine();
> ```

@FlorentBunjaku1 this works fine. 
Thanks for your help!
