### ISSUE TITLE
Global [DisplayName] for jobs

### ISSUE THREAD

**Issue by rooks** [HangfireIO/Hangfire#205]
It seems that the only way to customize job display text on dashboard is to add `DisplayName` attribute to method. Here is the code from HtmlHelper.DisplayJob` that returns job name:

``` c#
var displayNameAttribute = Attribute.GetCustomAttribute(
    job.Method,
    typeof(DisplayNameAttribute), true) as DisplayNameAttribute;

if (displayNameAttribute == null || displayNameAttribute.DisplayName == null)
{
    return String.Format("{0}.{1}", job.Type.Name, job.Method.Name);
}

try
{
    var arguments = job.Arguments.Cast<object>().ToArray();
    return String.Format(displayNameAttribute.DisplayName, arguments);
}
catch (FormatException)
{
    return displayNameAttribute.DisplayName;
}
```

I want to be able to specify global display name format. Is `DisplayJob` method a good place to put additional format logic in?

**Comment by odinserj** [comment]
`DashboardOptions` class in version 1.7.0 contains the `DisplayNameFunc` property you can use to specify a `DashboardContext, Job` &rArr; `string` callback.

**Comment by plk** [comment]
@odinserj  - is it possible customise the argument listing in the details view using attributes? `JobDisplayName` only seems to change the listing view.
