### ISSUE TITLE
Change hangfire initialization is causing different behavior on graceful shutdown

### ISSUE THREAD

**Issue by joaozacharias** [HangfireIO/Hangfire#2070]
Hello,
I'm updating the hangfire version as i checked the deprecated message when i use 'app.UseHangfireServer()' method.
After did this and start to use AddHangfireServer() with service collection instead UseHangfireServer() with application builder, the graceful shutdown doesn't work anymore, cancellation token is not triggered and the server/workers is not going down after receive the SIGTERM.

I clone hangfire application and made the change bellow and now seems to work.

![hangfire changes](https://user-images.githubusercontent.com/28767219/182354337-e7446b63-9c0f-4b71-aaab-307a38841833.png)

Could you please check if this change is valid? And if it's valid, please apply.

**Comment by odinserj** [comment]
Hm, [according to the docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice) the StopAsync method should also be called during the shutdown, so I except that these features duplicate each other. If not, we should conduct an investigation and check .NET Core's source code to see the difference, e.g. when and how ApplicationStopping/StopAsync methods are called.

**Comment by joaozacharias** [comment]
Hi, I got you.
During my tests the StopAsync() is not called as soon the application receive the SIGTERM and then the cancellationToken is not triggered and workers/serves are active.
When i used this another initalization that register the actions in application lifetime everything went well.
I'm using .Net Core 3.1, please if you could do the investigation.
Thanks!

**Comment by odinserj** [comment]
Will continue investigation a bit later, was struggling to install .NET 5.0 on Ubuntu 22.04 box, then struggling to install supported OpenSSL 1.X, now struggling to make SSL working to connect to job storage 🤗

**Comment by joaozacharias** [comment]
I'm still doing some tests and i think i found the problem, i have another "IHostedService" in my application with a Thread.Sleep in the method **_hostApplicationLifetime.ApplicationStopping.Register()_**, when i remove this service from DI the cancellationToken is triggered but the application goes down without time to have a graceful shutdown, this occurs when i use **_AddHangfireServer()_**, when i use **_app.UseHangfireServer()_** everything works fine.

**Comment by joaozacharias** [comment]
I tried to use these options:

**Comment by joaozacharias** [comment]
When i try to use the options below, the cancelation token is not triggered.
**_options.ShutdownTimeout = TimeSpan.FromSeconds(15);
options.StopTimeout = TimeSpan.FromSeconds(10);
options.ServerTimeout = TimeSpan.FromSeconds(10);_**

**Comment by odinserj** [comment]
@joaozacharias can you also try to increase the .NET Core's `HostOptions.ShutdownTimeout` value as [written in this post](https://andrewlock.net/extending-the-shutdown-timeout-setting-to-ensure-graceful-ihostedservice-shutdown/#the-solution-increase-the-shutdown-timeout) at least to 20 seconds to be sure the host doesn't affect the behavior?

**Comment by odinserj** [comment]
> i have another "IHostedService" in my application with a Thread.Sleep

But this can be the reason and if .NET Core allows one background service to block another ones during shutdown, then probably using `ApplicationStopping` all the times is the best idea to have a consistent behavior.

**Comment by joaozacharias** [comment]
> @joaozacharias can you also try to increase the .NET Core's `HostOptions.ShutdownTimeout` value as [written in this post](https://andrewlock.net/extending-the-shutdown-timeout-setting-to-ensure-graceful-ihostedservice-shutdown/#the-solution-increase-the-shutdown-timeout) at least to 20 seconds to be sure the host doesn't affect the behavior?

Yes, i did.
![image](https://user-images.githubusercontent.com/28767219/183385089-6e5725bb-845c-4652-acb8-58258b84446c.png)
This "ShutdownTime" value is 90 seconds.
