### ISSUE TITLE
ContinueBatchWith overload missing for job continuation with async method

### ISSUE THREAD

**Issue by sbaird32** [HangfireIO/Hangfire#2085]
As far as I can tell, there is a missing overload on `BackgroundJobClientExtensions` for running a job continuation using an `Expression<Func<Task>>`. The overload does exist for `Expression<Action>`.

This means that within a nested batch, I cannot continue a batch with a job that calls an async method by using `IBatchAction.ContinueBatchWith()`.

I believe the missing overload on `BackgroundJobClientExtensions` should be:
```
public static string ContinueBatchWith([NotNull] this IBackgroundJobClient client, [NotNull] string batchId, [InstantHandle] Expression<Func<Task>> methodCall, [CanBeNull] IState nextState = null, BatchContinuationOptions options = BatchContinuationOptions.OnlyOnSucceededState)
```

Versions:
Hangfire.Pro 2.3.0.0
Hangfire.Core 1.7.30.0

**Comment by odinserj** [comment]
Thank you for reporting this! You are totally correct, I've just added the missing methods, but unfortunately for .NET Core platforms only to avoid breaking changes. Here's the announce – https://www.hangfire.io/blog/2022/08/26/hangfire.pro-2.3.1.html.
