### ISSUE TITLE
Dashboard AllowAnonymous

### ISSUE THREAD

**Issue by clint2627** [HangfireIO/Hangfire#2116]
Is there a way to flag the Dashboard endpoint with AllowAnonymous? This is a .net core 3.1 project. I can't seem to bypass the authentication setup for the rest of my project. What I would like to do is set the [AllowAnonymous] attribute on the dashboard page. Is this possible somehow? 

Basically I have authentication wrapped around all endpoints. A JWT token is required. If there is an endpoint (or entire controller) I don't care about authenticating, I can simply add the [AllowAnonymous] attribute to it. I want to do something similar with hangfire dashboard. Otherwise .net core will not allow me to browse to the dashboard without a valid JWT token.

**Comment by hasanmanzak** [comment]
```
        app.UseHangfireDashboard(options: new DashboardOptions
        {
            Authorization = new List<IDashboardAuthorizationFilter> { new NoAuthFilter() }
        });
```

**Comment by clint2627** [comment]
Thanks but I think I have a different issue going on now. Running locally everything is working as expected. But once deployed to our kubernetes environment I get 401. But I think I will try your example and see what happens.

**Comment by hasanmanzak** [comment]
I missed this part, sorry:

```
public class NoAuthFilter : IDashboardAuthorizationFilter
{
    public bool Authorize(DashboardContext context)
    {
        return true;
    }
}
```

**Comment by clint2627** [comment]
Progress! The dashboard is loading but there's no styling. Any tips on that?

**Comment by clint2627** [comment]
I know whats going on. Just don't know what to do about it. Is there any way to tell hangfire what the root of the site is ?

**Comment by clint2627** [comment]
I used the PrefixPath and that seemed to solve my issue. Now I need to figure out how to get basic authentication working so it prompts for credentials.

**Comment by clint2627** [comment]
I got basic auth working: https://github.com/HangfireIO/Hangfire/issues/2118
