### ISSUE TITLE
Critical vulnerability found (GHSA-8g2p-5pqh-5jmc) in System.Data.SqlClient <= 4.8.4

### ISSUE THREAD

**Issue by JoostvdB94** [HangfireIO/Hangfire#2123]
See https://github.com/advisories/GHSA-8g2p-5pqh-5jmc

System.Data.SqlClient 4.4.0 that is targeted in Hangfire.SqlServer is affected by security vulnerability / advisory GHSA-8g2p-5pqh-5jmc

Updating to System.Data.SqlClient 4.8.5 should resolve this problem

**Comment by JoostvdB94** [comment]
You're right. I'll close this issue and the PR

**Comment by 0xced** [comment]
Also, note that starting with version 1.8.0-rc2, the `Hangfire.SqlServer` package does not depend on `System.Data.SqlClient`  anymore at all. The consumer is in charge to choose between `System.Data.SqlClient` and `Microsoft.Data.SqlClient`, including the version he wants to use.
