### ISSUE TITLE
The HtmlHelper class should provide access the UrlHelper

### ISSUE THREAD

**Issue by 0xced** [HangfireIO/Hangfire#2142]
If you register a customer job history renderer with `JobHistoryRenderer.Register` you'll have a `HtmlHelper`. But if you need to render a link to a custom razor page that you registered you are out of luck since you don't have access to the `UrlHelper` and its `To` method.

As a workaround I had to use reflection in https://github.com/ahydrax/Hangfire.Atoms/pull/9: https://github.com/0xced/Hangfire.Atoms/blob/59cd5e91526f02392de194ff680d2351904c542b/src/Hangfire.Atoms/Dashboard/HtmlUtils.cs#L17

What would be the best way to fix this? Expose it as a property like this? `UrlHelper Url => _page.Url;` 

Note: this is true as of both Hangfire.Core 1.7.32 and 1.8.0-rc2.

**Comment by odinserj** [comment]
Thanks @0xced, added `HtmlHelper.Page` property to the `dev` branch. `_page` field is still here, to reflection-based approach will not be broken.

**Comment by 0xced** [comment]
I had found another (convoluted) way without accessing the private `_page` field for Hangfire.Atoms: https://github.com/ahydrax/Hangfire.Atoms/commit/af17f6f556ade2569e222eae5638560b8d804dbe

But having the `Page` exposed publicly is a good idea anyway. 👍 I have other projects where I'm still relying on the private `_page` field for custom job history renderers.

**Comment by 0xced** [comment]
For the record: this was commit 1ae167e3ffc87429a64cf95201c40508101cf25c that shipped as part of Hangfire 1.8.0-rc3.
