### ISSUE TITLE
Jsonb data type for jobs table in postgresql 

### ISSUE THREAD

**Issue by sahapasci** [HangfireIO/Hangfire#2145]
Postgresql supports jsonb data type which can be used in `jobs` tables `arguments` columns so that postgresql can use indexes while running some sql queries related with `arguments` column

**Comment by azygis** [comment]
This is not the correct repo to report Hangfire.PostgreSql issues. Anyway, [it's been reported](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/266) and I started working on it.

This one can be closed.
