### ISSUE TITLE
A way to delete Failed jobs after some days

### ISSUE THREAD

**Issue by hnalpha323** [HangfireIO/Hangfire#2156]
Hi, 
I understand that Succeeded jobs are deleted after a day.
However, failed jobs are never cleaned and keep clogging up the space.
We want to put a retention of 30 days. so we have enough time to trace back a job to queue it but if we don`t check it doesn`t keep clogging the space,
I saw we can use "AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete) " to delete them but I believe it just deletes the job right after the retries.

Is there any way to delete the failed jobs after some days?
We`re using Hangfire 1.7.31 with Redis storage

**Comment by talhaimam** [comment]
@hnalpha323 Did you have any luck with this topic? We are currently sitting on loads of failed jobs in Redis and we want to both clean them all up right away, and also implement a permanent process for cleanup.

**Comment by robertoandrade** [comment]
looking for a similar solution here. Only option I could think of was to schedule a job to query the storage for the history of jobs and delete them via code?

**Comment by talhaimam** [comment]
I have obtained the following code sample from Hangfire Support to clean up failed jobs. They said we can substitute the "count" parameter in the URL to display more jobs on the same screen (don't use hundreds of thousands though).

```
var api = JobStorage.Current.GetMonitoringApi(); 
var failedJobs = api.FailedJobs(0, 1000 /* limit */);

while (failedJobs.Count > 0)
{
    foreach (var job in failedJobs)
    {
        BackgroundJob.Delete(job.Key);
    }

    failedJobs = monitor.FailedJobs(0, 1000 /* limit */);
}
```

They said that we can apply the AttemptsExceededAction.Delete to delete background jobs instead of failing them when all retry attempts are exhausted:
`GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 10, OnAttemptsExceeded = AttemptsExceededAction.Delete });`

I still don't get how/where I would use the code sample to clean up failed jobs, any ideas? @robertoandrade  @hnalpha323

**Comment by GlebPunko** [comment]
where can I find full code for fix this bug that you overwrite? I wanna delete failed tasks from Hangfire and how can I register this method?

**Comment by hnalpha323** [comment]
The code I pasted above is the full code for a Recurring Job to delete failed jobs
for how to register it? 
Inside your JobSchedulerWorker (which should be an IHostedService) you can something like this 
            `await Task.Run(() => _jobScheduler.ScheduleFailedJobsCleanupJob(_jobDispatherConfiguration.JobIntervalCronExpression), cancellationToken);`
where in your Job Scheduler you can 

```
public void ScheduleFailedJobsCleanupJob(string cronJobExpression)
        {
            if (_jobsCleanupEnabled)
            {
                _logger.LogInformation("Scheduling Hangfire Failed Jobs Cleanup");
                RecurringJob.AddOrUpdate("HangFireJobsCleanup", () => _jobFactory.Create<FailedJobsCleanupJob>().Execute(JobCancellationToken.Null), cronJobExpression);
                _logger.LogInformation("Done Scheduling Hangfire Failed Jobs Cleanup");
            }
        }
```
        
        Remember to AddTransient of your cleanupJob class in DI

**Comment by sabiland** [comment]
Would be cool if there was a `button` on Dashboard UI to delete **ALL** `Failed jobs`.
