### ISSUE TITLE
Timezone Problems in Dashboard

### ISSUE THREAD

**Issue by cm-andrews** [HangfireIO/Hangfire#2166]
We have started noticing issues in the dashboard recently where servers are being marked as unresponsive in the server overview as the dashboard thinks that the last heartbeat has been over an hour ago.

The client PC and the server are all set to Europe/Berlin (+1). The issue is not present if the timezone set in the Postgresql configuration is etc/UTC.

I initially reported the issue at https://github.com/frankhommers/Hangfire.PostgreSql/issues/284 to no avail.

**Comment by azygis** [comment]
We've fixed the issue in the storage provider, this can be closed.
