### ISSUE TITLE
Stucked Handfire.SqlServer.DynamicMutex 

### ISSUE THREAD

**Issue by knopa** [HangfireIO/Hangfire#2179]
My configuration 

- hangfire version 1.7.33
- .net 7
- linux docker on azure app service with vnat outbound
- hangfire has separate database and in connection string i have max pool size 150
- according to db metricts i have max 9-10 open session per minute
- i had job running over 12h (usual one)

I have experience issue with 
Handfire.SqlServer.DynamicMutex with CreateAndOpenConnection
System.Data.ProviderBase.DbConnectionFactory.TryGetConnection
with next exception
**Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.**

After some time i Server will be restarted due to server timeout and stopped non-gracefully, but jobs keep running old one but new got timeout exception in 15s

**Comment by odinserj** [comment]
Please try to install the latest version of the `System.Data.SqlServer` explicitly as shown in the first paragraphs of https://docs.hangfire.io/en/latest/configuration/using-sql-server.html

**Comment by odinserj** [comment]
Hi @knopa, was the issue resolved after upgrading the `System.Data.SqlClient` package?

**Comment by knopa** [comment]
Hi @odinserj, in generally it's so rare issue but very painfull. We got it only once. Hard to say does if it fully goes away. I'll let you know if it happens again.

**Comment by odinserj** [comment]
Thanks for your response, will be happy to hear if the issue persists
