### ISSUE TITLE
Log custom messages to the job history page?

### ISSUE THREAD

**Issue by ses4j** [HangfireIO/Hangfire#218]
The job history page currently shows Processing, Succeeded, etc.  Is it possible for a job to write arbitrary logging (for instance, periodic "current status" messages or warnings) into it? If not, is that a feature you are interested in?

**Comment by samcalma** [comment]
How can we help on getting this implemented?

**Comment by vip32** [comment]
+1

**Comment by efirdman** [comment]
+1

**Comment by pascalberger** [comment]
+1

**Comment by peters** [comment]
+1

**Comment by searope** [comment]
+1

**Comment by oliverkane** [comment]
+1

**Comment by ses4j** [comment]
Note that pull request #232 (referenced above but maybe lost in the chain) implements this.

**Comment by RuiRomano** [comment]
+1

**Comment by dazinator** [comment]
+1

**Comment by samshiles** [comment]
Please see: https://github.com/samshiles/hangfire.job.logging for one way to get job output logged to the hangfire console. It requires a very small change to hangfire which should be 100% backwards compatible. PR: #466

**Comment by IanGrainger** [comment]
+1

**Comment by stajs** [comment]
+1

**Comment by vip32** [comment]
@samshiles : first thanks for sharing the idea to insert in the state table directly.
however, you don't need to inject the jobid, using a jobcontext makes it much easier and transparant
this can be used inside your joblogger to get the right jobid. i just did that in my project and works really well.

public class JobContext : IServerFilter
    {
        [ThreadStatic]
        private static string _jobId;
        [ThreadStatic]
        private static Type _jobType;

        public static string JobId { get { return _jobId; } set { _jobId = value; } }

        public static Type JobType { get { return _jobType; } set { _jobType = value; } }

        public void OnPerforming(PerformingContext context)
        {
            JobId = context.JobId;
            JobType = context.Job.Type;
        }

        public void OnPerformed(PerformedContext filterContext)
        {
        }
    }

**Comment by jasoncouture** [comment]
+1

**Comment by DonWMason** [comment]
+1

**Comment by cocowalla** [comment]
+1

**Comment by gandarez** [comment]
+1

**Comment by Mykezero** [comment]
+1

**Comment by MaxMelcher** [comment]
+1

**Comment by mrcrbrown** [comment]
+1

**Comment by migajek** [comment]
+1

**Comment by sergeyzwezdin** [comment]
Any update on this?

**Comment by smith288** [comment]
+1

**Comment by dandcg** [comment]
+1

**Comment by trudeo** [comment]
+1.

Any update on this?

**Comment by maklipsa** [comment]
+1

**Comment by jonnyaeast** [comment]
+1

**Comment by slypete** [comment]
+1

**Comment by reggieboyYEAH** [comment]
+1

**Comment by TcPhilBushnell** [comment]
+1

**Comment by kevinpengz** [comment]
+1

**Comment by raphaelpare** [comment]
+1

**Comment by cable729** [comment]
+1

**Comment by odinserj** [comment]
Hey guys, see what @pieceofsummer did in the [Hangfire.Console](https://github.com/pieceofsummer/Hangfire.Console) extension, even with colours and live updates! Almost all storages are supporting this with no changes!

![dashboard](https://cloud.githubusercontent.com/assets/1078718/19828235/cf0aa914-9dc9-11e6-93b4-2cb33eff1c28.png)

**Comment by vip32** [comment]
@odinserj That looks very cool. Just what we need.
I suppose this also uses the hangfire tables for its storage (SQL server provider). Any recommendation on that, does that scale?

**Comment by pieceofsummer** [comment]
@vip32 it uses Hangfire's Sets to store data. 

If you're going to log large amounts of data, or having lots of jobs daily, you can setup clustering (sharding/whatever it is called in your DB engine) of sets table by key. Also decreasing the amount of time console logs are stored may be an option.

P.S. Logging large amounts of data is not recommended, as the browser may just hang while displaying it. After all, the purpose is to track job status, not to dump debug logs. Use it wisely :)

P.P.S. I've also added progress bars in the latest build, so it's even more fun now.

**Comment by waynebrantley** [comment]
@pieceofsummer Great library...exactly what was needed!!
