### ISSUE TITLE
DashboardUI authentication with AAD/Microsoft.Identity.Web

### ISSUE THREAD

**Issue by Trapulo** [HangfireIO/Hangfire#2186]
Hi,
I cannot find a way to make DashboardUI to authenticate users based on AAD/Microsoft.Identity.Web. I'm looking for a way to authorize Dashboard to a list of users from AAD (the "main" is authenticating users there).

All docs and auth library seems old.

any idea?
.NET core 7
thanks

**Comment by Trapulo** [comment]
I have:
`    builder.Services
          .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
          .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureAd"));
`
so I tried:
`
   app.MapHangfireDashboard("/hangfire", new DashboardOptions
        {
            Authorization = new[] { new HangfireAuthorizationFilter() },
        }).RequireAuthorization();

...

public class HangfireAuthorizationFilter : IDashboardAuthorizationFilter
{
    public bool Authorize(DashboardContext context)
    {
        return true;
    }
}
`

and if I get /hangfire, it returns an HTTP 401

**Comment by Trapulo** [comment]
My project was missing

```
  builder.Services
            .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));

```
to enable also web app sign in and authentication features, and not webapi authentication only that I use.

**Comment by mohammedsouleymane** [comment]
> My project was missing
> 
> ```
>   builder.Services
>             .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
>             .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));
> ```
> 
> to enable also web app sign in and authentication features, and not webapi authentication only that I use.

@Trapulo Does this work when you host the application.

**Comment by mohammedsouleymane** [comment]
@Trapulo I am able to use the openid connect but it only works on localhost any ideas on what could be causing this.

**Comment by Trapulo** [comment]
> @Trapulo I am able to use the openid connect but it only works on localhost any ideas on what could be causing this.

too hard to find. Maybe you have some policy loaded that limits in your asp.net, I don't know sorry

**Comment by dashberg** [comment]
@Trapulo dude it took me forever to figure out you were using webapp (AddMicrosoftIdentityWebApp) and not webapi. In the end you saved my day :)
