### ISSUE TITLE
Perfomance degradation of dequeue operation after upgrading to 1.7.34

### ISSUE THREAD

**Issue by ivanovevgeny** [HangfireIO/Hangfire#2188]
I upgraded from v1.7.11 to 1.7.34, after that tasks from Enqueued began to be distributed much more slowly.

Environment:
- average 2-10 new jobs/sec
- 6 servers with hunders workers

My configuration:

```
GlobalConfiguration.Configuration
	.UseSqlServerStorage("DB", new SqlServerStorageOptions
	{
	  CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
	  SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
	  QueuePollInterval = TimeSpan.Zero,
	  UseRecommendedIsolationLevel = true,
	  DisableGlobalLocks = true
	});
```

I found out that the problem appeared in version 1.7.28 - with long polling, if polling interval is less than 1 second.
I didn't want to rollback from 1.7.34 to 1.7.27, so I changed QueuePollInterval to 1 sec, and issue was resolved for my environment.

Enqueued count from zabbix
![image](https://user-images.githubusercontent.com/8840414/230596562-c9fc34a3-2fea-4445-8322-e5c80ae14c62.png)

**Comment by odinserj** [comment]
Thanks for reporting this! Will be fixed in 1.7.35 today.
