### ISSUE TITLE
Keyword not supported: trust server certificate

### ISSUE THREAD

**Issue by fairking** [HangfireIO/Hangfire#2192]
Hi everyone,

Hangfire v.1.7.34

The following latest braking changes https://stackoverflow.com/questions/17615260/the-certificate-chain-was-issued-by-an-authority-that-is-not-trusted-when-conn

On some of my development server I use `TrustServerCertificate=True;` in my mssql connection string for EF7 and it is working fine. But Hangfire throws the following error:
```
Start installing Hangfire SQL objects... Keyword not supported: 'trust server certificate'.
```

Is there any way to fix such issue?

Thanks.

**Comment by odinserj** [comment]
That's because Hangfire 1.7.X uses System.Data.SqlClient version by default. I just released Hangfire 1.8.0 that sticks with Microsoft.Data.SqlClient instead, so configuration will be the same with EF7. In previous versions you can use Microsoft.Data.SqlClient in the following way:

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(
        () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
```
