### ISSUE TITLE
SqlServerStorageOptions SqlClientFactory does not compile?

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#2193]
EDIT 1: I have **managed** to make it work (Upgraded to `Schema 9`) without `SqlClientFactory` setting by adding `TrustServerCertificate=True;` to connection string.

EDIT 2: Does Hangfire 1.8.0 **takes automatically default optimal init settings** as it was necessary to add in 1.7 ?

EDIT 3: New `Dashboard` looks `fantastic`.

----------------------------------------------------------------------

Trying to migrate to 1.8.0. I use` System.Data.Sql` through all the app.

This does not compile:
```
GlobalConfiguration.Configuration
    .UseSqlServerStorage("connection_string", new SqlServerStorageOptions
    {
        SqlClientFactory = System.Data.SqlClient.SqlClientFactory
        // or
        SqlClientFactory = Microsoft.Data.SqlClient.SqlClientFactory
    });
```
`Error | CS0119 | 'SqlClientFactory' is a type, which is not valid in the given context`

There are issues with certificate? Because maybe Hangfire 1.8.0 uses `Microsoft.Data.Sql `instead of `System.Data.Sql` ?

`{"ClassName":"Hangfire.BackgroundJobClientException","Message":"Background job creation failed. See inner exception for details.","Data":null,"InnerException":{"ClassName":"Microsoft.Data.SqlClient.SqlException","Message":"A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)","Data":{"HelpLink.ProdName":"Microsoft SQL Server","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"-2146893019","HelpLink.BaseHelpUrl":"https://go.microsoft.com/fwlink","HelpLink.LinkId":"20476","ExecutionId":"f6b44443-1aec-4f4a-8414-f2bdc7a0daef","SqlError 1":"Microsoft.Data.SqlClient.SqlError: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)"},"InnerException":{"ClassName":"System.ComponentModel.Win32Ex…`

**Comment by odinserj** [comment]
Great you was able to resolve the issue, I just added more warnings to the upgrade guide and release notes. Yes, recommended settings will be applied automatically now based on the current schema version, unless `TryAutoDetectSchemaDependentOptions` is disabled: https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuration. And yeah, dashboard can now accommodate almost everything 😎.

**Comment by sabiland** [comment]
> Yes, recommended settings will be applied automatically now based on the current schema version
Great!

> And yeah, dashboard can now accommodate almost everything 😎.
Also great! What I miss with dashboard is Queues (if more than one `default` used for example) tab.

**Comment by odinserj** [comment]
> Also great! What I miss with dashboard is Queues (if more than one default used for example) tab.

Hm, what do you mean?

**Comment by sabiland** [comment]
I mean some preview (or maybe statistics) about all queues used. I use one default queue and one custom queue (and possibly more in the future).

**Comment by odinserj** [comment]
Yes, nothing is changed for the queues since 1.7.X.

**Comment by sabiland** [comment]
👍👍
