### ISSUE TITLE
UseDefaultCulture override for captureDefault

### ISSUE THREAD

**Issue by niphlod** [HangfireIO/Hangfire#2195]
Hi,
   following https://www.hangfire.io/blog/2023/04/28/hangfire-1.8.0.html#default-culture I was trying to set `captureDefault : false` but it doesn't seem that `UseDefaultCulture` has a valid interface for it.

**Comment by odinserj** [comment]
Wow, don't understand how this happened. The corresponding overloads are really missing, will add them in 1.8.1 release soon, thanks for the report!

**Comment by niphlod** [comment]
no worries, keep up with the good work ;-)
