### ISSUE TITLE
Dashboard UI -> Force Light/Dark mode

### ISSUE THREAD

**Issue by meriturva** [HangfireIO/Hangfire#2197]
There is any way to force light/dark mode for DashBoard UI?

I'm updating to the latest version 1.8.x and I don't find an easy way to disable dark mode.
Thanks.

**Comment by odinserj** [comment]
Sure, I will add an option to disable dark mode support. It's currently applied by a [separate CSS](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/Content/css/hangfire-dark.css) and we can just don't include it when corresponding option is disabled.

**Comment by glen-84** [comment]
@odinserj It would be nice if you could also force light/dark mode, independent of your operating system preference.

**Comment by odinserj** [comment]
> @odinserj It would be nice if you could also force light/dark mode, independent of your operating system preference.

Unfortunately it's much more difficult to implement given the current implementation of dark mode, so will be postponed. Perhaps there will be a way in browsers themselves to toggle different modes for a particular page.
