### ISSUE TITLE
UseDashboardStylesheet and UseDashboardJavaScript -> not present on GlobalConfigurationExtensions

### ISSUE THREAD

**Issue by meriturva** [HangfireIO/Hangfire#2198]
Looking at the updated global configuration class:

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/GlobalConfigurationExtensions.cs#L215

I found a new method `UseJobDetailsRenderer` (thanks I will look deeply into that new feature to integrate log info to detail job page)
but I don't find any methods named: `UseDashboardJavaScript` and `UseDashboardStylesheet` present in the blog post:

https://www.hangfire.io/blog/2023/04/28/hangfire-1.8.0.html#custom-css-and-javascript-resources

Am I wrong?
Thanks

**Comment by odinserj** [comment]
Thanks for the report, I will add them and release 1.8.1 soon. Currently they can be accessed via `DashboardRoutes.AddJavaScript` and `DashboardRoutes.AddStylesheet` methods (`Hangfire.Dashboard` namespace).
