### ISSUE TITLE
After upgrading to 1.8.0 some drop of performance

### ISSUE THREAD

**Issue by sabiland** [HangfireIO/Hangfire#2199]
I am writing this just for info. After upgrading `Hangfire` to` 1.8.0` and `Schema 9` successfully, I've noticed some drop (every cca. hour issues happen (slowness), maybe MSSQL locks DB because of slowness or locks) of `performance` on Jobs which are `10-20/sec`.

We will create new empty DB and start totally fresh. Will `notify` here when it's done.

**Comment by odinserj** [comment]
Can you post here your configuration logic related to Hangfire? Because otherwise there should be less network calls and thus better throughput. Migrations weren't so big as in version 1.7.0 so should affect anything heavily.

**Comment by sabiland** [comment]
Look screenshot below. Since upgrading to `1.8.0` our most frequent Hangfire operation (up to `30/sec` in peak time) started to have problems. Not always, from time to time. Graph is for `2 days`. Last time (`1.7.x`) I we had an issues it was because MSSQL started blocking Hangfire, because Hangfire was making `1000s operations/sec`. After we started on clean/empty DB, everything was OK. So I guess upgrade to `Schema 9` is not optimal?

<img width="1259" alt="Screenshot 2023-05-04 at 09 57 21" src="https://user-images.githubusercontent.com/12098915/236144144-cd88f41e-5057-4f47-bf62-2a1c02fbbde3.png">

`Today we will do the same` - Will create `new empty DB` and I'll just change `connection string` and notify it here if everything will be ok.

**Comment by odinserj** [comment]
Hm, there should be nothing special. Can you post here your configuration logic related to Hangfire (and tell me whether you changed anything after upgrade) to understand it more? Also, what offering and pricing tier are you using for your SQL Server offering?

**Comment by sabiland** [comment]
This is my configuration for 1.8.0. Of course I `removed` `recommended defaults` as per `your documentation `right?

```
// NOTE: 28042023 - AUTOMATIC DEFAULT VALUES !!!
// https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.8.html
// https://docs.hangfire.io/en/latest/getting-started/aspnet-core-applications.html
services.AddHangfire(configuration => configuration
    .SetDataCompatibilityLevel(CompatibilityLevel.Version_180)
    .UseSimpleAssemblyNameTypeSerializer()
    .UseRecommendedSerializerSettings()
    .UseSqlServerStorage(tsHangfireConnectionString, new SqlServerStorageOptions()
    {
        EnableHeavyMigrations = true
    })
    );
// NOTE: 28042023
// https://docs.hangfire.io/en/latest/background-processing/configuring-queues.html
// NOTE: 30082021
services.AddHangfireServer(options =>
{
    options.Queues = new[] { Globals.hangfireQueueDefault, Globals.hangfireQueueNeoPopup };
});
// END: Hangfire
```

**Comment by sabiland** [comment]
It seems starting with new clean DB and Schema 9 solved all the issues. I think there has to be some issues when upgrading DB Schemas.

**Comment by sabiland** [comment]
Yes, definitely going to new `clean empty DB `(Schema 9) solved the issues. Look at the graph. Everything ok now.

<img width="675" alt="Screenshot 2023-05-05 at 08 43 00" src="https://user-images.githubusercontent.com/12098915/236393059-978c347c-5358-47f1-8ff4-44ef94319a7c.png">

**Comment by odinserj** [comment]
This can be caused by buffer pool, since a lot of pages can be loaded into memory during the migration. What offering are you using for SQL? And what hardware / pricing tier?

**Comment by sabiland** [comment]
`What offering are you using for SQL? And what hardware / pricing tier?` Emm what do you mean by that ?

**Comment by odinserj** [comment]
> What offering are you using for SQL? And what hardware / pricing tier?

E.g. what type of SQL Server you are using – on-premise on dedicated hardware, on VM or some cloud-based offering like SQL Azure Managed Databases, etc. And also what's the actual hardware / pricing tier is used.

> 1000-10.000 calls to DB per second

Hm, do you have any evidence for this? Especially useful would be to know what are the actual queries that are being executed during this time.

**Comment by sabiland** [comment]
> E.g. what type of SQL Server you are using – on-premise on dedicated hardware, on VM or some cloud-based offering like SQL Azure Managed Databases, etc. And also what's the actual hardware / pricing tier is used.

MSSQL 2012 on-premise on high-end dedicated machines. Soon we will migrate to MSSQL 2019 servers.
 
> > 1000-10.000 calls to DB per second
> 
> Hm, do you have any evidence for this? Especially useful would be to know what are the actual queries that are being executed during this time.

Yes, our DataBase guys made analysis and they saw this clearly from the data.

-------------------
Can you please confirm, that 1.7.x default init settings are applied in 1.8.0 without need to set them up? I am not sure if this is true after 1 week checking our production app/graphs/DB.

**Comment by sabiland** [comment]
@odinserj Our DB guys checked HangfireDB. A lot of lockings happens. Here are some logs if it helps you. We run 4 apps (DotNet7) on 4 servers and one MSSQL Hangfire DB.

```
Blocked session id: | 514 (blocked by 312)
-- | --
Blocked process: | Core Microsoft SqlClient Data Provider
Database: | TSHangfire3
Host: | V-FPW-TVCHL-01
User: | TSHangfireUser
Start time: | 8 maj 2023 14:38
Blocked SQL fragment: | xp_userlock

<div style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif, serif, EmojiFont; font-size: 15px; padding: 0px 0px 0px 15pt; border-style: none none none solid; border-left-width: 6pt; border-left-color: rgb(238, 238, 238);"><ul style="margin-top: 0px; margin-bottom: 0px;"><ul style="margin-top: 0px; margin-bottom: 0px;"><li style="margin: 0px;"><font face="Calibri,sans-serif" size="2" style="font-family: Calibri, sans-serif, serif, EmojiFont;"><span style="font-size: 11pt;"><font face="Segoe UI,sans-serif" style="font-family: &quot;Segoe UI&quot;, sans-serif, serif, EmojiFont;"><span lang="en"> </span></font></span></font></li></ul></ul></div>
```

**Comment by odinserj** [comment]
What's the output of the following query? We need to ensure it correctly populated – I see that it's blocked on `xp_userlock`.

```sql
SELECT * FROM [HangFire].[Schema]
```

**Comment by sabiland** [comment]
Ok I asked the guys...Will notify you.

**Comment by sabiland** [comment]
<img width="456" alt="Screenshot 2023-05-09 at 13 05 24" src="https://github.com/HangfireIO/Hangfire/assets/12098915/b1d99df3-5454-44e9-913f-16b6686dd0dc">

**Comment by sabiland** [comment]
It looks like this locking happens exactly `periodically`:

<img width="1225" alt="Screenshot 2023-05-09 at 13 14 48" src="https://github.com/HangfireIO/Hangfire/assets/12098915/df9d7eb7-0a85-4d8c-9455-8f5ce2d47d12">
<img width="1240" alt="Screenshot 2023-05-09 at 13 15 49" src="https://github.com/HangfireIO/Hangfire/assets/12098915/61792fcd-1723-40fe-b69b-b4cee9ee2fac">

**Comment by odinserj** [comment]
Please try to set the `SqlServerStorageOptions. DeleteExpiredBatchSize` to 1000. Looks like full table scan is used when expiring all jobs (each 30 minutes). If it's the case, I will add a table hint to force seeks in expiration queries in 1.8.1.

**Comment by sabiland** [comment]
Ok I'll try right now, but it says, that `default` value is already `1000` ?

<img width="1040" alt="Screenshot 2023-05-09 at 14 58 30" src="https://github.com/HangfireIO/Hangfire/assets/12098915/d5bc9dd1-979f-45bd-af9d-b04557586183">

I will notify if there will be some improvements.

**Comment by odinserj** [comment]
Great, thanks a lot for your assistance! Please let me know if this happens again. 

Expiration manager seems like the last place that doesn't use table hints to avoid table scans – all the other queries already use `WITH (FORCESEEK)` to make queries predictable. Will include the fix with 1.8.1.

**Comment by sabiland** [comment]
Ok. `Will monitor whole week everything` and notify you. Thanks for your quick help today!

**Comment by odinserj** [comment]
Really happy we tracked this down, I will also update the code docs, that this is schema-dependent value now in 1.8.

**Comment by sabiland** [comment]
FYI, everything is OK now. GREAT stuff! :) Red line shows deploy with 1000 init setting.

<img width="715" alt="Screenshot 2023-05-10 at 09 15 28" src="https://github.com/HangfireIO/Hangfire/assets/12098915/5de40d09-3426-4160-bf10-e891a9d3468f">

**Comment by odinserj** [comment]
That's really awesome news, thanks for feedback! I will add the missing table hint to avoid full table scans that 99% cause this problem in 1.8.1.

**Comment by sabiland** [comment]
@odinserj  Just one quick question. When those issues `were still going on`, ma App was returning randomly `503 (Service Unavailable)` to clients. But my App didn't crash, it ran normally. Could that be related somehow to those Hangfire issues/blockings?

**Comment by odinserj** [comment]
Timeouts can cause this, however we should see the logged exception messages to know for sure.

**Comment by sabiland** [comment]
EventViewer logs on server says this for 503 response:
`The TLS protocol defined fatal alert code is 70. The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly. Source: The previous system shutdown at 1:04:13 PM on ‎5/‎5/‎2022 was unexpected.
`

**Comment by odinserj** [comment]
Omg, found only this one – https://stackoverflow.com/questions/67634538/the-tls-protocol-defined-fatal-alert-code-is-70, don't understand whether it can be related to Hangfire.
