### ISSUE TITLE
Hangfire 1.8 - SQL Server User Account Permission Error

### ISSUE THREAD

**Issue by HernJer** [HangfireIO/Hangfire#2200]
After upgrading to version 1.8 we are continuously receiving the below error: 
Exception caught: 'Microsoft.Data.SqlClient.SqlException' in Microsoft.Data.SqlClient.dll ("The user does not have permission to perform this action.") 

The exception continues nonstop. Can I be provided the required permissions for the service account or a way to disable to functionality if unable to assign permissions?

**Comment by odinserj** [comment]
Thanks for details @HernJer. I think we can make an attempt to fetch those counters and disable further lookups if they can't be obtained. What do you think?

**Comment by HernJer** [comment]
Yes that would work. Would also be a good idea to disable the lookup from setup. Maybe add a DisablePerformanceCounterFetch option to SqlServerStorageOptions. The dashboard would also need a change to remove the metrics from displaying. Currently they display ??? values. For a clean look they could be prevented from displaying using the SqlServerStorageOptions setting.

**Comment by odinserj** [comment]
Sure, will do this in the next patch release, thank you for reporting.

**Comment by restimartinez** [comment]
Just a contribution. 

In addition to the above I have noticed in my database the object name does not start with SQLServer:Databases. In the code I see that the call is hardcoded : 

SqlServerStorage.PerformanceCounterDatabaseMetric("SQLServer:Databases", "Active Transactions", null)
SqlServerStorage.PerformanceCounterDatabaseMetric("SQLServer:Databases", "Data File(s) Size (KB)", null)
SqlServerStorage.PerformanceCounterDatabaseMetric("SQLServer:Databases", "Log File(s) Size (KB)", null)

![Capture](https://github.com/HangfireIO/Hangfire/assets/11334802/507ed4b8-d4f4-4c89-923b-e8a2f6c5a395)

"SQLServer:Databases" not found in my database

**Comment by odinserj** [comment]
Fixed in https://github.com/HangfireIO/Hangfire/commit/3c0eab97eb62dcf29a82d1c4d53bc4acc200d12f and https://github.com/HangfireIO/Hangfire/commit/9fddeb12830fa0126022a26013e629099fbe2d81, works fine on SQL Azure.
