### ISSUE TITLE
Question - IBackgroundJobClientV2, IRecurringJobManagerV2

### ISSUE THREAD

**Issue by coolhome** [HangfireIO/Hangfire#2206]
With the introduction of `IBackgroundJobClientV2` and `IRecurringJobManagerV2` is the intent that `IBackgroundJobClient` and `IRecurringJobManager` are deprecated? This is a breaking change that prevents targeting 1.7 and 1.8 which is not clear in the release notes: https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.0

**Comment by odinserj** [comment]
I expect those V2 interfaces will be merged into regular ones in Hangfire 2.0 to avoid duplicating things – anyway there will be a breaking change.
