### ISSUE TITLE
Hangfire.AspNetCore 1.8.0  missing  IServiceCollection AddHangfireServer

### ISSUE THREAD

**Issue by giusemar** [HangfireIO/Hangfire#2208]
After upgradind my project by NuGet packages from Hangfire.AspNetCore 1.7.34  to 1.8.0  I had Compilation failed  :  problem is here: -> services.AddHangfireServer();  It seems we are missing the public static IServiceCollection AddHangfireServer() method.  My project use Microsoft.AspNetCore 2.2.0. Any idea?

**Comment by awright415** [comment]
Are you using AspNetCore within a .NET Framework application?

Upgrading to 1.8.0 wiped out those extension methods in our application (net472), presumably because it's matching the `!NET451` part of the directive, whereas those extension methods used to have a positive match for `NET461`.

**Comment by awright415** [comment]
@odinserj Any chance that `Hangfire.NetCore` not including `net461` as a target was just an oversight, since many of the relevant classes moved between projects for this release?

This situation seems a lot like this issue from a few years back, where `net461` was added to `Hangfire.AspNetCore` because a similar preprocessor directive meant newer .NET framework applications were getting the `net451` nuget.

https://github.com/HangfireIO/Hangfire/issues/1487

**Comment by giusemar** [comment]
currently i'm using Hangfire.AspNetCore 1.7.34 within a .NET4.8  Web Api application  with Microsoft.AspNetCore 2.2.0, and all works fine.   The problems come when i try to upgrade Nuget packages  Hangfire.AspNetCore 1.8.0  - Hangfire.SqlServer 1.8.0 (the only two packages required ) -   i don't know about "Hangfire.NetCore".

**Comment by odinserj** [comment]
> @odinserj Any chance that Hangfire.NetCore not including net461 as a target was just an oversight, since many of the relevant classes moved between projects for this release?

Looks like an oversight, yes, will check this.

**Comment by odinserj** [comment]
Thank for reporting this! I've just added the `net461` target for Hangfire.NetCore package, so it should be working in 1.8.1 that will be released soon.

**Comment by awright415** [comment]
> Thanks for reporting this! I've just added the `net461` target for Hangfire.NetCore package, so it should be working in 1.8.1 that will be released soon.

That's great news. Thank you for fixing this so quickly!
