### ISSUE TITLE
Reschedule an existing scheduled job ?

### ISSUE THREAD

**Issue by h-c-a** [HangfireIO/Hangfire#221]
In one of my methods i use BackgroundJob.Schedule to schedule a job with a time span of 5 minute.

BackgroundJob.Schedule(() => Console.WriteLine("Hello, world!"), TimeSpan.FromMinutes(5));

However in those five minute time span if i receive an update,i need to be able to reset the time span to 5 minutes again.

I need to know if its possible to get the instance of a scheduled job and is it possible to reset the time span on the job ?.

i wonder if this is possible?

**Comment by kszepieto** [comment]
What if job is part of a batch or there are any continuations build on this job ??
