### ISSUE TITLE
Hangfire 1.8 - Target schema version is less than the current schema version

### ISSUE THREAD

**Issue by marekbomber** [HangfireIO/Hangfire#2211]
After upgrading to version 1.8 we are continuously receiving the below error:
`Hangfire current database schema version 9 is newer than the configured SqlServerStorage schema version 8. Will not apply any migrations.`

Target schema version is 8:
https://github.com/HangfireIO/Hangfire/blob/v1.8.0/src/Hangfire.SqlServer/Install.sql#L20

Current schema version is 9, because it is achievable:
https://github.com/HangfireIO/Hangfire/blob/v1.8.0/src/Hangfire.SqlServer/Install.sql#L762

I think the script should be target schema version 9.

**Comment by odinserj** [comment]
Thanks for reporting this! Already committed the change, it will be available in 1.8.1.
