### ISSUE TITLE
Hangfire 1.8 - Full-Width Responsive Dashboard bug

### ISSUE THREAD

**Issue by ViolentRage** [HangfireIO/Hangfire#2213]
Hi,
I have a dashboard render bug.
I'm using a 4K screen, all pages are correct, except for the overview page: I have to scroll to see the footer.
![image](https://github.com/HangfireIO/Hangfire/assets/30320945/d251fdb2-c022-49e3-b910-6cab181d079e)
![image](https://github.com/HangfireIO/Hangfire/assets/30320945/003239e3-ac12-4dbd-8026-83d6484f4837)

Thanks.

**Comment by odinserj** [comment]
This is somehow related to the locked aspect ratios for charts. I will try to see what can we do here.
