### ISSUE TITLE
Hangfire.Autofac: include support for .NETStandard v2.0

### ISSUE THREAD

**Issue by ConPac** [HangfireIO/Hangfire#2219]
Hi,

It would be nice to include support for .NETStandard v2.0 in Hangfire.Autofac to ease its use besides recent versions of Autofac.

When publishing an ASP.Net project using .NET v7.0, Hangfire.Autofac v2.3.1 and Autofac v7.0.1, some errors appear telling about different versions used in several BCL libraries like System.IO.FileSystem and System.Net.Primitives. Those errors are resolved now adding references to the most recent version of that mentioned libraries.

Thanks in advance,
Paco.

**Comment by odinserj** [comment]
Please try the new Hangfire.Autofac 2.4.1 version, it should have everything included.

**Comment by ConPac** [comment]
It works as expected when publishing and there's no need now to add references to System.IO.FileSystem and System.Net.Primitives.
Thank you very much for your quick response.
