### ISSUE TITLE
WorkerCount doesn´t work

### ISSUE THREAD

**Issue by edelciomolina** [HangfireIO/Hangfire#2222]
I'm facing a weird problem and I can't find a solution.
I'm not sure if it's a bug or a configuration issue.

After I started using 3 servers _(physical machines)_ to run each one with a copy of the same version of Hangfire by Console, the WorkerCount settings stopped working as expected, running only 1 job at a time for each physical server.

Today I have 3 physical servers and for each of these I create N queues, each queue is destined to a customer.
I do it this way, to divide the tasks between my clients, allowing each one to have a little space for their requested jobs.

Notice from the images below, that I have 3 physical servers, associated in the same queue name, where each queue has a WorkerCount of 10. So I hope that each physical server can process 10 jobs from each queue, thus having 30 jobs at the same time.

![image](https://github.com/HangfireIO/Hangfire/assets/4604923/5cfd6d4b-ebaf-4926-be46-ad200de678fe)
![image](https://github.com/HangfireIO/Hangfire/assets/4604923/75eaacdd-1f64-48b7-af8b-21974a1b485f)
![image](https://github.com/HangfireIO/Hangfire/assets/4604923/8fb8d3f0-4e01-4f31-8836-c6d70a24bc25)

But notice below that the queue _(name of my customer, which was associated with the physical server)_ has several jobs allocated, but getting only 3, a quantity that can be seen below.

<img width="949" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/4604923/e0b35c54-2390-4a5b-8bdf-ed3de79783fd">

As proof, here is the queue of processes running, where you can see that each server only executes a single task at a time from the queue, while I expected it to be 10.

<img width="677" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/4604923/e4817523-5841-45fa-acc3-a057a5e05f74">

Below are some of the settings I'm using on my hangfire.
Did I miss some configuration or is this in fact a bug?

```c#
GlobalConfiguration.Configuration.UseConsole(new ConsoleOptions { BackgroundColor = "#292929" });
GlobalConfiguration.Configuration.UseJobsLogger();
GlobalConfiguration.Configuration.SetDataCompatibilityLevel(CompatibilityLevel.Version_180);
GlobalConfiguration.Configuration.UseSimpleAssemblyNameTypeSerializer();
GlobalConfiguration.Configuration.UseRecommendedSerializerSettings();
GlobalConfiguration.Configuration.UseSqlServerStorage(connectionString, new SqlServerStorageOptions()
{ 
    UseRecommendedIsolationLevel = true,
    CommandBatchMaxTimeout = TimeSpan.FromMinutes(60), 
    QueuePollInterval = TimeSpan.FromSeconds(5), 
    DisableGlobalLocks = true, 
    SlidingInvisibilityTimeout = TimeSpan.FromSeconds(30), 
});
GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute
{
    Attempts = System.Diagnostics.Debugger.IsAttached ? 0 : 3,
    DelaysInSeconds = new int[] {60 * 2 , 60 * 5, 60 * 10 }
});
```

```c#
public static BackgroundJobServerOptions GetOptionsBase(string machineName, string customerName)
    {

        return new BackgroundJobServerOptions
        { 
            WorkerCount = 10, 
            HeartbeatInterval = new System.TimeSpan(0, 0, 15), 
            ServerCheckInterval = new System.TimeSpan(0, 0, 15), 
            SchedulePollingInterval = new System.TimeSpan(0, 0, 5), 
            ServerName = $"{Environment.MachineName} ({customerName})" , 
            Queues = (new List<String>(){ customerName }).ToArray()
        };

    }
```

**Comment by edelciomolina** [comment]
@odinserj 
.Net Framework 4.6.1

```xml 
  <package id="Hangfire" version="1.8.0" targetFramework="net461" />
  <package id="Hangfire.Console" version="1.4.2" targetFramework="net461" />
  <package id="Hangfire.Core" version="1.8.0" targetFramework="net461" />
  <package id="Hangfire.JobsLogger" version="0.2.1" targetFramework="net461" />
  <package id="Hangfire.RecurringJobAdmin" version="1.0.5" targetFramework="net461" />
  <package id="Hangfire.SqlServer" version="1.8.0" targetFramework="net461" />
```

**Comment by odinserj** [comment]
Please try upgrading to the latest version, versions 1.7.35 and 1.8.2 contain fix for this issue.

**Comment by odinserj** [comment]
Can you try to use the STDump utility to obtain stack traces of a running process and post its output here? It will help to understand why workers are blocked.

https://github.com/odinserj/stdump

**Comment by edelciomolina** [comment]
Is this information what you need? [result.log](https://github.com/HangfireIO/Hangfire/files/11644299/result.log)

**Comment by odinserj** [comment]
Thanks for the log, it's make the debugging much easier. Please ensure that Hangfire.SqlServer 1.8.2 was actually deployed, I still see `DynamicMutex` in stack traces, which [was removed](https://github.com/HangfireIO/Hangfire/commit/1b48b15ee53dd41cbc026d09bc28969b4d8f531a) in 1.8.1.

**Comment by edelciomolina** [comment]
Bullseye!
<img width="185" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/4604923/87914c82-4749-46ce-aa88-56647b0a802b">

Now everything is working like a charm.
<img width="948" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/4604923/e6f35ceb-a171-4735-ab2d-47d1379be8b8">

Thank you so much!
