### ISSUE TITLE
Migrate to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by 1bberto** [HangfireIO/Hangfire#2227]
Is there an idea to migrate from completely away from `System.Data.SqlClient` to `Microsoft.Data.SqlClient`?

**Comment by sven5** [comment]
Still no answer?

**Comment by odinserj** [comment]
In Hangfire 1.7.X it is possible to use Microsoft.Data.SqlClient package by using an explicit connection factory as in the following example:

```csharp
GlobalConfiguration.Configuration
    .UseSqlServerStorage(
        () => new Microsoft.Data.SqlClient.SqlConnection(@"Server=.\;Database=Hangfire.Sample;Trusted_Connection=True;"));
```

In Hangfire 1.8.X, Microsoft.Data.SqlClient will be used by default if installed into the target project, please see https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#installation for detalis.
