### ISSUE TITLE
No more hearbeats sent after calling BackgroundJobServer.SendStop

### ISSUE THREAD

**Issue by FrankNiemeyer** [HangfireIO/Hangfire#2233]
I use the `BackgroundJobServer.SendStop` method followed by `BackgroundJobServer.WaitForShutdown` and sufficiently long `StopTimeout` and `ShutdownTimeout` to ensure that running jobs can finish before the server gets actually shut down (i.e. "to drain the queues"). This works as expected.

However, some period after `SendStop` was executed, the running jobs get set to the "Failed" state, despite that the jobs are still running fine. It seems that after calling `SendStop` no more heartbeats are sent, even if the server continues to run due to a longer `Stop/ShutdownTimeout`, which means that the server gets removed from the list of active servers and the jobs running on this server get marked as "aborted".

If my guess is correct, why doesn't the server continue to send heartbeats until it _actually_ shuts down? Is this by design? Can I somehow work around this issue?

I've tried setting the `BackgroundJobServerOptions.ServerTimeout`, but this seems to be limited for some reason to 24 h max. (we have very long running simulation jobs, which might take multiple days).

Thanks for your help!

**Comment by odinserj** [comment]
Good catch, heartbeats should be sent until the whole server is ready for shutdown, of course. It should be fixed in 1.8.4 and backported to the 1.7.X branch.

**Comment by FrankNiemeyer** [comment]
Nice, thanks for the quick response!

**Comment by odinserj** [comment]
I've just pushed the changes, you can use `1.8.3-build-03819` or `1.7.36-build-03820` version from CI feed (`https://ci.appveyor.com/nuget/hangfire`) or increase the `BackgroundJobServerOptions.HeartbeatInterval` on your servers to avoid them being killed.
