### ISSUE TITLE
History Graph does now show any stats

### ISSUE THREAD

**Issue by jorgelaranjo** [HangfireIO/Hangfire#2245]
**Bug Report**

**Description:**
Upgraded from 1.7.33 to 1.8.3
Before upgrading History Graph was showing all stats correctly per day and per week.
After upgrade those are not showing, at best you can see the last job showing on the day/week chart, until you refresh the page.

Because a job just ran and you were online on the dashboard, it shows, but if you refresh, goes back to zero.

Shouldn't be showing zero I think, looking at the stats.json returned.
Browser console does not show errors

The refresh of stats is set for 20 seconds

**Steps to Reproduce:**
1. Upgrade from 1.7.33 to 1.8.3.
2. Run hangfire, run jobs, log it latter and look at Scheduler
3. Expected to chart all results as per `stats.json`

**Screenshots / Recordings:**
Just after running a job
![image](https://github.com/HangfireIO/Hangfire/assets/1196202/e8cd6071-f17a-4ae4-91f2-1294d98893e5)

and after refreshing dashboard
![image](https://github.com/HangfireIO/Hangfire/assets/1196202/1a376498-86b7-4cbf-b3cd-63be6f21a1cc)

**Environment:**
- Operating System: All
- Browser (if applicable):  All

**Additional Information:**
PostgresSQL and Schema is 19

**Related Issues:**
#1369 

**Steps Taken to Resolve:**
Look at console errors, log errors. Nothing detected

**Additional Context:**
Stats json report back expected results

```json
{
    "servers:count": {
        "value": "10",
        "intValue": 10,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "recurring:count": {
        "value": "7500",
        "intValue": 7500,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "retries:count": {
        "value": "0",
        "intValue": 0,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "enqueued:count-or-null": {
        "value": "0",
        "intValue": 0,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "failed:count-or-null": null,
    "succeeded:count": {
        "value": "6,400,022",
        "intValue": 6400022,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "failed:count": {
        "value": "0",
        "intValue": 0,
        "style": "default",
        "highlighted": false,
        "title": null
    },
    "deleted:count": {
        "value": "193",
        "intValue": 193,
        "style": "default",
        "highlighted": false,
        "title": null
    }
}
```

Interesting on a different deployment, which is 100% the same it does work as expected
![image](https://github.com/HangfireIO/Hangfire/assets/1196202/33cbb4b0-6e23-4aa6-aade-43787911d521)

**Comment by odinserj** [comment]
Hm, looks like the previous problem was related to cached `hangfire.js` script. Can you please try to clear web caches and reload the page? Resource URLs contain version to avoid caching between versions, but anyway may be it will help.

**Comment by Qubitus** [comment]
Have the same problem after upgrading from 1.7.31 to 1.8.3.
About 1200 jobs run throughout the day, but the history graph keeps displaying 0:
<img width="603" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/2839534/e760685d-ecf6-4ca7-a720-9ccb7e86370a">

**Comment by odinserj** [comment]
@Qubitus what job storage are you using?

**Comment by Qubitus** [comment]
We are using PostgreSQL as job storage

**Comment by odinserj** [comment]
So both cases rely to PostgreSQL job storage. Can you please tell me exact package and its version you are using? I checked https://github.com/hangfire-postgres/Hangfire.PostgreSql/ repository, but it doesn't contain anything suspicious, and don't see any changes in Hangfire itself that can cause this.

**Comment by jorgelaranjo** [comment]
> So both cases rely to PostgreSQL job storage. Can you please tell me exact package and its version you are using? I checked https://github.com/hangfire-postgres/Hangfire.PostgreSql/ repository, but it doesn't contain anything suspicious, and don't see any changes in Hangfire itself that can cause this.

https://github.com/hangfire-postgres/Hangfire.PostgreSql/releases/tag/1.19.13

**Comment by Qubitus** [comment]
I'm using Hangfire.PostgreSql version 1.19.13

**Comment by odinserj** [comment]
Can you please show the full source code of the page's canvas element? I'd like to check what data is being written there.

![image](https://github.com/HangfireIO/Hangfire/assets/1078718/20e1cb41-f049-4f73-a1ce-6dedf41972ca)

**Comment by Qubitus** [comment]
This is the full source of the history graph canvas:
<img width="828" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/2839534/75dd2b24-9eb1-4854-b1d5-0dbeeddf94eb">

**Comment by jorgelaranjo** [comment]
At times it even shows the latest jobs but nothing else like in this case.
It usually happens when the job run and the dashboard is active on the browser.

```
<canvas width="301" height="55" id="historyGraph" data-succeeded="{&quot;2023-08-02T22:29:02.7383065Z&quot;:0,&quot;2023-08-02T21:29:02.7383065Z&quot;:0,&quot;2023-08-02T20:29:02.7383065Z&quot;:0,&quot;2023-08-02T19:29:02.7383065Z&quot;:0,&quot;2023-08-02T18:29:02.7383065Z&quot;:0,&quot;2023-08-02T17:29:02.7383065Z&quot;:0,&quot;2023-08-02T16:29:02.7383065Z&quot;:0,&quot;2023-08-02T15:29:02.7383065Z&quot;:0,&quot;2023-08-02T14:29:02.7383065Z&quot;:0,&quot;2023-08-02T13:29:02.7383065Z&quot;:0,&quot;2023-08-02T12:29:02.7383065Z&quot;:0,&quot;2023-08-02T11:29:02.7383065Z&quot;:0,&quot;2023-08-02T10:29:02.7383065Z&quot;:0,&quot;2023-08-02T09:29:02.7383065Z&quot;:0,&quot;2023-08-02T08:29:02.7383065Z&quot;:0,&quot;2023-08-02T07:29:02.7383065Z&quot;:0,&quot;2023-08-02T06:29:02.7383065Z&quot;:0,&quot;2023-08-02T05:29:02.7383065Z&quot;:0,&quot;2023-08-02T04:29:02.7383065Z&quot;:0,&quot;2023-08-02T03:29:02.7383065Z&quot;:0,&quot;2023-08-02T02:29:02.7383065Z&quot;:0,&quot;2023-08-02T01:29:02.7383065Z&quot;:0,&quot;2023-08-02T00:29:02.7383065Z&quot;:0,&quot;2023-08-01T23:29:02.7383065Z&quot;:0}" data-failed="{&quot;2023-08-02T22:29:02.7409085Z&quot;:0,&quot;2023-08-02T21:29:02.7409085Z&quot;:0,&quot;2023-08-02T20:29:02.7409085Z&quot;:0,&quot;2023-08-02T19:29:02.7409085Z&quot;:0,&quot;2023-08-02T18:29:02.7409085Z&quot;:0,&quot;2023-08-02T17:29:02.7409085Z&quot;:0,&quot;2023-08-02T16:29:02.7409085Z&quot;:0,&quot;2023-08-02T15:29:02.7409085Z&quot;:0,&quot;2023-08-02T14:29:02.7409085Z&quot;:0,&quot;2023-08-02T13:29:02.7409085Z&quot;:0,&quot;2023-08-02T12:29:02.7409085Z&quot;:0,&quot;2023-08-02T11:29:02.7409085Z&quot;:0,&quot;2023-08-02T10:29:02.7409085Z&quot;:0,&quot;2023-08-02T09:29:02.7409085Z&quot;:0,&quot;2023-08-02T08:29:02.7409085Z&quot;:0,&quot;2023-08-02T07:29:02.7409085Z&quot;:0,&quot;2023-08-02T06:29:02.7409085Z&quot;:0,&quot;2023-08-02T05:29:02.7409085Z&quot;:0,&quot;2023-08-02T04:29:02.7409085Z&quot;:0,&quot;2023-08-02T03:29:02.7409085Z&quot;:0,&quot;2023-08-02T02:29:02.7409085Z&quot;:0,&quot;2023-08-02T01:29:02.7409085Z&quot;:0,&quot;2023-08-02T00:29:02.7409085Z&quot;:0,&quot;2023-08-01T23:29:02.7409085Z&quot;:0}" data-deleted="" data-succeeded-string="Succeeded" data-failed-string="Failed" data-deleted-string="Deleted" data-period="day" class="chartjs-render-monitor" style="display: block; width: 301px; height: 55px;">
            </canvas>
```

**Comment by jorgelaranjo** [comment]
@odinserj Any idea about the root cause?

**Comment by odinserj** [comment]
I see stats are formed correctly, and for each date/time it has `0`s. This data is returned directly from storage implementation, and I don't remember anything touched in those methods, and implementation of the storage itself wasn't changed in recent versions. Do you have time synchronization issues on your machines or database server?

**Comment by jorgelaranjo** [comment]
> I see stats are formed correctly, and for each date/time it has `0`s. This data is returned directly from storage implementation, and I don't remember anything touched in those methods, and implementation of the storage itself wasn't changed in recent versions. Do you have time synchronization issues on your machines or database server?

No problems with sync. @Qubitus also facing the same issue which at least gives me some comfort that is reproducible.

Perhaps this may explain it?

```
  0     <PackageReference Include="Hangfire" Version="1.8.3" />                                                                                                                                                     
  1      <PackageReference Include="Hangfire.Tags" Version="1.8.5" />                                                                                                                                            
  2     <PackageReference Include="Hangfire.PostgreSql" Version="1.19.12" />                                                                                                                                        
  3     <PackageReference Include="Hangfire.Tags.PostgreSql" Version="1.9.6" />   
```

**Comment by jorgelaranjo** [comment]
Running 1.8.14 and issue still present

Canvas
```
<canvas width="1798" height="331" id="historyGraph" data-succeeded="{&quot;2024-07-05T11:25:16.1650829Z&quot;:1,&quot;2024-07-05T10:25:16.1650829Z&quot;:0,&quot;2024-07-05T09:25:16.1650829Z&quot;:0,&quot;2024-07-05T08:25:16.1650829Z&quot;:0,&quot;2024-07-05T07:25:16.1650829Z&quot;:0,&quot;2024-07-05T06:25:16.1650829Z&quot;:0,&quot;2024-07-05T05:25:16.1650829Z&quot;:0,&quot;2024-07-05T04:25:16.1650829Z&quot;:0,&quot;2024-07-05T03:25:16.1650829Z&quot;:0,&quot;2024-07-05T02:25:16.1650829Z&quot;:0,&quot;2024-07-05T01:25:16.1650829Z&quot;:0,&quot;2024-07-05T00:25:16.1650829Z&quot;:0,&quot;2024-07-04T23:25:16.1650829Z&quot;:0,&quot;2024-07-04T22:25:16.1650829Z&quot;:0,&quot;2024-07-04T21:25:16.1650829Z&quot;:0,&quot;2024-07-04T20:25:16.1650829Z&quot;:0,&quot;2024-07-04T19:25:16.1650829Z&quot;:0,&quot;2024-07-04T18:25:16.1650829Z&quot;:0,&quot;2024-07-04T17:25:16.1650829Z&quot;:0,&quot;2024-07-04T16:25:16.1650829Z&quot;:0,&quot;2024-07-04T15:25:16.1650829Z&quot;:0,&quot;2024-07-04T14:25:16.1650829Z&quot;:0,&quot;2024-07-04T13:25:16.1650829Z&quot;:0,&quot;2024-07-04T12:25:16.1650829Z&quot;:0}" data-failed="{&quot;2024-07-05T11:25:16.166533Z&quot;:0,&quot;2024-07-05T10:25:16.166533Z&quot;:0,&quot;2024-07-05T09:25:16.166533Z&quot;:0,&quot;2024-07-05T08:25:16.166533Z&quot;:0,&quot;2024-07-05T07:25:16.166533Z&quot;:0,&quot;2024-07-05T06:25:16.166533Z&quot;:0,&quot;2024-07-05T05:25:16.166533Z&quot;:0,&quot;2024-07-05T04:25:16.166533Z&quot;:0,&quot;2024-07-05T03:25:16.166533Z&quot;:0,&quot;2024-07-05T02:25:16.166533Z&quot;:0,&quot;2024-07-05T01:25:16.166533Z&quot;:0,&quot;2024-07-05T00:25:16.166533Z&quot;:0,&quot;2024-07-04T23:25:16.166533Z&quot;:0,&quot;2024-07-04T22:25:16.166533Z&quot;:0,&quot;2024-07-04T21:25:16.166533Z&quot;:0,&quot;2024-07-04T20:25:16.166533Z&quot;:0,&quot;2024-07-04T19:25:16.166533Z&quot;:0,&quot;2024-07-04T18:25:16.166533Z&quot;:0,&quot;2024-07-04T17:25:16.166533Z&quot;:0,&quot;2024-07-04T16:25:16.166533Z&quot;:0,&quot;2024-07-04T15:25:16.166533Z&quot;:0,&quot;2024-07-04T14:25:16.166533Z&quot;:0,&quot;2024-07-04T13:25:16.166533Z&quot;:0,&quot;2024-07-04T12:25:16.166533Z&quot;:0}" data-deleted="" data-succeeded-string="Succeeded" data-failed-string="Failed" data-deleted-string="Deleted" data-period="day" style="display: block; height: 301px; width: 1635px;" class="chartjs-render-monitor">
            </canvas>
```

and this is on an instance that runs 1000+ jobs a day and has more than 500,000 jobs executed.

**Comment by jorgelaranjo** [comment]
It does seems related to https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/333 which only applied for people using `Hangfire.PostgreSql`
