### ISSUE TITLE
Adding custom state(s) to Jobs UI

### ISSUE THREAD

**Issue by Qubitus** [HangfireIO/Hangfire#2265]
Hi,

We have implemented 2 new (failed) job states for our recurring jobs to execute:
- Transient Failure
- Systemic Failure

We would also like to make this distinction in the UI and were wondering if it was possible to extend the "Jobs" page to also include these. Something along the lines of:
<img width="296" alt="image" src="https://github.com/HangfireIO/Hangfire/assets/2839534/f4e7d4d9-191f-407c-88f4-26385fcbc73b">

Is this currently possible and if so, could you give us some guidance in how we could achieve this.
We know we can create a new dashboard page, however that's not really what we are looking for at this moment.

Kind regards

**Comment by odinserj** [comment]
You can do this without modifying the page itself, please see the [`JobsSidebarMenu`](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/JobsSidebarMenu.cs) class for examples.

**Comment by Qubitus** [comment]
Closing this issue, as we've reached our goal.
