### ISSUE TITLE
Unexpected error code on request: 405

### ISSUE THREAD

**Issue by dazbradbury** [HangfireIO/Hangfire#2267]
_Thanks for the brilliant library, as always!_

We are currently running Hangfire version 1.8.4 in a NET6 environment. Since moving to NET6 we're seeing errors in the UI:

1) Pressing Requeue just hangs: 

![image](https://github.com/HangfireIO/Hangfire/assets/1332601/d427f478-f166-4504-87bf-3f7bd88e491d)

Console shows the error: 

![image](https://github.com/HangfireIO/Hangfire/assets/1332601/c9fe5626-f19c-4fcb-94dd-da7ce54d602d)

And we can see the POST request: 

![image](https://github.com/HangfireIO/Hangfire/assets/1332601/d0c9ee0e-a7af-4f57-bfaa-09f6ef214cd4)

2) We see similar issues on /hangfire/stats, and the delete endpoint. It just seems POSTs from the UI aren't working.

Looking at your source, I can only see `MethodNotAllowed` here: 

https://github.com/HangfireIO/Hangfire/blob/f5aff77117ad0d3dee2783da159cc9b1549178be/src/Hangfire.Core/Dashboard/CommandDispatcher.cs#L52

And these requests are definitely being sent as POST requests.

The main issue is that we can't requeue / delete jobs from the UI. Is this a known issue? Or have we mis-configured something whilst moving from NET48 -> NET6?

**Comment by dazbradbury** [comment]
Thanks @odinserj - Your comment has got us looking internally, suspecting a middleware getting called before hangfire. I'll close this issue now as it's likely a configuration/middleware ordering issue, rather than something Hangfire specific. 

The NET48 -> NET6 transition has been quite the minefield!

**Comment by dazbradbury** [comment]
Just to confirm, we needed to make sure we call: 

```c#
app.UseHangfireDashboard();
```

Before we called our own routing configuration / handling, which was interfering with the response.

**Comment by odinserj** [comment]
Great the issue was resolved! Any problems with Hangfire itself during the transition?

**Comment by dazbradbury** [comment]
Our process was to test the web workers and background workers separately until it was relatively stable, and then for a period have them running concurrently (so we could switch traffic between), before switching everything over to a NET6 environment.

This meant there were a subset of jobs, where if they were created/enqueued on a NET48 process, then picked up by a NET6 hangfire job runner (or vice-versa), wouldn't be able to deserialize. But that's to be expected because of the type changes. 

It also meant jobs failing in NET6, would get retried and processed by a NET48 worker. So I had some DB queries to pull out jobs that had to be retried, but were ultimately successful, to try to isolate issues on the NET6 worker. I don't think there is a way to filter successful jobs in the UI like this, which may have been handy. But the DB structure made this fairly easy anyway!

So no, not really, the Hangfire portion was very smooth, thanks!
