### ISSUE TITLE
Is there any way to inject ClinentFactory into BackgroundJob ???

### ISSUE THREAD

**Issue by ltb27** [HangfireIO/Hangfire#2269]
![image](https://github.com/HangfireIO/Hangfire/assets/96302113/6821c1c5-cea0-4711-94c4-9d24827781e3)

I am working on my tenancy project, so that i want each tenancy will automatically create job into specific job storage by the HttpContext info(to get domain name).I was reading the source code so that , I see that if i call BackgroundJob.Enqueue so that the BackgroundJob will take the default BackgroundJobClient that has JobStorage is JobStorage.Current. so,How to Inject ClinentFactory  to automatically take BackgroundJobClient automatically ?

**Comment by ltb27** [comment]
![image](https://github.com/HangfireIO/Hangfire/assets/96302113/c8494eaf-09c7-4d6f-b54c-acb00e408bc5)

**Comment by ltb27** [comment]
![image](https://github.com/HangfireIO/Hangfire/assets/96302113/6627f963-b253-4a8f-8da7-0e50b679e698)

**Comment by odinserj** [comment]
Static `BackgroundJob` class is for the simplest use cases. For advanced ones, including DI / IoC you can use `IBackgroundJobClient` interface and its implementation, `BackgroundJobClient` with any `JobStorage` instance you want.

**Comment by ltb27** [comment]
yes, thank you so much
