### ISSUE TITLE
How to add recurring job with both TimeZone and QueueName?

### ISSUE THREAD

**Issue by SoftCircuits** [HangfireIO/Hangfire#2271]
This appears it might be some sort of bug.

I'd like to do the following.

``` cs
jobManager.AddOrUpdate<IEdiImporterWorkerService>("JobID",
    x => x.RunAsync(),
    "*/10 * * * *",
    TimeZoneInfo.Local,
    "QueueName");
```

But I get a warning.

>Warning CS0618 'RecurringJobManagerExtensions.AddOrUpdate<T>(IRecurringJobManager, string, Expression<Func<T, Task>>, string, TimeZoneInfo, string)' is obsolete: 'Please use the AddOrUpdate<T>(string, Expression<Func<T, Task>>, string, RecurringJobOptions) extension method instead. Will be removed in 2.0.0.'

So then I change my code as follows.

``` cs
RecurringJobOptions options = new()
{
    TimeZone = TimeZoneInfo.Local,
    QueueName = WorkerServicesHelper.TrackTraceQueue,
};

jobManager.AddOrUpdate<IEdiImporterWorkerService>("JobID",
    x => x.RunAsync(),
    "*/10 * * * *",
    options);
```

But now this gives me a warning on the line that assigns a value to `RecurringJobOptions.QueueName`.

> Warning CS0618	'RecurringJobOptions.QueueName' is obsolete: 'Please use non-obsolete AddOrUpdate with the explicit `queue` parameter instead. Will be removed in 2.0.0.'

So I go around and around in circles trying to do this in a way that doesn't warn me is obsolete. Is this even possible?

**Comment by cezar-pimentel** [comment]
For sure! Do it like this my friend:

![image](https://github.com/HangfireIO/Hangfire/assets/12258489/f6c9db9f-20a6-4b87-b07a-835f29f7b58f)

`RecurringJob.AddOrUpdate<TJob>(jobId, "desiredQueueName", x => x.ExecuteAsync(null), cronExpression, new RecurringJobOptions
{
    MisfireHandling = MisfireHandlingMode.Relaxed,
    TimeZone = TimeZoneInfo.Local
});`

Note that the QueueName parameter is being set within the AddOrUpdate method, and not as a RecurringJobOptions property.

Let me know if this works for you.

**Comment by SoftCircuits** [comment]
@cezar-pimentel: Yep, that one is warning free. Thanks!

**Comment by cezar-pimentel** [comment]
> @cezar-pimentel: Yep, that one is warning free. Thanks!


Nice! You're welcome! Thanks for replying man!

👊

If possible, close the issue.

**Comment by SoftCircuits** [comment]
Done

**Comment by samhoov** [comment]
When I use method `public static void AddOrUpdate<T>([NotNull] string recurringJobId, [NotNull] string queue, [NotNull][InstantHandle] Expression<Func<T, Task>> methodCall, [NotNull] string cronExpression, [NotNull] RecurringJobOptions options)` the queue of the job is 'default' insted of queueName.

**Comment by mthrift2100** [comment]
This still seems to be an issue. I am attempting to use the AddOrUpdateDynamic and it is assigning it to the 'default' queue regardless.  Below is my code:

```
 public async Task AddOrUpdateRecurringJob<T>(string jobName, Expression<Func<T, Task>> methodCall, string cronExpression, TimeZoneInfo timeZoneInfo, string queue)
 {
     _reccuringJobManager.AddOrUpdateDynamic<T>(jobName,
                                                queue,
                                                methodCall,
                                                cronExpression, 
                                                new DynamicRecurringJobOptions() { MisfireHandling = MisfireHandlingMode.Relaxed, TimeZone = TimeZoneInfo.Local });


     await Task.CompletedTask;
 }
```
