### ISSUE TITLE
Is Hangfire version 1.8.5 issue?

### ISSUE THREAD

**Issue by guytechNet** [HangfireIO/Hangfire#2295]
Hi all,
I want setup a scheduler job so that it will auto run at 01:00:00 AM everyday (TimeZoneInfo.Local as GMT+7 -> My PC or My Server )
My code 
`public IActionResult Index()
{
  RecurringJob.AddOrUpdate(() => Console.WriteLine("Transparent!"), Cron.Daily(1, 0), new RecurringJobOptions { TimeZone = TimeZoneInfo.Local }); // TimeZoneInfo.Local as GMT+7 -> My PC or My Server 
  return View();
}`

I saw Hangfire version 1.8.5 has been saved CreatedAt and NextExecution incorrect so that it got to view correct. Why?

> Field	Value
> NextExecution	1695405600000 
**-> It execute my job at 18:00:00 PM of now** -> I not want it.

Attach picture
![hangfire_dashboard](https://github.com/HangfireIO/Hangfire/assets/118602474/8a350a6c-8bb8-484f-b553-87f9bdc085fc)

![hangfire_dashboard2](https://github.com/HangfireIO/Hangfire/assets/118602474/f88e9af6-9d7b-4b06-82b2-19b104928c57)

![hangfire_dashboard3](https://github.com/HangfireIO/Hangfire/assets/118602474/b7f5e9cf-6928-4d57-98b6-752e979aa286)

**Comment by odinserj** [comment]
I see that dashboard shows the expected time, 01:00 AM, according to the first screenshot. Is this correct?
As for the database values, Hangfire always persists date/time values in UTC, and performs date manipulation on the server side, with database as a time authority whenever supported (like with SQL Server and Hangfire.Pro.Redis).

**Comment by odinserj** [comment]
So if database entries contain an 18:00 PM value, then local time for +7 is 01:00 AM as expected, so history looks correct.

**Comment by guytechNet** [comment]
You're incorrect. My local time for GMT+7. I want a Recurring Job 01:00 AM everyday.
`This is my code as follow
public IActionResult Index() { RecurringJob.AddOrUpdate(() => Console.WriteLine("Transparent!"), Cron.Daily(1, 0), new RecurringJobOptions { TimeZone = TimeZoneInfo.Local }); // TimeZoneInfo.Local as GMT+7  
return View(); }`
But I checked history runtime of Hangfire is incorrect.
I checked data of Recurring Job at database Hangfire (as **Hangfire.Hash** table so that I got result picture above)
**I thinked a logic of Hangfire insert data without TimeZoneInfo.Local. Can you review it?**

**Comment by odinserj** [comment]
Hangfire persists everything in UTC format, performing local time calculations between storing the value and restoring it back. Storing a date/time value in a database in a local format will lead to errors when the server's time zone is changed or when different recurring jobs have different time zones specified. So this is by design.

Each recurring job has its assigned time zone also recorded in the same hash. So when Hangfire reads the UTC value from database, it converts it to a specified time zone first. So, in your case, it will read the 18:00 value and add +7 hours before using the value, resulting in 01:00 AM as expected.

**Comment by guytechNet** [comment]
> Hangfire persists everything in UTC format, performing local time calculations between storing the value and restoring it back. Storing a date/time value in a database in a local format will lead to errors when the server's time zone is changed or when different recurring jobs have different time zones specified. So this is by design.
> 
-> I find that your logic designs are too complicated and confusing for users.
Why not consider the values that users initialize into the **Hash table** to be the **configuration values** that users want so that it **excludes** the server's time zone being changed **or** are there other time zones specified?
-> It means input and output by **configuration values** of users.

> Each recurring job has its assigned time zone also recorded in the same hash. So when Hangfire reads the UTC value from database, it converts it to a specified time zone first. So, in your case, it will read the 18:00 value and add +7 hours before using the value, resulting in 01:00 AM as expected.

-> The next time you receive a configuration value that is not added +7 hours before using the value.
