### ISSUE TITLE
Do not export Annotations

### ISSUE THREAD

**Issue by Demivan** [HangfireIO/Hangfire#2302]
For projects that use own annotations or JetBrains.Annotations it is annoying that IDEs suggest annotations from Hangfire.

**Comment by odinserj** [comment]
Sure, I've marked all the types there with the `[EditorBrowsable(EditorBrowsableState.Never)]` annotation, let's see whether it helps. We can not remove those annotations, because they are public, but still can try to hide them from the editor's perspective.

**Comment by Demivan** [comment]
Thanks. Will test when 1.8.6 is out.

**Comment by Demivan** [comment]
It works, thanks again
