### ISSUE TITLE
Hangfire Dashboard UI - Bootstrap and Moment Js Version

### ISSUE THREAD

**Issue by TejendraPrasad** [HangfireIO/Hangfire#2304]
Hi Team,

Is it possible to upgrade bootstrap, moment and jquery JavaScript? as is getting caught up in security testing.

Thank you!

**Comment by odinserj** [comment]
Hi, updated jQuery to 3.7.1, but I'm afraid Bootstrap 3.4.1 is the latest of 3.X and moment.js 2.29.4 is the latest for this package.

**Comment by TejendraPrasad** [comment]
Thank you! Is there any future plan to upgrade to bootstrap 4 or 5.

**Comment by odinserj** [comment]
Have, but not in the near future, because there were a lot of changes in the newer versions.

**Comment by TejendraPrasad** [comment]
Thank you again.
