### ISSUE TITLE
Overview with duplicate frames

### ISSUE THREAD

**Issue by dorathoto** [HangfireIO/Hangfire#2306]
When updating hangfire 1.7.23 to 1.8.5 several frames appear as if something was quadrupling.

It's probably something you already had, but didn't know about. I have no idea what it could be.

Stack:
ASP.NET 7.0.11

PrintScreen
[https://ibb.co/crJM35y](https://i.ibb.co/VqVr9yL/hangfire.jpg)

**Comment by odinserj** [comment]
Thank you for reporting this. Please ensure you aren't calling `UseSqlServerStorage` method multiple times. If you are using different job storages, you can leave a call `UseSqlServerStorage` only for the default one (that will be assigned to a static field), and pass `new SqlServerStorage`-created instances to other places.

I have also committed a fix for this that will be available with 1.8.6.
