### ISSUE TITLE
Trigger recurring task doesn't update the Last Executed Time

### ISSUE THREAD

**Issue by burningice2866** [HangfireIO/Hangfire#233]
As the subject states, triggering a recurring task through the Dashboard doesn't update the Last Executed Time.

Is this as intended or a bug?

**Comment by erictrade** [comment]
:heavy_plus_sign: :one: to MissedRunAction.
We are expecting some issues in jobs not triggered here.
Is it really triggered again when the server is re-started? We think that sometimes the server goes down for some time and then the recurring jobs are being skipped.

**Comment by Muchiachio** [comment]
@odinserj how's the progress on this one?

In my case, I have a recurring job, which is run monthly, but if the client triggers it (say in the middle of the month). Last job state and last execution date are not updated, this really confuses the client ;x

**Comment by ericmck2000** [comment]
This would be a great feature.

I use hangfire for infrastructure automation tasks.... Rebooting servers, and things which are very time critical.

If for some reason, it was unable to execute during its schedule, It would be extremely helpful to not execute the job.

**Comment by dotnetdan** [comment]
Is this feature still being planned?  The ability to run "all" missed jobs upon startup important for some scenarios.

**Comment by danroot** [comment]
I'm running into this as well in a use case closer to what burningice2866 and several others mention.   It has nothing to do with missed recurring jobs - just wanting to allow users to run what would normally be a scheduled job in a ad-hoc manner.  RecurringJob.Trigger(jobid) does run the job as expected, this but does not update LastExecuted.  The behavior I expected was that it would update LastExecuted both in the dashboard and in the RecurringJobDto returned by JobStorage.Current.GetConnection().GetRecurringJobs().

At this point, I could see an issue changing this behavior breaking code that expects the current behavior.  In that case, one potential fix would be an overload that allows changing this behavior:

      RecurringJob.Trigger(jobId, shouldUpdateLastExecuted)

**Comment by nharmonJA** [comment]
I also want to know if functionality to trigger a recurringJob and have it update LastExecuted values is still being planned?

My scenario is that we have multiple queries that need to be ran on a daily basis and we are adding a dashboard page specifically for viewing the status of that subset of all of our hangfire jobs. If any of the queries failed for any reason they need to be able to be re-ran from this new dashboard after the source of the error is fixed; in which case we then run into the issue of the re-ran query may have been successful, but because it doesn't update any of the LastExecuted values we can't show that the status went from Failed to Succeeded.

**Comment by SpoinkyNL** [comment]
Still an issue. Could we at the very least get an optional `updateLastJob` parameter on the Trigger method?

In our case we have a recurring job which retrieves data every 20 minutes, however if someone views this data and wants a fresh set they can manually fire the job, but this doesn't update the last executed time (which they use to judge wether or not to manually fire the job)

**Comment by odinserj** [comment]
Call to the `Trigger` method now updates `LastExecution` field in the latest 1.7.0 betas, so I'm closing this issue.
