### ISSUE TITLE
Inconsistency in language

### ISSUE THREAD

**Issue by robertovaldesperez** [HangfireIO/Hangfire#2332]
![image](https://github.com/HangfireIO/Hangfire/assets/15571467/3062c5e7-5d6a-4b92-a3a4-2ab08d194073)

**Comment by odinserj** [comment]
Hm, what language is used in the HTML page of your Dashboard UI?

![image](https://github.com/HangfireIO/Hangfire/assets/1078718/5ccb6d60-24f6-4c54-ab7d-db89a5b6e510)

**Comment by robertovaldesperez** [comment]
Hi @odinserj Im using 
![image](https://github.com/HangfireIO/Hangfire/assets/15571467/5f0bc199-570d-4e09-b13a-29fa2fc5c70d)

**Comment by odinserj** [comment]
That's simply too many locales included in the built-in Moment.js script, will try to exclude those missing in Hangfire.Core itself.
