### ISSUE TITLE
Update dependencies of "Hangfire.AspNet" nuget package

### ISSUE THREAD

**Issue by RudeySH** [HangfireIO/Hangfire#2333]
I just ran into an issue where I was unknowingly using an old version of Hangfire.Core, because I was referencing Hangfire.AspNet, whose dependencies look like this:

![image](https://github.com/HangfireIO/Hangfire/assets/3918757/ffa8602b-c16b-4e9f-b824-b187a1a7aefd)

**Comment by odinserj** [comment]
Please reference the required packages and its versions explicitly, `Hangfire.AspNet` supports every version since `1.6.0` and there's no need to bump every Hangfire-related package to a higher version with each `Hangfire.Core` release, since it's very impractical.

```csharp
<PackageReference Include="Hangfire.Core" Version="X.Y.Z" />
<PackageReference Include="Hangfire.AspNet" Version="0.2.0" />
```
