### ISSUE TITLE
Proper rendering of generic arguments on job details page

### ISSUE THREAD

**Issue by olivermue** [HangfireIO/Hangfire#2338]
When having a method like this as an Hangfire Job
```csharp
public class MyTasks
{
    public async Task DoSomething(
        Guid parentId,
        IEnumerable<Guid> childIds,
        IEnumerable<string> childNames,
        PerformContext performContext)
    {
        // ...
    }
}
```
it will be rendered as follows:
![Job details method rendering](https://github.com/HangfireIO/Hangfire/assets/17193431/c9abbb2c-c996-4cc1-b139-323e12e0287d)

As you can see, the generic arguments are rendered with the backtick and don't show the used generic argument and a simple copy & paste isn't possible anymore.

Unfortunately I get a bunch of errors, if I try to simple clone and build the solution, so I can't really test it, but if I'm right the problem could be solved with an easy patch (untested):
```diff
diff --git a/src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs b/src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
index 58b61f75..969d9e68 100644
--- a/src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
+++ b/src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
@@ -279,7 +279,7 @@ public string Render(bool isJson, string deserializedValue, string rawValue)
                         isJson ? "FromJson" : "Deserialize"));
 
                     builder.Append("&lt;")
-                        .Append(WrapType(Encode(_deserializationType.Name)))
+                        .Append(WrapType(Encode(_deserializationType.ToGenericTypeString())))
                         .Append(WrapIdentifier("&gt;"))
                         .Append('(');

```

Maybe someone can test and implement this.

**Comment by odinserj** [comment]
Oh sorry for the errors, the build was failing yesterday, now I've fixed this and should be working fine. This is a great addition, let's try to see it in action.

**Comment by odinserj** [comment]
The fix was relatively simple, thanks for the hint! Here's how it's displayed now:

![image](https://github.com/HangfireIO/Hangfire/assets/1078718/bd5fb047-eb29-4f7d-be6c-c499003420b6)
