### ISSUE TITLE
SQL Query on Hangfire.State table is very slow 

### ISSUE THREAD

**Issue by Shibshankar01** [HangfireIO/Hangfire#2342]
I am making a hangfire job that will mail me the summary about all the failed jobs in the last 12 hours. To do this I want data from the Hangfire.State (Data Column). And, whenever I execute the query to fetch data from the State table using the Id column, the query takes a lot of time and I get TimeOutException. Since I don't have Entities for the Hangfire tables in .Net I cannot use repository pattern. 
How can I handle this?

**Comment by odinserj** [comment]
Hi @Shibshankar01, can you send me the query you are executing and the output of the following query to understand what schema version are you using for Hangfire?

```sql
SELECT * FROM [HangFire].[Schema]
```

**Comment by Shibshankar01** [comment]
Hi @odinserj,
The query is
"Select * From Hangfire.State nolock where Id in ({Ids})". Ids is comma seperated StateIds received from Hangfire.Job Table for all the failed Jobs.
And the [Hangfire].[Schema] Version is 7.
Thanks in advance.

**Comment by odinserj** [comment]
State table has a composite primary key, try querying by both JobId or Id, in this case there will be an index seek operation, not scanning through all the records.

Or, much better, see the Job table as it has current state name associated, and query against it instead.

**Comment by odinserj** [comment]
*by both JobId and Id
