### ISSUE TITLE
"Next execution" is in the past, and "Last execution" is N/A

### ISSUE THREAD

**Issue by yong2khoo-lm** [HangfireIO/Hangfire#2344]
<img src="https://github.com/HangfireIO/Hangfire/assets/51041738/3c5d3a5f-c010-436b-8f7d-dfba1ba096eb" width=400 />

After upgrading from schema 7 to schema 9 (1.8.6), when creating a new recurring job, this happens.

> "Next execution" is in the past, and "Last execution" is N/A

Did i overlook something? (eg: table update typo, etc)

- I went through a history post of https://github.com/HangfireIO/Hangfire/issues/1459. But guess it isn't quite the same, as the 'Score' is not -1.

**Comment by odinserj** [comment]
Please try upgrading to version 1.8.7, it now displays whether there are time synchronization issues between application host and job storage in the bottom of the page, and let me know if that's the case.

**Comment by yong2khoo-lm** [comment]
![image](https://github.com/HangfireIO/Hangfire/assets/51041738/3ee55c44-262b-430a-99f0-7b2d47efbeaa)

Fyi, with v1.8.6, using back the deprecated method will works.

**Comment by yong2khoo-lm** [comment]
for now, since it is working, then let me close first.

**Comment by odinserj** [comment]
Hey, I'm looking at this problem right now, and it looks really strange that non-deprecated method works differently than the deprecated one. I checked every line of `RecurringJob` class and found no differences between them. If you'll experience this problem once again, please let me know what `AddOrUpdate` method overload you are using to look at that method more precisely - unfortunately there are a lot of them due to backward compatibility.

**Comment by yong2khoo-lm** [comment]
> Hey, I'm looking at this problem right now, and it looks really strange that non-deprecated method works differently than the deprecated one. I checked every line of `RecurringJob` class and found no differences between them. If you'll experience this problem once again, please let me know what `AddOrUpdate` method overload you are using to look at that method more precisely - unfortunately there are a lot of them due to backward compatibility.

Sure no problem.

**Comment by yong2khoo-lm** [comment]
It turns out, after a test again, it looks like i have to rebuild my application .dll after every database restore.
So probably it is not due to the deprecated method or not.

**Comment by odinserj** [comment]
> It turns out, after a test again, it looks like i have to rebuild my application .dll after every database restore.

What do you mean?

**Comment by yong2khoo-lm** [comment]
> > It turns out, after a test again, it looks like i have to rebuild my application .dll after every database restore.
> 
> What do you mean?

My bad for confusion. Let me elaborate:

- At first i mentioned upgrading to schema 9 that it doesn't work. I suspect some tables didnt get properly migrated (with manual script execution, probably due to human error). 
- So I redo with the schema 5 again (restore database, this time not updating the schema). Just after the restore, i create a recurring job. The same observation appears (next execution in the past, and no next execution). 
- Then, I tried the deprecated code, build and patched the application .dll (which consume the hangfire) to the server. It works. (then i posted here)
- But, finally, I request the colleague to restore the database again, patching the application .dll (this time with non-deprecated code). It seems to be working also
- Updating the table schema to 9. Subsequent testing also works.
- Hence i deduced that, most likely nothing to do with the code. Instead, after a database restore, i should also build and patch the .dll instead?

- There is a bit overhead when requesting the database restore and testing. sorry for inconvenience.
