### ISSUE TITLE
Hangfire 1.8.7 throws errors in .Net8 because of old SqlClient

### ISSUE THREAD

**Issue by alexkleinwaechter** [HangfireIO/Hangfire#2346]
Hangfire.SqlServer SqlCommandSet throws error on
`Type? type2 = sqlClientAssembly.GetTypes().FirstOrDefault((Type x) => x.Name == "SqlCommandSet");`

Error:
System.Reflection.ReflectionTypeLoadException: "Unable to load one or more of the requested types.
Could not load type 'SqlGuidCaster' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field."

This error seems to be related to 
[Could not load type 'SqlGuidCaster' from assembly Microsoft.Data.SqlClient #1930](https://github.com/dotnet/SqlClient/issues/1930)

Best!
Alex

**Comment by odinserj** [comment]
It looks like Microsoft.Data.SqlClient 5.1.X itself is broken in .NET 8.0. According to information from the referenced issue, 5.2.0 should be released by the end of the month, so nothing to fix in Hangfire.SqlServer itself.
