### ISSUE TITLE
AddOrUpdate not working for updating a disabled schedule such as "0 0 30 2 *"

### ISSUE THREAD

**Issue by qpzmm2000** [HangfireIO/Hangfire#2352]
Initally I have created a job with "0 0 30 2 *" because I am not sure the schedule. It will be marked as "disable" and I can trigger the job manually.
If I call the method AddOrUpdate to update the schedule, the cron expression will be updated but the job will never run.

I checked the HangFire.Set table is not updating. The cron on HangFire.Hash is updated but the NextExecution is empty.
There is a workaround by deleting the job and call the AddOrUpdate again to change the schedule.

**Comment by odinserj** [comment]
Can you tell me more about the use case and how can I reproduce the issue. I just tried to make the following calls, and get the output as expected. Also, what version of Hangfire.Core you are using?

```csharp
RecurringJob.AddOrUpdate("initially-disabled", () => Console.WriteLine("Disabled"), "0 0 30 2 *");
RecurringJob.AddOrUpdate("initially-disabled", () => Console.WriteLine("Now enabled"), "* * * * *");
```

**Comment by qpzmm2000** [comment]
I have simulated the case and it occurs again. I created some API and found that the problem is not caused by first time change. You can reproduce it by repeating the prcoess and finally the schedule will not be updated.

AddDisable -> ChangeToNormal -> AddDisable  -> ChangeToNormal 

`[HttpGet("AddDisable")]
public async Task TestHangFire()
{
    RecurringJob.AddOrUpdate("TestHangFire", () => Console.WriteLine("Disabled"), "0 0 30 2 *", new RecurringJobOptions { TimeZone = TimeZoneInfo.Local });
}
[HttpGet("Remove")]
public async Task Remove()
{
    RecurringJob.RemoveIfExists("TestHangFire");
}
[HttpGet("ChangeToNormal")]
public async Task ChangeToNormal()
{
    RecurringJob.AddOrUpdate("TestHangFire", () => Console.WriteLine("Disabled"), "0 9 * * *", new RecurringJobOptions { TimeZone = TimeZoneInfo.Local });
}`

![HangFireHash](https://github.com/HangfireIO/Hangfire/assets/9086303/2313febe-a7e2-4880-8d84-296e2172b079)
![HangFireSet](https://github.com/HangfireIO/Hangfire/assets/9086303/1ada8df8-0c74-4066-9d5d-83119f672daf)
![job](https://github.com/HangfireIO/Hangfire/assets/9086303/2f996d4d-09f7-447b-a733-7a00cef79a66)

**Comment by qpzmm2000** [comment]
The bug occur on version 1.8.3 and fixed on the latest version. Thank you.
