### ISSUE TITLE
Checking if response is already started breaks custom IDashboardDispatchers

### ISSUE THREAD

**Issue by SPWizard01** [HangfireIO/Hangfire#2356]
This change, specifically:
https://github.com/HangfireIO/Hangfire/pull/2350

this check: https://github.com/maliming/Hangfire/blob/56898cee0ecee2bee8a905df7e6e7f38cc007178/src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardResponse.cs#L63

Breaks custom dashboard dispatchers(i.e. hangfire console) because their content is written using:
`return context.Response.WriteAsync(content);`
i.e. https://github.com/HangfireIO/Hangfire/blob/60d6b3c91dca25b2ba76da8defbf5b3d9201017f/src/Hangfire.Core/Dashboard/RazorPageDispatcher.cs#L38C28-L38C36

the workaround is to use Response.Body, however I am not sure if this was intended

**Comment by odinserj** [comment]
@maliming, do you have any suggestions on this? I'm going to remove the `HasStarted` condition in the `WriteAsync` method.

**Comment by maliming** [comment]
hi @odinserj 

The `public override Task WriteAsync(string text)` no need to check, my mistake, sorry, you can remove it.
