### ISSUE TITLE
Package id is different of package name (Installing Hangfire on osx using Xamarin.Studio)

### ISSUE THREAD

**Issue by jjchiw** [HangfireIO/Hangfire#236]
Hi

It seems there is a problem installing Hangfire in osx using the add package feature of Xamarin Studio, It seems there is a "misspelling", the package id is `Hangfire.Redis`, but the folder that is created is `HangFire.Redis`, so when Xamarin Studio tries to update the packages.config file, and tries to add `<package id="Hangfire.Redis" version="1.1.1" targetFramework="net45" />` the operation cannot be done because it's looking for the folder `Hangfire.Redis` and since the folder created is `HangFire.Redis`  the operation can not be done and package is not added....and .nupkg file too is `HangFire.Redis` instead of `Hangfire.Redis`

I don't know why Nuget create HangFire.Redis instead of Hangfire.Redis that it's the Id of the package of what I see in https://github.com/HangfireIO/Hangfire/blob/master/nuspecs/Hangfire.Redis.nuspec but in nuget.org appears as `Install-Package HangFire.Redis`

Thanks for Hangfire, it's awesome.

![screen shot 2014-11-04 at 12 34 01 pm](https://cloud.githubusercontent.com/assets/642319/4899100/4d470ae0-6418-11e4-9434-028c95605d88.png)

**Comment by odinserj** [comment]
Package casing is not an issue anymore with recent .NET Core versions.
