### ISSUE TITLE
TrimList() does not trim the correct items

### ISSUE THREAD

**Issue by neildodson** [HangfireIO/Hangfire#2364]
Version: 1.8.10
Storage: Hangfire.SqlServer
ConfigurationLogic: any
Custom Filters: none

Description:

The SQL query executed by TrimList() sorts the list items in reverse order  (Id desc) before applying the window to keep using keepStartingFrom and keepEndingAt:

````
            string trimSql =
$@";with cte as (
    select row_number() over (order by Id desc) as row_num
    from [{_storage.SchemaName}].List with (xlock, forceseek)
    where [Key] = @key)
delete from cte where row_num not between @start and @end";
````

Whereas the expected sense is (surely) that items are examined in ascending ID order.

The unit tests currently work because they keep the same number of items from either side of the middle of the list. If for example you add a fifth item (i.e. value "4" below) as part of the test setup, then the test fails):

````
     [Theory, CleanDatabase]
     [InlineData(false, false), InlineData(false, true)]
     [InlineData(true, false), InlineData(true, true)]
     public void TrimList_TrimsAList_ToASpecifiedRange(bool useBatching, bool useMicrosoftDataSqlClient)
     {
         UseConnection(sql =>
         {
             Commit(x =>
             {
                 x.InsertToList("my-key", "0");
                 x.InsertToList("my-key", "1");
                 x.InsertToList("my-key", "2");
                 x.InsertToList("my-key", "3");
                 x.InsertToList("my-key", "4");
                 x.TrimList("my-key", 1, 2);
             }, useMicrosoftDataSqlClient, useBatching);

             var records = sql.Query($"select * from [{Constants.DefaultSchema}].List").ToArray();

             Assert.Equal(2, records.Length);
             Assert.Equal("1", records[0].Value);
             Assert.Equal("2", records[1].Value);
         }, useMicrosoftDataSqlClient);
     }
````
The solution is just to order by Id ascending in the CTE...
Happy to create a PR if that helps.

**Comment by neildodson** [comment]
Hmm, looking at this further it does look like this is by design, since the corresponding GetRangeFromList() also counts backwards, and the test for that is explicit...

**Comment by odinserj** [comment]
Yep, this is a very specific data structure, and I'm dreaming to get rid of it one day 😊.

**Comment by neildodson** [comment]
If it counted items from the front, this would be a very useful data structure for me though :-) I think it's the only way I can do what I need without forking HF itself...

**Comment by neildodson** [comment]
Just to elaborate, I'm trying to use the list as a kind of message queue persistence for a customisation I'm writing. It works like this:

- As jobs are handled by Hangfire, message items get added to the back of the list by an arbitrary number of concurrent workers (using a custom filter). 
- A single Hangfire background process runs a loop (server instance have to compete for a lock to do this). Each time the loop runs, it creates a write-only transaction, reads a batch of messages from the front of the list, processes them, adds deletes to the transaction unit of work, then commits. Because of the logic involved, this gets more efficient the larger the batch of messages used.

The 2 existing methods for reading and trimming list items look like they produce good performant SQL, so no problem there.

But because the windowing logic counts from the back of the list, I have to orchestrate between the filter invocations which append messages (producers) and the message deletion in my background process (consumer). Otherwise, new concurrent additions to the back of the list mean the cached SQL query (in the transaction unit of work) for trimming items hits the wrong ones (because the window has effectively moved further in from the front). And that's needs some coarse-grained distributed locks which are hurting the performance a lot...

If the indexing sense of the two list methods (GetRangeFromList and TrimList) are reversed, it all works super nicely. 

Just noting it down here for reference.

**Comment by neildodson** [comment]
Thanks for looking at this. That's neat, but I think this requires scanning the whole set for each deletion, and that won't scale up for what I want to do. I have another idea though - I will reach out to you if I get it working...
