### ISSUE TITLE
Can not change the state of a job to 'Enqueued': target method was not found

### ISSUE THREAD

**Issue by sergeyzwezdin** [HangfireIO/Hangfire#239]
I'm trying to enque new job with external object like this:

```
public class Worker
{
    public Worker(int a)
    {
    }

    public void Notify()
    {
        // ...
    }
}
```

Now, I try to enque it:

```
Worker w = new Worker(5);
BackgroundJob.Enqueue(() => w.Notify());
```

But once code run, I see an exception:

> Failed Can not change the state of a job to 'Enqueued': target method was not found.
> System.IO.FileNotFoundException

Could you advise how to fix that?

Thank you!

**Comment by S3NS4Ti0N** [comment]
Would be awesome to know what resolved your issue.

I got the same. I got only 1 Server where my Dashboard and my BackGroundJobServer is running.
