### ISSUE TITLE
After using the latest version 1.8.14, the dashboard displays English but cannot display Chinese！

### ISSUE THREAD

**Issue by gao-chao-2020** [HangfireIO/Hangfire#2457]
Hello, after using the latest version 1.8.14, the dashboard displays English. I tried various ways to force the time zone, but it still shows English. But with version 1.8.12 or earlier, I didn't set the time zone and it displayed in Chinese. May I ask how to translate version 1.8.14 in Chinese? Is it a configuration error or a bug?

1.8.14
![20241022152837](https://github.com/user-attachments/assets/91ac6e4a-3360-42fe-ba02-0c0e9b9eb759)
![20241022152752](https://github.com/user-attachments/assets/62b555e3-5617-4e71-9aed-ff9ea2a0953c)

1.8.12
![20241022153014](https://github.com/user-attachments/assets/491828a9-c533-4a01-be8d-b421a9eeaed6)
![20241022153002](https://github.com/user-attachments/assets/2dd6f6e1-866f-4c8f-a8fd-2f9f364abd25)

code
![image](https://github.com/user-attachments/assets/978684db-e7c4-4327-bfb3-39e10f4a8a1b)
![image](https://github.com/user-attachments/assets/002dfd18-c95a-4ab2-8662-f0592e9939d2)

**Comment by odinserj** [comment]
Thanks for reporting. This problem is already fixed and will be solved in 1.8.15 soon – there were problems with localization file collection script in 1.8.14, so no localizations are included in the package file.

**Comment by gao-chao-2020** [comment]
Thank you very much for clarifying my doubts. Thank you!
