### ISSUE TITLE
Provide a ceiling value for `WorkerCount` setting

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#246]
Every worker owns a connection to a storage. Currently `WorkerCount` value in `BackgroundJobServerOptions` is being calculated as a `ProcessorCount * 5` value. In usual cases this value is ok as a default, but consider you have a 20-core server. In this case there will be 100 workers, and it is fine. However, since each worker use a connection, this value can produce errors:
- SQL connection pool have 100 connections [by default](http://msdn.microsoft.com/en-US/library/8xx3tyca%28v=vs.110%29.aspx).
- Redis pool have 50 connections [by default](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Redis/RedisStorageOptions.cs#L25).

To make things more predictable, the **default** value should have a maximum at, for example, 40 to produce enough workers and leave some connections for other components.

**Comment by voidmonk** [comment]
Hi @odinserj, seems like `BackgroundJobServerOptions` still allows only a maximum of 20 workers. Is it still required to be max 20, or can it be increased/overridden somehow?

**Comment by acmediainc** [comment]
> Hi @odinserj, seems like `BackgroundJobServerOptions` still allows only a maximum of 20 workers. Is it still required to be max 20, or can it be increased/overridden somehow?

Hi, thoughts on this? Is it still maxed to 20?

**Comment by odinserj** [comment]
It's a limit only for the default value. You can set as many workers as you want.

**Comment by acmediainc** [comment]
Thank you very much, love the product btw...built some really cool stuff with it :-)
