### ISSUE TITLE
Recurring job does not trigger

### ISSUE THREAD

**Issue by dillenmeister** [HangfireIO/Hangfire#247]
Only two of my five recurring jobs trigger when they should.

I browsed through the code a little bit and found that if there is no last execution time, the GetMatches function (https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/ScheduleInstant.cs#L53) uses UtcTime.AddSeconds(-1) instead. It then tries to GetOccurences between UtcTime.AddSeconds(-1) and UtcTime.AddSeconds(1). It looks a bit weird to me and I definately think this is the reason why they never trigger.

If I manually insert a LastExecution row in the HangFire.Hash table for the jobs that never triggers everything works fine.

**Comment by luisrudge** [comment]
@octaviordz sorry to ask, but how did you manage to schedule a job that runs 100 years from now?

**Comment by nirinchev** [comment]
Can't speak about @octaviordz, but my guess would be ```BackgroundJob.Schedule(() => /* MyAction */, DateTimeOffset.UtcNow.AddYears(100)```.

**Comment by luisrudge** [comment]
thanks @nirinchev!

**Comment by octaviordz** [comment]
Yes just like @nirinchev said.

**Comment by odinserj** [comment]
Sorry guys for the delay. Well, there are three different topics in this issue:

1. BUG: Recurring jobs sometimes do not trigger first time they should (as reported by @dillenmeister).
2. BUG: Hangfire allows to create recurring jobs with invalid CRON format (as reported by @octaviordz).
3. Feature: Some of you wants to create a recurring jobs that will never be triggered automatically.

All the problems will be fixed in 1.3.2, and since the latest have workaround, I'll schedule it to 1.4.0 (by implementing pause/resume for recurring jobs).

**Comment by S3NS4Ti0N** [comment]
I got the same problem with the 1.4.5 version.

i got about 1.637.623 recurring jobs, I got 2 types of Jobs. 1 Job which is sending my mails, which should run every minute. and the other jobs which run every 2 days at different days, and times.

My mailing job is the only one that doesnt get triggered. Before i got the other jobs added, there was no problem with my mailing job to get triggered.

Any workaround here ?

I am currently using 1.4.5 with SQL Server 2012 on Win 2012 R2.

**Comment by octaviordz** [comment]
Hi @S3NS4Ti0N 
I think it would be really helpful if you activate the logging for Hangfire. Maybe the logging provides enough information to pin point the issue. I don't think you are having the exact issues I was having.

I don't know if you already have a logging library in your project but I used NLog it is quite easy to make Hangfire to log in its own log file.
You can take a look at http://docs.hangfire.io/en/latest/configuration/configuring-logging.html for different loggeing libraries supported by Hangfire.
And look at https://github.com/nlog/NLog/wiki/Configuration-file#rules for NLog rules, configuration file.
But a file like this should be a good star point
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true">
  <targets async="false">
    <target name="logFile" xsi:type="File"
            fileName="${basedir}/logs/log"
            archiveFileName="${basedir}/logs/log-{#}"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="7"
            concurrentWrites="true"
            keepFileOpen="false"
          />
  </targets>  
  <rules>
    <logger name="*" minlevel="Warn" writeTo="logFile" />
  </rules>
</nlog>
```

**Comment by S3NS4Ti0N** [comment]
I will do that tomorrow, and post the logs.

**Comment by S3NS4Ti0N** [comment]
I have added logging, and created a new issue.

@octaviordz : Thanks for your help :)
