### ISSUE TITLE
'System.ObjectDisposedException' in System.Transactions.dll

### ISSUE THREAD

**Issue by ddiosdado-tea** [HangfireIO/Hangfire#2471]
I am currently trying out Hangfire, checking if it can be used in conjunction with some old .net 4.7 code we currently have, I created a new console application targeting net 4.7, added the `Hangfire.Core` and `Hangfire.SqlServer` packages both are versions 1.8.15.
The console app is very simple:
```c#
static void Main(string[] args)
{
    GlobalConfiguration.Configuration.UseSqlServerStorage("ConnectionString");
    using (var server = new BackgroundJobServer())
    {
        Console.WriteLine("Hangfire Server started. Press any key to exit...");
        Console.ReadKey();
    }
}
```
I am firing a job from our api(separate project also written in 4.7), the job gets executed but I can see the following exceptions before and after the job is executed:
```
Exception thrown: 'System.ObjectDisposedException' in System.Transactions.dll
```
I forced VS to throw the exception in order to get more details:
```
Cannot access a disposed object.
Object name: 'Transaction'.
at System.Transactions.Transaction.get_TransactionInformation()

Tracked it down here:
AppData\Local\SourceServer\..\src\Hangfire.SqlServer\SqlServerDistributedLock.cs
using (var command = CreateReleaseCommand(connection, resource, out var resultParameter))
{
    command.ExecuteNonQuery();
```
![{16365D5D-B49A-4734-9839-0AFE288452C1}](https://github.com/user-attachments/assets/c1d7be49-39ca-470b-8291-998d4e992b53)

I am aware of a [similar issue](https://github.com/HangfireIO/Hangfire/issues/1348) but the solution there was just to sort of ignore the exception, is that really ok?

By the way I also tried running the same console app but this time targeting .net 5 and no exceptions are thrown there.

**Comment by odinserj** [comment]
This is how the `EnlistedTransactionDisposed` property getter is implemented, please see https://github.com/HangfireIO/Hangfire/issues/1348#issuecomment-466405550 for details. Hangfire.SqlServer for newer platforms doesn't use `System.Transactions` assembly, that's why you don't have those exceptions.

**Comment by odinserj** [comment]
Also, the release command is being executed anyway, this is just a first-chance exception handler that doesn't cause the command to be aborted.

**Comment by ddiosdado-tea** [comment]
I see, and you are right, my commands are still being executed, it just makes my team nervous to see those underlying exceptions, thanks for the amazing library and also thanks for the prompt response, I appreciate it.
