### ISSUE TITLE
JobDisplayNameAttribute Not Displaying Correctly in Hangfire with Custom JobFilterProvider

### ISSUE THREAD

**Issue by Olezha228** [HangfireIO/Hangfire#2474]
I am currently implementing a custom JobFilterProvider in my application to manage job filters without using attributes directly on the methods. However, I am encountering an issue where the display name for jobs is not being rendered as expected in Hangfire. My jobs work perfectly tho.

**Problem Description**
I have created a class called RecurrentJobFilterProvider that implements IJobFilterProvider. This provider is intended to return specific job filters based on the job type and method names. Here is a simplified version of the relevant code:

```c#
public class RecurrentJobFilterProvider : IJobFilterProvider
{
    public IEnumerable<JobFilter> GetFilters(Job job)
    {
        if (job.Type.GetMethod(nameof(ICmsRetailEventDataLoader.LoadNewEventsAsync)) is not null)
        {
            return new[]
            {
                new JobFilter(new JobDisplayNameAttribute("Load new events from DB"), JobFilterScope.Global, 0),
                new JobFilter(new AutomaticRetryAttribute { Attempts = 0 }, JobFilterScope.Global, 1)
            };
        }

        // Additional conditions for other methods...
        
        return Enumerable.Empty<JobFilter>();
    }
}
```

I have verified through debugging that the code correctly enters the GetFilters method, confirming that my custom provider is being invoked as intended.

I register the custom filter provider like this:
```c#
JobFilterProviders.Providers.Add(new RecurrentJobFilterProvider());
```

This registration occurs before setting up Hangfire:

```c#
builder.Services.AddHangfire(config => HangfireBootstrapper.ConfigureHangfire(config, dataFlowConnectionString));
builder.Services.AddHangfireConsoleExtensions();
```

**Expected Behavior**
I expect the display names defined in the JobDisplayNameAttribute to appear correctly in the Hangfire dashboard, such as "Load new events from DB" for the corresponding job.

**Actual Behavior**
Instead of displaying the custom names, the Hangfire dashboard shows the job names in the format "Class.Method" (queue), which is not user-friendly and does not reflect the intended display names.

**Steps to Reproduce**
1. Create a custom JobFilterProvider as shown above.
2. Register it before configuring Hangfire.
3. Trigger jobs that should use the filters defined in RecurrentJobFilterProvider.
4. Observe the job names displayed in the Hangfire dashboard.

**Additional Information**

1. Hangfire version:
```
    <PackageReference Include="Hangfire" Version="1.8.14" />
    <PackageReference Include="Hangfire.Console.Extensions.Serilog" Version="2.0.0" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.9" />
```
2. .NET version: 8.0
3. Framework: ASP.NET

_I would appreciate any guidance on how to resolve this issue so that my custom display names are shown correctly in the Hangfire dashboard. If there are any known limitations or additional configurations needed for custom job filters, please let me know.
Thank you for your assistance!_

**Comment by odinserj** [comment]
The `JobDisplayNameAttribute` is not a filter, that's why it's not triggered. This is just a regular attribute for Dashboard UI and isn't related to background processing. You can try to apply either `DisplayNameAttribute` or `JobDisplayNameAttribute` (the latter is able to use [`ResourceManager`](https://github.com/HangfireIO/Hangfire/blob/5b696d4174e13c3dd9489cc6a863d3417c632e31/src/Hangfire.Core/JobDisplayNameAttribute.cs#L36)) or specify some global display callback through the `DashboardOptions.DisplayNameFunc` property.

**Comment by Olezha228** [comment]
Wow, seems like your advice of using `DashboardOptions.DisplayNameFunc` property worked out perfectly for us. Thank you so much! I think the issue may be closed.

Btw, here is final configuration using `DashboardOptions.DisplayNameFunc`:

      ```
app.UseHangfireDashboard("/hangfire", new DashboardOptions
      {
          Authorization = [new AllowAllAuthorizationFilter()],
          DisplayNameFunc = (_, job) =>
          {
              if (job.Method.Name == nameof(ICmsRetailEventDataLoader.LoadNewEventsAsync))
              {
                  return "Load new events from DB";
              }
              return job.Method.Name;
          }
      });
```
