### ISSUE TITLE
SqlServerStorage Memory Allocation Issues

### ISSUE THREAD

**Issue by kfrancis** [HangfireIO/Hangfire#2485]
Getting these notices on AppInsights, thought it worth sharing.

Hangfire.AspNetCore v1.8.14
Hangfire.SqlServer v1.8.14

- [ ] SqlServerStorage.UseConnection - Excessive allocations due to SqlConnection.Close
- [ ] SqlServerStorage.CreateAndOpenConnection - Excessive allocations due to SqlConnection.Open

## SqlServerStorage.UseConnection - Excessive allocations due to SqlConnection.Close

Description: `SqlConnection.Close` is causing unusually high memory allocations.

Current condition: 20% of your Memory was spent in ```````````SqlConnection.Close``````````` called from ```````````Hangfire.SqlServer.SqlServerStorage.UseConnection```````````. We expected this value to be <5%.

Call Stack:

0. Type System.Int64
1. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlStatistics.GetDictionary()
2. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlConnection.Close()
3. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlConnection.Close()
4. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.UseConnection(class System.Data.Common.DbConnection,class System.Func`2<class System.Data.Common.DbConnection,!!0>)
5. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.UseConnection(class System.Data.Common.DbConnection,class System.Func`2<class System.Data.Common.DbConnection,!!0>)
6. hangfire.sqlserver!Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingSlidingInvisibilityTimeout(class System.String[],value class System.Threading.CancellationToken)
7. hangfire.core!Hangfire.Server.Worker.Execute(class Hangfire.Server.BackgroundProcessContext)
8. hangfire.core!Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(value class System.Guid,class System.Object)
9. hangfire.core!Hangfire.Processing.BackgroundExecution.Run(class System.Action`2<value class System.Guid,class System.Object>,class System.Object)

## SqlServerStorage.CreateAndOpenConnection - Excessive allocations due to SqlConnection.Open

Description: `SqlConnection.Open` is causing unusually high memory allocations.

Current condition: 17% of your Memory was spent in ```````````SqlConnection.Open``````````` called from ```````````Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection```````````. We expected this value to be <5%.

Call Stack:

0. microsoft.applicationinsights.ilrepack!Microsoft.ApplicationInsights.Extensibility.W3C.W3CUtilities.GenerateId(unsigned int8[],int32,int32)
1. microsoft.applicationinsights.ilrepack!Microsoft.ApplicationInsights.DataContracts.DependencyTelemetry..ctor()
2. microsoft.applicationinsights.ilrepack!Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.BeforeOpenConnectionHelper(value class System.Collections.Generic.KeyValuePair`2<class System.String,class System.Object>,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher,class Microsoft.ApplicationInsights.Common.<96c40741-8caa-4ba9-a694-1384d0574bb9>PropertyFetcher)
3. microsoft.applicationinsights.ilrepack!Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(value class System.Collections.Generic.KeyValuePair`2<class System.String,class System.Object>)
4. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteConnectionOpenBefore(class Microsoft.Data.SqlClient.SqlDiagnosticListener,class Microsoft.Data.SqlClient.SqlConnection,class System.String)
5. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlConnection.Open(value class Microsoft.Data.SqlClient.SqlConnectionOverrides)
6. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
7. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.UseConnection(class System.Data.Common.DbConnection,class System.Func`2<class System.Data.Common.DbConnection,!!0>)
8. hangfire.sqlserver!Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingSlidingInvisibilityTimeout(class System.String[],value class System.Threading.CancellationToken)
9. hangfire.core!Hangfire.Server.Worker.Execute(class Hangfire.Server.BackgroundProcessContext)
10. hangfire.core!Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(value class System.Guid,class System.Object)
11. hangfire.core!Hangfire.Processing.BackgroundExecution.Run(class System.Action`2<value class System.Guid,class System.Object>,class System.Object)

**Comment by odinserj** [comment]
I'm afraid these issues are out of scope, because point to `Open` and `Close` methods in the Microsoft.Data.SqlClient package.
