### ISSUE TITLE
RavenDB Support

### ISSUE THREAD

**Issue by devmondo** [HangfireIO/Hangfire#26]
Hi, 
this is awesome library, thanks for it.

is there a possibility to use ravendb as back end storage instead of Redis ?

thanks in advanced.

**Comment by OV2012** [comment]
++1 for RavenDB support

**Comment by laedit** [comment]
:+1: for RavenDB support

**Comment by AlexRetzlaff** [comment]
:+1: for RavenDB support

Any takers for a open source project (I would contribute 1 oDesk .Net dev to kick it off)

**Comment by mjohnson0580** [comment]
+1 for RavenDB support

**Comment by bar10dr** [comment]
+1 for RavenDB support

**Comment by vip32** [comment]
+1 for RavenDB support

**Comment by stevo-knievo** [comment]
+1 for RavenDB 4 support :)
