### ISSUE TITLE
Support for Distributed processing?

### ISSUE THREAD

**Issue by coonmoo** [HangfireIO/Hangfire#264]
Heya,

I have an infrastructure of 15 servers running an asp.net web app behing a load balancer.
I want to achieve the following goals with hangfire:
1. Is it possible to execute a background job on the same server it was queued at?
2. Can I queue an background job to be executed on all 15 servers? (e.g. to clear the memory cache on all servers etc.)?

I read that you can attribute your class with a name of a queue the process should be put in. But I'm looking for something like:

BackgroundJob.Enqueue(() => Console.WriteLine("Hello, world!"), "QueueName");

and BackgroundJob.Enqueue(() => Console.WriteLine("Hello, world!"), RUN_ON_ALL_SERVERS);

Thank you

**Comment by Zoxive** [comment]
I'm looking for the same thing.

1. Enqueue a job for a specific Server (By name?)
2. Enqueue a job that will run on every Server.

Is this currently possible?

**Comment by gandarez** [comment]
> Enqueue a job for a specific Server (By name?)
What about creating queues for each server and schedule the job in the desired queue(which naturally goes to the right server)?

> Enqueue a job that will run on every Server.
You might use a common queue name(e.g: default)
