### ISSUE TITLE
Remove dependency on `OWIN` package 

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#267]
Since the Katana project will be merged with ASP.NET 5 in a [future release](https://katanaproject.codeplex.com/wikipage?title=roadmap), there will be no `OWIN` package anymore, and this dependency should be eliminated. I've seen some projects on GitHub that already removed this dependency:

* https://github.com/VQComms/TracingMiddleware
* https://github.com/damianh/LimitsMiddleware

**Comment by fenixbrood** [comment]
Will this be patched or should I fork hangfire

**Comment by robfarmergt** [comment]
@odinserj When is 2.0 estimated to be released? Is there a work around without OWIN for those of us using ASP.NET 5?
