### ISSUE TITLE
Paging and sorting of recurring jobs in Dashboard

### ISSUE THREAD

**Issue by nirinchev** [HangfireIO/Hangfire#281]
When there are numerous (several thousand) recurring jobs, the Dashboard UI gets quite sluggish. It would be a nice improvement to have paging like in the jobs pages.

Also, it would be a huge improvement to change the sort criteria to something more meaningful. Usually, I want to see succeeded jobs in reverse chronological order and the current Id sorting is mostly meaningless. Similarly, for recurring jobs, a natural sort key would be Next execution, etc.

I browsed through the code and noticed that the dashboard pages call monitor.XXXJobs passing the pager values to build a storage specific query for the exact number of rows. I was thinking that since we wouldn't want to change the core MonitoringApi logic, we could enable sorting by non-Id columns in the dashboard by fetching all rows - ```monitor.XXXJobs(0, int.MaxValue)``` and then using Linq to sort and page them in-memory. It would be slower indeed, but in the end of the day, I think it will be more useful than manually searching for the last executed job. What are your thoughts on that?

**Comment by odinserj** [comment]
Done by implementing generic `GetRangeFromSet` command. Will be :ship: with 1.4.0.

**Comment by alexandis** [comment]
GetRangeFromSet is great, but what about using server sorting + server filtering? I can't see the way to easily organize this...
