### ISSUE TITLE
Windows Service and System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by jwiscarson** [HangfireIO/Hangfire#282]
I've been working with and figuring out Hangfire for a week or so. I had success running it in-process, but we need several developers to use the same job scheduling engine and database. I moved Hangfire to a Windows Service and got it installed correctly, but whenever I run the same job that failed previously, I get a FileNotFoundException.

I read the exception log, and the message referenced the folder location it was trying to download my file from -- of course, the same folder the Hangfire service is executing in. I copied the .dll to that folder, but I still get a similar error message.

    System.IO.FileNotFoundException: Could not load file or assembly 'AppFramework.Operations.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    The system cannot find the file specified.

There's more to the error log, but I'd rather not paste a wall of text if I can avoid it. What am I missing here? How do I expose my public data types and functions to Hangfire?

**Comment by jwiscarson** [comment]
I think I've resolved this. I didn't have a constructor for my unit test class. When I added it in, I forgot to restart the service before re-running my tests.

I have Hangfire sending e-mails from my unit test assembly, provided I copy it into the directory that the service runs from. The exception in my original post threw me off, but after re-reading [passing dependencies](http://hangfire.readthedocs.org/en/latest/background-methods/passing-dependencies.html), I realized I had missed something.

I'm confused, though, because I've gotten inconsistent results from Hangfire here. Do I need to copy my .dlls into the Hangfire service directory? Should I modify a PATH variable somewhere to point to my .dll sources? Or is there another, better solution?

**Comment by odinserj** [comment]
Consider your custom .NET Windows Service project as a simple console application – it must have reference to all of your assemblies. There is no magic here – Hangfire does not store any code in its database, only assembly qualified type names and target method name.

**Comment by jwiscarson** [comment]
I haven't found that to be true. My Hangfire project has no reference to my outside .dlls, but putting them in the same directory allows Reflection to find them. It looks like I could also install them in the Global Assembly Cache, but I don't think that would be wise.

**Comment by odinserj** [comment]
Yep, in .NET you can also specify the custom [probing paths](http://stackoverflow.com/questions/1892492/c-sharp-set-custom-path-to-referenced-dlls), however this is an out of topic of this project.

**Comment by jwiscarson** [comment]
It also looks like you can specify a path to the file in your call to [Type.GetType](https://msdn.microsoft.com/en-us/library/ee332784%28v=vs.110%29.aspx) (under Resolving Generic Types). If the caller could optionally specify a search directory for the assembly, that would widen the potential uses. Would you consider this out of scope for this project as well?

**Comment by odinserj** [comment]
Very interesting! Should the assembly path be stored within a background job itself or this should be a configuration option passed to a Hangfire Server instance?

**Comment by jwiscarson** [comment]
I'd prefer storing the assembly path with the background job.

However, I know I'm biased. I'm using Hangfire to centrally schedule jobs from a number of different ASP.NET services, rather than having my team go through me and deploy these jobs in one assembly.

What do you think?

**Comment by odinserj** [comment]
I think it depends on the paths we are using. Absolute paths may be different for each server, so we are unable to store them in a background job. However, I don't know whether `Type.GetType` allows us to use absolute paths.

Relative paths may be stored in background jobs. However, if we decide to change our application structure, this decision will kill us. That is why I prefer to pass assembly paths to the Hangfire Server instance. What do you think?

**Comment by jwiscarson** [comment]
You make a good point. I was thinking about this along with rikbosch's response [here](http://discuss.hangfire.io/t/one-queue-for-the-whole-farm-and-one-queue-by-server/490/4), and planned to filter by using a queue associated with each server. I hadn't considered how restrictive that would be for a general use case. In order to fully leverage the paths, you would **have** to use these ideas together, which would lead to a lot of bugs and confused developers.

After considering your point, I agree with your conclusion. The safest decision is to pass assembly paths to the Hangfire Server instance.

**Comment by jwiscarson** [comment]
As a follow up, I want to say thanks for having this discussion with me. It made me re-think the path I had chosen for this project, and I've consolidated all my recurring job projects into one Hangfire Windows Service project.

**Comment by odinserj** [comment]
@jwiscarson, what is the way you do manage your recurring jobs? How do you deploy it?

**Comment by jwiscarson** [comment]
I set up one solution for our Hangfire jobs, like so (of course the jobs aren't Project1 and Project2 -- our project names just won't mean anything here):
 * Jobs (folder)
   * Project1Job
   * Project2Job
   * ...
 * AppServices (Windows Service with Hangfire installed from NuGet)
 * Core (static Hangfire classes with a connection string to a central DB for all Hangfire jobs, plus some base classes to deal with essential setup for e-mailing jobs, things like that)
 * HangfirePortal (web project to set up the hangfire dashboard).

I'm a developer at a community college in Washington State, in the US, and we only have a three-person developer staff. I set Hangfire up on an MSSQL DB that our central application framework shares, and then created some static classes that mirror the Hangfire BackgroundJob and RecurringJob classes exactly, with connections pointing to the central DB. A brute-force solution, I know -- I'm trying to get us off Quartz.NET right now, because maintaining jobs on it is a total nightmare for me.

I'm pretty much the only source of recurring jobs, so I'm picking through all older projects for work that should transition to recurring jobs. We have one other developer who will want to use this, and I'll just pair program with her to put anything she needs for right now.

Is this what you were asking?

As for deploying the service, I tried creating a Windows installer, but I quickly discovered that the ClickOnce installer is not intended to install Windows Services. Since it'll end up on (at most) two servers, I've just been copying and pasting the executable during testing. Do you have any suggestions here?

**Comment by jwiscarson** [comment]
I did find that I needed to add my .dll references to both the Windows Service and the web projects, otherwise the portal wouldn't let me requeue any jobs. I couldn't figure out if there was a way to have the portal and the Windows Service in the same project, but I'd love to be able to do this and simplify one more piece.
