### ISSUE TITLE
Sql Timeouts in ExpirationManager.cs

### ISSUE THREAD

**Issue by davidsblog** [HangfireIO/Hangfire#287]
With the Hangfire.SqlServer package, if there is a large volume of expired records, then the ExpirationManager will throw a SqlException because it attempts to delete a large number of records in a single command.

**Comment by Yalpe** [comment]
We are also experiencing this issue on our end. Looks like Hangfire is never able to recover and it is getting increasingly laggy now.

**Comment by Yalpe** [comment]
EDIT3: We change the database type in the service tier from standard to web and it is much much better now.

**Comment by odinserj** [comment]
I've changed the implementation. Hangfire now deletes expired records in multiple passes. Each pass deletes top 1000 rows, so it does not stress SQL Server anymore.
