### ISSUE TITLE
Hangfire version freezes at 1.0.0.0 on Dashboard

### ISSUE THREAD

**Issue by gjmveloso** [HangfireIO/Hangfire#288]
I'm not sure when this started but since 1.3 version I'm seeing that dashboard shows Hangfire to be at 1.0.0.0 version. Probably because the assembly binaries file versions are not set (using official NuGet packages).

This does not affect anything but on large deployments this versioning information could be helpful

Thanks for such great library!

**Comment by odinserj** [comment]
Thank you for reporting this! Since this is not a critical bug, I've scheduled it to the *1.4.0* version.
