### ISSUE TITLE
Redis Timeout Expired

### ISSUE THREAD

**Issue by jhST** [HangfireIO/Hangfire#290]
Server Error in '/' Application.
Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[TimeoutException: Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use.]
   ServiceStack.Redis.PooledRedisClientManager.GetClient() in c:\projects\hangfire-pro\src\Hangfire.Redis\RedisStorageOptions.cs:0
   Hangfire.Redis.RedisMonitoringApi.UseConnection(Func`2 action) in c:\projects\hangfire-pro\src\Hangfire.Redis\RedisMonitoringApi.cs:648
   Hangfire.Redis.RedisMonitoringApi.HourlySucceededJobs() in c:\projects\hangfire-pro\src\Hangfire.Redis\RedisMonitoringApi.cs:402
   Hangfire.Dashboard.Pages.DashboardPage.Execute() +368
   Hangfire.Dashboard.RazorPage.TransformText(String innerContent) +68
   Hangfire.Dashboard.RazorPage.TransformText() +38
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(RequestDispatcherContext context) +299
   Hangfire.Dashboard.DashboardMiddleware.Invoke(IOwinContext context) +516
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +523
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +3897072
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +287
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +3897072
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +272
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +33
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +150
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +42
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +415
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.5.27.0

**Comment by odinserj** [comment]
> This may have occurred because all pooled connections were in use.

Hangfire uses connection pools to obtain connections as quickly as possible. The majority of them are obtained by worker threads. As the latest version, default connection pool size is *50 connections*. If you have more than 40 workers (you can see the number on the Servers page in the dashboard or by multiplying cores count by 5), consider to increase the pool size as [written here](http://docs.hangfire.io/en/latest/configuration/using-redis.html#connection-pool-size).
