### ISSUE TITLE
Bug found in CronExpressionDescriptor.

### ISSUE THREAD

**Issue by jwiscarson** [HangfireIO/Hangfire#299]
Hangfire has forced me to finally learn cron timing expressions. After reading [this article(https://code.google.com/p/ncrontab/wiki/CrontabExpression), and noticing that Hangfire requires times in GMT/UTC (I'm in the US, under Pacific time, so UTC - 8), I tried working with the following cron expression: "*/60 0,1,15-23 * * 1-5"

Hangfire throws an exception: ![untitled](https://cloud.githubusercontent.com/assets/5872334/6003261/0cdda076-aaaf-11e4-8a37-a4ca091a961a.jpg)

If I change "0,1,15-23" to "15-23", the cron works fine.

**Comment by odinserj** [comment]
Page now catches `CronExpressionDescriptor` exceptions and displays raw cron expression in case of them. Thank for the reporting!
