### ISSUE TITLE
Task Output - How to display in Dashboard

### ISSUE THREAD

**Issue by dealproc** [HangfireIO/Hangfire#308]
The user story method of my inquiry:

`As a user, when a job executes, I would like to read details about what was performed within the job.`

The full response is more of the same.  My idea here is that, with other products in this space, we can get copious information about the bowels of what was performed in the system during execution.  Use Octopus Deploy as your baseline for this.  During a deployment execution, the screen breaks down the "job" into its distinct parts, and within each part, displays to the end user the details of that work.  In the case of console applications, it scrapes the output of the console application into the screen and allows a full review of the work that was performed, without having to navigate to a dedicated logging file somewhere.

Is there any focus on this endeavor and/or does anyone see the need to have this sort of item?  I personally see this as an imperative feature of any scheduling system, but I may be biased.  I'd like to gain feedback from others.

Also, added to this, if there is a case whereas you would say "Successful, but with warnings" or similar, so that there could be an instance where the work did complete without errors, but there were things we want to bring to the attention of the user that they may need to go back and review, etc.

**Comment by yngndrw** [comment]
There is a pull request (#232) and issue (#218) for the ability to output execution information from jobs.

**Comment by samshiles** [comment]
Please see: https://github.com/samshiles/hangfire.job.logging for one way to get job output logged to the hangfire console. It requires a very small change to hangfire which should be 100% backwards compatible. PR: #466

**Comment by odinserj** [comment]
Hey guys, see what @pieceofsummer did in the [Hangfire.Console](https://github.com/pieceofsummer/Hangfire.Console) extension, even with colours and live updates! Almost all storages are supporting this with no changes!

![dashboard](https://cloud.githubusercontent.com/assets/1078718/19828235/cf0aa914-9dc9-11e6-93b4-2cb33eff1c28.png)
