### ISSUE TITLE
Expiration tablock hint and configurable CheckInterval

### ISSUE THREAD

**Issue by travisblakeney** [HangfireIO/Hangfire#313]
When the ExpirationManager cleans up the expired records on Sql Server we are seeing an unnecessary amount of locking on the tables which is affecting the performance of our database when under load. We are wanting to submit a pull request with 2 changes.

1. Remove the with (tablock) hint in the sql statement that is executed as part of the cleanup
2. Add a configurable TimeSpan on the SqlServerStorageOptions class so that cleanup can be run more frequently.

Do these sound like changes you would be happy accepting? 

If you have any other suggestions or alternatives that would help with the cleanup please let us know.

**Comment by odinserj** [comment]
Travis, I'll be very happy to accept those PRs! Table locks were actual for previous expiration manager implementation and non-huge table sizes. So they were bad all the time :)
