### ISSUE TITLE
Increase the `Server.Id` column size

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#314]
Currently, this column has a max size of `50` chars, and sometimes this is not enough – please see [this thread](http://discuss.hangfire.io/t/error-on-hangfire-connections-to-the-sql-server/706). We may safely increase the max size of this column to `100` or so as the `Server` table contains very few records, without any growing.

To do this, we need to add a migration. However, I'm thinking about waiting for other schema changes, since I don't want to include this rare case in a dedicated migration.

**Comment by odinserj** [comment]
Issue #369 is aimed to change the schema too, please co-operate.

**Comment by odinserj** [comment]
Closing the issue as PR #376 is merged into the `dev` branch.

**Comment by tjipz8** [comment]
please increase the column size

when running on azure virtual node hangfire produce error 'String or binary data would be truncated'   

i have to manually change the datatype Server.Id column  to nvarchar(200)

**Comment by burningice2866** [comment]
> please increase the column size
> 
> when running on azure virtual node, hangfire produce error 'String or binary data would be truncated'
> 
> i have to manually change the datatype Server.Id column to nvarchar(200)

I believe you're free to propose a pull request with the necessary change, you can use this pull request as a basis which changed the server.id size to 100 https://github.com/HangfireIO/Hangfire/pull/376
