### ISSUE TITLE
Unit testing problem after update to version 1.3.4

### ISSUE THREAD

**Issue by sophisma** [HangfireIO/Hangfire#325]
Greetings. 
After updating Hangfire to version 1.3.4 some unit tests I had written previously started failing.
After debugging the test cases I traced the problem to the way that the arguments are handled on the new version.
In the following line of code I'm checking if a certain notification is being enqueued for processing:

this.backgroundJobClientMock.Verify(x => x.Create(It.Is<Job>(job => job.Method.Name == "ProcessNotification" && job.Arguments[0]) == notification.Id.ToString()), It.IsAny<EnqueuedState>()));

You can see that I'm checking if the notification's Id is being passed as an argument. 
Suppose that the id is 1, since the type of Arguments[0] is string, one would expect the value to be "1", but instead the value comes as "\"1\"" an the test fails. In this version of Hangfire the arguments include the canceled quotation marks, I'm guessing this is not the intended behavior.
The problem can be easily solved by using the following line instead but I just decided to write this to let you know about it.

this.backgroundJobClientMock.Verify(x => x.Create(It.Is<Job>(job => job.Method.Name == "ProcessNotification" && job.Arguments[0].Replace("\"", string.Empty) == notification.Id.ToString()), It.IsAny<EnqueuedState>()));

On the previous version we were using it was working fine.

**Comment by odinserj** [comment]
Starting from HangFire 1.1.0, job arguments are being serialized to JSON
strings using Json.net to handle more complex data structures and have a
simpler way to customize the serialization.

четверг, 12 марта 2015 г. пользователь sophisma написал:

> Greetings.
> After updating Hangfire to version 1.3.4 some unit tests I had written
> previously started failing.
> After debugging the test cases I traced the problem to the way that the
> arguments are handled on the new version.
> In the following line of code I'm checking if a certain notification is
> being enqueued for processing:
>
> this.backgroundJobClientMock.Verify(x => x.Create(It.Is(job =>
> job.Method.Name == "ProcessNotification" && job.Arguments[0]) ==
> notification.Id.ToString()), It.IsAny()));
>
> You can see that I'm checking if the notification's Id is being passed as
> an argument.
> Suppose that the id is 1, since the type of Arguments[0] is string, one
> would expect the value to be "1", but instead the value comes as "\"1\"" an
> the test fails. In this version of Hangfire the arguments include the
> canceled quotation marks, I'm guessing this is not the intended behavior.
> The problem can be easily solved by using the following line instead but I
> just decided to write this to let you know about it.
>
> this.backgroundJobClientMock.Verify(x => x.Create(It.Is(job =>
> job.Method.Name == "ProcessNotification" &&
> job.Arguments[0].Replace("\"", string.Empty) ==
> notification.Id.ToString()), It.IsAny()));
>
> On the previous version we were using it was working fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HangfireIO/Hangfire/issues/325>.
>


-- 
Kind regards, Sergey Odinokov,
Founder/developer @ http://hangfire.io
Contacts:
    Email: odinserj@gmail.com
    Skype: odinserj
