### ISSUE TITLE
enhance automatic retry with transient detection for azure

### ISSUE THREAD

**Issue by karoberts** [HangfireIO/Hangfire#326]
For running hangfire on azure with SQL Azure as the storage, you periodically get transient sql errors that will go away with a quick retry.

As part of issue 284, an automatic retry was added.  The problem is that it logs every exception, even if the exception is one of the transient sql errors that are common on azure.

Microsoft provides a simple way to detect if a sql exception is transient in this library
`Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling`
using this class
`SqlDatabaseTransientErrorDetectionStrategy`

It would be helpful to not log the transient errors, as they are just noise in the logs.  We see these in our logs on production and get alerted when the attempt succeeds on the very next retry.

**Comment by odinserj** [comment]
Implemented in the following way:

* 1st exception – logging with `LogLevel.Debug`.
* 2nd exception – with `LogLevel.Info`.
* 3rd – with `LogLevel.Warning`.
* Other – with `LogLevel.Error`.
* On attempts exceeded – with `LogLevel.Fatal`.
