### ISSUE TITLE
Support other languages in Dashboard

### ISSUE THREAD

**Issue by bhugot** [HangfireIO/Hangfire#331]
Hello,

Would be great if the dash board could be display in others langages.

Thanks.

**Comment by odinserj** [comment]
Yep, it would be awesome. There are two sub-tasks: 

1. Extract resources.
2. Think about [localization options](http://docs.nuget.org/Create/Creating-Localized-Packages).

I'll be glad to accept a pull request that implement this, after discussing localization approaches (under item 2).

**Comment by odinserj** [comment]
Is anybody wants to do this?

**Comment by schulz3000** [comment]
I'm interested in doing point 1. Can I start with it?
Also I think we need a third point here: Ability of setting the language. Should it be autodetected by browserlanguage or can the user set it manually?

**Comment by odinserj** [comment]
I think we should not reinvent the wheel here and use regular resource files to store translations and use regular .NET methods to retrieve the localized strings that use `CultureInfo.CurrentUICulture`. The main point is how to deliver the resource strings – use additional NuGet packages for satellite assemblies or store translations in one NuGet package.

**Comment by sackerud** [comment]
Any movement on this issue? I've done a couple of translations before and contribute with swedish. I'm gravitating towards the single package approach as described on nuget.org.

**Comment by gandarez** [comment]
I can help on translating to Portuguese as well.

**Comment by Elph** [comment]
I created a PR with this feature, please let me know what do you think...

**Comment by gandarez** [comment]
Looks good and as soon it gets approved by @odinserj I'll start translating to pt-BR.

**Comment by Elph** [comment]
I can work on the spanish translation also when accepted.

**Comment by gandarez** [comment]
@odinserj please tell me as soon as you get it accepted.

**Comment by odinserj** [comment]
I've just merged the PR by @Elph. So nothing prevents us from adding translations :tada: We can start from embedding localized resources into Hangfire itself without spawning additional NuGet packages due to the simplicity of this approach.
