### ISSUE TITLE
1.4.0 RC ignoring settings on BackgroundJobServerOptions

### ISSUE THREAD

**Issue by xavero** [HangfireIO/Hangfire#336]
The following code should start the HangFire server with the specified settings ( listening in the ExclusiveResource queue with one worker and SomeName). Instead, it's listening in the DEFAULT queue with 40 workers and using the machine name.
Only happens in HangFire 1.4.0 version. Version 1.3 it's ok.

```csharp
var options = new BackgroundJobServerOptions() {
  Queues = new string[] { "ExclusiveResource" },
  WorkerCount = 1,
  ServerName = "SomeName" };

var jobStorage = new Hangfire.SqlServer.SqlServerStorage("someconnectionstring");

JobStorage.Current = jobStorage;
JobActivator.Current = new Hangfire.Unity.UnityJobActivator(somecontainer);

app.UseHangfireServer(options, jobStorage);
```
![hangfire](https://cloud.githubusercontent.com/assets/2027728/7139173/2266fa54-e29b-11e4-802e-75b7c04234d3.png)

**Comment by xavero** [comment]
wow, that´s was fast.

**Comment by odinserj** [comment]
Thanks for reporting! Version 1.4.1 already shipped and [available in NuGet](https://www.nuget.org/packages/HangFire/).

**Comment by odinserj** [comment]
@xavero, this is yet another advantage of using continuous integration server and automatic deployment on tags :smiley:
