### ISSUE TITLE
Build project using bat with VS2013

### ISSUE THREAD

**Issue by Cussa** [HangfireIO/Hangfire#339]
There is a error of targeting when try to build the project using the bat with a machine that only have Visual Studio 2013.

I corrected this error in my fork, but can't test that in other VS.

https://github.com/Cussa/Hangfire/commit/5fdbb0df1bac7d6434932c60b9cc0505dc8c1e0c

**Comment by odinserj** [comment]
Intersting, what is the error message you have?

**Comment by odinserj** [comment]
@Cussa, any news?

**Comment by odinserj** [comment]
Okay, will remove it in 1.4.2, found some related QA on StackOverflow. Hope this will not hurt to other environments.

**Comment by odinserj** [comment]
Okay, I removed it. Thanks, @Cussa.
