### ISSUE TITLE
Halflings fonts are not available to FireFox

### ISSUE THREAD

**Issue by dealproc** [HangfireIO/Hangfire#341]
Want to debug this a bit more, but this is at least a placeholder for now... in Firefox, when Hangfire Dashboard is under SSL and attached to the ~/Hangfire url, the UI cannot seem to get the `~/hangfire/fonts/glyphicons-halflings-regular/woff` or `~/hangfire/fonts/glyphicons-halflings-regular/ttf` fonts.  Not sure the exact cause of this yet... just the first i'm noticing it.

**Comment by odinserj** [comment]
My development machine can't run Firefox for a strange reason I don't know (the whole window is always frozen). Have you learned something new about this bug?

**Comment by dealproc** [comment]
I haven't... going to need to create a demo project with 1.3.4 and see if i can re-create the issue.  the product we have Hangfire in is under code-freeze, so we can't take it to 1.4.0

**Comment by dealproc** [comment]
A blank project and adding the hangfire 1.4.1 libs seems ok.. but this is without the dashboard permissions information.  Will need to mock a user store and see if that makes a difference.

**Comment by odinserj** [comment]
@dealproc, please feel free to re-open this issue, if you have any news – I'm cleaning the issue list.
