### ISSUE TITLE
Enqueued jobs cannot be deleted from Dashboard

### ISSUE THREAD

**Issue by hernangm** [HangfireIO/Hangfire#342]
If you want to delete one or many jobs from the enqueued jobs page, they are note being deleted. However, if you click on the job id, and delete it from there, it does get deleted.

![imagen 2](https://cloud.githubusercontent.com/assets/393556/7209490/5db155ba-e51f-11e4-9996-a0ce33bfb85e.png)

**Comment by odinserj** [comment]
Thanks for the reporting, there was a small mistake in the order of routes for enqueued jobs page. The fix will be shipped with 1.4.2.

**Comment by hernangm** [comment]
No problem, the least I can do for such a wonderful tool!
