### ISSUE TITLE
Hangfire - Not taking any job from queue.

### ISSUE THREAD

**Issue by senthilsivanath** [HangfireIO/Hangfire#343]
Queue has many jobs to be processed but processing and scheduled count is 0. Basically hangfire not considering any jobs for processing.

![image](https://cloud.githubusercontent.com/assets/1016068/7243574/3eb17198-e7ec-11e4-8c91-0a36176c8488.png)

**Comment by odinserj** [comment]
Can you show me the queued jobs? You can also try to upgrade to 1.4.0, this can fix your error.

**Comment by senthilsivanath** [comment]
Have upgraded it to 1.4 and an app pool recycle resolved the issue.

**Comment by odinserj** [comment]
Yay, thanks for response. Closing the issue.
