### ISSUE TITLE
Multiple hangfire instances with single DB, but one shared application code

### ISSUE THREAD

**Issue by kimmobrunfeldt** [HangfireIO/Hangfire#344]
Our situation is that we have single database, and two instances applications which use hangfire to queue jobs. Our codebase, and thus methods are identical in both application instances.

Is there any possible problems with that scenario we should be aware of? One possible problem that comes to my mind is that in the deploy process, we might have different code for a moment in the instances. I read this issue https://github.com/HangfireIO/Hangfire/issues/69 too, but didn't get a full picture of all possible problems we might face.

**Comment by odinserj** [comment]
Hangfire uses distributed locks to synchronize work between application instances, so there will be no problems with multiple application instances.

Different code *may* cause problems, you are right. But what case do you mean?

**Comment by kimmobrunfeldt** [comment]
Ok thanks for the information!

I mean the case where we deploy a new version of our app:

* Publish new code to instance 1

--- Here's the moment where applications use different code, it might take 5 to 60 minutes ---

* Publish new code to instance 2

**Comment by odinserj** [comment]
In this case you have the same problems with your regular web requests (user submits request to instance 2, and it uses an old code base to process it). How do you handle them?

**Comment by kimmobrunfeldt** [comment]
Yeah we'll have problems with the normal requests too. I was thinking that we maybe could serve read-only routes in between deployment, but probably we will eventually have to have small maintenance breaks anyway.

**Comment by kimmobrunfeldt** [comment]
Thanks for the help!

**Comment by odinserj** [comment]
You can also use job versioning to control code change issues. So instead of using `MyJob.DoStuff` method you can have `MyJob.DoStuffV1` and `MyJob.DoStuffV2` (better to use interfaces with namespaces like `V1`, `V2` or so). So you are able to modify code of `DoStuff` and have explicit control what to do if a worker executes previous version (fail, invoke the new version with new arguments or so).
