### ISSUE TITLE
Rename hangfire instance in dashboard

### ISSUE THREAD

**Issue by ojosdegris** [HangfireIO/Hangfire#346]
Right now I have multiple asp.net apps on the same server using the same db. In the dashboard they are shown as 

xxxx-servername:port1
xxxx-servername:port2

is there a way to set custom name when registring hangfire in owin?

**Comment by odinserj** [comment]
```csharp
var options = new BackgroundJobServerOptions
{
    ServerName = "MyServerInstance"
};

var server = new BackgroundJobServer(options);
// or
app.UseHangfireServer(options);
```

But double check that different processes use different server names.

**Comment by ojosdegris** [comment]
Thank you Sergey!
