### ISSUE TITLE
ArgumentRenderer - Support for TimeSpan and DateTime

### ISSUE THREAD

**Issue by yngndrw** [HangfireIO/Hangfire#353]
The "fullArgs" sample includes TimeSpan and DateTime parameters which are rendered as:
```cs
    FromJson<TimeSpan>("\"12:13:14\""),
    Deserialize<DateTime>("2012-11-10T00:00:00.0000000"),
```

There is no Argument render for these hence the deserialisation in the output, but it would be nicer if they were rendered as:
```cs
    TimeSpan.Parse("12:13:14"),
    DateTime.Parse("2012-11-10T00:00:00.0000000"),
```

A block can be added into "public static ArgumentRenderer GetRenderer(Type type)" in JobMethodCallRenderer.cs (Around line #334):
```cs
                if (type == typeof(TimeSpan) || type == typeof(DateTime))
                {
                    return new ArgumentRenderer
                    {
                        _enclosingString = String.Empty,
                        _valueRenderer = value => String.Format(
                            "{0}.Parse({1})",
                            WrapType(type.Name),
                            WrapString(string.Format("\"{0}\"", value)))
                    };
                }
```

**Comment by yngndrw** [comment]
Pull request added: #354

![image](https://cloud.githubusercontent.com/assets/1834655/7442777/a140f25a-f117-11e4-9d40-2799d2275d3e.png)

**Comment by yngndrw** [comment]
Pull request created: #358

![image](https://cloud.githubusercontent.com/assets/1834655/7442777/a140f25a-f117-11e4-9d40-2799d2275d3e.png)

**Comment by odinserj** [comment]
Closing the issue as PR is already merged.
