### ISSUE TITLE
Sql Queue name length

### ISSUE THREAD

**Issue by maleet** [HangfireIO/Hangfire#369]
I like to have descriptive queue names and length of 20 is quite restrictive. Can't it be nvarchar(50)?

    [HangFire].[JobQueue](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[JobId] [int] NOT NULL,
	[Queue] [nvarchar](20) NOT NULL,
	[FetchedAt] [datetime] NULL)

I know I can have instead of queue named "company_client_web_result_jobs" "c_c_w_r_j" but then I need to have separate documentation what describes purpose of this queue.

**Comment by odinserj** [comment]
Agreed, would you like to create a PR for this?

**Comment by odinserj** [comment]
Closing the issue as PR #376 is merged into the `dev` branch.
