### ISSUE TITLE
Jobs fetched in a wrong order from multiple queues

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#370]
The `BackgroundJobServerOptions` class allows you to specify multiple queues to listen:

```csharp
var queues = new [] { "critical", "default" };
var options = new BackgroundJobServerOptions { Queues = queues };
```

In many examples it is shown that a worker will fetch jobs from the `critical` queue first, and then from the `default` giving a possibility to use jobs priorities. However currently jobs from the `default` are served first. If you use 3 or more queues, priority becomes even more weird:

```csharp
var queues = new [] { "queue-1", "queue-2", "queue-3" };
```

Currently, priority is the following: `queue-2`, then `queue-3`, then `queue-1`. However, it should be: `queue-1`, then `queue-2`, then `queue-3`.

/cc @BoltR, @marcoCasamento

**Comment by BoltR** [comment]
Sorry for the delay in replying to this, I've been busy with vacation/sickness and haven't had a chance to look through any code until now.

The old behavior was that queues aren't created until they are used. Every time a job is added to one of the queues it also tries to add that queue to the Set containing the available queues. This explains why they are sometimes out of order; If queue-1 isn't used for a week, it won't even exist until it is and then is tacked on to the end. It is kind of wasteful.

No matter which way I think of fixing this **solely inside the JobStorage code** it requires passing the list of queues/BackgroundJobServerOptions into the JobStorage:
-The method that would require the least changes to how the Redis *implementation* currently works would be having the list of queues available when jobs are added. That way you could check every time a job is added to make sure the queue is added in the correct position. However, this is overly complex, and very wasteful.
-The method that requires the least friction would be creating the queues when the JobStorage is created. You get the major benefit of removing the queue adding code from each job creation. However, you are still passing the list of queues into the JobStorage constructor. This slightly complicates setup code, and gives the opportunity for the end user to really break something if they don't do it correctly. For no benefit I can think of other than fixing this bug?

In my mind the proper way to fix this is to have Hangfire create the queues when it is initialized. That way the JobStorage code can remain queue unaware.

Considering your have already closed the issue, I will assume that it's something that you have already fixed. Maybe I am completely off base with my reasoning on this issue, but with your past indication (that I agree with) that the Redis structure be the same between implementations, I am not sure what *I* am supposed to do to fix this in my own implementation?

**Comment by BoltR** [comment]
Would you consider adding a `public abstract void SetQueues(string[] queues)` to the definition of JobStorage?
That way each JobStorage has an easy way to manage queue creation/deletion in a way that Hangfire can guarantee happens at the proper time?

**Comment by BoltR** [comment]
Ugh, it just occurred to me after looking through the code that I was probably looking at this problem the wrong way. You probably don't care the order than the storage returns the queues in to things such as the MonitoringApi, you only care about the result of FetchNextJob.

In which case, ignore all my previous comments. I guess I should have waited an extra day to recover before looking at this!

**Comment by odinserj** [comment]
That is the diff for the fix:

![image](https://cloud.githubusercontent.com/assets/1078718/7725873/0cdf5fd6-ff07-11e4-871c-ede6f820034c.png)

**Comment by BoltR** [comment]
Thank you, I had already put in a similar fix.Though, thinking about it again today, I should probably tweak things slightly so one worker doesn't potentially get stuck waiting on a job in a queue that will never come.

Sorry about all those comments above. I had completely misunderstood what the problem was, and had forgotten that the BackgroundJobServerOptions just controls what queues are to be processed, rather than what queues are in storage.
A embarrassingly slow start to getting back up to speed.

**Comment by odinserj** [comment]
@BoltR, don't worry, my description of an issue is not as full as should be :frowning:
