### ISSUE TITLE
Run recurrings jobs on per machine basis

### ISSUE THREAD

**Issue by bjornsallarp** [HangfireIO/Hangfire#379]
We have a load balanced application and have a couple of small jobs that fetches something externally and stores in memory on the server. Each job has to run on each machine, obviously, so I configured each server to have a unique queue and a shared default queue. The recurring jobs are attributed with  my "LocalQueueAttribute" to make them one per machine. The queue-name doesn't make the job unique from a job with the same name on a different queue so it doesn't work. Depending on which machine picks it up and schedules it will also run it.

Is there a way to achieve this already or functionality that could be added?

**Comment by maleet** [comment]
+1

**Comment by odinserj** [comment]
Since 1.5.0-beta1 it is possible to specify a queue for recurring job at runtime so you could use local queues for each machine. Please read http://hangfire.io/blog/#queues-for-recurring-jobs

**Comment by bjornsallarp** [comment]
Awesome! I'll try it out. Thanks for the great work you're putting into this library!
