### ISSUE TITLE
How to stop a job ?

### ISSUE THREAD

**Issue by tiger2014** [HangfireIO/Hangfire#380]

**Comment by odinserj** [comment]
Just ensure your method is using [cancellation tokens](http://docs.hangfire.io/en/latest/background-methods/using-cancellation-tokens.html) and call the `BackgroundJob.Delete` method.

```csharp
var jobId = BackgroundJob.Enqueue(() => SomeMethod(JobCancellationToken.Null));
BackgroundJob.Delete(jobId);
```

**Comment by tiger2014** [comment]
but I use 'RecurringJob.AddOrUpdate(() => Console.WriteLine("重复任务：每秒"), "0/5 * * * *  ");'

How to stop it ?

**Comment by odinserj** [comment]
Here is the code:

```csharp
RecurringJob.RemoveIfExists("Console.WriteLine");
```
