### ISSUE TITLE
"Manual launch" jobs or recurring jobs without schedule

### ISSUE THREAD

**Issue by geirsagberg** [HangfireIO/Hangfire#382]
It would be really cool if one could register jobs that will show up in the dashboard but can only be launched manually, e.g. `ManualJob.AddOrUpdate<IMyService>(service => service.DoOneTimeStuff())`.

I have tried hacking it with e.g. recurring jobs with CRON expressions for 31st of February, but Hangfire crashes.

**Comment by smhinsey** [comment]
I'd be interested in this as well.

**Comment by vip32** [comment]
interesting how you want to pass in the job arguments then. the dashboard should also facilitate that.
the feature sure is interesting, in my current project we build a mvc pages which can handle our non scheduled job starting. another scenerio is making a POST request to the dashboard to start a job, so a more JS style app can take care.

**Comment by kataik** [comment]
I'd like to have something like that as well, for example
`jobId = BackgroundJob.Stash<IMyService>(service => service.DoOneTimeStuff());`
`DoOtherStuff();`
`BackgroundJob.Enqueue(jobId);`

**Comment by gandarez** [comment]
@kataik what did you mean with "stash"? Does it have the same meaning of "Manual Update"?

**Comment by gandarez** [comment]
+1

**Comment by kataik** [comment]
Hi Carlos,
I mean it would be nice to have something scheduled somewhere, but
trigerred manually - even from a different service. If you mean something
like that on "Manual Update", then yes. :)

Best,
Kornél

2015-11-29 23:05 GMT+01:00 Carlos Henrique Guardão Gandarez <
notifications@github.com>:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HangfireIO/Hangfire/issues/382#issuecomment-160475354>
> .
>



-- 
Kornél Bálint Kátai
Software Developer

Sonrisa Kft
H-1022 Budapest, Bég u. 3-5., HUNGARY

**Comment by gandarez** [comment]
@kataik I'll try to do something related to it into my branch "manual-job"
https://github.com/gandarez/Hangfire/tree/manual-job

**Comment by gandarez** [comment]
Hey guys I've done 99% of the new Manual State job. Please refer to https://github.com/gandarez/Hangfire/commit/830f3ebe87ad2432959978bdca7ab4cfe201b8a7

**Comment by vip32** [comment]
a meaningful addition. will your solution be merged? seems like it cannot work as a standalone extension.

**Comment by gandarez** [comment]
@vip32 I didn't do PR yet!

Could you please clone my repo and try by yourself?
https://github.com/gandarez/Hangfire/tree/manual-job

**Comment by JesseKlaasse** [comment]
Has this ever been merged into the main branch? This is a very valuable addition..

**Comment by wmekal** [comment]
Hi @geirsagberg @smhinsey @vip32 @kataik @gandarez,

What is the status of this issue? 

Client asked for such a thing in my project...

**Comment by geirsagberg** [comment]
Doesn't look like anything is merged yet, and no PR has been made. The next steps would be for someone to:

1. Fork @gandarez' repo https://github.com/gandarez/Hangfire/tree/manual-job
2. Rebase on latest master from upstream
3. Send a PR

I'd do it myself, but unfortunately cannot prioritize this at the moment.

**Comment by wmekal** [comment]
Thanks for reply!

I'll ask whether I can do it as work for my client, then I'm able to do it soon. 

Eventually, but I cannot guarantee when, I can do it in my free time.

**Comment by odinserj** [comment]
You can now create recurring jobs that never occur by choosing some great date like `Feb 31` for cron expression, and those jobs will be placed at the top of the list in the dashboard.

**Comment by wmekal** [comment]
Thanks for information :).

**Comment by Recodify** [comment]
`RecurringJob.AddOrUpdate(() => new MyJob().Execute(null), Cron.Never);`

**Comment by toepoke** [comment]
Thanks @Recodify - for anyone else the job appears in the dashboard as "DISABLED" but can be executed through the dashboard UI.

I'd argue you don't need a specific feature?
