### ISSUE TITLE
dashboard recurring jobs sorting

### ISSUE THREAD

**Issue by vip32** [HangfireIO/Hangfire#391]
the job list is not sorted on Id. i use alphanumeric Ids and they are randomly sorted.

**Comment by vip32** [comment]
actually it should be sorted on the Value column (however the UI shows the field as Id)

Could roughly be fixed in SqlServerConnection like this:
```csharp
public override List<string> GetRangeFromSet(string key, int startingFrom, int endingAt)
        {
            if (key == null) throw new ArgumentNullException("key");

            const string query = @"
select [Value] from (
	select [Value], row_number() over (order by [Value] ASC) as row_num 
	from HangFire.[Set]
	where [Key] = @key 
) as s where s.row_num between @startingFrom and @endingAt order by s.Value";

            return _connection
                .Query<string>(query, new { key = key, startingFrom = startingFrom + 1, endingAt = endingAt + 1 })
                .ToList();
        }
'''

**Comment by odinserj** [comment]
In the latest 1.7.0 betas recurring jobs are sorted based on their next execution interval, starting with those that will not be scheduled (scheduled to Feb 30, for example).

**Comment by abelbraaksma** [comment]
> ecurring jobs are sorted based on their next execution interval

Not anymore. At least in the current version, recurring jobs that happen tomorrow are in the middle, at the beginning and at the bottom of the list.

I'll create an issue to make this configurable.
