### ISSUE TITLE
Hangfire packages have improper casing

### ISSUE THREAD

**Issue by MichaelGG** [HangfireIO/Hangfire#393]
The package names use HangFire, but the assemblies use Hangfire. This causes builds on case-sensitive systems to fail to find the files.

**Comment by MichaelGG** [comment]
Any way we can get this renamed? Causes manual intervention each time a package is upgraded.

**Comment by odinserj** [comment]
@MichaelGG, I've contacted NuGet support and asked them to change the casing of a package. If this will not help, I'll contact other people. In ASP.NET 5 wrong casing will be a big headache.

**Comment by MichaelGG** [comment]
Any luck there?

**Comment by odinserj** [comment]
Package casing is not an issue anymore with recent .NET Core versions.
