### ISSUE TITLE
Queued Jobs executed out of order?

### ISSUE THREAD

**Issue by AdityaSantoso** [HangfireIO/Hangfire#398]
Hi, I got quite an odd problem today. 

There are two jobs that were created and enqueued at the same second, very close to each other. The queue only has one worker. But it seems like they were executed out of order. This is the snippet from the state of the database. The job in question has id 9107 and 9108. 9108 is executed first before 9107. 

From Hangfire.Job:

Id   | StateId   | StateName   | CreatedAt             | ExpireAt
---- | --------- | ----------- | --------------------- | --------
9107 | 28584     | Succeeded   |2015-07-09 03:07:49.117|2015-07-10 03:07:50.307
9108 | 28577     | Succeeded   |2015-07-09 03:07:49.240|2015-07-10 03:07:49.760

From Hangfire.State, note the bolded "EnqueuedAt" and "StartedAt":

Id  | JobId | Name   | Reason | CreatedAt| Data
--- | ----- | ------ | ------ | -------- | ----- 
28574|9107|Enqueued|NULL|2015-07-09 03:07:49.320|{"EnqueuedAt":**"2015-07-09T03:07:49.1155927Z"**,"Queue":"subonp"}
28578|9107|Processing|NULL|2015-07-09 03:07:49.790|{"StartedAt":**"2015-07-09T03:07:49.7746512Z"**,"ServerId":"subscriberorderandportfolio:rd00155df07156:996","WorkerNumber":"1"}
28584|9107|Succeeded|NULL|2015-07-09 03:07:50.040|{"SucceededAt":"2015-07-09T03:07:50.0241239Z","PerformanceDuration":"147","Latency":"766"}
28573|9108|Enqueued|NULL|2015-07-09 03:07:49.320|{"EnqueuedAt":**"2015-07-09T03:07:49.2406106Z"**,"Queue":"subonp"}
28575|9108|Processing|NULL|2015-07-09 03:07:49.540|{"StartedAt":**"2015-07-09T03:07:49.5397152Z"**,"ServerId":"subscriberorderandportfolio:rd00155df07156:996","WorkerNumber":"1"}
28577|9108|Succeeded|NULL|2015-07-09 03:07:49.760|{"SucceededAt":"2015-07-09T03:07:49.7428509Z","PerformanceDuration":"184","Latency":"315"}

Any idea what could have caused this? Smells like quite a nasty race condition.

**Comment by yngndrw** [comment]
No ordering is specified on the dequeue query so jobs can be pulled in any order that SQL Server decides: (I'm assuming SQL Server here)
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerJobQueue.cs#L50

I don't think it makes sense to try to guarantee Job Processing order with something like Hangfire for a couple of reasons:
1) If there are multiple workers, jobs may be completed in a different order to the order in which they are picked up.
2) If there is a transient failure, the job may be re-queued and end up being processed at a later time.

Hangfire only guarantees at-least once processing.

**Comment by AdityaSantoso** [comment]
It is indeed SQL Server. Does the same behaviour apply to other storages like MSMQ? 

Maybe I got the wrong impression that the job "queue" implies a FIFO job ordering. But assuming single-worker scenario is that not expected that first order that got in is also the first that got processed? I agree that failure case does make things a bit hairy ... 

If a simple `Enqueue()` does not suffice, do you have any suggestions as to how to guarantee job processing ordering? I don't mind exploring other libraries or frameworks if it comes to it

**Comment by yngndrw** [comment]
As far as I'm aware MSMQ only guarantees message ordering for transactional inserts into a transactional message queue, subject to the failure caveat that I mentioned above. Other queues such as the AWS Simple Queue Service do not guarantee message ordering at all, not that there's a Hangfire storage provider for that but I just wanted to show that a number of queues do not guarantee message order. I'm not sure what guarantees Redis provides.

SQL server will usually return results in the natural order without an order by clause, but it is technically undefined behaviour and it does occasionally return them in a different order. The solution here would be to specify the order, but that would likely be slightly slower. Maybe this could be a configurable change to the Hangfire SQL storage provider ?

As for suggestions, it depends on how critical the ordering is and if you just need to retain the ordering across small groups of items or across all of them.

If you only need to retain ordering across small groups you could use continuations which were added in v1.4.0 which will allow you to setup your dependencies
http://hangfire.io/blog/2015/04/13/hangfire-1.4.0.html

I'm not fully sure if the MSMQ storage provider could guarantee your ordering, but you could try that. I believe it would work for your usage, but you need to ensure that the jobs were inserted and persisted in the correct order.

You could also consider just using MSMQ on its own with a transactional queue and transactional inserts / reads.

**Comment by AdityaSantoso** [comment]
Thanks for the pointers. Continuation looks good. For my use case I only need to make it such that a small group of jobs have guaranteed ordering. I can maintain the job id of previous jobs and make the current job a continuation of that job id. Bonus point that it is not storage specific I guess.
