### ISSUE TITLE
Generic method in Job

### ISSUE THREAD

**Issue by ztam** [HangfireIO/Hangfire#408]
I'm trying to enqueue a generic method:

`BackgroundJob.Enqueue(() => MyService.DoWork<T>(p1, p2, p3);`

This seems to be a resolved issue: https://github.com/HangfireIO/Hangfire/issues/136 but I get the following error:

<pre>System.ArgumentException

The type or method has 1 generic parameter(s), but 0 generic argument(s) were provided. A generic argument must be provided for each generic parameter. 

System.ArgumentException: The type or method has 1 generic parameter(s), but 0 generic argument(s) were provided. A generic argument must be provided for each generic parameter.
   at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParamters)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at Hangfire.Storage.InvocationData.GetNonOpenMatchingMethod(Type type, String name, Type[] parameterTypes)
   at Hangfire.Storage.InvocationData.Deserialize()</pre>

What am I missing here?

Thanks

**Comment by Ermesx** [comment]
What is T ? What Type ?
When you use generic parameters they have to be strong specified.
It means T = ex. string.

**Comment by ztam** [comment]
T is my custom type passed on from the containing method, I should have written `<CustomType>` instead.

**Comment by supergibbs** [comment]
Any update on this issue? I'd prefer to not write my job without generics...

**Comment by supergibbs** [comment]
Apparently it works in v1.2.0+ with a wrapper class but it's not well documented. I found it in the [release notes](https://github.com/HangfireIO/Hangfire/releases/tag/v1.2.0).

https://github.com/HangfireIO/Hangfire/pull/222

**Comment by fabriciogs** [comment]
I'm having the same kind of issue. This the signature of my method:

```c#
        [AlertFail]
        [AutomaticRetry(Attempts = 3)]
        [Queue("centralfile")]
        public void ProcessFile(string connectionString, IEnumerable<T> entityList,
            long processId, int userId)
{...}
```

The issue seems to be: IEnumerable<T>

Using 1.5.0-beta2 here.

**Comment by ditrytus** [comment]
We were having the exact same problem recently while enqueuing methods with the following signature:
```
public void Foo<T>(IEnumerable<T> aList) 
```
I read the source code and done some experiments and it seems that Hangfire can deserialize job invocation of generic method only if arguments types are given exactly in generic arguments like this:
```
public void Foo<T>(T aList)
```
As a workaround we had to refactor our method like this:
 ```
public void Foo<T>(T aList) where T : IEnumerable
```
And we had to give up on our enumerable items to be strongly typed but it worked.
I think it wouldn't be much effort to serialize generic parameters values along with the rest of job invocation, and then Hangfire could easily support all sorts of generic methods.

**Comment by manura** [comment]
We use Hangfire to queue and execute our services.

Here is our implementation

public interface IHangfireTask
	{
		/// <summary>
		/// Executes the service.
		/// </summary>
		/// <param name="context">The context.</param>
		void Execute(string context);
	}

//called method
public void AddToQueue<T>(string contex) where T : IHangfireTask
		{
			BackgroundJob.Enqueue<T>(x => x.Execute(context))
		}

//calling the method to enque job
	RecurringJob.RemoveIfExists(job.Id);
		
		 RecurringJob.AddOrUpdate<JobQueueManager>(
                job.Id,
                x => x.ConnectionIterate<DispatchUserExpiryAdminReminder>(job.JobType),
                job.Expression);
				
				RecurringJob.Trigger(job.Id);

But when I try to debug the code it gives the following error.

The type or method has 1 generic parameter(s), but 0 generic argument(s) were provided. A generic argument must be provided for each generic parameter.

But If we call like this it works 

BackgroundJob.Enqueue<DispatchUserExpiryAdminReminder>(x => x.Execute(context))

Does anybody having idea about this.

**Comment by supergibbs** [comment]
@manura You need to use a wrapper class, see my comment above
