### ISSUE TITLE
Flat file or in-memory storage

### ISSUE THREAD

**Issue by dzolnjan** [HangfireIO/Hangfire#409]
Is there support for embedded or simple in-memory store?

**Comment by nirinchev** [comment]
Yes - https://github.com/perrich/Hangfire.MemoryStorage

Or via nuget: ```Install-Package Hangfire.MemoryStorage```

**Comment by vip32** [comment]
sqlite provider (:memory:) is also in progress https://github.com/vip32/Hangfire.SQLite

**Comment by pvanroos** [comment]
Any flat file support?
