### ISSUE TITLE
Recurring job within date/time range

### ISSUE THREAD

**Issue by dzolnjan** [HangfireIO/Hangfire#411]
Is it possible to define recurring job like this:

1) start at 10:00
2) stop at 16:00
3) repeat every minute while within 1 and 2 ( currentTime => 1 < currentTime < 2 )
4) run this every day
*) plus if possible define 1 and 2 to run in specific timezone

**Comment by nirinchev** [comment]
Recurring jobs take as input regular cron string. So any pattern you can specify as cron will be possible for recurring jobs. For your example, you can use ```* 10-16 * * *```. This will run the job every minute between 10 and 16, every day. You can use some online tool like http://www.cronchecker.net/ to validate your cron formats.

I don't think you can specify different timezones though, so you'll have to convert to UTC the start and end times.

**Comment by jcoutch** [comment]
For others who run across this post and want to use a cron string within a specified date range, I added a new job type and published it as a Nuget package: [`Hangfire.RecurringDateRange`](https://www.nuget.org/packages/Hangfire.RecurringDateRange/).  Usage information is on the main [GitHub repo](https://github.com/jcoutch/Hangfire.RecurringDateRange).

It's just a copy of RecurringJobManager and RecurringJobScheduler, but altered to only trigger during a specified date range AND when the supplied cron expression matches.  It's also using NCrontab.Advanced under the covers.

It hasn't been thoroughly tested (as of version 0.2.0.1), so if you find any bugs, feel free to report them:
https://github.com/jcoutch/Hangfire.RecurringDateRange/issues
