### ISSUE TITLE
Stack trace markup code missing copyright notice

### ISSUE THREAD

**Issue by atifaziz** [HangfireIO/Hangfire#418]
The [stack trace markup code in Hangfire](https://github.com/HangfireIO/Hangfire/blob/5a770aab402b820f262f0872b18c2d3304bb7128/src/Hangfire.Core/Dashboard/HtmlHelper.cs#L250-L395) seems to [come from the ELMAH project](https://bitbucket.org/project-elmah/1x/src/7576b913e220d9ddf5473f5875f5ea8ce3380c9e/src/Elmah/ErrorDetailPage.cs?at=default#ErrorDetailPage.cs-383). ELMAH uses [Apache License, Version 2.0](https://bitbucket.org/project-elmah/1x/src/7576b913e220d9ddf5473f5875f5ea8ce3380c9e/COPYING.txt?at=default), which requires (at the very least and among other things) that the [copyright notice](https://bitbucket.org/project-elmah/1x/src/7576b913e220d9ddf5473f5875f5ea8ce3380c9e/src/Elmah/ErrorDetailPage.cs?at=default#ErrorDetailPage.cs-4) be maintained.

**Comment by odinserj** [comment]
Hello, @atifaziz. I've added all the notices with commit 5ed91f13b37aba991b2977615b090afbf8716bef. I've also included them into [Third party files and licenses](http://hangfire.io/licensing.html#third-party-files-and-licenses) section in the official site. I'm adding all the used projects to give appropriate attributions, even when a license don't require to do so, but completely missed your code, sorry for this. Your stack trace highlighter significantly improves the debugging experience when something goes wrong, thank you for it!

Should I do anything else?

**Comment by atifaziz** [comment]
@odinserj Thanks for addressing this so quickly and [dedicating a page where you explicitly list the various libraries and licenses](http://hangfire.io/licensing.html#third-party-files-and-licenses) is commendable and goes a step further than most.

> Should I do anything else?

I would've said that it's important to also mention that the stack trace highlighting code is licensed under [Apache License, Version 2.0](http://www.apache.org/dev/apply-license.html). Your modifications, if you had made any, would go with the terms of [LGPL v3](http://www.gnu.org/licenses/lgpl-3.0.en.html). However, I have a better proposal. Incidentally, I recently refactored and extracted the stack trace parsing and formatting code from [ELMAH](https://elmah.github.io/) into stand-alone projects and NuGet packages:

* [StackTraceParser](https://github.com/atifaziz/StackTraceParser)
* [StackTraceFormatter](https://github.com/atifaziz/StackTraceFormatter)

What I could offer is a PR that uses those via NuGet to the same effect and in lieu of the code you have currently included. The packages from both projects directly include the source code into the host project so there's going to be no external dependencies introduced at the library/binary level. Moreover, all code elements will be internal so your public API surface will remain identical before and after. Any objections? Should I go ahead?

**Comment by odinserj** [comment]
Hm, explicit license name makes sense, I've just added it, thank you for the tip. [StackTraceFormatter](https://github.com/atifaziz/StackTraceFormatter) is definitely solves all the problems. I've planned this change for the next release (some betas already available). If you have time and would like to incorporate the changes to the `dev` branch, I'll be happy to receive them from you (I'm using ELMAH for a veery long time).

**Comment by atifaziz** [comment]
Submitted PR as #419.

Glad to hear ELMAH has been serving you well.
Thanks for Hangfire, which is awesome!
