### ISSUE TITLE
TypeConverter cannot convert from System.String.

### ISSUE THREAD

**Issue by ppumkin** [HangfireIO/Hangfire#438]
New commer here. Installed this into my webforms app, got everything going fine. But on my first test I get this error.

This is the data it shows on dashbaord.

```
using Web.UI.Libs.MsDynamicsCrm;

ContactUs.PostToCRMAndEmail(
    Deserialize<UserRequestData>("{\"UserHostAddress\":\"::1\",\"UserAgent\":\"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36\",\"JTrackCookie\":{\"Name\":\"jtrack\",\"Path\":\"/\",\"Secure\":false,\"Shareable\":false,\"HttpOnly\":false,\"Domain\":null,\"Expires\":\"0001-01-01T00:00:00\",\"Value\":\"827-1438589078631\",\"HasKeys\":false,\"Values\":[null]},\"UTMZCookie\":null}"),
    "ppumkin",
    "testing@no.solutions",
    "testing",
    "075",
    "Testing from local, and hangfire",
    "Business Lease",
    1);

```

And the errror

```
Failed An exception occurred during arguments deserialization.
System.NotSupportedException

TypeConverter cannot convert from System.String.

System.NotSupportedException: TypeConverter cannot convert from System.String.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Hangfire.Common.Job.DeserializeArguments(IJobCancellationToken cancellationToken)
```

Any suggestions?

**Comment by odinserj** [comment]
What Hangfire version are you using?

**Comment by ppumkin** [comment]
Hangfire 1.4.6

**Comment by odinserj** [comment]
This may happen, when Json.NET can not deserialize the `UserRequestData` class. Does it serve as a base class for other DTOs that you are passing to the `Enqueue` method?

**Comment by ppumkin** [comment]
That class was specifically designed for fire and forget :0

````
    public class UserRequestData
    {
        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }
        public HttpCookie JTrackCookie { get; set; }
        public HttpCookie UTMZCookie { get; set; }


        /// <summary>
        /// Constructor to be used in "HTTPRequest" with context to be passed to out of context queued operations.
        /// </summary>
        /// <param name="HTTPRequest"></param>
        public UserRequestData(HttpRequest HTTPRequest)
        {
            UserHostAddress = HTTPRequest.UserHostAddress;
            UserAgent = HTTPRequest.UserAgent;
            JTrackCookie = HTTPRequest.Cookies["jtrack"];
            UTMZCookie = HTTPRequest.Cookies["__utmz"];
        }
    }
````

**Comment by Caldas** [comment]
Did you tried to add a simples Constructor without parameters?

**Comment by ppumkin** [comment]
Yea I just removed the constructor, and only left the properties inside the calls. I assing the porerties before the Enqueu... same problem. Goes into Queue then Retreis x 10. Maybe its the CookieData its trying to deserialise and failing... maybe because of NULL?

**Comment by ppumkin** [comment]
IT works now without HttpCookie

```
  public class UserRequestData
    {
        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }
        //public HttpCookie JTrackCookie { get; set; }
        //public HttpCookie UTMZCookie { get; set; }
  }
```

**Comment by odinserj** [comment]
Json.Net can't deserialize those objects too. Try to use simpler types, e.g. include only data you need, you can't modify cookies in a background job anyway. 

I've modified Hangfire to throw original Json deserialization exception to help to reveal the original problem. Don't like hidden exceptions :-)

**Comment by ppumkin** [comment]
Thanks a million. 
I have lots of room to redo the models the way they need to be.

So I moved back the constructor into the Model and it throws the same error. So its not just complex types really. 

I am sure I used JSON.NET to serialise and deserilase classes like this many times before. It doesn't make sense to me. :( This is realllly simple model its failing on with the same exception message :(

```
ContactUs.PostToCRMAndEmail(
    FromJson<UserRequestData>("{\"UserHostAddress\":\"::1\",\"UserAgent\":\"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36\",\"JTRackID\":\"=1\"}"),
    "ppumkin",
    "testing@no.solutions",
    "testing",
    "075",
    "Testing from local, and hangfire",
    "Business Lease",
    1);
```

**Comment by odinserj** [comment]
The exception will be improved, but in the next version. Now it throws because Json.net can't deserialize classes without default constructor. Please add it and place `JsonConstructor` attribute on it to allow Json.net to choose the correct constructor overload, if you still need to have a constructor with HttpRequest parameter.

```csharp
    public class UserRequestData
    {
        public string UserHostAddress { get; set; }
        public string UserAgent { get; set; }
        public HttpCookie JTrackCookie { get; set; }
        public HttpCookie UTMZCookie { get; set; }

        [JsonConstructor]
        public UserRequestData() {}

        public UserRequestData(HttpRequest HTTPRequest)
        {
            UserHostAddress = HTTPRequest.UserHostAddress;
            UserAgent = HTTPRequest.UserAgent;
            JTrackCookie = HTTPRequest.Cookies["jtrack"];
            UTMZCookie = HTTPRequest.Cookies["__utmz"];
        }
    }
```

**Comment by ppumkin** [comment]
Haaaa, I knew it was something to do with default constructor. I just missed the Json attribute, but was reading about it just as you posted. Yea, this worked, but you MUST put that `JsonConstruct` attribute on, without it it wont work either.

OK This solves a double whammy I suppose.

Thanks!

**Comment by odinserj** [comment]
Okay, glad to hear, thanks for highlighting the problem with deserialization exception messages!
