### ISSUE TITLE
Exceptions seem to be swallowed after first retry

### ISSUE THREAD

**Issue by thomaseyde** [HangfireIO/Hangfire#441]
I have a recurring task, running every minute. It's job is to read events from NEventStore from a given checkpoint. When the task succeeds, it will write the last successful checkpoint to disk.

Here's what happens:

- I restart the website
- Task runs as expected
- Task fails, there's a problem with an external service
- A retry is scheduled, it contains the exception details 
- The retry succeeds for some reason

Every run after this succeeds, according to Hangfire, but:

- The checkpoint is never updated. That's why I know the task isn't really successful.
- Every task runs as scheduled after this, but they finish suspiciously fast.
- There are no more retries.
- There are no failed tasks, but there should be.
- I also log unhandled exceptions to Elmah, but none is logged.

If I restart the website again, it starts all over by failing and retrying once, then all false positives.

**Comment by odinserj** [comment]
Thomas, can't reproduce the issue. The following method is retrying correctly until I'm fixing the method:

```csharp
public void Test() { throw new InvalidOperationException(); }
```

Can you tell more details about exception you are receiving. Could you make a GitHub repo with reproduction of your issue?

**Comment by thomaseyde** [comment]
I think I finally nailed it down:

I have a long running task that will sometimes take longer than the scheduled period. So to prohibit the task from running more than once, I guard it with the following:

        static int isProcessing;

        public static void Fail()
        {
            if (Interlocked.CompareExchange(ref isProcessing, 1, 0) != 0) return;
            // something fails here...
            Interlocked.Exchange(ref isProcessing, 0);
        }

*I realize now that I am not protecting the guard against failures, so when an exception happens, it will not reset the flag, which is why all future jobs end immediately. But the first one still failed. Why isn't the failure reported?*

I corrected this by wrapping it in a `try..finally` block. The job list now shows successful jobs where the duration alternates between long and short.

The problem still remains, but in a different way:

- Failures are not well reported.
- A failed job scheduled for a retry is reported as sussessful.
- The retry queue is reset when the job finish
- The failed queue is empty

# Conclusions

I guess the Failed queue is meant for jobs that still fails after all retries, that would explain why it's empty.

Failing jobs should not be reported as Succeeded, they haven't!

Retry queue should not be reset or cleared when the job still fails, as this is the only place left where we can look for errors.


# Full test code

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            GlobalConfiguration.Configuration.UseSqlServerStorage("Hangfire");

            app.UseHangfireDashboard();
            app.UseHangfireServer();

            const string jobId = "Exceptional";

            RecurringJob.AddOrUpdate(jobId, () => Fail(), Cron.Minutely);
            RecurringJob.Trigger(jobId);
        }

        static int isProcessing;

        public static void Fail()
        {
            if (Interlocked.CompareExchange(ref isProcessing, 1, 0) != 0) return;

            try
            {
                var terminateAsyncByCallingResult = LongRunningTask().Result;
                if (!terminateAsyncByCallingResult)
                {
                    throw new InvalidOperationException("Expected to fail before this");
                }
            }
            finally
            {
                Interlocked.Exchange(ref isProcessing, 0);
            }
        }

        static async Task<bool> LongRunningTask()
        {
            var longerThanTheSheduledPeriod = TimeSpan.FromSeconds(65);
            await Task.Delay(longerThanTheSheduledPeriod);
            Throw();
            return false;
        }

        static void Throw()
        {
            throw new InvalidOperationException("Should fail here");
        }
    }
