### ISSUE TITLE
Recurring Jobs: job runs locally when manual triggered despite enqueuing a job

### ISSUE THREAD

**Issue by erictrade** [HangfireIO/Hangfire#444]
Hello. Before pointing the issue, I'd like to describe our scenario:

![hangfire](https://cloud.githubusercontent.com/assets/9271579/9966884/a5e719f4-5e15-11e5-94da-07c487988661.png)

Our problems is that, when trying to trigger a recurring job, despite of enqueuing a job to be processed, the Hangfire Dashboard and the RecurringJob.Trigger method is trying to run the job calling the method. I see 2 problems here:

1. When using a dedicated server to run the jobs as we are, manual triggering uses our Web Machine resources, despite that delegating to the right dedicated machine to process the job. And, if this job is long, it's delaying the response time and may also come to time outs.
2. In our case, having the Dashboard separated, when trying to trigger we are receiving an error, because we don't have (and are not willing to have) all the dependencies of our project on the Dashboard. We just want to deploy the main DLLs so the deployed dashboard can know our jobs to list and also requeue/trigger the jobs, and not processing using that machine.

So, thinking of this scenario, and how hangfire is currently handling the trigger of recurring jobs, what do you think? Does it makes sense?

Thanks in advance!

**Comment by odinserj** [comment]
This is a bug, the `RecurringJobManager` class ignores the given queue. I've scheduled it to 1.4.7, would you like to fix the code (in the `master` branch)?

**Comment by erictrade** [comment]
Hi, I tried to see the code, but I didn't understand why it's not using the queue, since the same call - BackgroundJobClient .Create(Job job, IState state) - is used when a job is re-enqueued.
Re-queing a job works, but triggering a recurring job doesn't. Any more suggestions about where to look? I'm not so familiar with hangfire code. I just read something here and there...

**Comment by odinserj** [comment]
@erictrade, the fix is available in the [1.5.0-beta4](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.0-beta4) release.
