### ISSUE TITLE
HangFire.Azure.ServiceBusQueue not working

### ISSUE THREAD

**Issue by dersia** [HangfireIO/Hangfire#445]
Hi,

I tried to add HangFire.Azure.ServiceBusQueue to my Project since I'm trying to get it into azure.
It Looks like there is a issue when I try to set the configuration as shown in the readme.md.

Compiler says: 'HangFire.Azure.ServiceBusQueue.ServiceBusQueueSqlServerStorageExtensions.UseServiceBusQueues().ServiceBusQueueSqlServerStorageExtensions.UseServiceBusQueues()' is not supported by the language

I'm on Hangfire.SqlServer 1.4.6.0 and Microsoft.ServiceBus 3.0.0.0

Kind Regards,

Sia

**Comment by dersia** [comment]
Ok, Looks like this is already fixed in the sources, but the NuGet-Package is not updated on NuGet.org

**Comment by barclayadam** [comment]
Hi Sia,

Apologies, this is my fault for not getting NuGet updated! As you have found the project has been updated and should work with your version of Hangfire. I've been using in production for a number of months now.

I'll close this now. Feel free to open an issue if you find something specific that does not work.

**Comment by barclayadam** [comment]
Version 1.0.0 has now been released to NuGet:

https://www.nuget.org/packages/HangFire.Azure.ServiceBusQueue/

**Comment by odinserj** [comment]
:tada: Awesome, @barclayadam! Would you like to create a blog post regarding the 1.0.0 release for this project? I've already twitted about the release, but a blog post is much better... Official site is based on Jekyll, making it very easy to write and author new posts. Here is an example of the [latest post](https://github.com/HangfireIO/HangfireIO.github.io/blob/master/_posts/2015-08-31-hangfire-1.5.0-beta3.md). GitHub avatars are placed automatically :-)
