### ISSUE TITLE
Hangfire.Core: When a job fails, it's being re-scheduled endless [beta-3]

### ISSUE THREAD

**Issue by strongwinderic** [HangfireIO/Hangfire#447]
Nothing much to say about it. It's just this: after updating to beta-3, when a job fails, it's being re-scheduled again, and again when it fails again. Have I said again? Let me say again then that it's being re-scheduled again.

Jokes apart, it's not respecting the AutomaticRetry Attribute attempts limit, so, each job that fails is trying to be processed forever. On beta-2 we don't have this behaviour.

**Comment by odinserj** [comment]
@erictrade, can't reproduce this behavior, only one attempt made as expected. The following method used to test this:

```csharp
[AutomaticRetry(Attempts = 1)]
public void Error()
{
    throw new InvalidOperationException();
}
```

![image](https://cloud.githubusercontent.com/assets/1078718/10138412/01d44bda-6607-11e5-8a91-63764c5266d3.png)

Can you provide more details?

**Comment by nkwinder** [comment]
Same thing happens to me also.  Recurring job Minutely ... with [AutomaticRetry(Attempts = 1)].
The jobs fails and keeps retrying indefinitely.

**Comment by erictrade** [comment]
@nkwinder: Now that you mentioned it, it makes sense. Was thinking about reproducing this in a small project, but coudn't think about what exactly scenario it was. Now that you mentioned, yes, it's only ocurring in recurring jobs.

**Comment by RydbirkJr** [comment]
I experience the same issue. I've got this job failing, and at some point it respected the retry attribute but then it started going past it. I can't seem to find any pattern where this makes any sense.

My setup:
SqlServer
Recurring job
Default retry attribute = 3

![hangfire error](https://cloud.githubusercontent.com/assets/6619563/10605585/e85146fe-772c-11e5-810e-5057f4ce0bbf.png)

**Comment by odinserj** [comment]
@RydbirkJr, please [turn on](http://docs.hangfire.io/en/latest/configuration/configuring-logging.html) the logging and paste the log messages here.

**Comment by RydbirkJr** [comment]
Hangfire logs multiple of the following lines:
Timestamp | Level | Host | Type | Source | Logger | Message | Stacktrace
---|---|---|---|---|---|---|---
2015/10/20 14:31:03.617 | Error | <...> | NLog.NLogRuntimeException | <no type>	 | Hangfire.Server.Worker | Error occurred during execution of 'Worker #1643d594' process. Execution will be retried (attempt 7 of 2147483647) in 00:00:38 seconds. | <no type>.CallSite.Target => UpdateDelegates.UpdateAndExecuteVoid3 => <no type>.CallSite.Target

**Comment by odinserj** [comment]
@RydbirkJr, good, we should now see all the inner exceptions to learn the details. Please modify your config with `${exception:Format="tostring"}` to see inner exceptions.

**Comment by RydbirkJr** [comment]
Hmm. I changed that part, and now Hangfire doesn't log through NLog even though I've generated 3 crashes after the change to NLog. I even updated NLog too see if that was the issue. Got any ideas? No other issues for NLog for the rest of the application.

**Comment by RydbirkJr** [comment]
But I can see that it still logs on startup / shutdown.

**Comment by TheBeardedLlama** [comment]
I can confirm that this was an issue for us as well when we were on version 1.4.5

After upgrading to 1.5.3 and doing some cleanup of the db tables, I have not seen this occur again.

However, it was definitely an issue and filled up both our db and our hard drives *very* quickly!

**Comment by AGRocks** [comment]
Same here. Occurring using _SQLite_ extension which means that issue is most probably to do with _Hangfire.Core_ project.
