### ISSUE TITLE
Retries icon stays after job expired

### ISSUE THREAD

**Issue by ppumkin** [HangfireIO/Hangfire#458]
HANGFIRE: 1.5.0

I deleted a job while it was in retry. 
It sayed in retry but as deleted, now it has expired, the job is still hanging around the dashboard. 

![image](https://cloud.githubusercontent.com/assets/1249683/10277040/23ce6538-6b4b-11e5-90a4-a9bc074ff6b7.png)

But there is no job for that.

![image](https://cloud.githubusercontent.com/assets/1249683/10277045/326b0240-6b4b-11e5-83df-c8723f4b40df.png)

I suspect its just a row that didnt get deleted somewhere?

**Comment by ppumkin** [comment]
In case you wondering, I did try and delete that job as its expired. But the button just freezing on "Deleting" and nothing happens.

**Comment by odinserj** [comment]
Hm, can't reproduce. I've enqueued a background job that throws an exception, waited for an automatic retry attempt and then clicked the `Delete` button on retries page. Everything is working as expected. I've looked at the code, but didn't realize any race conditions :-(

Can you provide more detailed steps that lead to this behavior?

**Comment by lucashby** [comment]
I am seeing the same issue:

![image](https://cloud.githubusercontent.com/assets/938632/11124484/443e818a-8933-11e5-9c3f-4cfe40c7f425.png)

**Comment by fabiohvp** [comment]
I'm also having the same problem, i'm using hangfire Hangfire v1.5.3

![bug hangfire](https://cloud.githubusercontent.com/assets/8272995/13751776/82c273a4-e9ea-11e5-8a23-f44b6cceac3d.jpg)

**Comment by jonleigh** [comment]
Experiencing the same issue with Hangfire 1.5.6.

The issue relates to entries in the Hangfire.[Key] table with Key = 'retries' and Value to the job to retry (although the job doesn't exist anymore).

Delete these entries (being careful not to delete actual retries) and everything will be back to normal

**Comment by timmkrause** [comment]
I am also not able to delete expired jobs in the "Retries" section.

**Comment by jooptroop2** [comment]
In response to jonleigh's message above: just a correction, it's the [Hangfire].[Set] table where [Key] = 'retries'

**Comment by rosdi** [comment]
I am using Hangfire 1.6.19, not sure if it has been fixed... if this is bothering you enough... just delete it manually...

`DELETE  FROM [HangFire].[Set] where [key] = 'retries'`

**Comment by SeppiHDamgaard** [comment]
Having the same issue on Hangfire 1.18.14 with Hangfire.Mongo 1.10.8.

In our case, these "ghost retries" appeared after changing the name or parameters of a method that was already enqueued. This led to an error (something like "No such method"), and as a result, 91 jobs got stuck in a permanent retry state. These jobs were not visible in any Hangfire tables in MongoDB, and they never retried—they just remained in limbo.

Or so we thought.

After some investigation, we found that these ghost jobs could be located using the following MongoDB query:

```
{
    "Key": { "$regex": "retries", "$options": "i" }
}
```

This made it possible for us to finally delete them after a year of being annoyed by them, hope it helps some one else some day :)

![Image](https://github.com/user-attachments/assets/3a5da536-8253-4792-875c-4198165e9bf9)

![Image](https://github.com/user-attachments/assets/d0121158-ce50-4fa0-a6af-4286ef09afea)

**Comment by odinserj** [comment]
It is possible that background job will be moved to the `Failed` state when storage is inaccessible for some time, and `Scheduled` &rarr; `Failed` state transition will not be processed by the `AutomaticRetry` filter, because filters aren't applied during such transition. I have just included possible transition from the `Failed` state to clean up the `retries` set, so no new entries should appear in the list, please let me know if you still see the new entries. As for the list cleanup, please clean the entries manually (it's safe to remove the whole list).
