### ISSUE TITLE
Infinite loop when trying to delete job that doesn't exist

### ISSUE THREAD

**Issue by DarthBender** [HangfireIO/Hangfire#467]
Hangfire version 1.5.2
I'm trying to delete job, that does not exist and my program goes into infinite loop. 
Is it possible, that the latest changes in BackgroundJobStateChanger.GetJobData method have caused this problem?

**Comment by sjwoodard** [comment]
I'm seeing something similar. Anytime I try to requeue or delete any job (even if it exists), I get a deadlock. E.g.

`var deleted = new BackgroundJobClient(_hangfireStorage).Delete(id);`

I am using Hangfire core ver. 1.5.2 with Hangfire.Pro.Redis 1.4.1

**Comment by sjwoodard** [comment]
As a temporary workaround I have found this to work:

    var state = _hangfireStorage.GetConnection().GetStateData(id);
    if (state != null)
        var deleted = new BackgroundJobClient(_hangfireStorage).Delete(id);

**Comment by DarthBender** [comment]
And this is my workaround:

```
var jobData = JobStorage.Current.GetConnection().GetJobData(jobId);
if (jobData != null)
{
   jobClient.Delete(jobId);
}
```
It's pretty similar to @sjwoodard workaround
