### ISSUE TITLE
Job still processing but Dashboard says succeeded

### ISSUE THREAD

**Issue by Huntk23** [HangfireIO/Hangfire#472]
So I have a job that takes about ~20 minutes to run and for some reason the Hangfire dashboard is saying the job succeeded but I can see it's still working. Did I miss something important in my setup that indicates the job should be in the processing status?

**Comment by odinserj** [comment]
How do you know it is still running? Does it use async methods?

**Comment by Huntk23** [comment]
It's a job that is updating Sales Force objects through their API. I can log in and see it's still updating records through their query language. Plus I am using SignalR within the method and it's still feeding clients information even though it says succeeded.

Yes the BackgroundJob.Enqueue calls an async method.

**Comment by IanYates** [comment]
Hangfire won't wait for your async code to finish.

You can wrap it in a Task.Run() call and then call .Wait() on the resulting task.

The AsyncContext in https://github.com/StephenCleary/AsyncEx can also help with this.

**Comment by Huntk23** [comment]
Perfect, thanks for the information!
