### ISSUE TITLE
Job processing trigger late than scheduled time

### ISSUE THREAD

**Issue by sarangitm** [HangfireIO/Hangfire#473]
Hello,
I am using hangfire in MVC5 application, storing job in SQL Server 2012 & using Hangfire version 1.5.2. I want to trigger job after 2 seconds of schedule time. For this I tried

```BackgroundJob.Schedule(()=> ScheduleManager.CircularImageJob(newPath), TimeSpan.FromSeconds(2));```

also,
```BackgroundJob.Schedule(()=> ScheduleManager.CircularImageJob(newPath), DateTime.UtcNow.AddSeconds(2));```

But the job triggers 8-10 seconds late after scheduling in development Env. In production server this become more worst. It takes more than 15-20 seconds to execute.

Any help on this will be appreciated.
Thanks in Advance.

**Comment by odinserj** [comment]
Please see the [Configuring the Polling Interval](http://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuring-the-polling-interval) section and consider to lower the polling interval or use Hangfire.SqlServer.Msmq extension.
