### ISSUE TITLE
Redis password is logged on startup and exposed in dashboard

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#474]
Posted on forum: [Redis Connection string is logged with the password](https://discuss.hangfire.io/t/redis-connection-string-is-logged-with-the-password/1507)

> When starting up, the server logs the following text:
> 11-04-2015 14:06:30 INFO Using job storage: 'redis://myPassword@myRedisServer/0'.
>
> The password that is used to connect to the redis server should not be logged. Recommend masking the password, otherwise, allow disabling logging the connection string.
> 
> Exposing the password in a log file is oftentimes considered a security risk.

Password is also exposed in dashboard, as it uses the `RedisStorage.ToString` method also. The password should be stripped in this method.

**Comment by odinserj** [comment]
Fixed in [Hangfire.Pro.Redis 1.4.2](https://github.com/HangfireIO/Hangfire.Pro/releases/tag/v1.4.2). **It is highly recommended to update to this release, and change Redis password.**

**Comment by erikvojtko** [comment]
Hello, this issue seems to be present in the current version of Hangfire. Here on the line 116 to be specific. https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/BackgroundJobServer.cs

**Comment by erikvojtko** [comment]
![HangfireLog](https://user-images.githubusercontent.com/47644973/190661508-87f7db3a-dc1a-4e66-ad04-3bf65d9272b5.png)

Is this enough?

**Comment by odinserj** [comment]
Thanks a lot! Could you also tell me what package you are using for the Redis storage implementation? And what version?

**Comment by odinserj** [comment]
I'm afraid this issue should be reported to Hangfire.Redis.StackExchange's repository (sorry, I'm from mobile) as it's a community-based one. You are correct, RedisStorage.ToString shouldn't expose the password, and it's responsibility of a storage to properly generate it. 

For example Hangfire.Pro.Redis doesn't simply return the connection string, it constructs it based on host name and port instead, without any chance to include a password.

**Comment by erikvojtko** [comment]
I see, thanks a lot for your quick help, I wrote a comment to a similar issue that's been mentioned there.

**Comment by odinserj** [comment]
Have a nice weekend!
