### ISSUE TITLE
NCrontab dependency not listed

### ISSUE THREAD

**Issue by barclayadam** [HangfireIO/Hangfire#475]
ncrontab is not listed as a dependency in nuget so is not pulled in automatically.

I'm not entirely sure what my problem is though, as this has only surfaced since upgrading to v1.5.2 but it looks like ncrontab has been in use for a long time before this release (was on 1.4 before).

I can create a pull request, but wanted to get feedback on the issue before.

**Comment by odinserj** [comment]
What do you mean? It is listed [here](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/packages.config#L7). It is ILMerged into `Hangfire.Core.dll` assembly, so there is no need to add it as a dependency.

**Comment by barclayadam** [comment]
Ah that is what I am missing then! 

I have a custom version of Hangfire locally that I did not put through the actual build system but instead just copied dlls from, therefore dependencies would not have been merged in so it looks like they are missing.

I thought it had to be something I had done (or not done)! Cheers
