### ISSUE TITLE
Should the Dashboard have counters?

### ISSUE THREAD

**Issue by stajs** [HangfireIO/Hangfire#482]
I am using Hangfire 1.5.2 in a ASP.NET 5/dnx project:

![image](https://cloud.githubusercontent.com/assets/2253814/11108155/6df79384-8949-11e5-82a6-b8c036ef96cd.png)

My dashboard...:

![image](https://cloud.githubusercontent.com/assets/2253814/11108177/91696e00-8949-11e5-95e3-4c8e9cc0a96c.png)

... is missing these counters (as indicated in the [carousel slideshow](http://hangfire.io/img/ui/dashboard.png) on the [homepage](http://hangfire.io/)):

![image](https://cloud.githubusercontent.com/assets/2253814/11108185/9d21fadc-8949-11e5-94c3-618b617c9b4a.png)

Have the counters been removed (i.e. the image is out of date) or should they be there (i.e. another potential problem with dnx)?

**Comment by odinserj** [comment]
Undocumented features :-) That metrics are for Redis, however there are some for SQL Server:

```csharp
GlobalConfiguration.Configuration
                .UseSqlServerStorage(@"Server=.\sqlexpress;Database=Hangfire.Sample;Trusted_Connection=True;")
    .UseMsmqQueues(@".\Private$\hangfire{0}", "default", "critical")
    .UseDashboardMetric(SqlServerStorage.ActiveConnections)
    .UseDashboardMetric(SqlServerStorage.TotalConnections)
    .UseDashboardMetric(DashboardMetrics.FailedCount);
```

**Comment by stajs** [comment]
I _did_ notice the Redis text, but cool there is _something_ for SQL Server!
