### ISSUE TITLE
successful history  json log

### ISSUE THREAD

**Issue by maze0417** [HangfireIO/Hangfire#492]
hello , master , 
in 
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/JobHistoryRenderer.cs#L151
i have one question,
because i want  the json string will be more pretty watch , i have tried some approaches to modify the style. i find one approach as below , but i think this will be need to change source code
`builder.AppendFormat("<dt>Result:</dt><dd style='white-space: pre-line;'>{0}</dd>", System.Net.WebUtility.HtmlEncode(result));`

could i have any your suggestion ? 

thanks

**Comment by VictorTomaili** [comment]
There is an issue for camel case dictionary keys. Currently i look at this and try to resolve without changing json settings. 

I modify some dictionary initializers like this in Hangfire.Core

```c#
new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
```
and this is solve my issue.

**Comment by aidmsu** [comment]
Hi, @maze0417! 

Sorry for delayed response. 

You can change rendering of job's state without changing source code. You just need to register custom state renderer:

```csharp
JobHistoryRenderer.Register(SucceededState.StateName, SucceededRenderer);

...

public static NonEscapedString SucceededRenderer(HtmlHelper html, IDictionary<string, string> stateData)
{
    var builder = new StringBuilder();
    builder.Append("<dl class=\"dl-horizontal\">");

    var itemsAdded = false;

    if (stateData.ContainsKey("Latency"))
    {
        var latency = TimeSpan.FromMilliseconds(long.Parse(stateData["Latency"]));

        builder.Append($"<dt>Latency:</dt><dd>{html.ToHumanDuration(latency, false)}</dd>");

        itemsAdded = true;
    }

    if (stateData.ContainsKey("PerformanceDuration"))
    {
        var duration = TimeSpan.FromMilliseconds(long.Parse(stateData["PerformanceDuration"]));
        builder.Append($"<dt>Duration:</dt><dd>{html.ToHumanDuration(duration, false)}</dd>");

        itemsAdded = true;
    }

    if (stateData.ContainsKey("Result") && !String.IsNullOrWhiteSpace(stateData["Result"]))
    {
        var result = stateData["Result"];
        builder.AppendFormat("<dt>Result:</dt><dd style='white-space: pre-line;'>{0}</dd>", System.Net.WebUtility.HtmlEncode(result));

        itemsAdded = true;
    }

    builder.Append("</dl>");

    if (!itemsAdded) return null;

    return new NonEscapedString(builder.ToString());
}
```
