### ISSUE TITLE
Hangfire.SqlServer.RabbitMq viable?

### ISSUE THREAD

**Issue by jvdonk** [HangfireIO/Hangfire#498]
Trying to put RabbitMq to work with Hangfire like so:
````
var storage =
    new SqlServerStorage(_instanceSettings.HangfireStorage)
        .UseRabbitMq((conf) => {
            conf.Uri = new Uri("amqp://hangfire:hangfire@myhangfirehost:3000/hangfire");
        });

GlobalConfiguration.Configuration
    .UseStorage<SqlServerStorage>(storage);
````
The connection to RabbitMq is succesfully made as I can see a connection appearing in the RabbitMQ dashboard when the Hangfire server is started.

But is see no messages coming in and beeing ackknowledged etc. The jobs that I enqueue are run, succesfully but I see no latency differences when not using RabbitMQ(and plain SqlServer instead) so I'm afraid RabbitMq isn't acually used.

How can I verify this? Checking the Sql DB itself? What to look for?

Also, the Hangfire.SqlServer.RabbitMq code isn't explicitly closing the AMQP connection and therefore hangs my service when shutting down.

Verifiable using this setup:
````
using RabbitMQ.Client;
using System;

namespace RabbitMQConnection {

    class Program {

        static void Main(string[] args) {
          
            ConnectionFactory factory = new ConnectionFactory();
            factory.Uri = "amqp://hangfire:hangfire@myrabbitmqhost:3000/hangfire";

            IConnection conn = factory.CreateConnection();

            Console.WriteLine(conn.IsOpen); //True!

            conn.Close(); // When ommitting this, the process isn't exited after the Console.ReadKey below but just keeps hanging.....           

            Console.ReadKey();
        }
    }
}

````

**Comment by jvdonk** [comment]
I managed to set Serilog to work which is confirming that RabbitMq isn't used but sqlserver polling instead:
![image](https://cloud.githubusercontent.com/assets/1164988/12320007/4c5167ee-baa6-11e5-9afa-699fa853bc81.png)

RabbitMQ connections tab when the Hangfire server is running:
![image](https://cloud.githubusercontent.com/assets/1164988/12320061/b3578b30-baa6-11e5-8f7b-fb76fbebbbd1.png)

RabbitMQ channels tab:
![image](https://cloud.githubusercontent.com/assets/1164988/12320077/c63510f6-baa6-11e5-8826-969b2d2019e5.png)

I haven't setup any exchanges/queues for hangfire, am I supposed to? Also, I don't specify any queues when using the .UseRabbitMq extension, assuming defaults will be used.

**Comment by odinserj** [comment]
@dennyferra, I'm planning to move `Hangfire.SqlServer.RabbitMQ` project to the separate GitHub repository, because I don't know anything about RabbitMQ and can't maintain it. Would you like to have it in your account? Or should I search for a new maintainer for the project? 

Currently it isn't clear who is the maintainer for RabbitMQ support :disappointed:

**Comment by dennyferra** [comment]
@odinserj Sure moving it over to my account makes sense. That should also get me to be more involved in maintaining it, and getting the updates and fixes I've been intending to do as well.

**Comment by odinserj** [comment]
Okay, so I'm removing it from the `dev` branch.

**Comment by htapal** [comment]
@dennyferra are you still maintaining Hangfire.SqlServer.RabbitMQ project?  Is the issue @jvdonk described been resolved?

**Comment by odinserj** [comment]
@dennyferra, as per our discussion, I've created a dedicated repository for Hangfire.SqlServer.RabbitMq – https://github.com/HangfireIO/Hangfire.SqlServer.RabbitMq and added you as a collaborator with admin rights.
