### ISSUE TITLE
Enqueue<T>(...): Passing T instance as argument throws InvalidOperationException

### ISSUE THREAD

**Issue by pchasco** [HangfireIO/Hangfire#499]
I am attempting to enqueue a background job using the BackgroundJob.Enqueue<T>(...) method. My goal is to remove the Hangfire dependency from various service layer components that should not need to have any knowledge of how the background job is implemented. Overall this has been pretty painless except for one sticky issue: IJobCancellationToken.

I want to support graceful shutdown of Hangfire by handing off the job cancellation token to our background processes. Again, this is easy with Hangfire but it does create a dependency on the Hangfire core components.

I thought using a simple class as an anti-corruption layer would make it easy to eliminate the dependency, but I'm finding that Hangfire doesn't support what I'm trying to do:

```c#
    public interface IBatch
    {
        void Execute(System.Threading.CancellationToken cancellationToken);
    }

    internal class JobHandler : Interfaces.IJobHandler
    {
        public void EnqueueBatch<T>() where T : IBatch
        {
            var job = new BatchJob<T>();
            job.Execute();
        }
    }

    internal class BatchJob<T> where T : IBatch
    {
        public void Execute()
        {
            // Exception here
            BackgroundJob.Enqueue<T>(m => Execute(m, JobCancellationToken.Null));
        }

        public void Execute(T instance, IJobCancellationToken token)
        {
            instance.Execute(token.ShutdownToken);
        }
    }
```

My idea here was that using this little indirection would enable my IBatch implementations to accept the .NET native CancellationToken and also allow Hangfire to activate <T> using the IoC container it has already been configured with. This removes the dependency on Hangfire for any IBatch implementations. 

It looks like however Hangfire is walking the expression parse tree doesn't like the fact that I'm passing the argument to the lambda as an argument to Execute. I receive the exception:

`
System.InvalidOperationException occurred
  _HResult=-2146233079
  _message=variable 'm' of type 'Business.IContractBatch' referenced from scope '', but it is not defined
  HResult=-2146233079
  IsTransient=false
  Message=variable 'm' of type 'Business.IContractBatch' referenced from scope '', but it is not defined
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
  InnerException: 
`

**Comment by odinserj** [comment]
Starting from 1.5.0, you can use regular `CancellationToken` type for graceful shutdown – http://hangfire.io/blog/2015/08/31/hangfire-1.5.0-beta3.html#cancellation-tokens

**Comment by pchasco** [comment]
Thank you!
