### ISSUE TITLE
Hangfire 1.5.3 restarts always long jobs after 30 minutes

### ISSUE THREAD

**Issue by lukaskolafa** [HangfireIO/Hangfire#514]
I am running Hangfire 1.5.3 with some long jobs running in background. I created some very simple dummy jobs with just one 'for' loop doing Thread.Sleep(1000) to make sure my code does not break hangfire. The job implements Cancellation as described in hangfire documentation. 

BUG: The job gets cancelled after 30 Minutes and is started again. 

InvisibleTimeout option is now obsolete and its value is ignored. No matter what value I set, job is always interrupted after 30 Minutes.

The server runs in IIS.

It seems that this bug was introduced with the new 1.5.x version.

**Comment by lukaskolafa** [comment]
I think the issue is somewhere in the Enqueue Dequeue Methods. When a job is started, entry is created in the JobsQueue table with empty FetchedAt time. When this value is null, the jobs gets allways restarted later. 

this sql re-fetches the jobs:

delete top (1) from [{0}].JobQueue with (readpast, updlock, rowlock)
output DELETED.Id, DELETED.JobId, DELETED.Queue
where (FetchedAt is null or FetchedAt < DATEADD(second, @timeout, GETUTCDATE()))
and Queue in @queues

it seems that this query should get the job immediately from the queue, but due to isolation level the job is hidden for this query and it does not get restarted immediately but after 30 minutes first. 

The fix could be to enqueue jobs with FetchedAt value GETUTCDATE() instead of NULL value, because the job is started at this moment already.. Not sure about this, hard to evaluate this in foreign code exactly.

Please let me know if I can help somehow while fixing this.

**Comment by bivo** [comment]
:+1:
I've got absolutely the same issue :(

**Comment by diegosilvestri** [comment]
I've  also i same problem with a job that need to produce 500.000 pdf file and this proces requires more days.:((((

**Comment by lukaskolafa** [comment]
more days seems to be quite a lot :) not sure if iis would run so long for such a long time. In my expirience IIS is doing recycle after few days (even if you configure allways on mode). I would suggest anyway to split your job into smaller ones.

for this problem, downgrade to 1.4.7. hangfire seems to work fine. Running stable for me since couple days..

**Comment by diegosilvestri** [comment]
Thanks a lot for your answer 

Diego (mobile)

**Comment by arauber** [comment]
I am getting the same issue.

I have tried both versions 1.4.7 and 1.5.3, and the problem persists - after 30 minutes of execution, the job is restarted concurrently. Not good for a long running process.

At this point I can see no solution to the problem. Has anyone solved this?


![image](https://cloud.githubusercontent.com/assets/17633830/13518122/a9ab84a2-e21e-11e5-92fb-b93dd3a2d136.png)

**Comment by lukaskolafa** [comment]
I am pretty sure 1.4.7 is working correctly. The error must be on your side. Please make sure you really use in all projects the same dll version and make sure you remove all tables first before starting the project again.

**Comment by SwissDusty** [comment]
You need to configure the timeout properly for it to work in 1.4.7.
In 1.4.7, Hangfire simply marks the job as 'in processing' and sets the start date. There is a timeout after which Hangfire assumes a job has crashed and therefore reschedules the job. the default timeout is 30 or 60 minutes - I don't remember (check the docs).
I'd strongly discourage using 1.5 with SQL storage for long running jobs, as 1.5 opens a DB transaction which will stay open for the whole job duration. This will cause problems with transaction logs and the like (especially, if you don't have a dedicated db for Hangfire).

**Comment by bijeebuss** [comment]
having the same issue on 1.5.3 but its not always 30 minutes
![capture](https://cloud.githubusercontent.com/assets/11799228/15914382/57706500-2d95-11e6-8623-6399f01d0deb.PNG)

**Comment by diegosilvestri** [comment]
Hi I have solved with 1.5.5
Diego Silvestri (mobile)
Il 09 Giu 2016 01:23, Michael Welnick <notifications@github.com> ha scritto:having the same issue on 1.5.3 but its not always 30 minutes

**Comment by odinserj** [comment]
@diegosilvestri, do you mean [1.5.6](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.6)? There was a fix for **SQL Azure** – connection governor kills connections after 30 minutes of inactivity. Now Hangfire issues some sort of a "ping" query to keep the connection active.

I'm closing this issue, if you have this problem with standalone SQL Server (not SQL Azure), please feel to reopen it.

**Comment by AJ1987** [comment]
@odinserj  Hi deal odinserj,  if I want to manually config the value of InvisibleTimeout and retry times when using standalone SQL Server. How could I realize it? thank you

**Comment by alensindicic** [comment]
I'm experiencing the same issue, after 30 minutes the job is restarted. I'm using NpgsqlConnection (Hangfire.PostgreSql 1.20.9) and Hangfire 1.8.14.
