### ISSUE TITLE
Bad deserialize object[string[]]

### ISSUE THREAD

**Issue by staufour** [HangfireIO/Hangfire#516]
If we have a method with objec[] args and passing to it string[] a bad cast error is raised (Newtonsoft.Json.Linq.JArray to System.String[])

``` c#
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        GlobalConfiguration.Configuration.UseSqlServerStorage("hangfire");

        app.UseHangfireDashboard();
        app.UseHangfireServer();

        BackgroundJob.Enqueue<JobActivator>(j => j.Execture(new object[] { new string[] { "Hello", "World" } }));
    }
}

public class JobActivator
{
    public string Execture(object[] args)
    {
        if (args != null && args.Length > 0)
        {
            return Combine((string[])args[0]);
        }

        return "no params";
    }

    private string Combine(string[] args)
    {
        return string.Join(" ", args);
    }
}
```

**Comment by aidmsu** [comment]
Hi, @staufour! Sorry for the delayed response.

Could you tell me what storage do you use?

If you use **MS Sql Server** or **Redis** arguments are serialized without saving type info by default.
So argument 
```
new object[] { new string[] { "Hello", "World" } }
``` 
serializes into 
```
[[\"Hello\",\"World\"]]
``` 
When job are deserialized `Hangfire` define by method parameter type that argument has `object[]` type. But there is no way to define type of each element of that array.

It's highly recommended using as simple as possible argument types. But if you can't avoid this case you should `TypeNameHandling.All` settings for argument serialization:
```
JobHelper.SetSerializerSettings(new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.All
});
```
In this case argument will serialize with saving type info: 
```
{"$type":"System.String[], mscorlib","$values":["{\"$type\":\"System.Object[], mscorlib\",\"$values\":[{\"$type\":\"System.String[], mscorlib\",\"$values\":[\"Hello\",\"World\"]}]}"]}
``` 
And your code will work correctly.
