### ISSUE TITLE
Provide a JobActivator implementation that accepts a delegate

### ISSUE THREAD

**Issue by tuespetre** [HangfireIO/Hangfire#525]
If there were a bundled implementation that accepted a simple `Func<Type,object>` delegate, there would be virtually no need to implement activators for the various containers floating around out there.

**Comment by burningice2866** [comment]
IMO it would be best to look at utilizing [Microsoft.Extensions.DependencyInject](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/) which aim is to be a single point of contact for all DI containers in the .Net space.

**Comment by tuespetre** [comment]
That's a good train of thought; perhaps then the suggestion should be:

- Let the default constructor for `JobActivator` wire up a default service provider (`TypeActivator` or whatever)
- Let the default `JobActivator` have an additional constructor which takes an `IServiceProvider` instance so consumers can pass in their own
