### ISSUE TITLE
Refactor Owin parts into Hangfire.Core.Owin

### ISSUE THREAD

**Issue by burningice2866** [HangfireIO/Hangfire#527]
Is there any support to refactor the Owin-components out of Hangfire.Core an into Hangfire.Core.Owin. This would follow the pattern of several other packages like WebApi and SignalR and remove the dependency on Owin for ie. plain asp.net applications which doesn't use it.

I would like to make a pull request containing this refactoring, even if it would only make into the next minor or major version.

**Comment by odinserj** [comment]
Closing, duplicates #621 that contains much more details
