### ISSUE TITLE
Consider allowing C# 6 syntax

### ISSUE THREAD

**Issue by atifaziz** [HangfireIO/Hangfire#531]
Is there a reason `Hangfire.Core` is [capped to C# 5 syntax](https://github.com/HangfireIO/Hangfire/blob/a5761072f18ff4caa80910cda4652970cf52e693/src/Hangfire.Core/Hangfire.Core.csproj#L30)?

**Comment by odinserj** [comment]
There was a reason to give users who are still using &le; Visual Studio 2013 to compile the solution. But since I've planned to switch it to C# 6.0 the `dev` branch anyway, and a lot of time passed since 2015 RTM, so I removed the restriction in the last (I hope) release before 1.6.0.
