### ISSUE TITLE
Update StackTraceFormatter to 1.1

### ISSUE THREAD

**Issue by atifaziz** [HangfireIO/Hangfire#532]
[StackTraceFormatter to 1.1](https://www.nuget.org/packages/StackTraceFormatter.Source/1.1.0), and more importantly, it's dependency [StackTraceParser 1.2](https://www.nuget.org/packages/StackTraceParser.Source/1.2.0), contains a critical bug fix. See the following issues for background and more:

* atifaziz/StackTraceFormatter#1.
* atifaziz/StackTraceParser#4.
* atifaziz/StackTraceFormatter#2.

However, since StackTraceFormatter 1.1 is embedded into Hangfire & uses C# 6, the upgrade isn't possible without addressing #531 first.

**Comment by odinserj** [comment]
I've updated the package, thanks for highlighting this!
