### ISSUE TITLE
Hangfire dashboard displays blank on azure - even when using Always On 

### ISSUE THREAD

**Issue by nigel-dewar** [HangfireIO/Hangfire#534]
Hi ,

Hangfire works perfect on local iis, and I have deployed hangfire with my .net 4.5 app to azure no problem, as db tables are populated etc. Problem is, even when app is using AlwaysOn in Azure, the hangfire dashboard displays completely blank, no errors, but nothing shows at all. 

strange.

**Comment by barclayadam** [comment]
I had this issue, took a little bit of tracking down but for anyone who encounters this it's because (or was in my case at least) of the default authorization filter which disables remote access.

To enable access use:

````
app.UseHangfireDashboard("hangfire", new DashboardOptions
            {
                AuthorizationFilters = Enumerable.Empty<IAuthorizationFilter>()
            });
````

Be warned this does open up the dashboard to anybody so it's worth considering what authorization filters to use.

Perhaps the default filter should be changed to output something to the log or request body in this instance as a clue as to what is going on?

**Comment by nigel-dewar** [comment]
Thank you very much for this info!

I had given up on hang fire and moved to quartz but now I can give hang fire another shot

Cheers

Nigel


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Adam Barclay <notifications@github.com> </div><div>Date:30/03/2016  05:55  (GMT+12:00) </div><div>To: HangfireIO/Hangfire <Hangfire@noreply.github.com> </div><div>Cc: nigel-dewar <nigeldewar@live.com> </div><div>Subject: Re: [HangfireIO/Hangfire] Hangfire dashboard displays blank on azure - even when using Always On  (#534) </div><div>
</div>
I had this issue, took a little bit of tracking down but for anyone who encounters this it's because (or was in my case at least) of the default authorization filter which disables remote access.

To enable access use:

````
app.UseHangfireDashboard("hangfire", new DashboardOptions
            {
                AuthorizationFilters = Enumerable.Empty<IAuthorizationFilter>()
            });
````

Be warned this does open up the dashboard to anybody so it's worth considering what authorization filters to use.

Perhaps the default filter should be changed to output something to the log or request body in this instance as a clue as to what is going on?

---

**Comment by gmcit** [comment]
```
 app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                Authorization = Enumerable.Repeat(new HangfireAuthorizationFilter(), 1)
            });
```

**Comment by iamvips** [comment]
> ```
>  app.UseHangfireDashboard("/hangfire", new DashboardOptions
>             {
>                 Authorization = Enumerable.Repeat(new HangfireAuthorizationFilter(), 1)
>             });
> ```
@louiedgomez This was really helpful. Thank you very much..!
