### ISSUE TITLE
Unable to 'find' a job?

### ISSUE THREAD

**Issue by buddybubble** [HangfireIO/Hangfire#543]
I want to be able to specify what happens, if a job was already scheduled. In our environment, it may happen that multiple requests to schedule a single job occur. I want to be able to only schedule the job for the first requests, all subsequent requests should not change the already scheduled job.

For this I either need a way to tell hangfire not to overwrite the job if it already exists, but only create it if its new. Or I need to be able to retrieve all jobs with a certain id and decide what to do with them myself. I am using hangfire.core and hangfire.mongo

**Comment by odinserj** [comment]
There is no way to do this out-of-the-box, however we can create a client filter that implement this feature. Here is the skeleton, please try this and ask any questions.

```csharp
public class SkipIfExistsAttribute : JobFilterAttribute, IClientFilter
{
  public void OnCreating(CreatingContext context) 
  { 
    var type = context.Job.Type.FullName;
    var method = context.Job.Method.MethodName;
    var arguments = context.Job.Args.Select(x => x.ToString()).ToArray();

    if (NeedToSkip(type, method, arguments))
    {
      context.Canceled = true;
    }
  }
}
```

You can use Redis-like operations using the `context.Connection` (there are set, hash and list types) to store and update information about last-runs. You can apply this filter to a method (by placing the `[SkipIfExists]` attribute), or globally via `GlobalConfiguration.Configuration.UseFilter(new SkipIfExistsAttribute())`.
