### ISSUE TITLE
Missed Recurring jobs are not triggered.

### ISSUE THREAD

**Issue by buddybubble** [HangfireIO/Hangfire#546]
I found a bug in the current implementation of Hangfire.Core (1.5.3), following steps can be used to reproduce:

1.  create a job to be executed once a year, starting in like 10 minutes
1. wait for the Backgroundjob server to schedule the next run (in our example this is in 10 minutes)
1. stop the server (no crash, just regular .dispose!)
1. wait 15 minutes (so the job should have been triggered by now if a server would have been available)
1. start the backgroundserver again

The skipped recurring job **will not be triggered**! This is contrary to what is described [here](https://github.com/HangfireIO/Hangfire/issues/233).

If I check the database (mongodb jobstore) I can see that the next execution time for this job was set to next year. 

Again, this goes contrary to what was said at the described location: 

> "Hangfire runs skipped recurring jobs automatically. [..] But only last missed run is being triggered."

It does, however work when I create a job to be executed every 5 minutes, stop the server **after** the first execution and restart 30 minutes later. In this case, hangfire will correctly detect missed executions and trigger the job once, like it was supposed to.

Please advise on how we can make this work, it is very important for us to not loose jobs! At the very least we have to be able to execute one instance of all skipped jobs at a server restart.

**Comment by odinserj** [comment]
Thank you for the detailed information, @buddybubble! I've just fixed this by adding a new field for recurring jobs (please read #552 for details). The changes are already available with the [1.5.5 release](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.5).
