### ISSUE TITLE
IBackGroundProcess support for DI / LOIC

### ISSUE THREAD

**Issue by ericmck2000** [HangfireIO/Hangfire#551]
Instead of....
            //Start background processing.
            Hangfire.Server.IBackgroundProcess[] BackgroundJobs = new Hangfire.Server.IBackgroundProcess[]
            {
                   kernel.Get<ONEGAS.LIB.Syslog.Server>()
            };
            app.UseHangfireServer(JobStorage.Current, hangfireOptions, BackgroundJobs);

It would be nice to have a method to allow IBackgroundProcesses to use DI.

**Comment by burningice2866** [comment]
+1

**Comment by burningice2866** [comment]
I'm really glad that IBackgroundProcess is being exposed as a extensibility point, but i also lack a more dynamic way resolve processes. At the moment i have multiple separate components in my solutions which all has one or more IBackgroundProcess's to run, but so far i have to query each component for its processes to build up a list which i can pass as an argument when spinning up the Hangfire Server.

Maybe looking at MEF as an easy way to discover available processes?

**Comment by burningice2866** [comment]
The AspNetCore implementation now got support for registering IBackgroundProcess as services and resolve them with support for DI

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.AspNetCore/HangfireApplicationBuilderExtensions.cs#L68

**Comment by burningice2866** [comment]
@odinserj I see the question as to put all ones IBackgroundProcess in a IoC container and let Hangfire discover them automatically. Is that possible now for not-Core version?
