### ISSUE TITLE
Unable to get RecurrentJobID associated with BackgroundJob

### ISSUE THREAD

**Issue by teodimache** [HangfireIO/Hangfire#554]
As it stands now the context of a BackgroundJob that is started from a RecurrentJob does not know which RecurrentJob it came from. I propose to add support for this kind of backtracking.

One way I need to use this feature is to disable job concurrency for individual RecurrentJobIDs similarly to what was proposed here https://discuss.hangfire.io/t/job-reentrancy-avoidance-proposal/607

**Comment by odinserj** [comment]
Closing this, as already merged into 1.6.0.
