### ISSUE TITLE
Hangfire Scheduled Jobs not fired up

### ISSUE THREAD

**Issue by dborregolopez** [HangfireIO/Hangfire#559]
Hello, 
I have a problem with the scheduled jobs that are not fired up and they stay on the 'Scheduled' queue until they are manually enqueued.
As a workaround I have seen that removing the rows from [hangfire].[set] table and restarting the server all the new scheduled jobs are working fine again, but I need to figure out what is going on and I'd like to know which is the proper fix.
(version Hangfire 1.5.3)

Thanks

**Comment by odinserj** [comment]
Hi, have you solved the problem? Looks like there is an exception, but we should learn what's happening here. Please, enable logging as written in [the docs](http://docs.hangfire.io/en/latest/configuration/configuring-logging.html) – they will reveal any exceptions appearing in the delayed job scheduler.
