### ISSUE TITLE
Custom IElectStateFilter not unit testable

### ISSUE THREAD

**Issue by cmaart** [HangfireIO/Hangfire#572]
Writing Unit Tests for a custom implementation of IElectStateFilter is not (easily) possible. 
The reason is simple: IElectStateFilter has 1 method:
`void OnStateElection(ElectStateContext context);`
`ElectStateContext` has only an internal constructor and can not be constructed in my test code.

**Comment by cmaart** [comment]
Same goes at least for `IServerFilter.OnPerforming` and `IServerFilter.OnPerformed`

**Comment by odinserj** [comment]
Ctor is now public, will be :ship: with 1.6.0.

**Comment by cmaart** [comment]
Thx :)
