### ISSUE TITLE
NuGet: cannot install Hangfire.Core correctly

### ISSUE THREAD

**Issue by osharper** [HangfireIO/Hangfire#576]
Here is output of a package manager console:

```
PM> install-package Hangfire.Core
Attempting to gather dependency information for package 'Hangfire.Core.1.5.6' with respect to project 'Foo', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Hangfire.Core.1.5.6' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Hangfire.Core.1.5.6'
Resolved actions to install package 'Hangfire.Core.1.5.6'
'Adding package 'Hangfire.1.5.6', which only has dependencies, to project 'Foo'.
Adding package 'Hangfire.1.5.6' to folder 'D:\Work\Foo\packages'
Added package 'Hangfire.1.5.6' to folder 'D:\Work\Foo\packages'
Added package 'Hangfire.1.5.6' to 'packages.config'
Successfully installed 'Hangfire.Core 1.5.6' to Foo
```

So, it claims to be installing `Hangfire.Core` but really it installs `Hangfire` all the way down somehow. In the end I'm getting only a `packages\Hangfire.1.5.6` folder with _Hangfire.1.5.6.nupkg_ and _readme.txt_ inside, so I have no .dll or anything else.

**Comment by odinserj** [comment]
Please try to [update](https://docs.nuget.org/consume/installing-nuget#updating-nuget-in-visual-studio) the NuGet Package Manager to the latest version. Hangfire.Core doesn't have a reference to the Hangfire package. Maybe your `packages.config` file has this reference.
