### ISSUE TITLE
File stream on background tasks

### ISSUE THREAD

**Issue by joaom182** [HangfireIO/Hangfire#579]
`Exception: Background job creation failed. -> The stream does not support writing`

I'm trying to process a file (.xls) in background, but was throwing exceptions, if i process on a main thread, everythings ok... 

Have any issue relationed with file streams on background tasks?

![image](https://cloud.githubusercontent.com/assets/3612098/15543303/bbdbc89e-226a-11e6-88b9-fd6f90bdcd18.png)

**Comment by IanYates** [comment]
It looks to me like you're trying to create a job where one of the parameters is a stream.  Is that correct?  Hangfire is trying to serialize the stream's contents which probably wouldn't work that well.

Could you make it a byte array instead?

If I'm misunderstanding could you please post some extra context?  Is the "xls" thing a red-herring?  Your "processing" of it doesn't involve loading up Excel and some COM objects does it?  (I could definitely see threading issues with that as the Office automation APIs are apartment threaded)

**Comment by odinserj** [comment]
@joaom182, store your streams outside of Hangfire – in a database, using the correct type (e.g. FILESTREAM), file system, etc., and pass only identifier (or file name) as an argument of your background job. Stream serialization will lead to inefficiency of background job processing.

**Comment by joaom182** [comment]
@IanYates @odinserj Thanks! Solved! :smile:
