### ISSUE TITLE
Is Core CLR going to be supported?

### ISSUE THREAD

**Issue by iraKudriashova-infotrack** [HangfireIO/Hangfire#580]
Is Core CLR going to be supported?

**Comment by senthilsivanath** [comment]
+1

**Comment by odinserj** [comment]
Not yet. I'd like to do this, but the project structure and tooling is changed between releases – `dnx`, `dotnet` command, `project.json` that will be switched back with `csproj` again in the [next release](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/). .NET Core support is currently a moving target, and I don't like to endlessly migrate all the Hangfire projects (there are a lot of them) to the new structure each time. And looks like internalization isn't supported yet.

I'm keeping an eye on this topic, but currently this is a time-wasting thing.

**Comment by odinserj** [comment]
Experimental support for .NET Core is available, see #604.
