### ISSUE TITLE
Unable to resolve dependency 'Hangfire.Core (= 1.5.6)'

### ISSUE THREAD

**Issue by Corstiaan84** [HangfireIO/Hangfire#582]
When trying to install HangFire.Postgresql from NuGet from within Xamarin Studio / MonoDevelop, I get the following error:

`Unable to resolve dependency 'Hangfire.Core (= 1.5.6)'.`

I cant install the Hangfire.Core (1.5.6) package by itself as well. Any ideas? :slight_smile:

**Comment by odinserj** [comment]
Please forward this issue to the `Hangfire.Postgresql` repository. I can't do anything here ¯\_(ツ)_/¯

**Comment by Corstiaan84** [comment]
Obviously. Thank you :-)
