### ISSUE TITLE
Incorrect reference to dapper in assembly Hangfire.SqlServer

### ISSUE THREAD

**Issue by alex-t0** [HangfireIO/Hangfire#583]
Markup from Hangfire.SqlServer.csproj:

`<Reference Include="Dapper, Version=1.40.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Dapper.1.42\lib\net45\Dapper.dll</HintPath>
      <Private>True</Private>
    </Reference>`

Version must be identical, or in Include attribute must be only "Dapper".

**Comment by odinserj** [comment]
What is the exact problem you have (can't build, can't open a solution, etc.)?

**Comment by alex-t0** [comment]
Runtime exception, cannot find Dapper 1.40.0.0. But may be it is not a problem of hangfire. I think this error happens because I rebuild hangfire manually with strong name. Now I rebuild hangfire again with reference to strong named Dapper, and now it works.

I think is better to build nuget packages, containing assemby with strong name. Why current version of nuget packages contains assemblies without strong name?

**Comment by alex-t0** [comment]
Yes, I see that version of Dapper.dll is 1.40.0.0. But nuget package version is 1.42.0. This confused me.

But it works after rebuilding all libraries with strong name. I did it because my solution contains only strong named assemblies and need strong named references.

So, problem not in hangfire.

But there was a little question: assemblies in current nuget packages specially does not contains strong name?

**Comment by stajs** [comment]
Whenever I see people mention Strong Naming, [I am reminded of this](http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/). If you insist on using Strong Naming, you could try [Strong Namer](https://github.com/dsplaisted/strongnamer).

**Comment by alex-t0** [comment]
Ok, thanks!
