### ISSUE TITLE
Didn't load app.config from Job

### ISSUE THREAD

**Issue by gandarez** [HangfireIO/Hangfire#586]
Hi,

I'm using Windows Service as Hangfire engine and at OnStart method I load (using Reflection) all my jobs and invoke RecurringJob.AddOrUpdate() based on my Interface. Eveyrthing occurs as expected, Hangfire loads my library, calls my method (Run), however when a specific job depends on its own config file it breaks.

It seems that no config file could be loaded to that library. Every single custom library (and its own config file) is located on binary folder under my windows service. 

Is there anything I'm missing?

**Comment by treymack** [comment]
`ConfigurationManager` reads settings from the host config file, so you'll have to copy those settings into the app.config for your Windows Service.

**Comment by gandarez** [comment]
@treymack I really don't like to do it because there're many plugins (libraries) that I'm loading in runtime and each one has its own configuration. 

Isn't there any alternative you imagine?

**Comment by pieceofsummer** [comment]
The alternative is to start each task in a separate AppDomain, with a custom config file.
