### ISSUE TITLE
Hangfire Discussion Board Offline?

### ISSUE THREAD

**Issue by Darkreaper101** [HangfireIO/Hangfire#588]
Good Day,

I've been trying to go onto the hangfire forum board, but it seems the forum board is down. Am I the only one that's currently experiencing this issue?

Regards

**Comment by yngndrw** [comment]
https://discuss.hangfire.io/ is down for me as well. (UK / BT)

http://www.isitdownrightnow.com/discuss.hangfire.io.html

**Comment by gandarez** [comment]
Also down in Brazil.

**Comment by Darkreaper101** [comment]
Hmmm thanks good to know I'm not the only one as I'm looking for some answers. :smile:

Thanks guys

**Comment by gandarez** [comment]
Alternatively you can access through Google's cache.

https://webcache.googleusercontent.com/search?q=cache:C8ulBjpYV6IJ:https://discuss.hangfire.io/+&cd=1&hl=en&ct=clnk&gl=br

**Comment by yilativ** [comment]
Me too
