### ISSUE TITLE
Hangfire Job starts multiple times

### ISSUE THREAD

**Issue by vknvnn** [HangfireIO/Hangfire#590]
![screenshot_5](https://cloud.githubusercontent.com/assets/5488493/15984773/14c200c4-3001-11e6-9255-c1557e6ccf38.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/5488493/15984774/18b0d75a-3001-11e6-948d-5c802bf0e702.png)

please me know,the issue is sometime 

regard,

**Comment by gandarez** [comment]
In my production environment this problem has started also. I don't know what happens since I didn't change anything.

@sergeyzwezdin Do you have any thoughts on this?

**Comment by sergeyzwezdin** [comment]
@gandarez, nope. Could you give more details?

**Comment by gandarez** [comment]
@sergeyzwezdin I can't reproduce the error because it happened 3 times in about 5 months. The problem is the job can't run twice a day and I got duplicated values!!

![image](https://cloud.githubusercontent.com/assets/782854/16007960/c40b281c-314b-11e6-802b-869abaf76255.png)

**Comment by gandarez** [comment]
@odinserj Do you have any thoughts on this?

**Comment by vknvnn** [comment]
do we encounter one of the issues common? this issue is sometime, i run to test, and i watch very especially common, I have a way to fixed: **[Use lock object]**, I create a flag to lock process other.

**Comment by odinserj** [comment]
@vknvnn, what Hangfire version, what storage, what storage version?

**Comment by vknvnn** [comment]
version 1.5.7, for mysqlstorege and sqlstorege, 
I hope to have answers soon,

regard,

**Comment by odinserj** [comment]
Heh, there are two packages for MySQL support: [Hangfire.MySql](https://github.com/chrislove/Hangfire.MySql) and [Hangfire.MySqlStorage](https://github.com/arnoldasgudas/Hangfire.MySqlStorage). Looks like you are using the latter. I briefly looked into the source code, and found that `MySqlServerQueue` class implementation uses non-atomic query to fetch a job from queue. And if distributed lock isn't working as expected, you'll get the problem described above.

Please create an issue in Hangfire.MySqlStorage repository or try to use another package – queue implementation is much better there.

**Comment by vknvnn** [comment]
why are you close it? while it still to have issue in Hangfire.SqlServer (= 1.5.7)

please describe for me!

**Comment by odinserj** [comment]
This problem is related to the [Hangfire.MySqlServerStorage](https://github.com/arnoldasgudas/Hangfire.MySqlStorage), that is a third-party extension I have no control under. So please file an issue there to attract attention of its author. This repository only contains source code for Hangfire.Core, Hangfire.SqlServer and Hangfire.SqlServer.Msmq packages.

**Comment by vknvnn** [comment]
sure [**odinserj**], But now I'm at home, Tomorrow on company, I will describe these configuration that i do, thank you because support me, I hope it work to I can demo for my boss.

regard,

**Comment by gandarez** [comment]
> Ah, now I see, you are using Hangfire.SqlServer also, sorry.

I'm also using Hangfire.SqlServer

**Comment by odinserj** [comment]
@gandarez, can you show me your configuration logic and your Dashboard UI screenshot?

**Comment by odinserj** [comment]
Are you using SQL Server, or SQL Azure?

**Comment by gandarez** [comment]
@odinserj I'm using SQL Server 2008 R2 in the same LAN.

Here's the configuration logic
```C#
GlobalConfiguration.Configuration.UseSqlServerStorage("Hangfire",
new SqlServerStorageOptions
{
    QueuePollInterval = TimeSpan.FromSeconds(AppConfig.GetInt32("QueuePollInterval", 5))
})
.UseFilter(new AutomaticRetryAttribute
{
    Attempts = AppConfig.GetInt32("AutomaticRetryAttempts", 3)
})
.UseFilter(new WorkflowJobFilter())
.UseFilter(new PreserveOriginalQueueAttribute());

_server =
new BackgroundJobServer(new BackgroundJobServerOptions
{
    Queues = _queues.ToArray(),
    SchedulePollingInterval = TimeSpan.FromSeconds(AppConfig.GetInt32("SchedulePollingInterval", 15)),
    ServerTimeout = TimeSpan.Parse(AppConfig.GetString("ServerTimeout", "01:00"), CultureInfo.InvariantCulture)
});
```

What do you need from UI?

**Comment by vknvnn** [comment]
the content below is my configuration run in web mvc 5:
public void Configuration(IAppBuilder app)
        {
            // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=316888

            var builder = new ContainerBuilder();
            var builderHangfire = new ContainerBuilder();

            var config = new HttpConfiguration();
            // Register your Web API controllers.
            builder.RegisterApiControllers(Assembly.GetExecutingAssembly());


            // Register your MVC controllers.
            builder.RegisterControllers(Assembly.GetExecutingAssembly());

            //Register Hangfire
            GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 1 });
            Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage("DefaultConnection");
            var options = new DashboardOptions
            {
                AuthorizationFilters = new[]
            {
                new LocalRequestsOnlyAuthorizationFilter()
            }
            };
            
            AutofacBootstrap.InitForeWeb(builder);
            var container = builder.Build();

            AutofacBootstrap.InitForHanfire(builderHangfire);
            var containerHangfire = builderHangfire.Build();

            //Hanfire 
            Hangfire.GlobalConfiguration.Configuration.UseAutofacActivator(containerHangfire);
            //Api 
            config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
            //MVC 
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));

            app.UseAutofacMiddleware(container);
            app.UseAutofacWebApi(config);
            WebApiConfig.Register(config);
            app.UseAutofacWebApi(config);
            app.UseWebApi(config);
            app.UseAutofacMvc();
            app.UseHangfireDashboard("/hangfire", options);
            app.UseHangfireServer();
        }

**Comment by odinserj** [comment]
@vknvnn, @gandarez, thanks for the feedback! I've found non-synchronized access to a transaction which may cause `Worker` and `Timer` threads to access a connection instance (that is not thread safe) at the same time. In this case, the `RemoveFromQueue` method may throw an exception, which will lead to job re-queue as shown in the picture.

**Comment by odinserj** [comment]
Hangfire 1.5.8 is just released!

**Comment by gandarez** [comment]
@odinserj I hope you release 1.6.0 beta 4 soon.

**Comment by gandarez** [comment]
@odinserj You rock!
