### ISSUE TITLE
Suppress or disable keepalive errors?

### ISSUE THREAD

**Issue by automys** [HangfireIO/Hangfire#592]
Hi there! Awesome project, thanks for all the work of contributors.

I'm using HangFire in Microsoft Azure against SQL Azure and am seeing lots of failed queries in my Application Insights logging from the command "SELECT 1;". My guess is this is from the ExecuteKeepAliveQuery method in SqlServerDistributedLock.

Is there a way to configure HangFire in this environment to avoid having this error occur (and get logged)? Perhaps a different configuration to account for SQL Azure or the keep alive strategy? Thanks!

**Comment by odinserj** [comment]
@automys, do you see any error message?

**Comment by automys** [comment]
The call is being logged by Application Insights as a failed query. See the image below. Looking at the code, it seems this is wrapped in a try/catch and a failure is being used to detect state. My question is whether there is any alternative to doing this that could avoid logging a failed query.

![sql-failure](https://cloud.githubusercontent.com/assets/16780630/16136305/530584ce-33de-11e6-98ac-cd6befd50c13.jpg)

**Comment by odinserj** [comment]
I've found a non-synchronized access to the transaction instance which may cause a keep-alive query to be executed simultaneously with the job queueing methods from different threads and cause exceptions to appear for this query, or for another query described in #590.

**Comment by odinserj** [comment]
Hangfire 1.5.8 is just released!

**Comment by automys** [comment]
This appears to have resolved the issue, thanks!
