### ISSUE TITLE
How to add more page in Dashboard?

### ISSUE THREAD

**Issue by stevenluoxiaohua** [HangfireIO/Hangfire#593]
How to add more page in Dashboard?

**Comment by gandarez** [comment]
following

**Comment by odinserj** [comment]
In short, you should do the following steps:

* Install the [RazorGenerator](https://visualstudiogallery.msdn.microsoft.com/1f6ec6ff-e89b-4c47-8e79-d2d68df894ec) extension for Visual Studio (here is [GitHub repo](https://github.com/RazorGenerator/RazorGenerator)).
* Create a `.cshtml` file with the following content. You can see more examples in the Hangfire repository.
```cshtml
@* Generator: Template TypeVisibility: Internal GeneratePrettyNames: true *@
@inherits RazorPage

@* The rest of a page *@
```
* Set the `CustomTool` property of a `.cshtml` file to `RazorGenerator`. After this step, a new class will appear in your project.
* Register page for a route for a new class:
```csharp
using Hangfire.Dashboard;
RouteCollection.Routes.AddRazorPage("/batches/started", x => new StartedBatchesPage());
```
* Add a new navigation menu item:
```csharp
NavigationMenu.Items.Add(page => new MenuItem("Batches", page.Url.To("/batches/started")));
```

**Comment by stevenluoxiaohua** [comment]
Register page for a route

any class is ok?
when call this class?

**Comment by odinserj** [comment]
> Set the CustomTool property of a .cshtml file to RazorGenerator. After this step, a new class will appear in your project.

You should use the class that created by RazorGenerator.

**Comment by gandarez** [comment]
You also may need to override its namespace.

```C#
@* Generator: Template
    TypeVisibility: Internal
    GeneratePrettyNames: true
    Namespace: Hangfire.Dashboard.Pages
*@
```

**Comment by gandarez** [comment]
@odinserj I couldn't find any extension or way to add a route

> RouteCollection.Routes.AddRazorPage("/batches/started", x => new StartedBatchesPage());

**Comment by weirdyang** [comment]
@odinserj 
the razor template generator isn't available for VS2022, is that the only way to extend or replace pages?
