### ISSUE TITLE
Ability to hide columns on page

### ISSUE THREAD

**Issue by gandarez** [HangfireIO/Hangfire#596]
Should be interesting to be able to disable specifc columns on Recurring Job Page or somewhere else. Specifically when the job's name is too large.

**Comment by odinserj** [comment]
Can you show the screenshot? Instead of hiding columns, we can simply shorted job name. For example, don't show namespaces if name is too long.

**Comment by gandarez** [comment]
@odinserj 
![image](https://cloud.githubusercontent.com/assets/782854/17373921/b2a2bba0-5980-11e6-9316-48ec417d7daf.png)

**Comment by odinserj** [comment]
That's because white spaces in the `Cron` and `Time zone` columns aren't wrapped. It is better to add `white-space: normal` CSS for these columns.
