### ISSUE TITLE
Adding custom pages to Hangfire Dashboard

### ISSUE THREAD

**Issue by gandarez** [HangfireIO/Hangfire#599]
Hi @odinserj 

I'm customizing the Dashboard to my needs and need your help if possible.

I created a class library to hold everything related to the customization. The first thorn in one's side is creating the new pages. It can't inherit from RazorPage and etc as I'll show below
![image](https://cloud.githubusercontent.com/assets/782854/16196239/aa59465a-36d3-11e6-823e-e21f32f052dc.png)
![image](https://cloud.githubusercontent.com/assets/782854/16196557/d43a9694-36d4-11e6-98ad-895d9a20e7ed.png)

Any thoughts or advices?

**Comment by odinserj** [comment]
Have you tried to build the solution? Are there any compilation errors?

**Comment by gandarez** [comment]
@odinserj 

1. The custom razor view was changed to Build Action -> None (as dashboard pages are)
2. The custom library compiles with no errors
3. When building the asp.net MVC project fails
4. The Hangfire version is 1.5.8 in both projects

![image](https://cloud.githubusercontent.com/assets/782854/16230054/fb6ec840-3795-11e6-9f4c-f83747c6583c.png)

![image](https://cloud.githubusercontent.com/assets/782854/16230139/6dc9872c-3796-11e6-94ee-35a600e5440c.png)

**Comment by gandarez** [comment]
@odinserj I figured out what was the problem. My custom library was using .Net 4.5 instead of 4.5.2;
