### ISSUE TITLE
Jobs stuck in Enqueued state after SQL Server is restarted

### ISSUE THREAD

**Issue by RupertAvery** [HangfireIO/Hangfire#600]
I am using HangFire version 1.5.3 with a SQL Server backend.

I have noticed that jobs remain in the Enqueued state after the following sequence of events:

- SQL service is stopped
- Jobs are enqueued, throwing exceptions
- SQL service is started
- Jobs are enqueued normally, however they are never executed

If the HangFire server is restarted, either by ending the process, or simply Disposing and creating a new instance of the server, the Enqueued jobs will be executed

If a Log provider is set, e.g.

```
LogProvider.SetCurrentLogProvider(new ColouredConsoleLogProvider());
```

Then the jobs will be executed even after the SQL service is restarted.

The problem persists even in 1.5.8

**Comment by odinserj** [comment]
Can you make a process dump to investigate the call stack of Worker threads and see method that is causing this behavior?

**Comment by RupertAvery** [comment]
Hmmm, is there anything in particular I should be looking for?  What tool do you recommend for the process dump?

**Comment by odinserj** [comment]
Task Manager &rarr; Details tab &rarr; Right-click on a process  &rarr; Create dump file. This will generate a dump file that you can open with Visual Studio and see call stacks of all the threads. This gives almost immediate answer what methods are blocked.

**Comment by odinserj** [comment]
Any news? Hangfire [1.5.9](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.9) was recently released with changes related to SQL Server and stuck workers, you can try to update. If the problem persists, please feel free to reopen the issue.

**Comment by RupertAvery** [comment]
Hi @odinserj, that's good to hear, I'll try this out and let you know how it goes. Thanks!
