### ISSUE TITLE
RecurringJob for specific storage

### ISSUE THREAD

**Issue by ADThomsen** [HangfireIO/Hangfire#601]
I have a setup with two different SQL server storages and I enqueue my tasks on the storage that I need.

However I cannot find a way to make a RecurringJob run on a specific storage. Am I missing it or is it not supported?

**Comment by odinserj** [comment]
There is the `RecurringJobManager` class, that is used by `RecurringJob` static members:

```csharp
var manager = new RecurringJobManager(yourStorage);
manager.AddOrUpdate(/* Arguments */);
```

**Comment by ADThomsen** [comment]
Cheers. I found that a week or so after posting this but didn't come around to update here.
