### ISSUE TITLE
Hangfire job on failure restarts multiple times and blocks all worker threads

### ISSUE THREAD

**Issue by rdehuyss** [HangfireIO/Hangfire#605]
Using Hangfire 1.5.8 and Sql Server as storage, once our job fails and it requeues, it is being processed multiple times and consumes all the worker threads, resulting in a dead-lock.

Probably related to bug #590 . What can I do to help pinpoint this issue?

![image](https://cloud.githubusercontent.com/assets/567842/16541375/2ba926f6-4081-11e6-87f6-76220e0a5dd6.png)

**Comment by odinserj** [comment]
Hi @rdehuyss, does your method can throw `OperationCanceledException` or it's descendants? Is it contain calls to async methods?

**Comment by vknvnn** [comment]
oh, I think: you using transaction in execute function,

**@odinserj** : i was read code, i saw it implemented as below: 

1. Get information.
2. Execute 
3. Update infomation (Remove)

if these items include transaction, this issue will resolve, 

please feedback if i wrong anything.

**Comment by rdehuyss** [comment]
@odinserj , @vknvnn - thx for the reply.

What are doing the following in this job:

- read a file from disk
- for each file, we need to enrich the data and do an http call (this is async) but the http call is started in it's own thread 
```
//WHY comment: do avoid deadlock: see http://www.nedstoyanov.com/async-await-deadlock/
return Task.Run(() => GetAsync<T>(url)).WaitAndUnwrapException();
```
- we insert the data in SQL server
- we update Elastic Server using NEST but using the sync api

The complete code can be found below:
```
                try
                {
                    var legitimatiekaart = ReadXmlFromFile(aidaFilesToProcess);
                    if (LegitimatiekaartDoesNotExist(legitimatiekaart))
                    {
                        var ssnWithSynergyId = FindPersonForHuidigINSZOrNull(legitimatiekaart);
                        var insertLegitimatiekaartWriteModel = AidaLegitimatiekaartXmlToWriteModelMapper.MapTo(legitimatiekaart, ssnWithSynergyId);

                        using (_legitimatiekaartDbContext)
                        using (var transaction = new TransactionScope(TransactionScopeOption.Required))
                        {
                            WriteLegitimatiekaartToSql(insertLegitimatiekaartWriteModel);
                            _mediatr.Publish(new AidaLegitimatiekaartInsertedNotification {AidaLegitimatiekaart = insertLegitimatiekaartWriteModel});

                            transaction.Complete();
                        }
                    }
                }
                catch (Exception e)
                {
                    var importAidaLegitimatiekaartJobException = new ImportAidaLegitimatiekaartJobException($"Error importing Aida Legitimatiekaart File {aidaFilesToProcess.RealFile}", aidaFilesToProcess.RealFile, e);
                    Logger.Error(importAidaLegitimatiekaartJobException);
                    throw importAidaLegitimatiekaartJobException;
                }
````

**Comment by odinserj** [comment]
@rdehuyss, try to update to the latest [1.5.9](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.9) version. There was a bug related to incorrectly handled `OperationCanceledException` and its derivatives. Once thrown during background processing, it caused all workers to stop.
