### ISSUE TITLE
Hangfire Serilog exception

### ISSUE THREAD

**Issue by AR1ES** [HangfireIO/Hangfire#606]
I have an exception when using Hangfire 1.6.0-build-02111 and Serilog 2.0.0 (ASP Net. Core app with net461 framework).

```
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'Hangfire.Server.BackgroundProcessingServer' threw an exception.
  Source=Hangfire.Core
  TypeName=Hangfire.Server.BackgroundProcessingServer
  StackTrace:
       at Hangfire.BackgroundJobServerOptions..ctor()
       at MyTestApp.Hangfire.Hangfire.ConfigHangfire(IApplicationBuilder app, IServiceScopeFactory scopeFactory) in D:\Projects\MyTestApp\src\MyTestApp\Hangfire\Hangfire.cs:line 17
       at MyTestApp.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceScopeFactory scopeFactory) in D:\Projects\MyTestApp\src\MyTestApp\Startup.cs:line 62
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'SerilogLogger' threw an exception.
       Source=Hangfire.Core
       TypeName=SerilogLogger
       StackTrace:
            at Hangfire.Logging.LogProviders.SerilogLogProvider.SerilogLogger..ctor(Object logger)
            at Hangfire.Logging.LogProviders.SerilogLogProvider.GetLogger(String name)
            at Hangfire.Logging.LogProvider.GetLogger(String name)
            at Hangfire.Logging.LogProvider.GetLogger(Type type)
            at Hangfire.Logging.LogProvider.For[T]()
            at Hangfire.Server.ServerWatchdog..cctor()
       InnerException: 
            HResult=-2147467261
            Message=Value cannot be null.
Parameter name: types
            ParamName=types
            Source=mscorlib
            StackTrace:
                 at System.Type.GetMethod(String name, Type[] types)
                 at Hangfire.Logging.LogProviders.SerilogLogProvider.SerilogLogger..cctor()
            InnerException: 
```

**Comment by IanYates** [comment]
Serilog 2.0 has some breaking changes.  The ILogger type has some extra methods on there and some other types have moved around, etc.  
I suspect this issue https://github.com/damianh/LibLog/issues/107 is related.

(Hangfire uses LibLog as per #265)

**Comment by odinserj** [comment]
Pull request against the `dev` branch is highly appreciated! Since we can't just upgrade to a new LibLog version, because it will cause breaking changes, we need to patch Hangfire's LibLog.cs file and test both Serilog 1.x and Serilog 2.x.

**Comment by IanYates** [comment]
Hey @odinserj - good point.  I haven't moved to Serilog 2.x for this sort of reason but will probably do so at the end of the month once I get some deadlines out of the way.  If no one's done testing and made a PR I'll happily make one then for you.

**Comment by odinserj** [comment]
Awesome, @IanYates!

**Comment by Asshiah** [comment]
I get the same error on my project with the final 1.6.0 version of Hangfire.AspNetCore

**Comment by hastarin** [comment]
Just a note that I hit this issue when upgrading to 1.6.0   It is not an issue with 1.5.9 and I've reverted to that for my purposes.

**Comment by brendan-ssw** [comment]
this is just another "me too" post: 
hangfire 1.6.0 with serilog 2.0.0 had this issue.
hangfire 1.5.9 with serilog 2.0.0 was ok.

**Comment by IanYates** [comment]
There's a PR in LibLog for this
https://github.com/damianh/LibLog/pull/110

The change seems very straightforward and is done in a backwards-compatible way.  However the PR in LibLog hasn't been merged yet.  @odinserj - ok for us to make the same change here now or do you think we should wait for LibLog to do their bit (and then repeat the change here)?

**Comment by odinserj** [comment]
We can't update LibLog because of breaking changes anyway, so we can just merge it to Hangfire repository itself. PR against the `master` branch will be highly appreciated to make them available in the next patch release.

**Comment by geirsagberg** [comment]
Chiming in with the same problem using Serilog 2.0. Reverting to Hangfire 1.5.9 worked for me as well.

**Comment by odinserj** [comment]
Hm, I've changed `Type.GetMethod` to `Type.GetRuntimeMethod`, because the former is not available in .NET Standard 1.3. And looks like this caused an exception. Would anybody like to fix this issue by creating a PR against the `master` branch?

**Comment by SuperTroye** [comment]
I am having a similar issue with running Hangfire in a aspnet core app.

`// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	// commented out loggerFactory because Hangfire is throwing exception
	loggerFactory.AddConsole(LdvConfig.GetSection("Logging"));
	loggerFactory.AddDebug();`

If I leave in this code, I get exception:
The type initializer for 'Hangfire.Server.BackgroundProcessingServer' threw an exception.

If I comment out the 2 lines in Configure, everything works fine.
`	//loggerFactory.AddConsole(LdvConfig.GetSection("Logging"));
	//loggerFactory.AddDebug();`

Is there a problem with this?
