### ISSUE TITLE
Hangfire 1.5.8 restarts always long jobs after 30 minutes

### ISSUE THREAD

**Issue by dmikov** [HangfireIO/Hangfire#607]
May be regression bug? But looks exactly like #514.
The job automatically restarts after 30 minute in the run. The job.queue has pick date populated and then reset again.
We are using MongoDb as a back-end. The mongoDb connection are set to 8 hours timeout. Don't know what else to do.

**Comment by odinserj** [comment]
There is the [`MongoStorageOptions.InvisibilityTimeout`](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/MongoStorageOptions.cs#L21) option, try to change it to a higher value.
