### ISSUE TITLE
how to use hangfire layout page as master layout for application?

### ISSUE THREAD

**Issue by bakamaru** [HangfireIO/Hangfire#608]
All i want to have my mvc views, controllers and it uses hangout layout page with out using core and razor generator?
How can i achieve this?

**Comment by gandarez** [comment]
I'm not pretty sure you'll be able to achieve what you wish. 
Why don't you use RazorGenerator?

I could simply extended Hangfire dashboard by inheritting from RazorPage
```C#
@inherits RazorPage
```

**Comment by bakamaru** [comment]
can you drop source code for this? I didn't find any in docs and sample repos.

**Comment by gandarez** [comment]
@bakamaru https://gist.github.com/gandarez/9df813fc7d11f85c0d585a8257aedd79

**Comment by weirdyang** [comment]
> @bakamaru https://gist.github.com/gandarez/9df813fc7d11f85c0d585a8257aedd79

@gandarez  is there any special naming convention for this to work?
