### ISSUE TITLE
Task executes is put in queue more than once when triggering manually

### ISSUE THREAD

**Issue by evaldas-raisutis** [HangfireIO/Hangfire#611]
When you trigger a task manually from the UI, if you click the button "Trigger Now" multiple times quickly, selected tasks will be sent to queue multiple times before deselecting tasks and disabling the button. I would expect the tasks to be sent once, regardless how many times the button is clicked.

**Comment by odinserj** [comment]
PR is welcome! :smile:

**Comment by odinserj** [comment]
Fixed by PR in 1.6.1
