### ISSUE TITLE
IDashboardAuthorizationFilter with .Net Core

### ISSUE THREAD

**Issue by imperugo** [HangfireIO/Hangfire#613]
Hi, 
I'm playing with Hangfire and .NET core and everything seems ok (well done).
I'd like to know how to protect the dashboard for authenticated users.

I'm using [IdentityServer](https://github.com/IdentityServer/IdentityServer3) with OpenId for the authentication and I'm trying to implement the logic into the my `IDashboardAuthorizationFilter`.

Unfortunately I didn't find a way to get the HttpContext or the current User.
How can I check if the current user is logged or not into my `IDashboardAuthorizationFilter`?

Thanks

**Comment by marcoCasamento** [comment]
I'm using a similar configuration (IdSrv v2). I simply add an AuthorizationFilter[] like:

```
var authorizationFilters = new IAuthorizationFilter[] 
                                                   { 
                                                       new AuthorizationFilter
                                                       {
                                                           Roles = "MyAuthorizedRole1;MyAuthorizedRole2"
                                                       },
                                                   };
app.UseHangfireDashboard("/path",
                                                   new Hangfire.DashboardOptions()
                                                   {
                                                       AuthorizationFilters = authorizationFilters
                                                   }
```

and then add those roles to the users that need it in the identityservr admin page (bt I believe what's really matter are the "Roles" of your Principal)

**Comment by imperugo** [comment]
Hi @marcoCasamento 
the problem here is that `AuthorizationFilter` doesn't exist and the `IAuthorizationFilter` is deprecated. The new one `IDashboardAuthorizationFilter` doesn't expose the User into the context so I can't check it (otherwise I don't have roles but claims)

**Comment by odinserj** [comment]
I've just added extension methods, please see the referenced commit. Meanwhile you can cast the context to `AspNetCoreDashboardContext` class to get the `HttpContext` property.

```csharp
class MyAuthorizationFilter : IDashboardAuthorizationFilter
{
    public bool Authorize(DashboardContext context)
    {
        var httpContext = ((AspNetCoreDashboardContext) context).HttpContext;
        return false;
    }
}
```

**Comment by kroniak** [comment]
It works like this: 

```c#
internal class HangfireAuthorizationFilter : IDashboardAuthorizationFilter
{
	private readonly string[] _roles;

	public HangfireAuthorizationFilter(params string[] roles)
	{
		_roles = roles;
	}

	public bool Authorize(DashboardContext context)
	{
		var httpContext = ((AspNetCoreDashboardContext)context).HttpContext;
		var result = _roles.Aggregate(false, (current, role) => current || httpContext.User.IsInRole(role));

		return result;
	}
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{

   app.UseHangfireDashboard(options:new DashboardOptions
		{
			Authorization = new[]
			{
				new HangfireAuthorizationFilter("admin")
			}
		});
}
```

**Comment by odinserj** [comment]
Or you can use the `GetHttpContext` extension method as well:

```csharp
public bool Authorize(DashboardContext context)
{
    var httpContext = context.GetHttpContext();
    // ...
```

**Comment by kroniak** [comment]
@odinserj where is this extension method?

**Comment by odinserj** [comment]
Ah, it's in the `Hangfire.Dashboard` namespace, ReSharper pampered me

**Comment by kroniak** [comment]
@odinserj which package? I dont see this extension in Dashboard namespace and my Resharper doesnt suggest me.

**Comment by odinserj** [comment]
Hangfire.AspNetCore 1.6.0, in the `AspNetCoreDashboardContextExtensions` class.

**Comment by kroniak** [comment]
@odinserj Его нет там )) вот скриншот

![hangfire](https://cloud.githubusercontent.com/assets/1502943/17053685/d3d594d8-500b-11e6-8ae3-088a3ad6a392.PNG)

**Comment by odinserj** [comment]
Hm, it was included only to the `Hangfire.Core` project, and not to `Hangfire.Core.NetStandard`. So it exists in net45, but doesn't exist on netstandard1.3. @kroniak, thanks for persistence!

**Comment by odinserj** [comment]
Fixed in b579546773d8ae57affc8a435954555ab1f23289.

**Comment by knopa** [comment]
How should be in Hangfire.Core  v1.6.2?
How can I get httpContext?

**Comment by kroniak** [comment]
@knopa Да, он там есть

**Comment by knopa** [comment]
<img width="244" alt="1a8487e92fd6ec1726137e6b00cea509" src="https://cloud.githubusercontent.com/assets/1783681/17526806/71336142-5e71-11e6-9822-5322a7c75c6b.png">

Хоть стрельни но нет экстеншина для DashboardContext

**Comment by kroniak** [comment]
@knopa oy, sorry. It is in only in the NETCore project.

https://github.com/HangfireIO/Hangfire/blob/4dec6435fb552364833c359079230ad04fd98e53/src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardContextExtensions.cs

**Comment by knopa** [comment]
@kroniak Any plan for Hangfire.Core?

**Comment by kroniak** [comment]
@knopa this is to @odinserj

**Comment by odinserj** [comment]
@knopa, the `DashboardContextExtensions` was mistakenly named `OwinDashboardContextExtensions` (please see your screenshot). It has the `GetOwinEnvironment` method:

**ASP.NET/OWIN applications**

```csharp
using Microsoft.Owin; // From the Microsoft.Owin package

public bool Authorize(DashboardContext context)
{
    var environment = context.GetOwinEnvironment();
    var owinContext = new OwinContext(environment);

    // ...
}
```

**ASP.NET Core applications**

```csharp
public bool Authorize(DashboardContext context)
{
    var httpContext = context.GetHttpContext();
    // ...
}
```

**Comment by knopa** [comment]
@odinserj 
Thanks, it works with owinContext.Request.User.IsInRole

**Comment by fredgate** [comment]
The authenticated user is also avilable via the Authentication property :
`owinContext.Authentication.User.IsInRole("...")`

**Comment by oskarhelling** [comment]
How can I access the UserManager in the Authorize method? Should I pass it in in the constructor?
