### ISSUE TITLE
Timeout displaying failed jobs page

### ISSUE THREAD

**Issue by jerome-gingras** [HangfireIO/Hangfire#616]
We tried upgrading from Hangfire 1.4.7 to 1.6.0 and we seem to be having a problem with the new StackTraceParser that was introduced in version 1.5.0. The regex evaluation is failing with a timeout exception on some of our stack traces. I know the timeout was added in order to avoid infinite loops loading the failed jobs page, but getting the timeout exception isn't really better in our case, since we can't see at all the failed jobs list.
Is there a way to catch that timeout exception or to just ignore them so that we could at least see the list?

**Comment by odinserj** [comment]
Thanks for reporting! I've fixed this by returning non-highlighted stack trace, when a timeout exception occurred. Will be shipped with 1.6.2.
