### ISSUE TITLE
Hangfire runs missed Jobs after server wakes up, can it be prevented?

### ISSUE THREAD

**Issue by evaldas-raisutis** [HangfireIO/Hangfire#620]
By default, it seems, hangfire will attempt to run jobs it has missed, if for example, server was down when jobs were supposed to be run. I would like to disable this functionality. We have jobs which import products into a webshop, and for the duration of an import site becomes quite unresponsive due to resources used by the import. 

Problem is we only want to run jobs at night OR when triggered manually through UI. Can I disable hangfire trying to run missed jobs after startup?

**Comment by evaldas-raisutis** [comment]
I have added an attribute `DisableConcurrentExecution` on the job, but all that does is delays the execution of second instance of a job until after first one is done. I want to be able to detect when a concurrent job has been run, and then cancel it all together.

So I added another attribute, which checks at `FailedState`. If this failed state checks out as Concurrent exception, I try to call `BackgroundJob.Delete(context.BackgroundJob.Id)`. However, what it does, is increments count of Deleted Jobs by 1 (doesn't actually show the job there though) and puts the job back in Retry queue. I can't find a method `Cancel `??

**Comment by Darrenmeehan** [comment]
This is also something I've to look into further, also with an import job.

**Comment by DBalashov** [comment]
I also can't found solution, but insert additional checking in start of job for time. For example, if job scheduled at 3:00 AM - I'm check current time inside job for 3:00 AM +/- 10 minutes. Job aborted if difference more than 10 minutes.

**Comment by evaldas-raisutis** [comment]
I ended up using this attribute:

```
    public class StopWakeUpExecution : JobFilterAttribute, IServerFilter
    {
        public void OnPerformed(PerformedContext filterContext)
        {

        }

        public void OnPerforming(PerformingContext filterContext)
        {
            using (var connection = JobStorage.Current.GetConnection())
            {
                var recurring = connection.GetRecurringJobs().FirstOrDefault(p => p.Job.ToString() == filterContext.BackgroundJob.Job.ToString());
                TimeSpan difference = DateTime.UtcNow.Subtract(recurring.LastExecution.Value);
                if (recurring != null && difference.Seconds < 15)
                {
                    // Execution was due in the past. We don't want to automaticly execute jobs after server crash though.

                    var storageConnection = connection as JobStorageConnection;

                    if (storageConnection == null)
                        return;

                    var jobId = filterContext.BackgroundJob.Id;

                    var deletedState = new DeletedState()
                    {
                        Reason = "Task was due in the past. Please Execute manually if required."
                    };

                    using (var transaction = connection.CreateWriteTransaction())
                    {
                        transaction.RemoveFromSet("retries", jobId);  // Remove from retry state
                        transaction.RemoveFromSet("schedule", jobId); // Remove from schedule state
                        transaction.SetJobState(jobId, deletedState);  // update status with failed state
                        transaction.Commit();
                    }
                }
            }
        }
    }
```

**Comment by evaldas-raisutis** [comment]
Seems after server wake up, hangfire will check for jobs due in the past and set next execution to "Now". Checking if task is due to execute within 15 second interval, gives a hint that task is executed after a server wake up.

**Comment by evaldas-raisutis** [comment]
@DBalashov that works on scheduled executions, but I also want to be able to execute the job manually when necessary.

**Comment by evaldas-raisutis** [comment]
It seems on coming back from idle, hangfire will grab jobs which were to be executed in the past and sets NextExecution to Now. It would be nice if there was a setting to prevent this.

**Comment by enrichz** [comment]
Any update on this?

**Comment by CBlaize** [comment]
This feature is also a requirement for my use case.  Jobs are expected to ONLY run at the designated time.  If the server was down at the designated time or it failed then it cannot be re-run at any later date.  period.

**Comment by pieceofsummer** [comment]
The recurring job scheduler only checks if there should be a scheduled execution since the previous job run, and triggers the job if needed. It doesn't care if the scheduled time is missed for 1 second or a few days.

I'd try to go with a client filter that would cancel "late" jobs:
```c#
public class NoMissedRunsAttribute : JobFilterAttribute, IClientFilter
{
    public TimeSpan MaxDelay { get; set; } = TimeSpan.FromMinutes(15);
    
    public void OnCreating(CreatingContext context)
    {
        if (context.Parameters.TryGetValue("RecurringJobId", out var recurringJobId) &&
            context.InitialState?.Reason == "Triggered by recurring job scheduler")
        {
            // the job being create looks like a recurrent job instance,
            // and triggered by a scheduler (i.e. not manually) at that.
            
            var recurringJob = context.Connection.GetAllEntriesFromHash($"recurring-job:{recurringJobId}");
            
            if (recurringJob != null && recurringJob.TryGetValue("NextExecution", out var nextExecution))
            {
                // the next execution time of a recurring job is updated AFTER the job instance creation,
                // so at the moment it still contains the scheduled execution time from the previous run.
                
                var scheduledTime = JobHelper.DeserializeDateTime(nextExecution);
                
                if (DateTime.UtcNow > scheduledTime + MaxDelay)
                {
                    // the job is created way later than expected
                    context.Canceled = true;
                }
            }
        }
    }

    public void OnCreated(CreatedContext context)
    {
    }
}
```

I haven't tested it though, so it may require some adjustments before it actually works :)

**Comment by 5p1k3md** [comment]
Hello,

i just ried the solution from @pieceofsummer  .
Unfortunately there is no initial state given with the compared string given at any time.
Is there an other way to determ a rerunning recurring job after server restart?

**Comment by Sephiii** [comment]
The only way that i found it's to recreate jobs at startup

`            using (var connection = JobStorage.Current.GetConnection())
            {
                foreach (var recurringJob in connection.GetRecurringJobs())
                {              
                        var jobTimeZone = TimeZoneInfo.FindSystemTimeZoneById(recurringJob.TimeZoneId) ?? TimeZoneInfo.Utc;
                        var name = recurringJob.Id;

                        RecurringJob.RemoveIfExists(recurringJob.Id);

                        var manager = new RecurringJobManager();

                        var job = new Hangfire.Common.Job(recurringJob.Job.Type, recurringJob.Job.Method, recurringJob.Job.Args);

                        manager.AddOrUpdate(name, job, recurringJob.Cron, jobTimeZone, recurringJob.Queue);
                    }
                }
            }
`

**Comment by nmangue** [comment]
I have tweaked @pieceofsummer code to get some state from the call stack instead of the filter context.
Here is the code I came up with:

```csharp
using System;
using System.Diagnostics;
using System.Linq;
using Hangfire.Client;
using Hangfire.Common;
using Hangfire.Server;

public class NoMissedRunsAttribute : JobFilterAttribute, IClientFilter
{
  public int MaxDelayMs { get; set; } = (int) TimeSpan.FromMinutes(1).TotalMilliseconds;

  public void OnCreating(CreatingContext filterContext)
  {
    if (filterContext.Parameters.TryGetValue("RecurringJobId", out var recurringJobId))
    {
      // the job being created looks like a recurring job instance.

      var recurringJob = filterContext.Connection.GetAllEntriesFromHash($"recurring-job:{recurringJobId}");

      if (recurringJob != null && recurringJob.TryGetValue("NextExecution", out var nextExecution))
      {
        var utcNow = DateTime.UtcNow;
    
        // the next execution time of a recurring job is updated AFTER the job instance creation,
        // so at the moment it still contains the scheduled execution time from the previous run.
        var scheduledTime = JobHelper.DeserializeDateTime(nextExecution);

        // Check if the job is created way later than expected
        // and if it was created from the scheduler.
        if (utcNow > scheduledTime.AddMilliseconds(MaxDelayMs) && IsCreatedFromRecurringJobScheduler())
        {
          filterContext.Canceled = true;
        }
      }
    }
  }

  private static bool IsCreatedFromRecurringJobScheduler()
  {
    // Get call stack
    var stackTrace = new StackTrace();
    return stackTrace.GetFrames().Any(f => f.GetMethod()?.DeclaringType == typeof(RecurringJobScheduler));
  }

  public void OnCreated(CreatedContext filterContext)
  {
    // Nothing to do.
  }
}
```

**Comment by Fungusware** [comment]
Has this been integrated, this feature to NOT run missed Jobs is essential for both of my current clients requirements.
