### ISSUE TITLE
Can't delete a job within a transaction scope

### ISSUE THREAD

**Issue by iamkoch** [HangfireIO/Hangfire#622]
Hi

As part of a migration, we have a requirement to delete some jobs. The jobs are being rescheduled with different parameters. We are also making some other changes in the same database. If any issues arrive during execution, we would like to rollback the entire transaction. 

We are using SQL Server storage. 

We have boiled down the issue to the following code: 

```
using(var t = new TransactionScope())
{
    BackgroundJob.Delete("blah");
}
```

This throws an exception 

```
The transaction associated with the current connection has completed but has not been disposed. The transaction must be disposed before the connection can be used to execute SW statements 
```

Has anyone else experienced this?

**Comment by odinserj** [comment]
Are you using `TransactionScope` in other places in your applications (explicitly or implicitly)? Looks like one of those instances aren't disposed.

Keep in mind, that `BackgroundJob.Delete` doesn't delete a job, it just moves them to the `Deleted` state. Background job may be processed, if a worker already picked up this job.

**Comment by iamkoch** [comment]
Hiya

The only place outside that scope is when I pull the scheduled jobs from the monitoring API.

In any case, changing the using statement to the following:

                    using (var trans = new TransactionScope(TransactionScopeOption.Required, TimeSpan.FromMinutes(5)))

Has fixed the issue. Bit of a strange one, but my requirement is a mixture of the monitoring API and the static BackgroundJob.

Happy to close this as I have found a solution, it's whether anyone feels this needs further investigation or not.
