### ISSUE TITLE
Can Dashboard user interface be extended? 

### ISSUE THREAD

**Issue by evaldas-raisutis** [HangfireIO/Hangfire#625]
We have been enjoying using Hangfire for adding Data Import Jobs. It would be also great to extend the user interface, in order to add additional functionality. Is there a way to extend the existing User Interface? For instance adding new tabs, pages, include additional JS files etc.

**Comment by nirinchev** [comment]
A cheap solution would be to add it as an iframe to your existing site. As far as I know, it's not easy to extend the current dashboard, unless you fork Hangfire and modify it locally.

**Comment by evaldas-raisutis** [comment]
I see. Thanks for the info :)

**Comment by odinserj** [comment]
Actually, it can be extended, and there are following extension points:

* **Routes** through the `DashboardRoutes.Routes`
* **Pages** through the `RazorGenerator` extension for Visual Studio, and `RazorPage` base class.
* **Navigation menu** items through the `NavigationMenu` class
* **Job sidebar menu** items through the `JobsSidebarMenu` class.

So you can add pages, new routes, menu items, etc. without recompiling Hangfire. Please see the source code for this classes for examples.

**Comment by maarten-kieft** [comment]
Thanks odinserj, You got me on the right path. I used this code in my startup to add a custom menu item:

 NavigationMenu.Items.Add(page => new MenuItem("Title of my menu item", "url/to/mypage")
            {
                Active = page.RequestPath.StartsWith("/url/to/my/page"),
            });

**Comment by alexandis** [comment]
And how to extend existing Dashboard pages? Let's say I want to add another button into Recurring Jobs page.
