### ISSUE TITLE
Multiple applications running same Sql Server DB, proposed SqlServerConnection change

### ISSUE THREAD

**Issue by h0lysl4y3r** [HangfireIO/Hangfire#629]
Hello,

we have multiple apps and Dashboard running under one Sql Server DB. We followed @odinserj answer in #69, when we implented a "Common" assembly with thin job classes for each app that are known to all. Then each application has a full implementation of the class with the same name (so two classes with same name but different namespaces). 

What we did then, 
- we inherited SqlServerConnection 
- overrode CreateExpiredJob and GetJobData methods to do custom de/serialization of Job
- also inherited SqlServerStorage, where we injected our own de/serializer of Job used by our SqlServerConnection

During de/serialization we then exchange types from "Common" assembly to local type with same name and vice versa. So only the app needs to know the type with full implementation. We also use separate queues for each app.

The only problem is the class SqlServerConnection, which is internal and has private _storage member, so we need to rebuild HangFire.SqlServer assembly with our changes instead of doing the changes only in our code.

Can the class SqlServerConnection be public and _storage member be protected?

**Comment by odinserj** [comment]
> * we inherited SqlServerConnection
> * overrode CreateExpiredJob and GetJobData methods to do custom de/serialization of Job
> * also inherited SqlServerStorage, where we injected our own de/serializer of Job used by our SqlServerConnection

Why did you do this?

**Comment by h0lysl4y3r** [comment]
We want to see in Dashboard types of jobs. So in our implementation Dashboard sees the types, we can requeue jobs etc. And the app (running HangFire server) can run the job, which is implemented there with the same class name as in the "Common" assembly.

**Comment by odinserj** [comment]
Please show me what types do you have in your shared assembly, and what types you have in your web applications. The solution I've proposed should work without changing Hangfire internals.

**Comment by h0lysl4y3r** [comment]
This is a sample class in shared assembly:
```
namespace Common.Jobs
{
	public class HelloWorldJobs
	{
		[Queue(QueueNames.HelloWorld)]
		public void HelloWorld(IJobCancellationToken cancellationToken)
		{
		}
	}
}
```
	
This is a sample class in app running HangFire server:
```
namespace MyApp.Jobs
{
	public class HelloWorldJobs
	{
		[Queue(QueueNames.HelloWorld)]
		public void HelloWorld(IJobCancellationToken cancellationToken)
		{
			Console.WriteLine("Hello World!");
		}
	}
}
```

This is how we configure a job in the app:	
```
var jobId = $"{typeof(Common.Jobs.HelloWorldJobs).FullName}.{nameof (Common.Jobs.HelloWorldJobs.HelloWorld)}";
RecurringJob.AddOrUpdate<Common.Jobs.HelloWorldJobs>(jobId, x => x.HelloWorld( JobCancellationToken.Null), Cron.Hourly, TimeZoneInfo.Local, QueueNames.HelloWorld);
```

Job is serialized with AssemblyQualifiedName and deserialized via Type.GetType(). We work with this behaviour as I wrote before by injecting our own de/serialization.
So after dequeueing instead of running HelloWorldJobs in Common.Jobs, the one in MyApp.Jobs is called.

**Comment by odinserj** [comment]
Your types are detached from each other, so they don't make any sense. Shared assembly should **define a shared interface**, using abstract classes or interfaces, and concrete applications should **implement this interface**. 

```csharp
// SHARED ASSEMBLY
public interface IHelloWorldJobs
{
    [Queue("shared")]
    void HelloWorld(IJobCancellationToken cancellationToken);
}

[Queue("application-b")]
public interface IShouldRunInApplicationAOnly
{
    void Method();
}

[Queue("application-b")]
public interface IShouldRunInApplicationBOnly
{
    void Method();
}
```

All job filter attributes, such as `[Queue]`, should be applied to interface methods, since Hangfire will work only using these interfaces, leaving concrete types untouched (except during the method call).

```csharp
// APPLICATION A
public class ApplicationAHelloWorldJobs : IHelloWorldJobs
{
    public void HelloWorld(IJobCancellationToken cancellationToken)
    {
        // Implementation for Application A
    }
}

public class ShouldRunInApplicationAOnly : IShouldRunInApplicationAOnly
{
    public void Method() { /* ... */ }
}

// APPLICATION B
public class ApplicationBHelloWorldJobs : IHelloWorldJobs
{
    public void HelloWorld(IJobCancellationToken cancellationToken)
    {
        // Application B implementation
    }
}

public class ShouldRunInApplicationBOnly : IShouldRunInApplicationBOnly
{
    public void Method() { /* ... */ }
}
```

Background jobs should be created **only using interfaces defined in shared assembly**. In this case, Hangfire will use only types defined in the shared assembly, and all the features will work without any references to Application A or Application B assemblies, including Dashboard UI, filters, etc.

```csharp
// Processing logic will depend on application
BackgroundJob.Enqueue<IHelloWorldJobs>(x => x.HelloWorld(JobCancellationToken.Null));

// Will be executed in instances of Application A
BackgroundJob.Enqueue<IShouldRunInApplicationAOnly>(x => x.Method());

// Will be executed in instances of Application B
BackgroundJob.Enqueue<IShouldRunInApplicationBOnly>(x => x.Method());

// AND NOT – use interface instead
BackgroundJob.Enqueue<ApplicationBHelloWorldJobs>(/* ... */);
```

Concrete implementation should be wired by an IoC container. Implementations make sense only when Hangfire is about to call the target method. Before making a call, it creates an instance of the defined type (interface, in our case, such as `IHelloWorldJobs`) by calling the configured job activator. For example, configuration with Hangfire.Autofac will look like this:

```csharp
var builder = new ContainerBuilder();
// Call these lines in Application A only
builder.Register<ApplicationAHelloWorldJobs>().As<IHelloWorldJobs>();
builder.Register<ShouldRunInApplicationAOnly>().As<IShouldRunInApplicationAOnly>();
// Call these lines in Application B only
builder.Register<ApplicationBHelloWorldJobs>().As<IHelloWorldJobs>();
builder.Register<ShouldRunInApplicationBOnly>().As<IShouldRunInApplicationBOnly>();

GlobalConfiguration.Configuration.UseAutofacActivator(builder.Build());
```

In this case, `Activator.Resolve(typeof(IHelloWorldJobs))` will return an instance of `ApplicationAHelloWorldJobs` or `ApplicationBHelloWorldJobs` class, depending on registrations, and application.

**Comment by h0lysl4y3r** [comment]
You're right, thank you. This is the way, we can run multiple apps. 
Btw. your last comment would be a great part of HangFire documentation.
