### ISSUE TITLE
Dashboard broken

### ISSUE THREAD

**Issue by Jojoshua** [HangfireIO/Hangfire#630]
Just upgraded from 1.5.9 to 1.6.1 and the dashboard just shows some header labels and the browser console shows script error. 

Script438:object doesn't support property or method 'addEventListener' 
File:js161 line 2, column 29759

**Comment by odinserj** [comment]
What is your browser/version? Have you tried to refresh the page?

**Comment by Jojoshua** [comment]
Ie 11. I did try to refresh and clear cache but did not help. I reverted back to 1.5.9 and works again.

**Comment by Jojoshua** [comment]
Fyi I am using sql server storage

**Comment by teamwoot** [comment]
Interesting.  The dashboard is broken for me also on IE 11, but works find in Google Chrome.

**Comment by odinserj** [comment]
Tried to reproduce this on my machine with IE11, but failed – all pages are working fine with no console messages at all. Any details, i.e. which page causes this error, and under what circumstances?

**Comment by Jojoshua** [comment]
Did you go from 1.5.9 to 1.6.1 and were you using sql server storage?

**Comment by odinserj** [comment]
The following line says that the problem is caused by javascript file in Hangfire 1.6.1, version 1.5.9 is unrelated here.

```
File:js161 line 2, column 29759
```

**Comment by odinserj** [comment]
What dashboard page throws this error?

**Comment by Jojoshua** [comment]
All pages were broken. The initial page and any links. It showed the Hangfire Dashboard at the top and the header for real time graph, history graph but nothing inside.

**Comment by odinserj** [comment]
Would you like to debug this in Internet Explorer developer tools to see what line in Hangfire is causing this exception?

To do this, open the developer tools by pressing F12 first, then go to the *Debugger* tab, and open the `js161` file as shown below.

![image](https://cloud.githubusercontent.com/assets/1078718/17403027/a8ce9c96-5a5e-11e6-970b-582a9e337755.png)

After opening a file, scroll it to the end and set the breakpoint as shown below. Don't be afraid of minimized code – it is completely unneeded, we need just to learn what Hangfire's line of code causes this exception, and it is not minimized at all.

![image](https://cloud.githubusercontent.com/assets/1078718/17403117/fcd0515e-5a5e-11e6-823b-3d9604827b7b.png)

**Comment by Jojoshua** [comment]
Ok here's the deal. It works on localhost but after publishing to server it breaks. The javascript debug stops at n.ready.promise js161(2,29759)
The error is object does not support property or method 'addEventListener'. Looks like you have code for addEventListener("load", I,!1). Does that help?

**Comment by Jojoshua** [comment]
From your screen shot it looks like your code is not minimized.... Mine is though.

**Comment by odinserj** [comment]
The file contains many different javascript files, they are concatenated. Some of them minimized, but the Hangfire's (originally `hangfire.js`) is not, and it is the latest script. We need to investigate what line in `hangfire.js` causes this behavior, skipping all the other scripts. So just scroll the script to the bottom, and ignore all the minimized lines.

**Comment by Jojoshua** [comment]
Turn on pretty print in the ie11 debugger and it is line 941

**Comment by odinserj** [comment]
> The error is object does not support property or method 'addEventListener'. Looks like you have code for addEventListener("load", I,!1). Does that help?

Still don't know what to do to remove the error. And you?

**Comment by Jojoshua** [comment]
This is an intranet site and ie11 defaults a compatibility mode. I read ie11 does not support addEventListener. Maybe try adding a meta tag http-equiv to x-ua-compatible content = ie=edge

**Comment by odinserj** [comment]
Added, will be shipped with 1.6.2 soon, thanks for the investigation!

**Comment by karol1990** [comment]
Guys,

The commit done to solve this problem doesn't solve it for IE8. The problem still does exists: 
Object doesn't support property or method 'addEventListener'. The version of hangfire I do use is 1.6.8 with SqlServer as store.
