### ISSUE TITLE
Can't see jobs details screen (any job)

### ISSUE THREAD

**Issue by guillaumeroy1** [HangfireIO/Hangfire#633]
Hangfire/Hangfire.Core 1.6.1
Hangfire.Pro/Hangfire.Pro.Redis 1.4.5
.NET 4.6.1

Stack : 

The given key was not present in the dictionary.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

```
[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +13763207
   Hangfire.Redis.<>c__DisplayClass22_0.<JobDetails>b__0(IRedisClient redis) +1095
   Hangfire.Redis.RedisMonitoringApi.UseConnection(Func`2 action) +51
   Hangfire.Dashboard.Pages.JobDetailsPage.Execute() +198
   Hangfire.Dashboard.RazorPage.TransformText(String body) +31
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +86
   Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +622
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +462
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +203
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +193
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +96
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +363
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137
```

**Comment by odinserj** [comment]
Can you please show me the output of the following commands executed against the background job identifier that causes the error:

```
hgetall hangfire:job:<jobid>
lrange hangfire:job:<jobid>:history 0 -1
```

**Comment by guillaumeroy1** [comment]
Here's the information in redis :

**hgetall hangfire:job:<jobid>**
 1) "RetryCount"
 2) "3"
 3) "State"
 4) "Failed"
 5) "Method"
 6) "Execute"
 7) "CurrentCulture"
 8) "\"en-US\""
 9) "Type"
10) "Avengers.Auditing.Activities.Handlers.HandleSlackEventJob, Avengers.Auditing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
11) "ParameterTypes"
12) "[\"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\"]"
13) "CurrentUICulture"
14) "\"en-US\""
15) "CreatedAt"
16) "2016-08-04T00:14:39.2436804Z"
17) "Arguments"
18) "[\"\\\"DEFAULT\\\"\",\"\\\"251932407580..T03TLTNDW\\\"\"]"

**lrange hangfire:job:<jobid>:history 0 -1**

avengersdev.redis.cache.windows.net:6379[1]> lrange hangfire:job:9bbd7ca9-365f-4803-bb78-517039384c0b:history 0 -1
 1) "{\"failedAt\":\"2016-08-04T00:20:21.1444199Z\",\"exceptionType\":\"System.InvalidOperationException\",\"exceptionMessage\":\"Slack id must be provided.\",\"exceptionDetails\":\"System.InvalidOperationException: ...\",\"state\":\"Failed\",\"reason\":\"An exception occurred during performance of the job.\",\"createdAt\":\"2016-08-04T00:20:21.2381302Z\"}"
 2) "{\"startedAt\":\"2016-08-04T00:20:20.7381695Z\",\"serverId\":\"rd000d3a60327a:84:44aa633d-5583-4ebd-b817-86790b3883f8\",\"workerId\":\"61c1f69a-4e3e-4581-a611-00590531b8de\",\"state\":\"Processing\",\"reason\":null,\"createdAt\":\"2016-08-04T00:20:20.8006703Z\"}"
 3) "{\"enqueuedAt\":\"2016-08-04T00:20:20.6131856Z\",\"queue\":\"default\",\"state\":\"Enqueued\",\"reason\":\"Triggered by DelayedJobScheduler\",\"createdAt\":\"2016-08-04T00:20:20.6912960Z\"}"
 4) "{\"enqueueAt\":\"2016-08-04T00:20:13.1219551Z\",\"scheduledAt\":\"2016-08-04T00:18:21.1219551Z\",\"state\":\"Scheduled\",\"reason\":\"Retry attempt 3 of 3: Slack id must be provided.\",\"createdAt\":\"2016-08-04T00:18:21.1375540Z\"}"
 5) "{\"failedAt\":\"2016-08-04T00:18:21.0282062Z\",\"exceptionType\":\"System.InvalidOperationException\",\"exceptionMessage\":\"Slack....\",\"exceptionDetails\":\"System.InvalidOperationException: ...\",\"state\":\"Failed\",\"reason\":\"An exception occurred during performance of the job.\",\"createdAt\":\"2016-08-04T00:18:21.1219551Z\"}"
 6) "{\"startedAt\":\"2016-08-04T00:18:20.6063368Z\",\"serverId\":\"rd000d3a60327a:84:44aa633d-5583-4ebd-b817-86790b3883f8\",\"workerId\":\"505fff69-45c1-425a-9060-53352f8700b1\",\"state\":\"Processing\",\"reason\":null,\"createdAt\":\"2016-08-04T00:18:20.6688360Z\"}"
 7) "{\"enqueuedAt\":\"2016-08-04T00:18:20.4813376Z\",\"queue\":\"default\",\"state\":\"Enqueued\",\"reason\":\"Triggered by DelayedJobScheduler\",\"createdAt\":\"2016-08-04T00:18:20.5594631Z\"}"
 8) "{\"enqueueAt\":\"2016-08-04T00:18:09.2070987Z\",\"scheduledAt\":\"2016-08-04T00:16:57.2070987Z\",\"state\":\"Scheduled\",\"reason\":\"Retry attempt 2 of 3: Slack id must be provided.\",\"createdAt\":\"2016-08-04T00:16:57.2383479Z\"}"
 9) "{\"failedAt\":\"2016-08-04T00:16:57.1133425Z\",\"exceptionType\":\"System.InvalidOperationException\",\"exceptionMessage\":\"Slack id must be provided.\",\"exceptionDetails\":\"System.InvalidOperationException: ...\",\"state\":\"Failed\",\"reason\":\"An exception occurred during performance of the job.\",\"createdAt\":\"2016-08-04T00:16:57.2070987Z\"}"
10) "{\"startedAt\":\"2016-08-04T00:16:56.6758813Z\",\"serverId\":\"rd000d3a60327a:84:44aa633d-5583-4ebd-b817-86790b3883f8\",\"workerId\":\"afdfccd3-00c2-4887-91c3-cd18874b929a\",\"state\":\"Processing\",\"reason\":null,\"createdAt\":\"2016-08-04T00:16:56.7539735Z\"}"
11) "{\"enqueuedAt\":\"2016-08-04T00:16:01.6387136Z\",\"queue\":\"default\",\"state\":\"Enqueued\",\"reason\":\"Triggered by DelayedJobScheduler\",\"createdAt\":\"2016-08-04T00:16:01.7168316Z\"}"
12) "{\"enqueueAt\":\"2016-08-04T00:15:28.1941438Z\",\"scheduledAt\":\"2016-08-04T00:14:54.1941438Z\",\"state\":\"Scheduled\",\"reason\":\"Retry attempt 1 of 3: Slack id must be provided.\",\"createdAt\":\"2016-08-04T00:14:54.2253785Z\"}"
13) "{\"failedAt\":\"2016-08-04T00:14:54.1012800Z\",\"exceptionType\":\"System.InvalidOperationException\",\"exceptionMessage\":\".....\",\"exceptionDetails\":\"System.InvalidOperationException: ...\",\"state\":\"Failed\",\"reason\":\"An exception occurred during performance of the job.\",\"createdAt\":\"2016-08-04T00:14:54.1941438Z\"}"
14) "{\"startedAt\":\"2016-08-04T00:14:53.6472622Z\",\"serverId\":\"rd000d3a60327a:84:44aa633d-5583-4ebd-b817-86790b3883f8\",\"workerId\":\"40ad2640-3204-4c86-934b-fa98c665ef86\",\"state\":\"Processing\",\"reason\":null,\"createdAt\":\"2016-08-04T00:14:53.7253901Z\"}"
15) "{\"enqueuedAt\":\"2016-08-04T00:14:39.2436804Z\",\"queue\":\"default\",\"state\":\"Enqueued\",\"reason\":null,\"createdAt\":\"2016-08-04T00:14:39.2593037Z\"}"

**Comment by odinserj** [comment]
All the properties in history entries are camel-cased. Did you change the serialization options recently?

**Comment by guillaumeroy1** [comment]
We are using the CamelCase serializer as the base serializer in all the application. 

I've tried to do that in my Hangfire configuration but it's not working:
 
            var settings = new JsonSerializerSettings();
            JobHelper.SetSerializerSettings(settings);

**Comment by odinserj** [comment]
Hi @guillaumeroy1, this bug was fixed in just release [Hangfire.Pro 1.4.7](https://github.com/HangfireIO/Hangfire.Pro/releases/tag/v1.4.7) and [Hangfire.Pro.Redis 2.0.1](https://github.com/HangfireIO/Hangfire.Pro.Redis/releases/tag/v2.0.1). Thanks for reporting this!

**Comment by guillaumeroy1** [comment]
Thanks, it's working now!

--
Sent from my phone




On Thu, Aug 11, 2016 at 10:54 AM -0400, "Sergey Odinokov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @guillaumeroy1<https://github.com/guillaumeroy1>, this bug was fixed in just release Hangfire.Pro 1.4.7<https://github.com/HangfireIO/Hangfire.Pro/releases/tag/v1.4.7> and Hangfire.Pro.Redis 2.0.1<https://github.com/HangfireIO/Hangfire.Pro.Redis/releases/tag/v2.0.1>. Thanks for reporting this!

-
