### ISSUE TITLE
Incorrect status code when auth filter denies access

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#638]
Current implementation of authorization filters returns HTTP 401 when access should be denied, which I'm pretty sure is an incorrect behavior. And [it's not just me](http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses).

The problem with incorrect status code is, when `IDashboardAuthorizationFilter` returns `false` (for example, because of the insufficient rights) for the *valid* and *authenticated* user, responding with `401 Unauthorized` would make HTTP stack automatically redirect to the login page, regardless of the user is already logged in. On the contrary, returning `403 Forbidden` will just display a page saying you're not allowed to access this resource. That's it.

You may even consider returning 401 or 403, depending on whether the user is authenticated.

P.S. The interesting fact is, ASP.NET's legacy `AuthorizeAttribute` also returns 401 for already authenticated users, but it does so for historical reason.

**Comment by pieceofsummer** [comment]
I think the correct implementation should be something like this:

```c#
if (!filter.Authorize(context))
{
    if (httpContext.Authentication.GetAuthenticationSchemes().Any())
    {
        // There's at least one authentication scheme enabled for this server
        // Issue an authentication challenge and allow it to do all the magic
                    
        return httpContext.Authentication.ChallengeAsync(new AuthenticationProperties()
        {
            // provide it with url to redirect back after successful authentication
            RedirectUri = UriHelper.BuildRelative(httpContext.Request.PathBase,
                                                  httpContext.Request.Path,
                                                  httpContext.Request.QueryString)
        });
    }
    else
    {
        // No authentication schemes available for this server,
        // so we fallback to a plain '403 Forbidden' response.
        // It still may be handled by the upstream middleware, like 
        // Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware

        httpContext.Response.StatusCode = 403;
        return httpContext.Response.WriteAsync("403 Forbidden");
    }
}
```

**Comment by odinserj** [comment]
Totally agree with you, thanks for the PR, I'll make a review in a couple of days!

**Comment by odinserj** [comment]
Moving to the 1.6.5 milestone, because the current implementation sometimes lead to infinite redirects. Will review the referenced PR tomorrow.

**Comment by odinserj** [comment]
@pieceofsummer, what if just return a `403 Forbidden` status code instead of 401. We can also leave a response untouched at all, if status code was already set. This will allow authorization filters to set a whatever response it wants (please see https://github.com/HangfireIO/Hangfire/commit/d0f37a3ebaccdb9fabf377c557451fbb7185197e for example implementation). What do you think?

**Comment by pieceofsummer** [comment]
That probably would work too (cannot check it at the moment), but you should at least remove writing text status, because it might mess with authorization filter, and **will** definitely mess with custom error pages filter (which won't return custom page because there's body content already present).

**Comment by pieceofsummer** [comment]
Just had a chance to test it, and it never gets you to authorization page, just returns `403 Forbidden`.

**Comment by odinserj** [comment]
@pieceofsummer, mmm? Looks like the most obvious and ideal solution to prevent confusion and infinite redirect loops without any complicated logic. 

```csharp
if (!filter.Authorize(context))
{
    httpContext.Response.StatusCode = httpContext.User.Identity.IsAuthenticated
        ? (int) HttpStatusCode.Forbidden
        : (int) HttpStatusCode.Unauthorized;

    return Task.FromResult(0);
}
```

**Comment by pieceofsummer** [comment]
It sure is the simplest one, but it won't preserve original url, so the user won't be redirected back to Hangfire dashboard after authentication. Should decide if we can live with that :)

**Comment by odinserj** [comment]
But Hangfire doesn't redirect to the login page also, we are just setting the status code. And why the middleware that redirects a user to the login page doesn't preserve the original URL? Let's leave it to the conscience of the authentication middleware!

**Comment by pieceofsummer** [comment]
Oh, I think I'm wrong, or they have fixed something in authorization package since the last time I tested it. I think we can close the issue now.

**Comment by odinserj** [comment]
Yeah, the 1.6.5 milestone is completed! :tada:
