### ISSUE TITLE
Authorization with dynamic roles, and tenants

### ISSUE THREAD

**Issue by papyr** [HangfireIO/Hangfire#639]
Hi, since this can support a SAAS app, we have scenarios where Company A's mgrs and employees, should be isolated from Company B's mgrs and employees (their own tasks and schedules). Can you please update the sample to show how to edit the roles in the GUI, the current dashboards or sample does not show this.

thanks

**Comment by odinserj** [comment]
Roles, users, claims and other aspects of authorization are totally out of scope of Hangfire – they are different in each application. You should tell Hangfire about your authorization rules manually in code, by using authorization filters. For more information, please see the [Configuring Authorization](http://docs.hangfire.io/en/latest/configuration/using-dashboard.html#configuring-authorization) article.
