### ISSUE TITLE
TransformText crashes on particular string

### ISSUE THREAD

**Issue by copperdogma** [HangfireIO/Hangfire#640]
This was the minimal version I could find that will crash the regex parser. This is the contents of Hangfire.State's Data field:

```
{
	"FailedAt": "2016-08-02T20:08:18.4048142Z",
	"ExceptionType": "Exception Type Here",
	"ExceptionMessage": "Exception Message Here",
	"ExceptionDetails": "at two.three() one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen 12345678901234567890123456789012345678901234567890"
}
```

I found it when it crashed on a particular set of data I was logging into ExceptionDetails. Took forever to winnow it down to the exact pattern that crashes the regex parser.

**Comment by odinserj** [comment]
This bug was fixed in [Hangfire 1.6.2](https://github.com/HangfireIO/Hangfire/releases/tag/v1.6.2) that is already released. Thanks for reporting!
