### ISSUE TITLE
Updating to 1.6.2 causes JobStorage.Current error

### ISSUE THREAD

**Issue by Yelnik** [HangfireIO/Hangfire#641]
As per the documentation here: http://docs.hangfire.io/en/latest/tutorials/highlight.html#id9

Error: 

> JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.

to set the server storage property we do `GlobalConfiguration.Configuration.UseSqlServerStorage("HighlighterDb");
    app.UseHangfireDashboard();
    app.UseHangfireServer();`

And as per my code:

`GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireDB");
                _backgroundJobServer = new BackgroundJobServer();`

Why do I get this error now? Did this update require arbitrarily setting this property 2 times?

**Comment by Yelnik** [comment]
This error is actually related to SQL Server itself being unresponsive/not running. The error generated in this situation used to reflect that, that Hangfire could not connect to the server. Now when there is an SQL server issue this is the error produced, which seems incorrect.

**Comment by odinserj** [comment]
The `Configuration` method has a wrong name (`Configure`), in this case job storage was not configured, and caused this exception. When there are problems with SQL Server, other exceptions are thrown.

**Comment by PeteCJohnson** [comment]
We've just started seeing this on 1.6.8.0. Is this related to SQL Server responsiveness as @ghost stated?
