### ISSUE TITLE
Azure ServiceBus Integration not working for .NET Core 5.0

### ISSUE THREAD

**Issue by philcarbone** [HangfireIO/Hangfire#642]
Can't get the ServiceBus Integration to work with .NET Core 5.0.

**Comment by odinserj** [comment]
Is the `WindowsAzure.ServiceBus` package compatible with .NET Core itself?

**Comment by odinserj** [comment]
.NET Core version for the package is not available: https://www.nuget.org/packages/WindowsAzure.ServiceBus/
