### ISSUE TITLE
hangfire:EnableRemoteMonitorAccess in ASP.NET Core

### ISSUE THREAD

**Issue by yetanotherchris** [HangfireIO/Hangfire#645]
Hello,

Awesome framework, and thanks for making it .NET Core friendly so quickly.

How can I enable the `"hangfire:EnableRemoteMonitorAccess"=true` setting in Hangfire hosted inside ASP.NET Core? I've tried both the legacy web.config way, and also in appsettings.json without any luck.

**Comment by pieceofsummer** [comment]
I believe this doesn't apply to any recent versions, and you should use authorization filters instead.

**Comment by yetanotherchris** [comment]
Thanks, that answered it for me
