### ISSUE TITLE
Retry attempt 1 of 10: No service for type 'CustomInferface' ASP CORE

### ISSUE THREAD

**Issue by cvanherk** [HangfireIO/Hangfire#655]
When using reflection to lookup for classes and instantiate with a type of interface, hangfire gives a error "No service for type 'CustomInferface'".
I'm using this code:

var recurringJobs = typeof(CustomInterface)
                .GetTypeInfo()
                .Assembly
                .GetTypes()
                .Where(x=>x.GetInterfaces().Contains(typeof(CustomInterface)))
                .Select(x=>(CustomInterface)Activator.CreateInstance(x));

            foreach (var instance in recurringJobs)
            {
                Hangfire.RecurringJob.AddOrUpdate<CustomInterface>(x => x.Execute(), instance.Cron());
            }

The task will go instantly to the retry tab.

**Comment by cvanherk** [comment]
forgot  config.UseDefaultActivator(); in the startup

**Comment by odinserj** [comment]
Or you can register the `CustomInferface` type :wink: 

```csharp
services.AddTransient<CustomInterface>();
```
