### ISSUE TITLE
Prolong expiration time of succeeded jobs

### ISSUE THREAD

**Issue by hahmed** [HangfireIO/Hangfire#66]
How long do jobs remain in the UI? They appear to be cleared out from the database quite quickly.

Would be cool if the duration was something like 7 days at least... The way I see it is, I would want to view all succeeded jobs even after a few days to make sure it did actually run esp. if someone has asked my if my email was sent out, or were the graphs updated etc.

**Comment by masterxml** [comment]
I'm using Hangfire as my backgroud job framework, I want to keep successed job more longer than 1 day.
It's good to know I can change the JobExpirationTimeout.
But I don't know where and how to change the ApplyStateContext.
Can anyone give me a point?

**Comment by masterxml** [comment]
I find the answer in here:
http://discuss.hangfire.io/t/succeeded-jobs-deleted/341/2?u=masterxml
