### ISSUE TITLE
EasyLOB, an Archetype for LOB Applications

### ISSUE THREAD

**Issue by EasyLOB** [HangfireIO/Hangfire#661]
Thanks for creating Hangfire!
I just published EasyLOB, an Open Source Archetype for building ASP.NET MVC LOB Application, at GitHub:

https://github.com/EasyLOB/EasyLOB/wiki

Hangfire is the application I recommend process Jobs with EasyLOB:

https://github.com/EasyLOB/EasyLOB/wiki/EasyLOB-Layers-Service

**Comment by odinserj** [comment]
Glad to hear that application frameworks begin to use Hangfire as a default background job processing system! And good luck with your project :four_leaf_clover:!
