### ISSUE TITLE
InvalidOperationException: Collection was modified in filter construction

### ISSUE THREAD

**Issue by wewebber** [HangfireIO/Hangfire#663]
We occasionally receive an exception with the message "System.InvalidationOperationException: Collection was modified; enumeration operation may not execute" and a stack trace like the following:

![image](https://cloud.githubusercontent.com/assets/6174028/18374110/57490cf8-768d-11e6-92de-0be29ee8912c.png)

The last call in our code is IBackgrounJobClient.Enqueue(Action<T>).  Based on the stack trace, it looks like something (not us, AFAICT) is modifying the list of filters while RemoveDuplicates() is being called on it.  This exception is not reliably reproducible.  The calling context is an ASP.NET application.  We're using Hangfire.Pro 1.4.7 with Hangfire.Core 1.6.2.

**Comment by odinserj** [comment]
@wewebber, where do you call the `UseBatches` configuration method? Is it possible that it may be called during the execution of your application (e.g. not during the startup)?

**Comment by wewebber** [comment]
@odinserj, we have one worker-hosting server process per machine (and several machines).  The error occurs (very intermittently) when a worker task within a server is submitting jobs for other workers to perform.  On startup, the server process does the calls (removing extraneous details, but in this order):

            Hangfire.GlobalConfiguration.Configuration.UseAutofacActivator(container);

            /* ... */

            RedisStorageOptions redisStorageOptions = new RedisStorageOptions()
            {
                InvisibilityTimeout = TimeSpan.FromMinutes(120)
            };
            Hangfire.GlobalConfiguration.Configuration.UseBatches();
            Hangfire.GlobalConfiguration.Configuration.UseRedisMetrics();
            Hangfire.GlobalConfiguration.Configuration.UseRedisStorage($"{hangfireRedisConnection},defaultDatabase={hangfireDbNum}", redisStorageOptions);

            /* ... */

            var options = new BackgroundJobServerOptions
            {
                // number of threads to run in parallel
                WorkerCount = maxCoresToRunInParallel,
                Queues = new[] { TaskPriority.High.ToString().ToLower(), TaskPriority.AboveNormal.ToString().ToLower(), TaskPriority.Default.ToString().ToLower(), TaskPriority.BelowNormal.ToString().ToLower(), TaskPriority.Idle.ToString().ToLower() }
            };

            using (var server = new BackgroundJobServer(options))
            {
                while (!this.shutdownRequested)
                {
                    Thread.Sleep(500);
                }
            }

There are no other calls to UseBatches() or any other GlobalConfiguration methods on the server.

There is also a WebUI machine that hosts the dashboards and submits jobs to the Hangfire queue.   It has a similar startup sequence and only calls UseBatches() once on startup.  We don't observe this error in the UI.

**Comment by odinserj** [comment]
The collection of filters is being modified during the background processing, and this is very strange, since the filters code is untouched for approximately 2 years, and this is the first issue. Please ensure first that it is not modified from your application's code:

* Make sure you're not registering a custom `IJobFilterProvider` throught the `JobFilterProviders` class. If so, that is the primary suspect.
* Look for all usages of `GlobalJobFilters` class in your code. Any modification to this collection should only be reached from `Application_Start` in `Global.asax` or the `Startup` class.

**Comment by wewebber** [comment]
Bingo, that looks like it!  Yes, there is some code that could modify the GlobalJobFilters in one thread while a job was being run in another.  Will rectify; thanks!
