### ISSUE TITLE
Internationalization of the dashboard

### ISSUE THREAD

**Issue by fredgate** [HangfireIO/Hangfire#664]
I would want that dashboard can be displayed according to the culture of the user.
In our application all URLs are prefixed by the language to display, like :

```
/en-US/register
/en-GB/orders/12
/fr-FR/account
...
```

We have a filter that set the culture of the thread processing the request according to the URL.
Would it be possible to have a URL of this form for the dashboard : /{culture}/hangfire ?

**Comment by Elph** [comment]
The dashboard will use the culture set on the thread so you're OK for that. The URL thing, I'm not so sure, probably doing some URL rewriting you can achieve that.

Anyway, if I'm not wrong, only English and Spanish are supported as a language for the dashboard, but you can implement yourself any other language you want (and contribute with them 😄 )

**Comment by odinserj** [comment]
So you are asking how to plug in the dashboard using a "dynamic" path like `/{culture}/hangfire`. For ASP.NET Core, you can just plug in the `AspNetCoreDashboardMiddleware` in a way you like. For OWIN you should play with the `IAppBuilder.Map` method, [here is an example](https://github.com/HangfireIO/Hangfire/blob/d92287faf2795e751faca818ffa7cd92b3a12b69/src/Hangfire.Core/AppBuilderExtensions.cs#L406). But this is completely out of topic, please Google how to map middleware to different paths.

One note, localized dashboards will appear only in 1.6.5, there was a bug that prevented resources to be copied to the NuGet package.
