### ISSUE TITLE
Hangfire suddenly stops processing recurring job

### ISSUE THREAD

**Issue by stormforce133** [HangfireIO/Hangfire#667]
Hi!
I have a Hangfire server with a recurring job every minute. But from time to time (every several days) it suddenly stops processing the job, and when I enter the dashboard it resumes the execution.
Another thing is that the relative times dislpayed (ie Last execution and Last execution) are not in time. Example: For a recurring job with * * * * it shows me Last execution 4 minutes ago, and the Next executions says 3 minutes ago.
The time is in UTC, maybe that has something to do.
Thanks in advance!
![handerror](https://cloud.githubusercontent.com/assets/2200353/18473317/a57484fe-7992-11e6-813a-ca7b887ed7d5.PNG)

**Comment by odinserj** [comment]
Are you processing background jobs in a web application? If yes, have you enabled its auto-start as [written here](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html)?

**Comment by stormforce133** [comment]
My bad, sorry. I was missing the Global applicationHost.config changes. Thanks for your aswer!
