### ISSUE TITLE
Log4Net stop working after Hangfire started

### ISSUE THREAD

**Issue by timurabdurafeev** [HangfireIO/Hangfire#671]
I starting hangfire server             

```csharp
Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(Constants.ConnectionString, new SqlServerStorageOptions
{
    PrepareSchemaIfNecessary = false,
    QueuePollInterval = TimeSpan.FromSeconds(15)
});
app.UseHangfireDashboard();
```

after that log4net stop writing logs

**Comment by odinserj** [comment]
Wasn't able to reproduce. Can you create a GitHub repository that reproduces the problem?

**Comment by timurabdurafeev** [comment]
https://github.com/timurabdurafeev/HangfireLog4netConflict

1. open Startup.cs and remove/comment 
` GlobalConfiguration.Configuration.UseSqlServerStorage("Data Source=(local);Initial Catalog=HangfireStuff;Integrated Security=True;");
            app.UseHangfireDashboard();
            app.UseHangfireServer();`

2. run web app 
3. make sure that 

_debug.log
_error.log
_info.log

has been created

4. remove newly created log files 
5. return back code lines which starting "hangfire" server
6. run web app again
7. check log files again - nothing is created

**Comment by odinserj** [comment]
Thanks for the repository, I was able to reproduce the issue. I removed the `[assembly: log4net.Config.XmlConfigurator(Watch = true)]` attribute and called `XmlConfigurator.Configure();` before initialising Hangfire, and everything is working now. Here are the xmldocs for `XmlConfiguratorAttribute` class that explain everything:

> Log4net will only look for assembly level configuration attributes once. When using the log4net assembly level attributes to control the configuration of log4net you must ensure that the first call to any of the log4net.Core.LoggerManager methods is made from the assembly with the configuration attributes.
>
> If you cannot guarantee the order in which log4net calls will be made from different assemblies you must use programmatic configuration instead, i.e. call the XmlConfigurator.Configure() method directly.

**Comment by timurabdurafeev** [comment]
It works me as well, thank you

**Comment by smann004** [comment]
I am happy to find a solution to my issue. I had started testing hangfire before timurabdurafeev posted his question. It looked really impressive however it caused log4net to stop working. I should have posted my question! Thanks for the question and answer.

**Comment by sunitakawale** [comment]
Thanks for sharing the information. Worked well for me.
