### ISSUE TITLE
RecurringJob.AddOrUpdate Exception: CRON expression is invalid. Please see the inner exception for details 

### ISSUE THREAD

**Issue by jrt324** [HangfireIO/Hangfire#672]
Ran code:
`RecurringJob.AddOrUpdate(() => Console.Write("Powerful!"), "0 12 * */2");`
always show exception CRON expression is invalid. Please see the inner exception for details.

**Comment by odinserj** [comment]
There should be 5 parts in a CRON string: https://github.com/atifaziz/NCrontab/wiki/Crontab-Examples
