### ISSUE TITLE
Error Page Recurring Jobs: An item with the same key is added.

### ISSUE THREAD

**Issue by faroca** [HangfireIO/Hangfire#678]
[ArgumentException: Ya se agregó un elemento con la misma clave.]
   System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) +56
   System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) +13737545
   System.Linq.Enumerable.ToDictionary(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) +278
   System.Linq.Enumerable.ToDictionary(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector) +70
   Hangfire.MySql.src.<>c__DisplayClass2a.<GetAllEntriesFromHash>b__27(ITable`1 table) +963
   Hangfire.MySql.src.<>c__DisplayClass4`2.<UsingTable>b__3(DataConnection db) +183
   Hangfire.MySql.Common.ShortConnectingDatabaseActor.Invoke(Func`2 func) +154
   Hangfire.MySql.src.DatabaseActor.UsingDatabase(Func`2 func) +157
   Hangfire.MySql.src.DatabaseActor.UsingTable(Func`2 action) +315
   Hangfire.MySql.src.MySqlStorageConnection.GetAllEntriesFromHash(String key) +178
   Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobDtos(IStorageConnection connection, IEnumerable`1 ids) +326
   Hangfire.Dashboard.Pages.RecurringJobsPage.Execute() +475
   Hangfire.Dashboard.RazorPage.TransformText(String body) +31
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +86
   Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +468
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +462
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +203
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +774
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +203
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +193
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +96
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +363
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137
![image](https://cloud.githubusercontent.com/assets/5476189/18870754/7669bdfc-84b2-11e6-9478-3816f06a917e.png)

**Comment by MaksimSimkin** [comment]
From stacktrace you can see, that error is coming from MySqlExtension.  Try to post an issue there.
 https://github.com/chrislove/Hangfire.MySql
