### ISSUE TITLE
1.6.5 BackgroundJob.Enqueue no longer functional

### ISSUE THREAD

**Issue by Yelnik** [HangfireIO/Hangfire#679]
You guys release some of the worst updates I have ever seen!

**Comment by odinserj** [comment]
Could you elaborate more what's happened (i.e. exception, message, screenshots, just more details) and what storage are you using?

**Comment by Yelnik** [comment]
Nothing happens. Literally nothing.

even BackgroundJob.Enqueue(() => System.Console.WriteLine("sgfueoh")); produces no output.

By literally nothing happens, I mean no exceptions, no message, no details. Nothing.

The server is configured by: GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireDB");

**Comment by Yelnik** [comment]
Could you not have just, you know, tested it ONCE before releasing it?

**Comment by odinserj** [comment]
Just tried to reproduce the issue, everything is working fine.

```csharp
namespace ConsoleApplication50
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseHangfireServer();
            app.UseHangfireDashboard("");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            GlobalConfiguration.Configuration
                .UseSqlServerStorage(@"Server=.\sqlexpress;database=issue679;integrated security=true");

            BackgroundJob.Enqueue(() => Console.WriteLine("Hello, World!"));

            using (WebApp.Start<Startup>("http://localhost:12345"))
            {
                Console.ReadLine();
            }
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/1078718/18914773/294b8092-8597-11e6-9495-6348d6dcddd9.png)

![image](https://cloud.githubusercontent.com/assets/1078718/18914802/41928e70-8597-11e6-9f5f-fd3fd60ed2c7.png)

Would you like to share a repository on GitHub that reproduces the issue? Have you tried to enable the logging, at least to the Console.Out:

```csharp
GlobalConfiguration.Configuration
    .UseColouredConsoleLogProvider()
    .UseSqlServerStorage(@"Server=.\sqlexpress;database=issue679;integrated security=true");
```

**Comment by Yelnik** [comment]
You might want to create a new project, download 1.6.5 with Nuget and try that again, because it will not work.

I just downgrade to 1.6.1, rebuild and run and everything works like it's supposed to.

**Comment by Yelnik** [comment]
Even better, create a new project, download 1.6.1 with Nuget, build and run the example, then update to 1.6.5, run, and you will see the issue then.

**Comment by odinserj** [comment]
> You might want to create a new project, download 1.6.5 with Nuget and try that again, because it will not work.

I've already did this, as you can see in my previous commit, but wasn't able to reproduce the issue. There's something different in your environment, and I need to know what is it to help you to resolve the issue. 

> Even better, create a new project, download 1.6.1 with Nuget, build and run the example, then update to 1.6.5, run, and you will see the issue then.

I've also just updated Hangfire.Highlighter sample from 1.6.1 to 1.6.5 to reproduce the issue, it's working fine too – http://highlighter.hangfire.io.

I'm here and I'm ready to help, but I can't do that without your involvement. Have you tried to set up the logging, it may help to reveal exceptions happening in the background:

```csharp
GlobalConfiguration.Configuration
    .UseColouredConsoleLogProvider()
    .UseSqlServerStorage(@"Server=.\sqlexpress;database=issue679;integrated security=true");
```

**Comment by Yelnik** [comment]
In `Startup.cs`, if I do

`     public void Configuration(IAppBuilder app) {
            ConfigureAuth(app);
            BackgroundJob.Enqueue(() => NetComms.NetworkThings.StartListening());
      }
`
and in `Application_Start()` in `Global.asax.cs` I do:

`            GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireDB");
            _backgroundJobServer = new BackgroundJobServer();`

It seems to work then with 1.6.5

**Comment by odinserj** [comment]
Could you tell me what was your previous setup?

**Comment by Yelnik** [comment]
I had the server configuration right above the BackgroundJob.Enqueue, inside `Configuration()`

**Comment by odinserj** [comment]
That should work too, and that works in my case. Could you share the source code of your previous setup?

**Comment by Yelnik** [comment]
That's really it, I don't put anything else in there besides what ASP.NET auto generated. Then I should ask if one of these setups is preferable or if one of them should not work?

**Comment by odinserj** [comment]
Could you share the source code of your previous setup by pasting it here? Otherwise our discussion is pointless, because I've tried every possible sequence of method calls, and all of them working fine.

**Comment by Yelnik** [comment]
Previously I was doing

```
        public void Configuration(IAppBuilder app) {
            ConfigureAuth(app);
            GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireDB");
            BackgroundJob.Enqueue(() => NetComms.NetworkThings.StartListening());
        }
```

and that was the only code I had anywhere for Hangfire

**Comment by odinserj** [comment]
You need to start at least one instance of background job server in order to process your jobs in any version of Hangfire. Without it nothing will happen like in your case. 

```csharp
public void Configuration(IAppBuilder app) 
{
    ConfigureAuth(app);
    GlobalConfiguration.Configuration.UseSqlServerStorage("HangfireDB");

    // Without this line background processing will not be performed
    // in any version of Hangfire.
    app.UseHangfireServer();
    
    BackgroundJob.Enqueue(() => NetComms.NetworkThings.StartListening());
}
```

**Comment by Yelnik** [comment]
Yes, sorry, that is exactly how I had it, but I think that is functioning now with 1.6.5. I don't know if the issue was old references or something but maybe cleaning/rebuilding many times has fixed it

**Comment by odinserj** [comment]
Okay, glad to hear all is working fine!

**Comment by stajs** [comment]
@odinserj Patience of a saint...
