### ISSUE TITLE
Dispatching to generic methods using EnqueueJob seems to be broken

### ISSUE THREAD

**Issue by spragchris** [HangfireIO/Hangfire#688]
Upgrading to 1.6.5 causes the issue, downgrading to 1.6.4 fixes the issue. **This is a show stopper for me, as using the generic is already a workaround for not supporting parameters with type 'object' (you get JObject deserialized)**

EnqueueJob seems to no longer be capable of dispatching commands to methods with type parameters. The following exception is thrown:

`ArgumentNullException: {"Value cannot be null.\r\nParameter name: method"}`

Offending code:
```
    public interface ICommandDispatcher
    {
        void Dispatch(object command);

        void DispatchTyped<TCommand>(TCommand command);
    }
```

`BackgroundJob.Enqueue(() => _commandDispatcher.DispatchTyped(new Command { Id = target.Id}));`

**Comment by odinserj** [comment]
This is a regression, and will be fixed in upcoming 1.6.6 ASAP. @spragchris, thanks for reporting!

**Comment by spragchris** [comment]
For us it's no problem to wait for 1.6.6. Thanks!

**Comment by odinserj** [comment]
@spragchris, 1.6.6 was just released and published to NuGet.
