### ISSUE TITLE
Error on "Recurring Jobs" page

### ISSUE THREAD

**Issue by capibaras** [HangfireIO/Hangfire#692]
There's an error when we try to access the Recurring Jobs page from the dashboard. 

Version 1.6.4

Field 'ExpressionDescriptor.expression' not found.

[MissingFieldException: Field 'ExpressionDescriptor.expression' not found.]
   CronExpressionDescriptor.ExpressionParser.Parse() +489
   CronExpressionDescriptor.ExpressionDescriptor.GetDescription(DescriptionTypeEnum type) +255
   CronExpressionDescriptor.ExpressionDescriptor.GetDescription(String expression, Options options) +42
   CronExpressionDescriptor.ExpressionDescriptor.GetDescription(String expression) +36
   Hangfire.Dashboard.Pages.RecurringJobsPage.Execute() +2975
   Hangfire.Dashboard.RazorPage.TransformText(String body) +26
   Hangfire.Dashboard.RazorPage.ToString() +7
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +65
   Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary`2 env) +430
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +273
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +561
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +187
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +561
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +561
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +187
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +185
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

![image](https://cloud.githubusercontent.com/assets/16759324/19378777/42350d28-91f7-11e6-8a6c-eb278ccf44b2.png)

**Comment by aidmsu** [comment]
Hi, @capibaras !

What storage do you use? Did you remove something manual in your storage bypassing Hangfire methods?

**Comment by capibaras** [comment]
Hi @aidmsu !

We use a SQL DB. I think the DB got corrupted at one point. We fixed this issue by deleting all the hangfile tables. It all worked fine after they were re-created.

**Comment by odinserj** [comment]
Reopening the issue, since dashboard should be tolerant to cases like this, showing actual data instead of crashing.
