### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by sk8main** [HangfireIO/Hangfire#696]
Hello,

The product that I am currently developing I wish to lock down the Content Security Policy, particularly around the script-src. Reading up on this matter it's good practice to NOT allow script-src unsafe-inline. When I remove this from my Content Security Policy response header the Hangfire Dashboard throws the following error:

_Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-FjG6huqkYlJ0b33s7WQijoMqeiICNGs7MKQVEulF4yI='), or a nonce ('nonce-...') is required to enable inline execution._

This error comes from the inline script used in the LayoutPage.cshtml, please see below:

```
<script>
            (function (hangFire) {
                hangFire.config = {
                    pollInterval: @StatsPollingInterval,
                    pollUrl: '@(Url.To("/stats"))',
                    locale: '@CultureInfo.CurrentUICulture'
                };
            })(window.Hangfire = window.Hangfire || {});
</script>
```

In there chance that this would be changed anytime soon so that this function belongs in a javascript file and is called from the LayoutPage.cshtml?

Thank you very much in advance

Russell

**Comment by BeczkaPGS** [comment]
Same problem here. Anybody found a solution for this ?
