### ISSUE TITLE
DI problem with DotNet Core Console Application

### ISSUE THREAD

**Issue by armartinez** [HangfireIO/Hangfire#697]
Hi, i'm using the following packages in my console app: 
- Hangfire.Core: 1.6.6
- Hangfire.SqlServer: 1.6.6

I'm using the default dotnet core DI provider with the following implementation: 

```
   public class DotNetCoreActivator : JobActivator
   {
        private IServiceProvider provider;

        public DotNetCoreActivator(IServiceProvider provider)
        {
           this.provider = provider;
        }

        public override object ActivateJob(Type type)
        {
           return provider.GetService(type) ?? Activator.CreateInstance(type);
        }
    }
```

Then in a custom (since it's a console app) Startup.cs file :

```
    public void ConfigureServices(IServiceCollection services)
    {
         ....
         services.AddTransient<IJobService, JobService>();
         services.AddTransient<JobService, JobService>();
    }

    public void Configure(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
    {
        GlobalConfiguration.Configuration
        .UseSqlServerStorage(Configuration.GetConnectionString("Default"))
        .UseActivator(new DotNetCoreActivator(serviceProvider));

        loggerFactory.AddDebug();
    }
```

As you can see, I have to bind the implementation of JobService, because when running a single recurring task with this line of code :

```
    RecurringJob.AddOrUpdate<IJobService>(...
```

There's always a call to bind JobService instead of only IJobService, can you tell me if I'm doing something wrong or is something else?

**Comment by armartinez** [comment]
I replaced my custom DotNetCoreActivator  for the AspNetCoreJobActivator in Hangfire.AspNetCore package 1.6.6, same result.

**Comment by Sebazzz** [comment]
What is the purpose of passing an interface to Hangfire instead of a concrete class?

**Comment by armartinez** [comment]
Decoupling the code. But it doesn't make any difference if I pass the concrete class, then it asks for the interface that the class implements. My guess is it just traverses the class hierarchy of the specified type and asks for the implementation of all the elements it finds.

**Comment by pieceofsummer** [comment]
Please elaborate on "there's always a call to bind JobService instead of only IJobService". `RecurringJob.AddOrUpdate<IJobService>(...)` uses neither `JobActivator` nor a DI container, and it should work even if you don't have any `IJobService` implementations at all. 

Type activation is done by `BackgroundJobServer` when the scheduled job is actually being executed.

**Comment by armartinez** [comment]
I meant that when the job is executed it looks for the interface and implementation bindings in the DI container else an exception is raised. Also this causes that two Jobs are added instead of just one (JobService call and IJobService call). I would expect that only the one for the interface would be necessary, so instead of having to do this : 

    services.AddTransient<IJobService, JobService>();
    services.AddTransient<JobService, JobService>();

Only this: 

    services.AddTransient<IJobService, JobService>();

**Comment by pieceofsummer** [comment]
> looks for the interface and implementation bindings in the DI container 

How do you know it looks for both interface and implementation? I've tried to reproduce your scenario, but it always seems to look by job interface.

I'd also like to highly discourage you from using static job managers (`RecurringJob.AddOrUpdate`, `BackgroundJob.Enqueue`) **and** `GlobalConfiguration` in .NET Core.

`GlobalConfiguration` methods excessively use static properties for storing configured values (e.g. `JobActivator.Current`, `JobStorage.Current` etc.). Static classes from above know nothing about DI, and create their own non-DI instances of clients. Which would only be half bad if Hangfire.AspNetCore bootstrapper not registered those static configuration properties as singletone services!

So some service instances could already be activated with configured values (for instance, JobActivator from your example), and then you call `.UseActivator(new DotNetCoreActivator(serviceProvider));` and change `JobActivator.Current` for those non-DI instantiates, while DI ones will continue using the old one. 

It is a mess :)

So you'd better avoid using those static methods at all, and better use `IRecurringJobManager` and `IBackgroundJobClient` from DI. And configure everything (including activator and database connection) inside `AddHangfire()` callback in `ConfigureServices`, while it hasn't started creating DI services yet.

**Comment by armartinez** [comment]
@pieceofsummer  Hi sorry for the delayed answer, but you are correct, the problem was indeed the static methods. I've changed the code to use the interfaces and now it's working fine, thanks a lot!!!!
I'm using a console application so in order to create an instance of the BackgroundJobServer I had to do it like this, in case somebody stumbles in the same issue : 

        var storage = (JobStorage)serviceProvider.GetService(typeof(JobStorage));         
        var scopeFactory = (IServiceScopeFactory)serviceProvider.GetService(typeof(IServiceScopeFactory));         
        var serverOptions = new BackgroundJobServerOptions()
        {
             Activator = new AspNetCoreJobActivator(scopeFactory)
        };

        using (var server = new BackgroundJobServer(serverOptions,storage))
        {  ....
