### ISSUE TITLE
Hangfire

### ISSUE THREAD

**Issue by wangli19** [HangfireIO/Hangfire#699]
@atifaziz @dsincl12 @andrecarlucci @ljubomir @vbfox  hello,Hangfire can support Framework.Net 4 ? If support ,Please let me know by telling me,tks!

**Comment by wangli19** [comment]
@atifaziz @dsincl12 @andrecarlucci @ljubomir @vbfox hello,Hangfire can support .Net  Framework 4 ? If support ,Please let me know by telling me,tks!

**Comment by aidmsu** [comment]
.NET 4.0 is not officially supported by Hangfire. There are nuget packages mady by @phillcampbell which allow using .NET Framework 4.0:
https://www.nuget.org/profiles/phillcampbell
