### ISSUE TITLE
Inconsistent constructors' accessibility

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#703]
Constructors:
- for `CreatedContext` and `ClientExceptionContext` are internal, while for `CreatingContext` is public;
- for `PerformingContext` and `ServerExceptionContext` are internal, while for `PerformedContext` is public;
- for `JobActivatorContext` is internal.

If exposing `IBackgroundJobFactory` / `IBackgroundJobPerformer` (so user can create custom implementations), then should also provide a way to create corresponding contexts. Hence, all of them should be public.

**Comment by odinserj** [comment]
Sure, let's call this inconsistency as a bug, so there are no problems of releasing it in the upcoming 1.6.7. Would you like to add a PR for this? I'm currently solving the problem with generics (#408).

**Comment by pieceofsummer** [comment]
Would be #710
