### ISSUE TITLE
AspNetCoreJobActivator.BeginScope() returns SimpleJobActivatorScope

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#706]
Since `BeginScope()` without args is not overridden in `AspNetCoreJobActivator`, the base implementation from `JobActivator` is being called. 

Even though it is obsolete, it'd be better to return a correct scope :)

**Comment by odinserj** [comment]
It was better to not to compile those methods against .NET Core at all in the 1.6.0 version. But now we can't remove those methods, so at least they should return the correct values. Would you like to create a pull request?
