### ISSUE TITLE
Add IPrincipal to DashboardContext

### ISSUE THREAD

**Issue by Sebazzz** [HangfireIO/Hangfire#707]
For an authorization filter, I think the primary means of authentication is using the existing IPrincipal available with the request. There is however no IPrincipal property on `DashboardContext`, which is passed in a `IDashboardAuthorizationFilter`. 

In legacy ASP.NET we can easily work around it by accessing `HttpContext.Current`. However, in ASP.NET Core something like that does not exist.

In ASP.NET Core, you need to use `IHttpContextAccessor` instead (_or cast `DashboardContext` to `AspNetCoreDashboardContext`_). But using the IHttpContextAccessor has a non-trivial performance cost, and is therefore not enabled [by default](https://github.com/aspnet/Hosting/issues/793).

I think that there should be an `IPrincipal` property available on the `DashboardContext`, so no workarounds are necessary for accessing a commonly used object in a authorization context.

**Comment by pieceofsummer** [comment]
> or cast DashboardContext to AspNetCoreDashboardContext

Why bother? There's an extension method to get `HttpContext` from `DashboardContext` :) https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardContextExtensions.cs#L25
