### ISSUE TITLE
DisplayNameAttribute not working as expected for the Job Name

### ISSUE THREAD

**Issue by iamhitarth** [HangfireIO/Hangfire#718]
Hi,

I am using Hanfire with ASP.Net Core and the DisplayNameAttribute doesn't seem to be working for me.

Below is my "job" method with the DisplayNameAttribute setup as detailed in #144 :
![image](https://cloud.githubusercontent.com/assets/5507180/20034485/39370dea-a424-11e6-82ae-698dee07686d.png)

Then I am enqueue-ing the job:
![image](https://cloud.githubusercontent.com/assets/5507180/20034491/5abc53da-a424-11e6-9c49-a0aedbdc39c8.png)

While the job executes successfully, on the dashboard all I end up seeing under the job name is the name of the method - which makes it really hard to understand which record just got processed successfully. 
![image](https://cloud.githubusercontent.com/assets/5507180/20034465/d46b3e0e-a423-11e6-8a94-e21908217253.png)

I am not using an interface either so not sure why it's not working as expected since it was supposed to have been added as feature in #148 . 

Any ideas as to why this might be happening?

Cheers

**Comment by pieceofsummer** [comment]
That's because it never worked on .NET Core, see #635.

And even on a full framework, it uses `String.Format()` which doesn't supports `"{dataQueueId}"` syntax to substitute arguments.

**Comment by natiki** [comment]
We are using .NET Full and encapsulate our params into an object like so:

```c#
public override void ExecuteJob(PerformContext aContext, OzCpHelloWorldInput aParams)
{
}
```

For it to be useful it would need to be able to descend into the object viz:

```c#
[DisplayName($"{aParams.SomeIntProp")]
```

**Comment by pieceofsummer** [comment]
Closing as #993 is merged now
