### ISSUE TITLE
Cron-tooltip showing wrong time

### ISSUE THREAD

**Issue by itssimple** [HangfireIO/Hangfire#727]
If I specify `0 22 * * *`, I'm supposed to get a tooltip that says the job is supposed to run at 22.00.
But it shows `22 minutes past the hour`

A job with `0 */4 * * *` shows `Every 4 hours`, which is correct.

**Comment by odinserj** [comment]
What version of Hangfire.Core are you using? Do you have a trailing or leading space in that expression? I've already reported issue like this to [CronExpressionDescriptor](https://github.com/bradyholt/cron-expression-descriptor/issues/51) repo and it should be already fixed.

**Comment by itssimple** [comment]
I'm currently using `1.6.6` from nuget.

And yes, there were trailing spaces. Thx.

**Comment by odinserj** [comment]
Ah, I didn't update the CronExpressionDescriptor package to the latest version after this issue was fixed. Thanks for reporting, will be fixed in 1.6.7.
