### ISSUE TITLE
JavaScript Dashboard Exception in 1.6.7 - Unable to get property 'update' of undefined or null reference

### ISSUE THREAD

**Issue by Jojoshua** [HangfireIO/Hangfire#745]
When loading the dashboard, a JavaScript unhandled exception occurs when you go to any section that is NOT the initial screen with the realtime graph i.e(jobs or recurring jobs). 
The error is this line ( realtime.update(); )  in this function

        Page.prototype._createGraphs = function() {
            var realtime = this.realtimeGraph = this._createRealtimeGraph('realtimeGraph');
            var history = this.historyGraph = this._createHistoryGraph('historyGraph');

            var debounce = function (fn, timeout) {
                var timeoutId = -1;
                return function() {
                    if (timeoutId > -1) {
                        window.clearTimeout(timeoutId);
                    }
                    timeoutId = window.setTimeout(fn, timeout);
                };
            };

            window.onresize = debounce(function () {
                realtime.update();
                history.update();
            }, 125);
        };

**Comment by odinserj** [comment]
@Jojoshua, thanks for reporting this! I've just fixed the issue, will be released in 1.6.8.
