### ISSUE TITLE
Skip the Job Execution if previous instance is still running

### ISSUE THREAD

**Issue by anupkumarsharma** [HangfireIO/Hangfire#746]
Is there good way to skip the job execution, if there is already a running version of it? I have seen several threads on this but didn't get a good answer.

**Comment by gandarez** [comment]
+1

**Comment by odinserj** [comment]
Guys, do you mean recurring jobs here?

**Comment by anupkumarsharma** [comment]
yes. I mean recurring job. To provide some more clarity let say I schedule a job every 15 mins. When the job start running, it might take more than 15 mins. In that case next trigger after 15 mins should be get skipped, since there is already an instance of same job in executing state.

**Comment by odinserj** [comment]
Could you describe me what that background job is doing?

**Comment by anupkumarsharma** [comment]
Well I have a WebApi pulling records from third party service and storing it into elastic DB. This problem comes during first initial sync or when the load is high. Although we want to schedule it for 15 mins, there are cases when it exceeds the time and I don't want to create one more instance of same job. Similarly we have similar jobs which imports data from files, I want the job to be sort of singleton (Only one running instance at any point of time, if the schedule triggers next one, it should skip the execution with alert or something like that).

**Comment by anupkumarsharma** [comment]
Hi There,
I believe the best way to implement this feature is to add a new state called Skipped. We can skip the instance for multiple executing instance. I have branch ready with complete feature including core, dashboard and unit test. You can have a look and let me know how this looks.  I am getting permission denied issue when trying to check the branch to server.

S C:\Workspace_Anup-OpenSource\Hangfire\Hangfire>  git push --set-upstream origin SkipJob
emote: Permission to HangfireIO/Hangfire.git denied to anupkumarsharma.
atal: unable to access 'https://github.com/HangfireIO/Hangfire.git/': The requested URL returned error: 403

I want to push the branch and create pull, to check with the community?

**Comment by iSatishYadav** [comment]
Any updates on this? Is there any way to achieve this in 2020?

**Comment by sahzudin** [comment]
Any updates on this?

**Comment by odinserj** [comment]
Please try using the [SkipWhenPreviousJobIsRunningAttribute](https://gist.github.com/odinserj/a6ad7ba6686076c9b9b2e03fcf6bf74e) job filter from the referenced gist.
