### ISSUE TITLE
state table exceed int32 max.

### ISSUE THREAD

**Issue by hasanaydogar** [HangfireIO/Hangfire#749]
we recently exceeded int32 max in state table.
In new version convert int to bigint for id column.

[https://discuss.hangfire.io/t/hangfire-job-id/2387/4?u=hasanaydogar](https://discuss.hangfire.io/t/hangfire-job-id/2387/4?u=hasanaydogar)

**Comment by odinserj** [comment]
Oh guys! With SQL Server! Congratulations, but sorry for this, I've already planned to switch to `bigint` in [1.7.0](https://github.com/HangfireIO/Hangfire/projects/2). Didn't realize it's a near future with Hangfire.SqlServer. How many jobs have you processed?

**Comment by hasanaydogar** [comment]
about 660 millions

**Comment by odinserj** [comment]
Did everything is working correctly now? If not, what Hangfire version do you have? I'll make a patch version ASAP to handle `long` instead of `int` in the code base.

**Comment by hasanaydogar** [comment]
Everything is ok now. We are using 1.4.6. We will update it to 1.6.7. we are testing 1.6.7 in our pre-prod code now. in a few days we will update in production code too.

**Comment by hasanaydogar** [comment]
Hi guys!
We are looking forward for 1.7.0 version of hangfire. Recently we also had terrible problem with Counter table. I think it is urgent to update all tables to bigint for all versions. :)
