### ISSUE TITLE
A strategy for moving types

### ISSUE THREAD

**Issue by vegar** [HangfireIO/Hangfire#757]
Does anyone have a strategy for handling recurring jobs where the job definition moved between two versions of the application?

Eg. In version 1 we schedule a `ISomeJob.Action()`, which is serialized as `{"Type": "OurApp.BackgroundJobs.ISomeJob, OurApp, Version=1.0.0.0", "Method": "Action"}`

In version 2, nothing changes, really, except that new instances of the job is serialized with a new version number. It seems like Hangfire is able get to the right type even though the version number has changed. 

In version 3, the application got huge, and someone decided that the `OurApp` assembly needed to be split. New recurring jobs will now be serialized as `{"Type": "OurApp.BackgroundJobs.ISomeJob, OurApp.BackgroundJobs, Version=3.0.0.0", "Method": "Action"}`. Existing jobs will now fail, since Hangfire is still looking for the interface in the `OurApp` assembly.

So how do you solve this issue?

**Comment by vegar** [comment]
Found [this chapter ](http://hangfire.io/blog/2014/05/10/are-your-methods-ready-to-run-in-background.html#method-may-become-unavailable) in the blog.

I guess there are no other strategy than keeping the old until the queue is empty?
No one with experience in trying to migrate jobs? e.g. accessing the database and overwrite activation data?

**Comment by EProd-Rhansen** [comment]
There are a couple of options. If history is not important, then you can always bring all of your hangfire instances down and just delete everything from the Hangfire tables except for Schema. They will rehydrate on their own with the correct data when the Hangfire instances are brought back up.

Alternatively, you can write a smarter script that will change the type from one to another in the database. The steps to accomplish that should be pretty obvious just from looking at the data. Let me know if you need help and I'll see if I can crank something out tomorrow.

**Comment by vegar** [comment]
The second option should be doable. 

The first option I'm not sure I understand. We are using mongo for persistence. 
If I delete everything - how and when and why would the jobs be recreated with the new types?

**Comment by EProd-Rhansen** [comment]
I'm not sure what using Mongo has to do with the question at hand. 

Are you concerned that you'll lose jobs that where scheduled using the BackgroundJob.Schedule command? If so, the only challenge to that I would offer is whether or not that is a valid concern given that jobs of this nature are generally expected to run at a specific point-in-time. Allowing them to run after a system is brought back up from maintanence may be doing so when the domain conditions that required their initial scheduling are no longer valid and may cause more problems than just killing them off.

I can't really understand why you'd be concerned about doing this with jobs scheduled via RecurringJob.AddOrUpdate. As the name suggests, that call will create a job record from the type provided if it does not exist, or update the jobs run conditions if it does exist. Essentially, you should be calling this method every time your hangfire instances start up for all of your recurring jobs.

If that is true, then deleting the data is just fine as it will be inserted against once you bring your systems back online.

**Comment by vegar** [comment]
Since I wasn't sure what you meant, I added mongo as an extra info to see if it was relevant. Deleting everything except schema is quite meaningless when using mongo since yer ain't no schema - except if schema in this context could mean something else, which against might have explained how things would start existing after deletion... 

Now I see that was not the case. Instead you were talking about recurring jobs and I was talking about scheduled jobs. 

We have jobs saying '30 days after user does something, check this and that'. We cannot just delete those jobs.

So - we have a couple of options: manually change the jobs to reflect new types, keep old 'shadow types' till all old jobs are done, or redesign away from scheduled jobs and instead use recurring jobs, which sounds more robust when it comes to changes.

**Comment by EProd-Rhansen** [comment]
Lol, it looks like a vocabulary conflict. If you look at the tables that Hangfire creates, then you'll see that there is a table called Hangfire.Schema. This table keeps track of the "database schema version" that your Hangfire instance is currently using. It is used by the built-in migration to determine what (if anything) it needs to do to your installation to bring it current.

With that being said, you've presented an edge case that makes it a requirement for you to take a more surgical approach to the problem. I'm not familiar with MongoDB unfortunately. If there is a management tool, then take a look at the data in Hangfire.Job, Hangfire.Hash, and Hangfire.Set. You should be able to see the updates that need to be made for this operation.

If you need help with that, then you might hit up the github repo for Hangfire.MongoDB.

**Comment by vegar** [comment]
Just to make the communication even easier, it doesn't look like the mongodb implementation have any 'Schema'-data stored anywhere :-)

Anyway - I think I've got a couple of pointers and hints. 

Thanks.
