### ISSUE TITLE
Read only permission for the dashboard

### ISSUE THREAD

**Issue by dbones** [HangfireIO/Hangfire#758]
As part of our deployment we will require that there is a read/view only role to the Dashboard.

similar to this forum request
https://discuss.hangfire.io/t/feature-request-read-only-dashboard/2514

**Comment by zlangner** [comment]
This would also be useful for my use case. We have a small number of users that can be trusted to not just delete or enqueue jobs willy nilly and a large number of users that would get benefit from seeing what is in the dashboard.

**Comment by mikechamberlain** [comment]
Hi guys, I've made a start on getting this working in agoda-com/Hangfire@49028c7cb4c02dd682c2a552af462215b0cdce2a. I'd appreciate some feedback on the design and the best way to move forward to get this in a state where it can be merged.

## Design

I identified two permissions:
- `CanTrigger` - user can trigger or enqueue jobs
- `CanDelete` - user can delete jobs

I encapsulated these in a `DashboardPermissions` object, which is eventually made available to the view through the `RazorPage`. The view can then switches certain features on and off.

## Current state

What's currently in that commit builds, runs, and behaves *exactly the same as before*, as [all permissions are hardcoded](https://github.com/agoda-com/Hangfire/blob/49028c7cb4c02dd682c2a552af462215b0cdce2a/src/Hangfire.Core/Dashboard/DashboardPermissions.cs#L23) to `true`.  

However, the following *does* work:

- changing `CanTrigger` to `false` in code hides all the trigger / enqueue buttons
- changing `CanDelete` to `false` in code hides all the delete buttons
- changing both `CanTrigger` and `CanDelete` to `false` also hides all job selection checkboxes as they become redundant

## What's next

Obviously, the permissions can't be hardcoded like this, and need to be configurable somehow by the user.  I think that we should use the user's roles and/or claims to determine their permissions. Could we ask the user to pass in a lambda taking a `CurrentPrincipal` or `IIdentity` that produces the correct `DashboardPermissions` object for the user? I'm a bit fuzzy on how to do this, especially as it needs to work for both .NET Classic and Core. Any advice would be appreciated.

Finally, once we've worked out the above, we should put similar checks into the Ajax calls to prevent unauthorized users from calling directly against the backend.

**Comment by odinserj** [comment]
I'm closing this issue as the feature is already implemented in 1.7.0, and this year will put more efforts into documentation.
