### ISSUE TITLE
Will separate windows background server scale out?

### ISSUE THREAD

**Issue by nrip-monotype** [HangfireIO/Hangfire#760]
As mentioned in the [overview page](http://hangfire.io/overview.html), [scale-as-you-grow](http://hangfire.io/overview.html#scale-as-you-grow) section, hangfire can be hosted as `separate backend server`. Will things scale out if I simply startup multiple instances of servers pointing to same hangfire storage (i.e. I want to avoid situation where same job runs on multiple hangfire server simultaneously)? 

Is this something that happens out-of-the-box?

Looks like this should be the case when looking at `web farm`/`web garden` scenario images. But `Separate Server` image isn't clear.

**Comment by odinserj** [comment]
Yeah, you don't need to configure anything. All the work is synchronised using the underlying storage.

**Comment by nrip-monotype** [comment]
Thanks!
