### ISSUE TITLE
[AddOrUpdate] Could not load file or assembly But [Enqueue] Is Ok

### ISSUE THREAD

**Issue by seven1276** [HangfireIO/Hangfire#773]
I want to know why I run ' BackgroundJob.Enqueue<ISyncService>(x => x.SyncBalance(cmd));' Is OK.
But I run ' RecurringJob.AddOrUpdate<ISyncService>(x => x.SyncBalance(cmd), Cron.Daily(23));' will be error!

Thanks a lot

![image](https://cloud.githubusercontent.com/assets/3192191/21468166/f722fc28-ca40-11e6-91e5-775dd7192e2d.png)

**Comment by anupkumarsharma** [comment]
Its due to the way there two features. If you don't want to delve into technical and wants this to work - Try something like this
Let say you have object of job with method GetJob, which returns the delegate
    // Initialize the Hangfire Jobs
                var hangFireJob = new  Hangfire.Common.Job(job.GetType(), job.GetType().GetMethod("GetJob"));
 var manager = new RecurringJobManager();
                        manager.AddOrUpdate("HelloWorld", hangFireJob, GetCronExpression("Recurring"));

**Comment by seven1276** [comment]
Thank you very much! It works and I will keep watching this awesome product
