### ISSUE TITLE
Warn users about automatic retry attempt if processing takes too much time

### ISSUE THREAD

**Issue by kanno41** [HangfireIO/Hangfire#78]
I enqueued a couple jobs, and one threw an exception (and broke inside Visual Studio, in Debug mode).  When I stopped and restarted the site, the job that threw an exception stayed in Processing, but was clearly hung (not even running).  All of the other jobs completed successfully.

I have 1 worker enabled, but when I restarted the site, it fetched another from the Queue, leaving it with 2 jobs currently in processing (with one hung).

It would be really neat to have the following:
A way to cancel jobs
Capture Console output from the jobs that are running/have run

**Comment by odinserj** [comment]
Implemented in 1.4.0
