### ISSUE TITLE
Self referencing loop issue in ASP.NET Core

### ISSUE THREAD

**Issue by mo-esmp** [HangfireIO/Hangfire#780]
I have `Self referencing loop detected for property 'X' with type 'Y'. Path 'Z'` issue. is there any way to handle this issue globally instead of putting `[JsonIgnore]` attribute every where, something like this:
```
services.AddHangfire(options => { 
    options.UseSqlServerStorage(configuration["ConnectionStrings:HangfireConnection"]); 
    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
});
```

**Comment by pieceofsummer** [comment]
Are you looking for `JobHelper.SetSerializerSettings()`?

**Comment by joesamraj** [comment]
How can we use JobHelper.SetSerializerSettings() in .Net Core 2.0?

**Comment by joesamraj** [comment]
Just realised this is a static class :)

**Comment by lizziecgee** [comment]
I had trouble figuring out how to implement these settings, so in case anyone else is also wondering, this is what my startup.cs looked like once I added code:
```
services.AddHangfire(options =>
{ 
  options.UseSqlServerStorage(configuration["ConnectionStrings:HangfireConnection"]); 
});

JobHelper.SetSerializerSettings(new JsonSerializerSettings
{
  ReferenceLoopHandling = ReferenceLoopHandling.Ignore
});
```
Happy coding!

**Comment by Prologh** [comment]
`SetSerializerSettings()` from `JobHelper` is now obsolete. Use `GlobalSettings` instead:

```cs
GlobalConfiguration.Configuration.UseSerializerSettings(new JsonSerializerSettings
{
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
});
```

**Comment by tranthaibinh111** [comment]
[DotNet Core 3.1]

I have the following settings

'''
services.AddHangfire(configuration => configuration
  .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
  .UseSimpleAssemblyNameTypeSerializer()
  .UseRecommendedSerializerSettings()
  .UseSqlServerStorage(Configuration.GetConnectionString("CronJob"))
  .UseSerializerSettings(new JsonSerializerSettings()
  {
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
  }));
'''

It worked.

**Comment by reaction1989** [comment]
I got the same error on Core 3.1

I used .UseRecommendedSerializerSettings().

I changed it to .UseRecommendedSerializerSettings(settings => settings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore));

Perhaps this should be the Recommended setting for .NET Core 3.1 ?
