### ISSUE TITLE
Recurring Job List: Default Sort Order

### ISSUE THREAD

**Issue by bradleyuk** [HangfireIO/Hangfire#791]
It appears the Recurring Job list on the Dashboard is ordered based on Date Created (or randomly/based on a hidden/internal unique id) which is fairly confusing / useless for end users.

Please can be it alphabetically ordered on the Id or Job columns or even better allow the column headings to be clicked to change the sorting?

**Comment by tseanf** [comment]
I would love this as well.

**Comment by odinserj** [comment]
In the latest 1.7.0 betas recurring jobs are sorted based on their next execution interval, starting with those that will not be scheduled (scheduled to Feb 30, for example).

**Comment by Rayzbam** [comment]
Allow recurring job ordering to be handle by any delegate or client implementation will clearly be a better suit here.

In my case, i just want to sort it by job name.
