### ISSUE TITLE
Sql Server 2008 Support

### ISSUE THREAD

**Issue by brettpostin** [HangfireIO/Hangfire#794]
The documentation states that the supported database engines are Sql Server 2008**R2** and above:

http://docs.hangfire.io/en/latest/configuration/using-sql-server.html

However, the nuget package indicates 2008 and above:

https://www.nuget.org/packages/Hangfire.SqlServer/

Additionally this sample uses 2008 express:

http://docs.hangfire.io/en/latest/tutorials/highlight.html 

Which is correct? Is it safe to assume Hangfire supports Sql Server 2008?

**Comment by odinserj** [comment]
I've quickly reviewed [new things in database engine](https://msdn.microsoft.com/en-us/library/bb510411(v=sql.105).aspx) in 2008 R2, comparing to 2008, and found nothing interesting. Try to run it under SQL Server 2008, I think this version is enough to successfully run Hangfire.
