### ISSUE TITLE
Job cancellation

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#80]
Sometimes there is a need to cancel a job. I think we can always cancel job with a custom cancelation check inside a job method as described in #73, but there is a way to simplify this.

Since a job may run in a different process, and sometimes on a different machine, we should make the cancellation process in two steps:

**Cancel job on client**

``` csharp
var jobId = BackgroundJob.Enqueue(() => SomeMethod());
BackgroundJob.Cancel(jobId);
```

**Check job was canceled on server**

The simplest method to cancel a job:

``` csharp
public void SomeMethod()
{
    if (BackgroundJob.IsCanceled(<Job Id>)) { return; }
}
```

But I don't like it because we need to pass job identifier and call a method that is related to HangFire. I thought there is a way to make a custom `CancellationTokenSource` (that is based on `JobStorage` class) and pass the `CancellationToken`:

``` csharp
public void SomeMethod(CancellationToken token)
{
    token.ThrowIfCancellationRequested();
}
```

But I didn't find any way to implement a custom `CancellationTokenSource` class. So I think to create an interface to provide similar feature:

``` csharp
public void SomeMethod(IJobCancellationToken token)
{
    if (token.IsCancellationRequested) { return; }
    // or
    token.ThrowIfCancellationRequested();
}
```

**Comment by gandarez** [comment]
When those PRs will be merged to production? 

I'm still facing a problem in my company that I need to cancel jobs.
