### ISSUE TITLE
Footer displays sensitive info

### ISSUE THREAD

**Issue by archangelf** [HangfireIO/Hangfire#802]
Hi,
we are using Hangfire in production and we faced with a problem that we need to open dashboard to authenticated users and everything works great! But, footer contains info about storage we are using, including password (redis). It looks like "redis://password@address/0 Time: 26.1.2017 17:29:00 GMT". We tried to customize the dashboard, but seems its impossible to remove such info from footer or footer at all.
Please advice.

**Comment by burningice2866** [comment]
@archangelf Looks like an issue in the Redis provider itself, not Hangfire.

The Hangfire dashboard will call the ToString() method of the Storage in use, its in here that the Redis Storage is exposing too much. Basically it should check for a @ character in the host, and if its present, then strip everything leading up to it.

https://github.com/HangfireIO/Hangfire.Redis/blob/master/Hangfire.Redis/RedisStorage.cs#L105

**Comment by archangelf** [comment]
Ok, but i`m not sure that this king of info really needs to be displayed in footer. As for me its rather some king of debug information. And in production i prefer to not display connection info in footer.

**Comment by odinserj** [comment]
@archangelf, what package are you using for Redis support? That issue was fixed years ago.

**Comment by archangelf** [comment]
@odinserj, I`m using Hangfire.Redis. What issue was fixed? Seem we have misunderstanding. Storage info is always present in footer. So my question is will you accept my proposal to remove storage information from footer or should we use forked version of Hangfire?

**Comment by odinserj** [comment]
So what version of Hangfire.Redis are you using, and what version of Hangfire.Core?

**Comment by archangelf** [comment]
Both libs are v 1.1.1

**Comment by odinserj** [comment]
Even merge that PR, you'll be forced to update to the latest version of Hangfire.Core, and decide what to do with Hangfire.Redis (free open-source alternatives are [available](https://www.nuget.org/packages/HangFire.Redis.StackExchange/)). So you can use a fork, or update to the latest versions.

**Comment by archangelf** [comment]
So latest version will not display connection info in footer?

**Comment by odinserj** [comment]
Nope

**Comment by archangelf** [comment]
That mean you are not plan to remove this info from footer?

**Comment by odinserj** [comment]
No, the primary use of dashboard is debugging. More information - better debugging experience.

**Comment by odinserj** [comment]
Closing this issue as no new activity.
