### ISSUE TITLE
Need way to check if backroundJob exists or an ability to enqueue once (maybe both)

### ISSUE THREAD

**Issue by DR9885** [HangfireIO/Hangfire#804]
It would be nice, if I had an option on background job, to choose to "Enqueue" or to "EnqueueOnce". So to ignore the queue if a file is in process or has already been processed in the past.

Possible Example Code (partially tested).
```C#
    public static class BackgroundJob2
    {
        public static void EnqueueOnce(Expression<Func<Task>> methodCall)
        {
            if (!Exists(methodCall))
                BackgroundJob.Enqueue(methodCall);
        }

        public static bool Exists(Expression<Func<Task>> methodCall)
        {
            var inputJob = Hangfire.Common.Job.FromExpression(methodCall);
            var queue = inputJob.Method.GetAttribute<QueueAttribute>().FirstOrDefault();
            var queueName = queue == null ? "default" : queue.Queue;

            var api = JobStorage.Current.GetMonitoringApi();
            var hasSucceeded = api.SucceededJobs(0, int.MaxValue).Select(x => x.Value.Job).Any(job => job.Args.SequenceEqual(inputJob.Args) && job.Method.Equals(inputJob.Method));
            var inProcess = api.ProcessingJobs(0, int.MaxValue).Select(x => x.Value.Job).Any(job => job.Args.SequenceEqual(inputJob.Args) && job.Method.Equals(inputJob.Method));
            var inQueue = api.EnqueuedJobs(queueName, 0, int.MaxValue).Select(x => x.Value.Job).Any(job => job.Args.SequenceEqual(inputJob.Args) && job.Method.Equals(inputJob.Method));

            return hasSucceeded || inProcess || inQueue;
        }
    }
```

**Comment by pieceofsummer** [comment]
This would be rather harsh on database, and won't work if the previously executed job was already deleted by retention policy.

But you may implement an `IClientFilter` to check if a job was ever created, and cancel creation if needed. Something like:

```c#
public class ExecuteOnceAttribute : JobFilterAttribute, IClientFilter
{
    public void OnCreating(CreatingContext filterContext)
    {
        var entries = GetAllEntriesFromHash(GetJobKey(filterContext.Job));
        if (entries != null && entries.ContainsKey("jobId"))
        {
            // this job was already created once, cancel creation
            filterContext.Canceled = true;
        }
    }

    public void OnCreated(CreatedContext filterContext)
    {
        if (!filterContext.Canceled)
        {
            // job created, mark it as such
            filterContext.Connection.SetRangeInHash(GetJobKey(filterContext.Job), 
                new [] { new KeyValuePair<string, string>("jobId", filterContext.BackgroundJob.Id) });
        }
    }

    private static string GetJobKey(Job job)
    {
        using (var sha512 = SHA512.Create())
        {
            return "execute-once:" + Convert.ToBase64String(
                sha512.ComputeHash(Encoding.UTF8.GetBytes(job.ToString())));
        }
    }
}
```

**Comment by DR9885** [comment]
Throwing Exception: Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.Data.SqlClient.SqlException: String or binary data would be truncated.

Failing on this line
                filterContext.Connection.SetRangeInHash(GetJobKey(filterContext.Job),
                    new[] { new KeyValuePair<string, string>("jobId", filterContext.BackgroundJob.Id) });

**Comment by pieceofsummer** [comment]
Seems like there's an overrun of a 100 characters limit by one character in GetJobKey(). Just decrease it a little, either by changing the prefix (like "exec-once:"), or by using a shorter hash (e.g. SHA256).

**Comment by DR9885** [comment]
Updated Key, and added JSON serialization to include arguments, seems to work.

        private static string GetJobKey(Hangfire.Common.Job job)
        {
            using (var sha512 = SHA512.Create())
            {
                return Convert.ToBase64String(sha512.ComputeHash(Encoding.UTF8.GetBytes("execute-once:" + JsonConvert.SerializeObject(job))));
            }
        }
