### ISSUE TITLE
Update Hangfire.Dashboard.Authorization (deprecated interfaces)

### ISSUE THREAD

**Issue by guillaume-fr** [HangfireIO/Hangfire#811]
Please, update Hangfire.Dashboard.Authorization package so it uses IDashboardAuthorizationFilter instead of the deprecated interface.

There is a pull request https://github.com/HangfireIO/Hangfire.Dashboard.Authorization/pull/6

Assembly Hangfire.Core, Version=1.6.8.0
Hangfire.Dashboard.Authorization, Version=2.1.0.0

**Comment by spoofi** [comment]
I created a new pull request - https://github.com/HangfireIO/Hangfire.Dashboard.Authorization/pull/8

With the upgrade packages and the implementation of all previous authorization filters. Please, update Hangfire.Dashboard.Authorization package.

**Comment by BenJBailey** [comment]
+1 on this. Please update this package with this pull request! I need this very often.

**Comment by glen-84** [comment]
@odinserj This issue should probably be closed.
