### ISSUE TITLE
 Hangfire.Autofac cant work in aspnetcore

### ISSUE THREAD

**Issue by newbe36524** [HangfireIO/Hangfire#813]
Hangfire.Autofac cant work in aspnetcore. Will it be supported ?

**Comment by mgmccarthy** [comment]
@pianzide1117, I'm working on an open source asp.net core project. We're using Autofac for our container, but NOT using Hangfire.Autofac, but we have Hangfire wired up and running.

Check out how to we did it:

https://github.com/HTBox/allReady/blob/836e185f01c7a3a43077bb1756df2cc77d38ca69/AllReadyApp/Web-App/AllReady/Startup.cs

https://github.com/HTBox/allReady/blob/836e185f01c7a3a43077bb1756df2cc77d38ca69/AllReadyApp/Web-App/AllReady/Configuration/Services.cs

**Comment by newbe36524** [comment]
@mgmccarthy many thanks.
I close this issue since it is too old.
