### ISSUE TITLE
Stack trace highlighting works incorrectly with .NET Core

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#818]
- Source file/line is not highlighted at all. Probably because the format of stack trace has changed.
- Even some invocations are not correctly highlighted.

And Async exceptions look totally unreadable there.

**Comment by pieceofsummer** [comment]
With a little effort though, a totally unreadable mess like this:
<img width="564" alt="screen shot 2017-02-24 at 23 29 37" src="https://cloud.githubusercontent.com/assets/2262364/23321924/46de698a-faea-11e6-8f40-f08fcdae1086.png">

can be turned into this:
<img width="843" alt="screen shot 2017-02-24 at 23 36 05" src="https://cloud.githubusercontent.com/assets/2262364/23321925/4710d79e-faea-11e6-9aec-5f741220df52.png">

**Comment by odinserj** [comment]
The problem was related to `Regex` matches that worked incorrectly with Unix-like paths. The problem was fixed in 1.6.21. Regarding async methods, things changed in .NET Core 2.1, so nothing will be changed in this repository.
