### ISSUE TITLE
Error handling around job creation?

### ISSUE THREAD

**Issue by markalanevans** [HangfireIO/Hangfire#820]
Recently purchased Pro.Redis.
So far so good, however we are interested to know how you hand the case where Hangfire fails to create a job(writing to redis).

Do we need to try/catch or do you just fail and log the error without throwing another exception?

**Comment by odinserj** [comment]
Do you mean that exception is thrown, when a batch is being created?

**Comment by markalanevans** [comment]
Both really. Basically i'm asking if while a job is Enqueued. 

Ex:
```
BackgroundJob.Enqueue(() => Console.WriteLine("Hello, {0}!", "world"));
```

If it fails to enqueue the job. What happens?

**Comment by odinserj** [comment]
An instance of the `BackgroundJobClientException` will be thrown, and it's up to you to choose what to do&nbsp;– log, retry, queue to a local queue, etc. There is no general guideline here, the behavior fully depends on your business needs.

**Comment by markalanevans** [comment]
Awesome. Thank you.
