### ISSUE TITLE
Long Running Job State or Meta-Data

### ISSUE THREAD

**Issue by DR9885** [HangfireIO/Hangfire#823]
Is there any way to store a job state or meta data for a long running job? So if/when the job restarts, it picks up where it left off?

**Comment by burningice2866** [comment]
That's a concern of the task itself, not the scheduler.

**Comment by anupkumarsharma** [comment]
Well, hangfire scope is to just run the code. Your requirement seems to be more of job specific. There is plenty of options to have such type of functionality. One way is to check when the job starts for any existing job state(Let say, you have stored previous job execution in mongo), if one exists just restart the job from same state else start as first execution. This is just an example.

**Comment by odinserj** [comment]
Have you considered breaking this job into a chain of continuations?

```csharp
var part1 = BackgroundJob.Enqueue();
var part2 = BackgroundJob.ContinueWith(2);
var part3 = BackgroundJob.ContinueWith(3);
```

**Comment by DR9885** [comment]
Well, right now each job is a file, and that file has many rows.

Originally, I was making a BackgroundJob passing each row as arguments. However, it started to choke SQL server because the data set was too large. And It would also cause hangfireUI to hang for long periods because large data. Which is why I moved back to processing one file per job, so I didn't have to serialize all the data into the database. 

I could pass the filename and row number, however, this would slow down processing and increase memory usage, because I would need to decompress, serialize the full file for every backgroundJob. Note: Every File I get is 1GB and every day I get 4 files. 

It would just be easier if I could set some sort of value on the job for a last run value.

**Comment by danielcor** [comment]
Why are these jobs not completing?   Perhaps you can store progress (row)
in a SQL table and read it when you get a new job?   Then you call skip to
the right row in the file.   If you store position it's even easier to skip.

   - Daniel

**Comment by pieceofsummer** [comment]
If you have `PerformContext` injected, it provides `GetJobParameter()` and `SetJobParameter()` methods you can call any time during job execution. Of course, they won't help you with 0.5GB back-ups, but saving some intermediate state is absolutely possible.

**Comment by DR9885** [comment]
PerformContext looks like it could work
