### ISSUE TITLE
Null reference exception when owinContext.Auth.User is null and I return false for Authorize implementation of IDashboardAuthFilter

### ISSUE THREAD

**Issue by ysmoradi** [HangfireIO/Hangfire#833]
See https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/Owin/MiddlewareExtensions.cs#L107

**Comment by odinserj** [comment]
Thanks @ysmoradi for reporting this, I've just released version [1.6.11](http://hangfire.io/blog/2017/03/14/hangfire-1.6.11.html).
