### ISSUE TITLE
Dashboard issue in v1.6.10

### ISSUE THREAD

**Issue by edwinprakash** [HangfireIO/Hangfire#835]
The dashboard is broken because the CSS and JS files referenced in the latest version are /js1610 and /css1610.
However, the dashboard routes for these are expecting only a 3 digit suffixes (see below).  Can someone please fix this to support 4 digit suffixes?  I could have done it but don't know how to submit a pull request and don't have the time to learn how to do it either.

      DashboardRoutes.Routes.Add("/js[0-9]**{3}**", (IDashboardDispatcher) new CombinedResourceDispatcher("application/javascript", DashboardRoutes.GetExecutingAssembly(), DashboardRoutes.GetContentFolderNamespace("js"), DashboardRoutes.Javascripts));
      DashboardRoutes.Routes.Add("/css[0-9]**{3}**", (IDashboardDispatcher) new CombinedResourceDispatcher("text/css", DashboardRoutes.GetExecutingAssembly(), DashboardRoutes.GetContentFolderNamespace("css"), DashboardRoutes.Stylesheets));

**Comment by burningice2866** [comment]
Heh, that's one of the more curious bugs I've seen in a long time :)

**Comment by odinserj** [comment]
Thanks guys for quick feedback! I've just released [1.6.11](http://hangfire.io/blog/2017/03/14/hangfire-1.6.11.html) with fix for this problem.
