### ISSUE TITLE
RecurringJobDto.NextExecution has delay in value getting set

### ISSUE THREAD

**Issue by ndicenso** [HangfireIO/Hangfire#843]
It seems that the NextExecution value is only returned after the job has values in the Hash table. Consider parsing the cron schedule when there is no hash value yet and returning the next occurrence from there as a fallback. This would guarantee that there is always a NextExecution shown in the returned Dto.

**Comment by ndicenso** [comment]
I updated from the original title. It seems the NextExecution is always set. There is just a delay in when the value is available. After calling AddOrUpdate on the job and then querying shortly after, the new values are not always immediately available.

**Comment by odinserj** [comment]
Implementation of recurring jobs was changed in the latest 1.7.0 betas and now next execution is set immediately.
