### ISSUE TITLE
IDashboardFilter Constantly calls Authorize Method in ASP.Net CORE

### ISSUE THREAD

**Issue by bedwar2** [HangfireIO/Hangfire#847]
I have in startup:

            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
              Authorization = new[] { new HangfireDashboardAuthorization() }
            });

And for the IDashboardAuthorizationFilter:

    public class HangfireDashboardAuthorization : IDashboardAuthorizationFilter
    {
        
        public HangfireDashboardAuthorization()
        {
        
        }

        public bool Authorize(DashboardContext context)
        {
            var httpContext = context.GetHttpContext();
            PerformanceAppContext appContext = (PerformanceAppContext) httpContext.RequestServices.GetService(typeof(PerformanceAppContext));
            if (appContext.Settings.Settings.HangfireAuthorization.Contains(appContext.Settings.EmployeeID))
            {
                return true;
            }

            return false;
        }

    }

If I set a breakpoint on the first line in Authorize and I go to the "/Hangfire" url to bring up the dashboard, I am seeing that this is being called every 1 second.  Why is the dashboard constantly pinging, is there a way to reduce the number of trips to reduce this constant calling of the authorize function?

**Comment by burningice2866** [comment]
Make sense since the dashboard is polling the server to update its graph and ui in regards of running/failed/enqueued jobs and so on.

**Comment by bedwar2** [comment]
Thanks, I understand that, I was just hoping the graph could refresh at a slower rate.

**Comment by burningice2866** [comment]
Have you tried increasing `StatsPollingInterval` on `DashboardOptions` ?

**Comment by bedwar2** [comment]
No I haven't and can't find that in the documentation.  I will try it.  Do you know if the value is in milliseconds?

**Comment by bedwar2** [comment]
Thanks so much for the quick replies, that was the answer and it is in milliseconds.  I will close this now.

**Comment by burningice2866** [comment]
I see that its not mentioned anywhere in the docs, so that can be improved. Glad you managed to get it to work.

**Comment by jeffreyfloresca04** [comment]
does it work when you set value for StatsPollingInterval?
