### ISSUE TITLE
Dashboard status SQL query

### ISSUE THREAD

**Issue by stibay** [HangfireIO/Hangfire#848]
I want to create a SQL query to get roughly the same result as the hangfire dashboard page.
Job info, cron, next execution, last execution, current status, last successfull execution and created date.

If a query is failing I also want to see when it was last executed successfully.

Not too familier with how the database is set up but do you have to do queries like this? Seems abit complicated and not sure how I would get the last successful execution

```
select
	[Key] = a.[Key],
	Cron = c.Value,
	LastExecution = cast(le.Value as datetime2),
	NextExecution = cast(ne.Value as datetime2),
	LastJobId = lj.Value,
	LastStatus = lj.StateName
from
	HangFire.Hash a

outer apply (
	select
		Value
	from
		HangFire.Hash
	where 
		Field = 'NextExecution' and a.[Key] = [Key]
) ne

outer apply (
	select
		Value
	from
		HangFire.Hash
	where 
		Field = 'LastExecution' and a.[Key] = [Key]
) le
outer apply (
	select
		Value,
		StateName
	from
		HangFire.Hash lj
	left join
		HangFire.Job j on j.Id = lj.Value
	where 
		Field = 'LastJobId' and a.[Key] = [Key]
) lj
outer apply (
	select
		Value
	from
		HangFire.Hash
	where 
		Field = 'Cron' and a.[Key] = [Key]
) c

where
	a.Field = 'Job'
```

**Comment by gandarez** [comment]
You can write your own queries and simply extend the behavior of Dashboard page.

**Comment by stibay** [comment]
@gandarez You got an example on how I could do that?
