### ISSUE TITLE
HttpContext of IDashboardAuthorizationFilter is isolated from MVC Controller HttpContext

### ISSUE THREAD

**Issue by sonphnt** [HangfireIO/Hangfire#854]
Hi Everyone,

I am trying to make a MVC Client with Hangfire that will be authenticated against IdentityServer 4.
For example I have 2 links like these:
http://mvcclient.com/hangfire (Hangfire dashboard)
http://mvcclient.com/secure 

First we try to access "http://mvcclient.com/secure" 
```
    public class HomeController : Controller
    {        
        [Authorize]
        public IActionResult Secure()
        {
            ViewData["Message"] = "Secure page.";
            return View();
        }

        public async Task<IActionResult> CallApiToGetToken()
        {
            // I have acccessToken here.
            var accessToken = await HttpContext.Authentication.GetTokenAsync("access_token");
            return View("json");
        }
    }
```

You will be navigated to IdentityServer login page. After login successfully there, you will be redirected back to "http://mvcclient.com/secure"

After this step, I would like to be able to access "http://mvcclient.com/hangfire"

```
public class HangFireAuthorizationFilter : IDashboardAuthorizationFilter
    {
        public bool Authorize(DashboardContext context)
        {           
            var httpContext = context.GetHttpContext();      
            // Can not get accessToken.
            var accessToken = httpContext.Authentication.GetTokenAsync("access_token");      
            return httpContext.User.IsInRole("admin");
        }
    }
```

But httpContext from DashboardContext is not the same with HttpContext in Controller, so I can not get any information from authentication.

How can we secure Hangfire dashboard in this case? or any suggesstion?

Thank you very much

**Comment by pieceofsummer** [comment]
Can it be you have Hangfire registered in the pipeline before the authentication middleware?

**Comment by sonphnt** [comment]
Thanks @pieceofsummer
