### ISSUE TITLE
Errors do not show in Elmah (because this is missing)

### ISSUE THREAD

**Issue by francnuec** [HangfireIO/Hangfire#867]
I'm sorry, I didn't want to start creating a new branch for this.

For `ElmahLogProvider`, providing the `ApplicationName` would ensure that `Hangfire` Errors also show up in the `Elmah.axd` page. Currently, the errors log to the database, but do not show up on the page. This is especially if you use the `SqlErrorLog` provider of `Elmah`.

So, this method <code>Log</code> in the <code>ElmahLogProvider</code> needs to be updated as this: (kindly note my comments)

            public bool Log(LogLevel logLevel, Func<string> messageFunc, Exception exception)
            {
                if (messageFunc == null) return logLevel >= _minLevel;

               var message = messageFunc();
               var context = HttpContext.Current; //context is also needed when available. Null value is ok.

                dynamic error = exception == null
                    ? Activator.CreateInstance(_errorType)
                    : Activator.CreateInstance(_errorType, exception, context); //added context as constructor parameter. Null value is ok.

                error.Message = message;
                error.Type = logLevel.ToString(); //comment this out to allow default exception type to show. This would make it look like other errors from the app. But this way is also good anyway.
                error.Time = DateTime.Now;
                error.ApplicationName = _errorLog.ApplicationName; //the application name MUST be added

                try
                {
                    _errorLog.Log(error);
                }
                catch (Exception ex)
                {
                    Debug.Print("Error: {0}\n{1}", ex.Message, ex.StackTrace);
                }

                return true;
            }

Hope this helps. :)

**Comment by odinserj** [comment]
Thanks @francnuec! I've added the `ApplicationName` to make `SqlErrorLog` to behave correctly. Unfortunately I can't add `HttpContext.Current`, without referencing to `System.Web`. We can use reflection, but I'll leave this implementation to community. Regarding the `Type` – Hangfire can emit informational and debug messages that aren't errors, and if we comment that line these messages will be treated as exceptions, and that's not good.
