### ISSUE TITLE
Hangfire ı/o problem

### ISSUE THREAD

**Issue by guncer** [HangfireIO/Hangfire#873]
Hi,
After using the hangfire in the production, different errors occured in the system. It is recovering after restarting the service.
When hangfire jobs are stopped , we dont get error.  Can you help us ? What could be the problem?

FOR example;

> nhibernate query error:
System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. 
The I/O package is not thread safe by default.
 In multithreaded applications, a stream must be accessed in a thread-safe way, 
such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)

> Mass transit error:
Probable I/O race condition detected while copying memory. 
The I/O package is not thread safe by default. In multithreaded applications,
 a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods.
This also applies to classes like StreamWriter and StreamReader. System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at 

> Hsm code block error:
System.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count at PayFlex.SmartBox.Security.StartableHsmHost.DecryptInSession(Session session, String value, Int32 keyIndex, Int32 retryCount) in F:\TeamcityAgent\work\8deb4e4cd3a46977\src\Core\PayFlex.SmartBox.Security\StartableHsmHost.cs:line 254 at PayFlex.SmartBox.Security.StartableHsmHost.DecryptInSession(Session session, String value, Int32 keyIndex, Int32 retryCount) in

**Comment by burningice2866** [comment]
Looks like a problem in your code which you're running through Hangfire. Could you elaborate some more on what kinds of jobs you're running and how often they are being run. Can the same job be running multiple times with different parameters, or is it just a scheduled job that runs once a day?

**Comment by guncer** [comment]
We have multiple recurring jobs which run for every five minutes and connect external data services. In addition, they are same type. These jobs do not contain business that is about Hsm, Masstransit or NHibernate.

**Comment by guncer** [comment]
The Hangfire was configured those parameters in our project:

` string hangfireDbConnection = ConfigurationManager.AppSettings["HangfireDbConnection"];
            HangfireConfigurator.CustomConfiguration.UseSqlServerStorage(hangfireDbConnection);
            HangfireConfigurator.CustomConfiguration.UseActivator(new WindsorJobActivator(container.Kernel));

            string hangfirePortalUrl = ConfigurationManager.AppSettings["HangfirePortalUrl"];
            JobMonitoringWebApp = WebApp.Start<OwinWebAppStarter>(hangfirePortalUrl);

            BankJobInitializer = container.Resolve<IBankJobInitializer>();

            BankJobInitializer.Init();

            var options = new BackgroundJobServerOptions
            {
                WorkerCount = Environment.ProcessorCount * 5,
                ServerTimeout = TimeSpan.MaxValue,
                ShutdownTimeout = TimeSpan.MaxValue,
                ServerCheckInterval = TimeSpan.FromMinutes(1),

                Queues = new[] { "recurring", "fireandforget" }
            };

            GlobalConfiguration.Configuration.UseFilter(new QueueAttribute("fireandforget"));
            GlobalConfiguration.Configuration.UseFilter(new AutomaticRetryAttribute()
            {
                Attempts = 1,
                OnAttemptsExceeded = AttemptsExceededAction.Delete
            });`

**Comment by burningice2866** [comment]
As the error indicates, some of your jobs seems to be running simultaneously accessing shared objects which are not thread safe. You need to introduce locks around those parts of your code to ensure multiple threads isn't executing the same non-thread-safe code at the same time.

**Comment by guncer** [comment]
Actually, when we are taken these errors, Hangfire continues to work. There is no shared object that be used between jobs.

**Comment by burningice2866** [comment]
Hangfire will always continue to work... there no error in no job which can make Hangfire to stop.
