### ISSUE TITLE
Recurring job for Every first Monday of month

### ISSUE THREAD

**Issue by siddhant4u** [HangfireIO/Hangfire#876]
How to set cron expression if I want to execute hangfire recurring job every first monday of every month?

The expression 1 9 * 1/1 1#1 does not work in hangfire (as it uses crontab syntax and 1#1 is throws exception.

regards,

Siddhant K

**Comment by pieceofsummer** [comment]
I believe `1 9 1-7 * 1` could work

**Comment by siddhant4u** [comment]
thanks
