### ISSUE TITLE
Entry point to call recurring background job in ASP.NET Core

### ISSUE THREAD

**Issue by waterforce1205** [HangfireIO/Hangfire#878]
I am trying to implement a recurring background job which will clean up my database after several days.
However, I cannot find any start point in ASP.NET Core to push the background job to the queue for the first time. All I found is that I have to make a request and then create a controller to handle that request. This controller is where I create the background job. I think this is a little "manually" and I have to make a request every times I start the app.
Is there anyway to push the background job to the queue instantly when I start the app for the first time?

**Comment by pieceofsummer** [comment]
Startup.cs's `Configure` method is a perfect place to implement startup logic. Just inject `IRecurringJobManager` as argument and configure your jobs there:
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IRecurringJobManager recurringJobs)
{
    // ...
    // ...
    // ...

   app.UseMvc();

   // configure recurring jobs
   recurringJobs.AddOrUpdate("your-job-id", Job.FromExpression<JobClass>(x => x.DoJob(null)), Cron.Weekly());
}
```

**Comment by moskvitin** [comment]
But what if you want to set cron for reccuring job from config and using `reloadOnChange: true`? Is there any best practice how to do this?
