### ISSUE TITLE
Trouble with lifetime scope using IoC and RecurringJob

### ISSUE THREAD

**Issue by dvladimirovich** [HangfireIO/Hangfire#888]
I'm using Hangfire v1.6.12, SimpleInjector v4.0.6, Hangfire.SimpleInjector v1.3.0 and ASP.NET MVC 5 project. I want to create recurringjob which will trigger and call a method with user identifier as input parameter.
My Start method looks like:
```
public void Start()
{
    lock(_lockObject)
    {
        if (_started) return;
        _started = true;

        HostingEnvironment.RegisterObject(this);
        GlobalConfiguration.Configuration
            .UseNLogLogProvider()
            .UseSqlServerStorage(ConfigurationManager.ConnectionStrings["HangfireMSSQLConnection"].ConnectionString);

        JobActivator.Current = new SimpleInjectorJobActivator(Bootstrapper.Container);
        GlobalConfiguration.Configuration.UseActivator(new SimpleInjectorJobActivator(Bootstrapper.Container));

        GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { LogEvents = true, Attempts = 0 });
        GlobalJobFilters.Filters.Add(new DisableConcurrentExecutionAttribute(15));

        _backgroundJobServer = new BackgroundJobServer();
    }
}
```
My job is creating in controller (for test purposes) and looks like:
```
string jobId = 1 + "_RecurseMultiGrabbing";
if (!HangfireBootstrapper.Instance.JobExists(jobId))
{
    RecurringJob.AddOrUpdate<IScheduleService>(jobId, scheduler => scheduler.ScheduleMultiPricesInfo(1), Cron.MinuteInterval(5));
}
```
Creator of SimpleInjector says that my implementation of container registrations is correct, but he doesn't sees active async scope (according SimpleInjector v4) creation in your method. I'll give you a stack trace:

> SimpleInjector.ActivationException: The IUnitOfWork is registered as 'Hybrid Web Request / Async Scoped' lifestyle, but the instance is requested outside the context of an active (Hybrid Web Request / Async Scoped) scope.
>    at SimpleInjector.Scope.GetScopelessInstance[TImplementation](ScopedRegistration`1 registration)
>    at SimpleInjector.Scope.GetInstance[TImplementation](ScopedRegistration`1 registration, Scope scope)
>    at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
>    at lambda_method(Closure )
>    at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
>    at SimpleInjector.InstanceProducer.GetInstance()
>    at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
>    at SimpleInjector.Container.GetInstance(Type serviceType)
>    at Hangfire.SimpleInjector.SimpleInjectorScope.Resolve(Type type)
>    at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_0.<PerformJobWithFilters>b__0()
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_1.<PerformJobWithFilters>b__2()
>    at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
>    at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass8_1.<PerformJobWithFilters>b__2()
>    at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
>    at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
>    at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

If you want to see whole question and discussion, please see this [link](http://stackoverflow.com/posts/comments/75095411?noredirect=1) on stackoverflow and read questions and comments.
We really need your participation and help!

**Comment by odinserj** [comment]
I see this issue is already resolved on SO (thanks for the link), but as a workaround. It's better to use submit a PR to the original [Hangfire.SimpleInjector](https://github.com/devmondo/HangFire.SimpleInjector) repository and leverage the `JobActivator.BeginScope` method appeared in Hangfire 1.5.0 to IoC container scopes like in [Hangfire.Autofac](https://github.com/HangfireIO/Hangfire.Autofac/blob/master/HangFire.Autofac/AutofacJobActivator.cs).

**Comment by dvladimirovich** [comment]
There is the same implementation as in Hangfire.SimpleInjector. Bu t we need to start scope, so I need to use this class. There was already similar question in your repository? the guy recommended to create a class, which will start Scope.
