### ISSUE TITLE
How to resolve dependencies?

### ISSUE THREAD

**Issue by im1dermike** [HangfireIO/Hangfire#890]
I've installed and configured Hangfire in my .NET Core web application's Startup class as follows:

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        services.AddHangfire(x => x.UseSqlServerStorage(connectionString));
    }
    
    public void Configuration(IAppBuilder app)
    {
        app.UseHangfireServer();
        app.UseHangfireDashboard();
        RecurringJob.AddOrUpdate(() => jobManager.DailyJob(), Cron.Daily);
    }

The question is how do I resolve the `jobManager` dependency for my Hangfire job?  FWIW, I'm using Autofac.

**Comment by odinserj** [comment]
If not too late, use the `RecurringJob.AddOrUpdate<IJobManager>(x => x.DailyJob())` method overload. The `IJobManager` service should be registered using the `IServiceCollection` interface.
