### ISSUE TITLE
Generic Methods that don't have all of the generic types in the argument list cannot be enqueued

### ISSUE THREAD

**Issue by sage-nathan-jones** [HangfireIO/Hangfire#893]
So from the test suite, the method `GenericMethod<T>() {}` is never used in the tests. The current behavior is to throw a Null Pointer Exception when trying to enqueue.

This test demonstrates the issue:
```
        [Fact]
        public void GetNonOpenMatchingMethod_HandlesMethodHasNoParametersOrTypes()
        {
            var method = TypeExtensions.GetNonOpenMatchingMethod(typeof(NonGenericClass), "GenericMethod",
                new Type[0]);
            Assert.Null(method);
        }
```
An exception is thrown rather than the Assert.Null()

**Comment by sage-nathan-jones** [comment]
#894 is a PR that addresses this and similar issues where the generic types are not in the method's arguments.

**Comment by odinserj** [comment]
Thanks a lot for PR, @sage-nathan-jones, especially for backward compatibility! We'll review it a bit later, with combination of PR #891.

**Comment by odinserj** [comment]
I've added the proposed tests to ensure we aren't getting an exception if a class contains such methods, and just ignore methods that contain unresolved type arguments. Full fix requires us to serialize type arguments into the method name like `MyMethod[[System.String, mscorlib],[System.Int32, mscorlib]]` and require much more efforts, especially when thinking about backward compatibility.
