### ISSUE TITLE
Is it right Cron expression?

### ISSUE THREAD

**Issue by dvladimirovich** [HangfireIO/Hangfire#895]
```
RecurringJob.AddOrUpdate<IScheduleService>(
                    recurringJobId: jobId, 
                    methodCall: scheduler => scheduler.ScheduleMultiPricesInfoAsync(1), 
                    cronExpression: "0 */12 * * *");
```
Is this Cron expression right for running every day at 12:00AM and 12:00PM ?

**Comment by aidmsu** [comment]
Hi, @dvladimirovich!

You are right, `0 */12 * * *` literally means *every 12 hours starting from 00:00*. It's the same as *every day at 12:00 AM and 12:00 PM*.

You also can use `0 0,12 * * *`. I think it's more clear for your case.

Finally I recommend [cronexpressiondescriptor](http://cronexpressiondescriptor.azurewebsites.net) service to transform cron expressions to human readable text.

**Comment by dvladimirovich** [comment]
Спасибо, Андрей)
