### ISSUE TITLE
SQL Azure support

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#91]
I've read the [differences](http://stackoverflow.com/questions/3235164/what-is-the-difference-between-sql-azure-and-sql-server-2008) between SQL Server and SQL Azure and found nothing, that prevents to run HF inside Microsoft Azure platform. However, I haven't test it yet.

**Comment by chris03** [comment]
There might be an issue with SQL Azure:
http://discuss.hangfire.io/t/hangfire-stops-processing-jobs-in-queue-after-database-errors-on-azure-sql

**Comment by odinserj** [comment]
@chris03, thank you for reporting this, created #284.

**Comment by devanathan2017** [comment]
any update ! still hangfire is not working with azure DB
