### ISSUE TITLE
Object getting Null seems like deserialization issue in Hangfire

### ISSUE THREAD

**Issue by furqansafdar** [HangfireIO/Hangfire#918]
Dear Hangfire team,

I have asked my question in detail on below link and wants to know what is wrong with my design approach.
https://stackoverflow.com/questions/44590115/object-getting-null-seems-like-deserialization-issue-in-hangfire

As per suggestion, I need to change my design because the state of Scheduler instance invoking the Execute method is not available in the Background job. Please provide help in suggesting the best possible solution in this situation.

**Comment by IanYates** [comment]
I've added some commentary on the answer at SO...  Hope that's of help.
