### ISSUE TITLE
Heavy database load, mainly caused by a certain internal query of Hangfire

### ISSUE THREAD

**Issue by sethsnel** [HangfireIO/Hangfire#921]
We use Azure to host our web application. The application has quite some background processes. Most of the time the processes run smoothly. However, sometimes major spikes in load occur.

We used to have the Hangfire tables in the same database as our application database. But to separate load we put Hangfire in a separate database. 

The Azure tier of this database is "S3 Standard".
Type of process: long running (several hours)

This query stands out in performance consumption:
```
(@queues2 nvarchar(4000),@queues1 nvarchar(4000))delete top (1) JQ
output DELETED.Id, DELETED.JobId, DELETED.Queue
from [HangFire].JobQueue JQ with (readpast, updlock, rowlock, forceseek)
where Queue in (@queues1,@queues2)
```
[Graphs](https://www.screencast.com/t/KoLJRtISEkR)

Are we doing something wrong or does Hangfire need improvement?

**Comment by odinserj** [comment]
45 hours is a very large value. What is the total number of workers you have, and what polling interval are you using? As an option, you could try to use the [Sliding Invisibility Timeout](https://github.com/HangfireIO/Hangfire/releases/tag/v1.6.14) fetching technique appeared in Hangfire.SqlServer 1.6.14.

**Comment by sethsnel** [comment]
We have 60 workers. The kind of jobs executed vary from milliseconds to minutes (potentially hours). So we have short lived as well as long running jobs.

Currently we didn't configure a specific polling interval, which leaves us at the default of 15 seconds. We will try out the new Sliding Invisibility Timeout setting, it looks interesting! What value would you recommend for us? @odinserj

**Comment by rondhavale** [comment]
Hi @sethsnel 

I am facing same issue. I would appreciate if you would let me know if you took any action to fix the issue?

Thanks,
Rohan

**Comment by odinserj** [comment]
@rondhavale what version of Hangfire do you use? I have an installation that uses the cheapest Basic plan with 5 DTUs (it's really slow) with Hangfire 1.7.1 and following options. There's a more efficient fetching implementation available in 1.7 that doesn't let multiple workers to access the table structure, so we can use sub-second polling intervals. We can call this method "long polling" and it works only when poll interval is less than 1 second.

```csharp
new SqlServerStorageOptions
{
    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
    QueuePollInterval = TimeSpan.FromMilliseconds(100),
    UseRecommendedIsolationLevel = true,
    UsePageLocksOnDequeue = true,
    DisableGlobalLocks = true,
}
```

With 100ms polling interval, the load average of that very constrained database is about 10% as in the screenshot below, with 500ms it's about 5% and so forth, so you can trade latency with CPU consumption just fine. For standalone server installation, even 50ms polling interval lead to 0% of CPU consumption.

![image](https://user-images.githubusercontent.com/1078718/56724185-29a2ea80-6753-11e9-8093-be737ff9ae49.png)

**Comment by odinserj** [comment]
And if you still on 1.6.X, please read the upgrade guide – https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html

**Comment by rondhavale** [comment]
@odinserj  Thank you for a quick response. Yes, I still use 1.6.x with Basic plan. Yesterday, I read about the features in 1.7 and they sound very interesting. We have a complex set of services that uses hangfire for queuing data processing requests. While upgrading seems to be a quick fix but for us it means testing all the data pipeline with the performance requirements again. Is there any temporary solution while we plan for this upgrade and implement it?

**Comment by odinserj** [comment]
You can decrease the total number of workers, increase the polling interval, increase the DTU count for your database by upgrading to a higher plan or use something like [Hangfire.Azure.ServiceBusQueue](https://github.com/HangfireIO/Hangfire.Azure.ServiceBusQueue) before upgrading to 1.7. After upgrade, I'd recommend to use the setting above.
