### ISSUE TITLE
Last run badge not visible for recurring jobs if the corresponding job was already expired

### ISSUE THREAD

**Issue by pieceofsummer** [HangfireIO/Hangfire#930]
<img width="315" alt="screen shot 2017-07-06 at 19 09 06" src="https://user-images.githubusercontent.com/2262364/27921017-2172fa38-627f-11e7-9ece-157769e4ca14.png">

Should either preserve last run result (for correct badge color selection) or just show it gray. Either way, it should be visually readable.

**Comment by odinserj** [comment]
@pieceofsummer, thanks for reporting. Sure, we can show the `expired` message in a light gray box.

**Comment by pieceofsummer** [comment]
@odinserj it actually shows the correct execution timestamp if hovered, so it would be enough just to provide a gray background color for the badge.
