### ISSUE TITLE
Microsoft.Azure.DocumentDB.1.15.0 missing method exception using Hangfire.AspNetCore 1.6.14

### ISSUE THREAD

**Issue by dalestone** [HangfireIO/Hangfire#938]
Hi, I have encountered an error when using hang fire for asp net core, using the azure document db provider throws a missing method exception when using 1.15.0 of the Document DB client
at UseAzureDocumentDbStorage()

###
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();

            services.AddHangfire(o =>
            {
                Hangfire.AzureDocumentDB.AzureDocumentDbStorageOptions azureDocumentDBStorageOptions = new Hangfire.AzureDocumentDB.AzureDocumentDbStorageOptions
                {
                    //Queues = new[] { "default", "critical" },
                    //RequestTimeout = TimeSpan.FromSeconds(30),
                    //ExpirationCheckInterval = TimeSpan.FromMinutes(15),
                    //CountersAggregateInterval = TimeSpan.FromMinutes(1),
                    //QueuePollInterval = TimeSpan.FromSeconds(2),
                    DefaultCollectionName = "Hangfire_jobs"
                };

              // throws missing method exception here
                o.UseAzureDocumentDbStorage("####", "###", "###", azureDocumentDBStorageOptions);

            });
        }
####
https://github.com/imranmomin/Hangfire.AzureDocumentDB/issues/4

Downgrading to 1.14.0 of the Document DB client resolves the issue but would like it to work with 1.15.0.

Thanks

**Comment by imranmomin** [comment]
@dalestone, thanks for reporting the issue. I will be soon releasing the final build.

**Comment by imranmomin** [comment]
@odinserj  - you can close the issue. Have already released a fix and the original issue is also closed

Release - 2.1.1
https://github.com/imranmomin/Hangfire.AzureDocumentDB/releases/tag/2.1.1
