### ISSUE TITLE
Missing UseSqlServerStorage in .Net Core 2.0

### ISSUE THREAD

**Issue by nicksav** [HangfireIO/Hangfire#943]
Hi
Looks like I am not able to use UseSqlServerStorage  in asp.net core 2.0. 
I am using Latest table version of Hangfire: 1.6.14

Please help

**Comment by Coemgen4** [comment]
I have the same trouble with 1.1 version.

**Comment by lrequena** [comment]
Had the same issue, just thought I leave the solution here in case anyone else lands on this.
Add Nuget reference to package Hangfire.SqlServer.
