### ISSUE TITLE
KeyNotFoundException using IMonitoringApi.ProcessingJobs(int from, int count)

### ISSUE THREAD

**Issue by BohdanZhmud** [HangfireIO/Hangfire#945]
Seeing KeyNotFoundException using IMonitoringApi.ProcessingJobs(int from, int count)

> The given key was not present in the dictionary.
> 
> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.<>c.<ProcessingJobs>b__8_1(SqlJob sqlJob, Job job, Dictionary`2 stateData)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.DeserializeJobs[TDto](ICollection`1 jobs, Func`4 selector)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.GetJobs[TDto](DbConnection connection, Int32 from, Int32 count, String stateName, Func`4 selector)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.<>c__DisplayClass8_0.<ProcessingJobs>b__0(DbConnection connection)
>    at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.ProcessingJobs(Int32 from, Int32 count)

related to https://github.com/HangfireIO/Hangfire/issues/871

**Comment by benjymous** [comment]
My fix in #948 should fix this too
