### ISSUE TITLE
Job always fails with System.IO.FileNotFoundException before eventually succeeding

### ISSUE THREAD

**Issue by dannief** [HangfireIO/Hangfire#949]
`<error  host="RD0003FF28D8E9"  type="Warn"  message="Failed to process the job '9': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:18."  source="mscorlib"  detail="System.IO.FileNotFoundException: Could not load file or assembly 'CA.Messaging.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.&#xD;&#xA;File name: 'CA.Messaging.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'&#xD;&#xA;   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)&#xD;&#xA;   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)&#xD;&#xA;   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark&amp; stackMark)&#xD;&#xA;   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)&#xD;&#xA;   at Hangfire.Storage.InvocationData.Deserialize()&#xD;&#xA;&#xD;&#xA;WRN: Assembly binding logging is turned OFF.&#xD;&#xA;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#xD;&#xA;Note: There is some performance penalty associated with assembly bind failure logging.&#xD;&#xA;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#xD;&#xA;"  time="2017-07-11T18:09:10.0353667Z" />`

The above is the error as logged to ELMAH. (Sorry about the format. I don't have access to the dashboard at the moment)

As the title says, the job will fail 1 or more time before eventually succeeding if given enough retry attempts. The setup we had before getting this error were 2 different hangfire databases each being accessed by it's own hangfire server. We then changed to having a single database, with 2 hangfire servers accessing this single database but using different queues. Each server only services a single queue. After we moved to this latter setup, this error started to appear. 

> Note that the `CA.Messaging.Service` assembly does exist and that the job will usually eventually succeed

**Possible related issues**
- #840 
- #926 
- #910
---

_**Edit**_
**After reading through Issue #926. I think this may be the bug I am seeing as well. I think my job may be failing due to the server processing a queue it is not configured to process**

----

**Setup Details**
- We are using Hangfire.Core and Hangfire.SqlServer version: **1.16.14**
- The relevant methods being invoked are `IBackgroundJobClient.Schedule`
- Jobs are stored in an Sql Server 2016 database locally and in a SQL Azure database when deployed. The error can be observed both locally and in Azure, but seems to occur more frequently in Azure.
- We also use the database that stores hangfire jobs to log errors with ELMAH and access a few common tables. 
- The hangfire servers accessing the database are an ASP.NET 5 Web API and a console application both targeting .NET Framework 4.6.1.
- We use SimpleInjector 4.0.8 to handle dependencies. Activator code below:

I have found this similar [stackoverflow issue](https://stackoverflow.com/questions/35219144/hangfire-failes-to-load-assembly), that suggests a work around might be to recreate the database. However we did recently create a new database but still received the error.

**SimpleInjectorJobActivator:**
```C#
using System;
using Hangfire;
using Injector = SimpleInjector;

namespace CA.Common.Service.Utils.Hangfire
{
    /// <summary>
    /// SimpleInjector Hangfire JobActivator
    /// </summary>
    /// <seealso cref="JobActivator" />
    public class SimpleInjectorJobActivator : JobActivator
    {
        private readonly Injector.Container container;
        private readonly Injector.Lifestyle lifestyle;

        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleInjectorJobActivator"/> class.
        /// </summary>
        /// <param name="container">The container.</param>
        /// <exception cref="System.ArgumentNullException">container</exception>
        public SimpleInjectorJobActivator(Injector.Container container)
        {
            if (container == null)
            {
                throw new ArgumentNullException("container");
            }

            this.container = container;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleInjectorJobActivator"/> class.
        /// </summary>
        /// <param name="container">The container.</param>
        /// <param name="lifestyle">The lifestyle.</param>
        /// <exception cref="System.ArgumentNullException">
        /// container
        /// or
        /// lifestyle
        /// </exception>
        public SimpleInjectorJobActivator(Injector.Container container, Injector.Lifestyle lifestyle)
        {
            if (container == null)
            {
                throw new ArgumentNullException("container");
            }

            if (lifestyle == null)
            {
                throw new ArgumentNullException("lifestyle");
            }

            this.container = container;
            this.lifestyle = lifestyle;
        }

        /// <summary>
        /// Activates the job.
        /// </summary>
        /// <param name="jobType">Type of the job.</param>
        /// <returns></returns>
        public override object ActivateJob(Type jobType)
        {
            return container.GetInstance(jobType);
        }

        /// <summary>
        /// Begins the scope.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <returns></returns>
        public override JobActivatorScope BeginScope(JobActivatorContext context)
        {
            if (lifestyle == null || lifestyle != Injector.Lifestyle.Scoped)
            {
                return new SimpleInjectorScope(container, Injector.Lifestyles.AsyncScopedLifestyle.BeginScope(container));
            }

            return new SimpleInjectorScope(container, new Injector.Lifestyles.AsyncScopedLifestyle().GetCurrentScope(container));
        }
    }
}
```

**Comment by dannief** [comment]
It seems the root of the issue is a server trying to deserialize a job it is not configured to handle. Since it is not configured to handle that job, it would likely not have reference to the job class and so deserialization fails. It seems that the server will grab any job from the db, even those it can't handle, because it will need to deserialize the job first to know if it can handle it or not, (via inspecting the Queue attribute value of the job class). If the server does not have a reference to the job class then deserialization and consequently the job fails with exception "File not found"

A current workaround is to ensure that all servers reference the DLLs for all jobs stored in the db, so that deserialization succeeds. After the job is deserialized, supposedly if the server is not configured to handle the queue to which the job belongs, it will be ignored and eventually tried by another server.

I am closing this issue as it a duplicate of several others and there is even a [pull request](https://github.com/HangfireIO/Hangfire/pull/755) which attempts to address the issue.

Related issues:

- #840
- #926
- #908 
- #910

**Comment by Deantwo** [comment]
Duplicate of #595
