### ISSUE TITLE
Duration and latency metrics for succeeded jobs

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#95]
It is useful to know the exact performance timings. And this feature was simple enough to implement. So, new stats added to the job details page:
- **Duration** – job method invocation time + method filters invocation time.
- **Latency** – delay between the job creation and method invocation. This metric shows you background job invocation overhead.

P.S. High latency and duration values on screenshot caused by global distributed lock and 10000 running jobs :)

![2014-05-20 22 38 57](https://cloud.githubusercontent.com/assets/1078718/3031578/09ee4ed2-e04e-11e3-86e5-164f53419e7b.png)

**Comment by purestgreen** [comment]
We use MSMQ for enqueuing jobs, yet I'm still seeing latencies of between 0.7 and 1.5 seconds... why is that? Shouldn't MSMQ be almost instantaneous?
