### ISSUE TITLE
Deleted job won't disappear from dashboard retries page

### ISSUE THREAD

**Issue by mikechamberlain** [HangfireIO/Hangfire#959]
I don't know how this happened but this job completed successfully, and I then deleted it, but it never removed itself from the retries page. If I try to delete it again it still remains.

Here's what happened:

1. The job failed
1. The job was added to the retries tab
1. The job was enqueued and this time succeeded
1. But the job remained in the retries tab
1. The job was manually deleted
1. The job still remains in the retries tab, now showing as Deleted :S

![image](https://user-images.githubusercontent.com/1414303/28865442-2cd608c2-779a-11e7-89fe-fa122c3cbae9.png)

**Comment by odinserj** [comment]
This should be fixed in the latest version, [1.6.17](https://www.hangfire.io/blog/2017/09/20/hangfire-1.6.17.html), thanks for reporting this bug!

**Comment by mikechamberlain** [comment]
Great news - will upgrading delete this stuck job? It's still lonelily hanging around on the dashboard months later.

**Comment by odinserj** [comment]
Nope, only by hands in your SQL Server database, by removing the corresponding entry in the HangFire.Set table with the `retries` key. This problem helped to reveal a bigger one, related to non-safe distributed locks that can cause other subtle issues. So this was a great report. Very hard to reproduce, but great, thank you for it!

**Comment by jawadabutt** [comment]
Where would i find the retries table in mongodb?
