### ISSUE TITLE
QueuePollInterval Memory leak on core

### ISSUE THREAD

**Issue by siada** [HangfireIO/Hangfire#960]
I believe that I've found that if you set the QueuePollInterval of SqlServerStorageOptions to 1 second, you end up with a fairly rapid memory leak:

![http://i.imgur.com/UKSrX7C.png](http://i.imgur.com/UKSrX7C.png)

I've managed to prove this as well in a test I've written:
https://github.com/siada/HangfireMemoryLeak

clone it and set the [connection string](https://github.com/siada/HangfireMemoryLeak/blob/master/Startup.cs#L46) then you should be able to just `dotnet run`. For me the process starts up on about 20MB of ram used, and every second climbs by 0.2MB

There doesn't even have to be any jobs configured for this to occur.

## Version:
1.6.14

## Storage: 
Hangfire.SqlServer

## Configuration:
                PrepareSchemaIfNecessary = false,
                SchemaName = "Hangfire_test",
                QueuePollInterval = TimeSpan.FromSeconds(1)
                GlobalConfiguration.Configuration.UseSqlServerStorage(connectionString, opt);
                using (var connection = new SqlConnection(connectionString))
                {
                    SqlServerObjectsInstaller.Install(connection, opt.SchemaName);
                }

**Comment by pieceofsummer** [comment]
Well, executing queries will be allocating some memory for their results. The more queries you execute (by decreasing the poll interval), the more memory would be allocated.

As I don’t see any garbage collection points on your graph, I assume that the allocated memory just had no chance to be freed yet.

Garbage collection usually happens when the app is idle, but yours might be quite busy at the time.

**Comment by odinserj** [comment]
@siada what version of .NET Core you are using? I found SqlConnection leaks in .NET Core 1.1 (and previous), please see [this comment](https://github.com/HangfireIO/Hangfire/issues/965#issuecomment-323082285) for workaround.

**Comment by siada** [comment]
The test project I created was 1.1, I'll update it to 2.0 see if I get the same behavior.

**Comment by odinserj** [comment]
You can try to upgrade your System.Data.SqlClient to version 4.3.1
