### ISSUE TITLE
SQL Connection not closing 

### ISSUE THREAD

**Issue by phoomperfectionist** [HangfireIO/Hangfire#965]
## Problem
We're facing a connection leak issue from using Hangfire and caused our database went down when it reaches the maximum amount of the session. As observed, the Hangfire's apparently trying to create a new session every time it runs a job, also when the connection lifetime is reached, but none of it gets closed (see screenshot below).  

![image](https://user-images.githubusercontent.com/14541040/29223194-e8938ccc-7eef-11e7-9ae2-e23b69f65d09.png)

## Code
Code to start the Hangfire background job server (Call once on application starts)
```
           lock (_lockObject)
            {
                if (_started) return;
                var serverOptions = new BackgroundJobServerOptions()
                {
                    ServerName = ServerQueue, 
                    Queues = new[] { ServerQueue, EnqueuedState.DefaultQueue },
                    WorkerCount = configuration.WorkerCount, // 2 workers
                    SchedulePollingInterval = TimeSpan.FromSeconds(configuration.PollingInterval) // ~1 min
                };

                _backgroundJobServer = new BackgroundJobServer(serverOptions);
                _started = true;
            }
```

Code to stop the Hangfire background job server (Call on application shutdown)
```
           lock (_lockObject)
            {
                if (_backgroundJobServer != null)
                {
                    _backgroundJobServer.Dispose();
                }
                _started = false;
            }
```

Configuration & Dashboard (Call once on startup)
```
            services.AddHangfire(x => x.UseSqlServerStorage(Configuration["ConnectionString"],
            new SqlServerStorageOptions()
            {
                    PrepareSchemaIfNecessary = false, // always False on production
                    QueuePollInterval = TimeSpan.FromMinutes(1),
                    SchemaName = "dbo"
            }));

            services.AddHangfire(x => x.UseDefaultActivator());

            app.UseHangfireDashboard("/Dashboard", new DashboardOptions { 
                      Authorization = new[] { new HangfireAuthorizationFilter() } 
            });
```

## Connection String
database=<DB_NAME>;uid=<USERNAME>;password=<PASSWORD>;Max Pool Size=100;Data Source=<HOST>,<PORT>;Connection Lifetime=10800

## Version
1.6.15

## Other Details
- Application is implemented with .NET Core 1.1
- Running on CentOS 7
- 2 servers are running at the same time
- We're not connecting to SQL Server in our own code

**Comment by odinserj** [comment]
Thanks for well-structured report and the detailed information! I couldn't reproduce this when .NET Framework 4.5. I currently installing .NET Core 2.0 to know if this problem exists there, then will try to use .NET Core 1.1. 

Meanwhile, could you spawn a small application on your server that creates and closes `SqlConnection` instances with relatively small connection lifetime. I suspect the problem in .NET Core rather than in Hangfire, because it closes every connection it acquires.

**Comment by odinserj** [comment]
I've found this [issue](https://github.com/dotnet/corefx/issues/17039) and [this PR](https://github.com/dotnet/corefx/pull/15431) related to connection leaks on .NET Core. They marked with .NET Core 1.1 milestone, but changes were [released](https://github.com/dotnet/corefx/issues/17039) only some months ago, so you can try to upgrade your System.Data.SqlClient to [version 4.3.1](https://www.nuget.org/packages/System.Data.SqlClient/4.3.1).

**Comment by phoomperfectionist** [comment]
@odinserj Seems like moving to Windows server solves the issue but anyways my production servers are Linux. It might be a problem with .NET Core itself, not the Hangfire. 

> so you can try to upgrade your System.Data.SqlClient to version 4.3.1.
I cannot find System.Data.SqlClient on my project or even the Hangfire project. Could you please suggest me how to do that?

**Comment by odinserj** [comment]
`Hangfire.SqlServer` package depends on it, please see the Dependencies section in https://www.nuget.org/packages/Hangfire.SqlServer/. Try to reference it in your project explicitly.

**Comment by phoomperfectionist** [comment]
@odinserj it doesn't work. Sessions are increasing over the time.

**Comment by phoomperfectionist** [comment]
@odinserj after upgrading my project to .Net Core 2.0, the problem got resolved. It came down to ~ 4 sessions per server and does close the session after a few minutes.
