### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by freeubi** [HangfireIO/Hangfire#966]
Hello,

there is a .net core suppport?  
"An easy way to perform background processing in .NET and .NET Core applications." on the website but i cant find any description about it.
The nuget package is not compatible with the .net core project (hangfire version: 1.6.15, .net coer version 2.0.0 preview2)

**Comment by stajs** [comment]
Yes, Hangfire supports .NET Core. I haven't upgraded to 2.0 yet, but am happily using it on 1.0.

**Comment by BurtonShane** [comment]
I've used it on .net core preview 2 with the in memory storage provider and had no issues.
