### ISSUE TITLE
1.6.15 SqlServerDistributedLock logic race condition on '0' timespan timeouts

### ISSUE THREAD

**Issue by ian-a-anderson** [HangfireIO/Hangfire#967]
After updating to 1.6.15 (Hangfire, Hangfire.Core, and HangFire.SqlServer)  we noticed a bunch of our recurring jobs started failing with DistributedLockTimeoutExceptions. After research this appears to affect jobs decorated with [DisableConcurrentExecution(0)]. 

Since this timeout of 0 is passed down into SqlServerDistributedLock, it seems like the issue is the new Stopwatch-based logic handling timeouts within SqlServerDistributedLock (lines 156-159):

`var started = Stopwatch.StartNew();`
`var attempt = 1;`

`while (started.Elapsed < timeout)`

If any ticks happen between Stopwatch.StartNew() and started.Elapsed, then "0" timeout requests will fail before any actual attempts to take the lock via sp_getapplock.

**Comment by odinserj** [comment]
Oh, I've just fixed this in commit 57985bf07f1cab8b6589741ca093f8c0e2042f37, will be released with 1.6.16.

**Comment by ian-a-anderson** [comment]
Great, thanks!
