### ISSUE TITLE
Make NCrontab accessible

### ISSUE THREAD

**Issue by rhegner** [HangfireIO/Hangfire#969]
Hangfire seems to include the sources for NCrontab, but these NCrontab classes are not accessible from my application. So it looks like if I need to do cron related stuff (find out next occurrence, for example) I need to reference NCrontab separately in my project.

This is not so nice since Hangfire and my app are then not using the same codebase for cron scheduling.

Would it be possible to make the NCrontab classes that ship with Hangfire accessible from the application? Or the other obvious solution would be to have a NuGet dependency for NCrontab in Hangfire instead of pulling in the sources.

**Comment by odinserj** [comment]
NCrontab is an internal thing to have an ability to change the cron parsing implementation without introducing breaking changes to your code, like in PR #853. Another advantage – consider your project or another package in your project already uses NCrontab 1.0 for internal stuff, and you can't upgrade it, and Hangfire requires 2.0. In this case you'll get a version lock, because neither of the versions can satisfy all the requirements.

So NCrontab is only for recurring jobs, and will not be exposed to public, so you can reference any version you want in your projects.

**Comment by rhegner** [comment]
Ok I see your point. So maybe making NCrontab accessible is not the right approach to solve my problem.

What I need is a way to determine the next occurence(s) based on a cron expression and it needs to be consistent with what hangfire does. I don't care how the cron expression is parsed, as long as it is parsed the same way as in hangfire.

So instead of making NCrontab accessible what I'd like to see in hangfire is a set of static methods like the following:

    public DateTime GetNextOccurrence(DateTime baseTime);
    public DateTime GetNextOccurrence(DateTime baseTime, DateTime endTime);
    public IEnumerable<DateTime> GetNextOccurrences(DateTime baseTime, DateTime endTime);

These can be implemented by Cronos or NCrontab or by whatever library you use internally.

**Comment by odinserj** [comment]
This interface is tied to the current implementation, and breaking changes will be required anyway. For example, Cronos returns `DateTime?`, not `DateTime`. Cronos has additional checks on `baseTime` and `endTime`, and also there may be additional meaning for boundaries (inclusive or exclusive), or other differences as well.

**Comment by rhegner** [comment]
So how can I find out based on a cron expression I pass to hangfire when the job will be executed for the next time?

**Comment by rhegner** [comment]
So the hangfire interface can be with `DateTime?` which is more generic. It should be possible to implement this interface with either of the underlying libraries.

I really don't care whether the behavior of these methods changes over time (when you change parsing) or what boundary handling they are using - as long as they return results which are consistent with what hangfire does.

**Comment by odinserj** [comment]
I do care 😛 Use [`GetRecurringJobDtos`](https://github.com/HangfireIO/Hangfire/blob/501ac6b0c14b2dc4473fec0e82c8e6e747d9def3/src/Hangfire.Core/Storage/StorageConnectionExtensions.cs#L64) method and `RecurringJobDto.NextExecution` to get the next execution time. Other methods will increase the maintenance burden.
