### ISSUE TITLE
Is this a bug? Or is my expression wrong?

### ISSUE THREAD

**Issue by ofnhkb1** [HangfireIO/Hangfire#975]
Is this a bug? Or is my expression wrong?
![1](https://user-images.githubusercontent.com/8349882/29501410-0795e3fa-865b-11e7-860a-ea0504cfb3e3.png)
![2](https://user-images.githubusercontent.com/8349882/29501411-079b15f0-865b-11e7-8b15-9a42ad544544.png)

**Comment by pieceofsummer** [comment]
Which timezone are you in? The dashboard graph shows your local time, while your cron expression uses UTC timezone.

**Comment by ofnhkb1** [comment]
I know that I need to set the local time zone at the time of the periodic task
