### ISSUE TITLE
Incorrect cron scheduling

### ISSUE THREAD

**Issue by Sorbjar** [HangfireIO/Hangfire#979]
According to crontab guru: https://crontab.guru/#0_6_1_*_2
Following schedule "0 6 1 * 2" runs on every tuesday and the first of the month.
![image](https://user-images.githubusercontent.com/10134777/29617509-6bc638f0-8815-11e7-8383-8333b07e4d3b.png)

In Hangfire it schedules that job on the next first day of the month that is a tuesday.

![image](https://user-images.githubusercontent.com/10134777/29617582-a4fa5a20-8815-11e7-8c39-100682c24a18.png)

**Comment by pieceofsummer** [comment]
It's actually a bit confusing, but it's actually part of specs.

[Wiki](https://en.wikipedia.org/wiki/Cron):
> While normally the job is executed when the time/date specification fields all match the current time and date, there is one exception: if both "day of month" (field 3) and "day of week" (field 5) are restricted (not "*"), then **one or both** must match the current day.[3]

**Comment by odinserj** [comment]
Standard is very odd in this case, and I've decided to create yet another one :wink: I'm closing the issue, because Hangfire is now using Cronos in 1.7.0 betas.
