### ISSUE TITLE
can remove references to Microsoft .NETCore.Portable.Compatibility？

### ISSUE THREAD

**Issue by xakepbean** [HangfireIO/Hangfire#982]
use dotnet publish -r win10-x64
exec *.exe after
Failed to initialize CoreCLR, HRESULT: 0x80004005

**Comment by RehanSaeed** [comment]
I'm seeing the same issue, is there a workaround?

**Comment by mikeli11** [comment]
To repro:

In VS2017:
1) Create new ASP.NET application
2) In package manager console: Install-Package Hangfire
3) Add in startup - .UseHangfireServer(), .UseHangfireDashboard(), services.AddHangfire(x =>UseSqlServerStorage())
4) cd into project folder
5) in CMD: dotnet publish -c Debug -f netcoreapp2.0 -r win7-x64
6) in publish folder (\WebApplication\bin\Debug\netcoreapp2.0\win7-x64\publish) in CMD: dotnet WebApplication.dll

Error:
Failed to initialize CoreCLR, HRESULT: 0x80004005

**Comment by stestet** [comment]
We are having the same problem... Is there hope?

**Comment by Salazander** [comment]
We had a similar issue (Failed to initialize CoreCLR, HRESULT: 0x80004005) and fixed it by targetting runtime win-x64 instead of win10-x64. Not sure why, but it looks like the wrong version of System.Private.CoreLib.dll gets copied into the publishing folder when targetting win10-x64

**Comment by graemefoster** [comment]
I'm getting this as-well when running on Cloud Foundry (dotnet publish -r ubuntu.14.04-x64)

**Comment by cbmek** [comment]
It is not possible to build `win10-x64` and `win7-x64`.
Will it ever be fixed?

**Comment by odinserj** [comment]
Reference to the `Microsoft.NETCore.Portable.Compatibility` package removed in the latest betas after moving the project to use new SDKs. Also, explicit `netstandard2.0` target was added to remove the reference burden so everything should be working fine now.
