### ISSUE TITLE
Semicolon in password results in Using job storage: '<Connection string can not be parsed>'

### ISSUE THREAD

**Issue by bendras** [HangfireIO/Hangfire#989]
Hi,
I have got a SQL DB password that contains a Semicolon(;) and it results in error message logged.

I believe this happens in `SqlServerStorage.ToString()` only.

Here is an example of connection string in use: `Server=localhost;Database=theDatabaseName;User Id=theUserName;Password='M%]:bC%r:}P;}wE_bVd(';`

**Comment by IanYates** [comment]
Interesting.  I can see you've got quoting already present in the password (as per https://stackoverflow.com/a/38734824/1053381 )

Funny - doing a google search on your exact error string finds, as hit number 2, another issue in here reporting it two years ago.  #392 
You might as well carry on there and close this as a dupe.

After a quick two minute browse through the Hangfire source I suspect the issue will be around here:  https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerStorage.cs#L128
The string is split - and string splits with escapes are always "fun".  See if you can find the problem there and possibly submit a PR.

**Comment by bendras** [comment]
Hi, yes the problem is in the `SqlServerStorage.ToString()`. 
The good: it is not critical, logging is not right. 
the #392 : missed this one. Duplicate

**Comment by pieceofsummer** [comment]
Escaping rules for connection strings are rather tricky, and there’s no way to handle them all with but a simple `String.Split()`.

I wonder why it doesn’t just use `SqlConnectionStringBuilder` for parsing. It would be the easiest and most accurate way to handle connection strings.
