### ISSUE TITLE
Getting a new weird issue...  relating to Redis and Console display..

### ISSUE THREAD

**Issue by dcorbett-fivebridgesllc** [HangfireIO/Hangfire#994]
[ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s]
   System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) +14154026
   Hangfire.Common.JobHelper.DeserializeDateTime(String value) +89
   Hangfire.Pro.Redis.<>c__DisplayClass12_1.<Servers>b__4(String x) +151
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +102
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +524
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +70
   Hangfire.Pro.Redis.RedisMonitoringApi.Servers() +794
   Hangfire.Dashboard.Pages.ProcessingJobsPage.Execute() +445

This is happening when I try to look at the job page, or when I look at the list of processing jobs.   This has been working well, but for some reason this started happen today.

Versions:
Hangfire.Console v 1.3.4
Hangfire.Core v1.6.16
Hangfire.Pro v2.1.0
Hangfire.Pro.redis v2.1.1
Hangfire.SqlServer v1.6.16
Hangfire.Unity v1.3.0

**Comment by pieceofsummer** [comment]
Shouldn't be related to Console, because it doesn't even run on processing jobs page (and also not present in stack trace).

**Comment by dcorbett-fivebridgesllc** [comment]
I cut out the non-relevant parts of the trace... it does happen on the processingJobs page, and in fact, this was displayed instead of the processingJobs page.   However, the cause is clearly in the MonitoringApi failing to parse a date.

**Comment by odinserj** [comment]
Yes, it does relate to Hangfire Pro itself. @dcorbett-fivebridgesllc, please try to upgrade to Hangfire.Pro.Redis 2.1.2.
